/**
 * Unit 39 — Time, Transformations & Angles (Stage 3 Year B).
 * Deliverable B. Built from units/u39/00_rubric_draft.md + 01_mapping_review.md.
 * Matches the UNIT DATA SCHEMA at the bottom of scripts/build_program_template.js.
 *
 * Measuring/creating/classifying angles with a protractor; angle relationships (right angles,
 * straight line 180°, point 360°, perpendicular); identifying angles in diagrams; transformations
 * (translate/reflect/rotate) and dissecting & rearranging shapes; elapsed time; time as decimals;
 * and 12-/24-hour duration problems. Green = Stage 4 Angle relationships.
 *
 * Program has the resource appendix merged (resource_appendix_attached: true); a standalone
 * Unit39_Resource_Appendix.docx is also emitted (Stage 5). Every resource URL verified live
 * in Stage 3 (units/u39/03_resources_staged.csv).
 *
 * Outcome -> Mini Lesson map (teaching sequence, then Stage-4 Green cards):
 *   R1->1 R2->2 R3->3 R4->4 Y1->5 Y2->6 Y3->7 Y4->8 Y5->9 Y6->10 G1->11 G2->12 G3->13
 */
module.exports = {
  unit_number: "39",
  unit_title: "Time, Transformations & Angles",
  term: null,
  duration: "2-3 weeks",

  resource_appendix_attached: true,

  // Every URL verified live in Stage 3 (25 videos oEmbed-verified, 13 worksheets curl HTTP 200);
  // see units/u39/03_resources_staged.csv. Unit 39 ships CODE-CANONICAL (hardcoded RESOURCES in
  // solo/index.html); the same rows are in units/u39/04_insert.sql for optional DB promotion.
  resources: {
    r1: [
      { type: "video", label: "Types of Angles — Acute / Obtuse / Right / Straight / Reflex | Math with Mr. J", url: "https://www.youtube.com/watch?v=UsE1hu-q0Cs" },
      { type: "video", label: "How to Use a Protractor to Measure an Angle | Math with Mr. J", url: "https://www.youtube.com/watch?v=N8TGOMH5Y50" },
      { type: "worksheet", label: "Corbettmaths — Types of Angles (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2018/09/Types-of-Angle-pdf.pdf" },
    ],
    r2: [
      { type: "video", label: "How to Measure Angles Using a Protractor | Math with Mr. J", url: "https://www.youtube.com/watch?v=j5D7acsExxw" },
      { type: "video", label: "How to Use a Protractor — Measuring and Drawing Angles | Math with Mr. J", url: "https://www.youtube.com/watch?v=2on99N5jBJ4" },
      { type: "worksheet", label: "Corbettmaths — Measuring Angles (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2018/02/measuring-angles.pdf" },
    ],
    r3: [
      { type: "video", label: "How to Draw Angles with a Protractor | Math with Mr. J", url: "https://www.youtube.com/watch?v=zh-tj7oTQlc" },
      { type: "video", label: "Drawing an Angle with a Protractor — 60° | Math with Mr. J", url: "https://www.youtube.com/watch?v=qYfH4NN0b-4" },
      { type: "worksheet", label: "Corbettmaths — Constructing / Drawing Angles (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/constructing-angles-pdf.pdf" },
    ],
    r4: [
      { type: "video", label: "Angles at a Point | Corbettmaths", url: "https://www.youtube.com/watch?v=mdAwUsf0k1s" },
      { type: "video", label: "Angles in a Straight Line | Corbettmaths", url: "https://www.youtube.com/watch?v=q5tV5V56Hr0" },
      { type: "worksheet", label: "Corbettmaths — Angle Facts (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/angle-facts-pdf1.pdf" },
    ],
    y1: [
      { type: "video", label: "Angles on a Straight Line and About a Point | Mr Mathematics", url: "https://www.youtube.com/watch?v=juix_jB1pss" },
      { type: "video", label: "Finding the Missing Angle of a Triangle | Math with Mr. J", url: "https://www.youtube.com/watch?v=LAlQnW6-6c4" },
      { type: "worksheet", label: "Corbettmaths — Missing Angles (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/missing-angles-pdf1.pdf" },
    ],
    y2: [
      { type: "video", label: "Transformations — Translations / Reflections / Rotations | Math Defined", url: "https://www.youtube.com/watch?v=YD3HIMUae_4" },
      { type: "video", label: "3 Types of Transformations — Translations Reflections & Rotations | Turtlediary", url: "https://www.youtube.com/watch?v=VJTxv-tRKj0" },
      { type: "worksheet", label: "Corbettmaths — Reflections (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/reflections-pdf.pdf" },
    ],
    y3: [
      { type: "video", label: "Compose and Decompose 2D Shapes | Underwater Math", url: "https://www.youtube.com/watch?v=KbDXgDeFoG4" },
      { type: "video", label: "3 Types of Transformations — Translations Reflections & Rotations | Turtlediary", url: "https://www.youtube.com/watch?v=VJTxv-tRKj0" },
      { type: "worksheet", label: "Corbettmaths — Rotations (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/rotations-pdf.pdf" },
    ],
    y4: [
      { type: "video", label: "Elapsed Time — T-Chart Strategy | Sally Osborne", url: "https://www.youtube.com/watch?v=4Eucvb7qFpk" },
      { type: "worksheet", label: "Corbettmaths — Time Calculations (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2019/10/Time-Calculations-pdf.pdf" },
      { type: "worksheet", label: "Corbettmaths Primary — Time (PDF)", url: "https://corbettmathsprimary.com/wp-content/uploads/2018/07/time-pdf.pdf" },
    ],
    y5: [
      { type: "video", label: "Converting Fractions and Decimals to Hours and Minutes | FountainMath", url: "https://www.youtube.com/watch?v=r6Z48Iv1HCI" },
      { type: "video", label: "How To Convert Decimal Time To Hours And Minutes | OnTheClock", url: "https://www.youtube.com/watch?v=IPaPdf9ck8M" },
      { type: "worksheet", label: "Corbettmaths — Time Calculations (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2019/10/Time-Calculations-pdf.pdf" },
    ],
    y6: [
      { type: "video", label: "The 24-Hour Clock | Mathematics Grade 5 | Periwinkle", url: "https://www.youtube.com/watch?v=Lj4YxVZWLVU" },
      { type: "video", label: "Understanding the 24-Hour Clock | Smartli", url: "https://www.youtube.com/watch?v=dQ5vIHA4L5s" },
      { type: "worksheet", label: "Corbettmaths — Timetables and Time (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2025/03/Timetables-and-Time-Practice-Questions.pdf" },
    ],
    g1: [
      { type: "video", label: "Complementary Angles & Supplementary Angles | Math with Mr. J", url: "https://www.youtube.com/watch?v=Qpq_XEeBBZw" },
      { type: "video", label: "Complementary and Supplementary Angles — How to Find Missing Angles | Math with Mr. J", url: "https://www.youtube.com/watch?v=E_ulN2FjJac" },
      { type: "worksheet", label: "Corbettmaths — Angle Facts (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/angle-facts-pdf1.pdf" },
    ],
    g2: [
      { type: "video", label: "Angles in Parallel Lines | Corbettmaths", url: "https://www.youtube.com/watch?v=5NfXvBdwKJE" },
      { type: "video", label: "Parallel Lines — Angle Examples | Corbettmaths", url: "https://www.youtube.com/watch?v=ARsZDZlPDhM" },
      { type: "worksheet", label: "Corbettmaths — Angles in Parallel Lines (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/angles-in-parallel-lines-pdf1.pdf" },
    ],
    g3: [
      { type: "video", label: "What are Complementary Angles? — Find Missing Angles | Math with Mr. J", url: "https://www.youtube.com/watch?v=odR4R_BPiH0" },
      { type: "video", label: "What are Supplementary Angles? — Find Missing Angles | Math with Mr. J", url: "https://www.youtube.com/watch?v=rkGQ7O2i4-U" },
      { type: "worksheet", label: "Corbettmaths — Missing Angles (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/missing-angles-pdf1.pdf" },
    ],
  },

  beyond_resources: [
    { type: "video", label: "Complementary Angles & Supplementary Angles | Math with Mr. J", url: "https://www.youtube.com/watch?v=Qpq_XEeBBZw" },
    { type: "video", label: "Angles in Parallel Lines | Corbettmaths", url: "https://www.youtube.com/watch?v=5NfXvBdwKJE" },
    { type: "worksheet", label: "Corbettmaths — Angles in Parallel Lines (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/angles-in-parallel-lines-pdf1.pdf" },
    { type: "worksheet", label: "Corbettmaths — Missing Angles (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/missing-angles-pdf1.pdf" },
    { type: "worksheet", label: "Corbettmaths — Angle Facts (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/angle-facts-pdf1.pdf" },
  ],

  syllabus_strands_summary: "Geometric Measure A & B, 2D Spatial Structure B, Non-spatial Measure B",
  strand_abbreviations_note: "GM = Geometric measure. 2DS = Two-dimensional spatial structure. NSM = Non-spatial measure. A/B = syllabus content group (Year A ~ Year 5; Year B ~ Year 6).",

  syllabus_outcomes: [
    { code: "MAO-WM-01", descriptor: "Develops understanding and fluency in mathematics through exploring and connecting mathematical concepts, choosing and applying mathematical techniques to solve problems, and communicating their thinking and reasoning coherently and clearly." },
    { code: "MA3-GM-03", descriptor: "Measures and constructs angles, and identifies the relationships between angles on a straight line and angles at a point." },
    { code: "MA3-2DS-01", descriptor: "Investigates and classifies two-dimensional shapes, including triangles and quadrilaterals, based on their properties." },
    { code: "MA3-NSM-02", descriptor: "Measures and compares duration, using 12- and 24-hour time." },
  ],

  content_points: {
    red: {
      heading: "Geometric measure A (angles) + foundational angle facts",
      heading_short: "Red -- Foundation",
      points: [
        "Classify angles as acute, right, obtuse, straight or reflex (GM-A).",
        "Measure angles of up to 360° using a protractor (GM-A).",
        "Create (draw) angles of up to 360° using a protractor (GM-A).",
        "Find missing angles using right angles (90°), a straight line (180°) and a point (360°) (GM-B).",
      ],
    },
    yellow: {
      heading: "Angle diagrams, transformations & time (applying)",
      heading_short: "Yellow -- On-level",
      points: [
        "Identify right/straight/point angles, vertex and arms, and angle types in diagrams.",
        "Use translate, reflect and rotate to describe transformations (position/orientation, not size).",
        "Dissect and rearrange one shape to make another.",
        "Calculate elapsed time using start/finish times and bridging; round to the nearest minute/hour.",
        "Represent commonly used time intervals as decimals.",
        "Convert between 12- and 24-hour time and solve duration problems.",
      ],
    },
    green: {
      heading: "Extended -- Stage 4 Angle relationships",
      heading_short: "Green -- Extension",
      points: [
        "Use complementary (90°), supplementary (180°) and vertically opposite (equal) angles (MA4-ANG-C-01).",
        "Identify corresponding, alternate and co-interior angles on parallel lines cut by a transversal (MA4-ANG-C-01).",
        "Solve numerical angle problems using reasoning (MA4-ANG-C-01).",
      ],
    },
  },

  working_mathematically: [
    { process: "Communicating", description: "Students use the language of angles (acute, reflex, vertex, perpendicular) and time (12-/24-hour, duration), and describe transformations." },
    { process: "Understanding and fluency", description: "Students measure and draw angles with a protractor, find missing angles, and calculate elapsed time." },
    { process: "Reasoning", description: "Students reason about angle relationships (90°/180°/360°), that transformations preserve size, and about duration." },
    { process: "Problem solving", description: "Students solve missing-angle and duration problems, and (Stage 4) apply complementary/supplementary, vertically opposite and parallel-line angle relationships." },
  ],

  outcomes: [
    { code: "R1", desc: "Classify angles as acute, right, obtuse, straight or reflex.", content_point: "GM-A: identify and describe angle size in degrees for the classifications acute, obtuse and reflex | MA3-GM-03 | Year A", lesson_ref: "Mini Lesson 1" },
    { code: "R2", desc: "Measure angles of up to 360° using a protractor.", content_point: "GM-A: measure angles of up to 360° using a protractor | MA3-GM-03 | Year A", lesson_ref: "Mini Lesson 2" },
    { code: "R3", desc: "Create (draw) angles of up to 360° using a protractor.", content_point: "GM-A: create angles of up to 360° using a protractor | MA3-GM-03 | Year A", lesson_ref: "Mini Lesson 3" },
    { code: "R4", desc: "Find missing angles on a straight line, at a point and at a right angle.", content_point: "GM-B: perpendicular lines (90°); adjacent angles add to 90° / 180°; angles at a point add to 360° | MA3-GM-03 | Year B", lesson_ref: "Mini Lesson 4" },
    { code: "Y1", desc: "Identify angle types and parts (vertex/arms) in diagrams.", content_point: "GM-B: recognise right/straight/point angles in diagrams; identify the vertex and arms; identify angle types from intersecting lines | MA3-GM-03 | Year B", lesson_ref: "Mini Lesson 5" },
    { code: "Y2", desc: "Describe transformations (translate, reflect, rotate).", content_point: "2DS-B: use translate/reflect/rotate; transformations change position and orientation but not size | MA3-2DS-01 | Year B", lesson_ref: "Mini Lesson 6" },
    { code: "Y3", desc: "Dissect and rearrange one shape to make another.", content_point: "2DS-B: dissect and rearrange one shape to make another | MA3-2DS-01 | Year B", lesson_ref: "Mini Lesson 7" },
    { code: "Y4", desc: "Calculate elapsed time using bridging and rounding.", content_point: "NSM-B: elapsed time from start/finish; add/subtract time using bridging; round to the nearest minute/hour | MA3-NSM-02 | Year B", lesson_ref: "Mini Lesson 8" },
    { code: "Y5", desc: "Represent commonly used time intervals as decimals.", content_point: "NSM-B: represent commonly used time intervals as decimals | MA3-NSM-02 | Year B", lesson_ref: "Mini Lesson 9" },
    { code: "Y6", desc: "Solve duration problems in 12- and 24-hour time.", content_point: "NSM-B: solve duration problems, including 12-hour and 24-hour notation | MA3-NSM-02 | Year B", lesson_ref: "Mini Lesson 10" },
    { code: "G1", desc: "Complementary, supplementary and vertically opposite angles.", content_point: "Stage 4 ANG: complementary (90°), supplementary (180°), vertically opposite angles | MA4-ANG-C-01 | Stage 4 (Core)", lesson_ref: "Mini Lesson 11" },
    { code: "G2", desc: "Angles on parallel lines cut by a transversal.", content_point: "Stage 4 ANG: corresponding, alternate and co-interior angles on parallel lines | MA4-ANG-C-01 | Stage 4 (Core)", lesson_ref: "Mini Lesson 12" },
    { code: "G3", desc: "Solve numerical angle problems using reasoning.", content_point: "Stage 4 ANG: solve numerical problems involving angles using reasoning | MA4-ANG-C-01 | Stage 4 (Core)", lesson_ref: "Mini Lesson 13" },
  ],

  lessons: [
    {
      num: 1, band: "R",
      title: "Classifying angles",
      outcomes: ["R1"], duration: "25 min",
      syllabus: "MA3-GM-03, MAO-WM-01 | GM-A: classify acute, obtuse, reflex",
      source: "DoE Lesson 7 (adapted)",
      doeLink: "Lesson 7 -- Creating, identifying and investigating angles",
      resources: "Angle cards, protractors",
      li: "classify angles as acute, right, obtuse, straight or reflex",
      sc: [
        "I know an acute angle is less than 90° and a right angle is exactly 90°.",
        "I know an obtuse angle is between 90° and 180° and a straight angle is 180°.",
        "I know a reflex angle is between 180° and 360°.",
      ],
      steps: [
        { label: "Activate (3 min):", content: "Show a right angle. Ask which angles are smaller (acute) and which are bigger (obtuse)." },
        { label: "Model (10 min):", content: "Build the angle types on a number line of degrees: acute <90°, right =90°, obtuse 90-180°, straight =180°, reflex 180-360°." },
        { label: "Guided practice (8 min):", content: "Students sort angle cards into acute, right, obtuse, straight and reflex." },
        { label: "Check (4 min):", content: "Exit question: what type of angle is 200°? What about 45°?" },
      ],
      vocab: "angle, acute, right, obtuse, straight, reflex, degrees",
      support: "Provide a reference strip showing each angle type with its degree range.",
      extension: "Estimate the size of given angles in degrees before classifying them.",
      assessment: "Students classify angles — links to R1 in the SOLO Show task.",
    },
    {
      num: 2, band: "R",
      title: "Measuring angles with a protractor",
      outcomes: ["R2"], duration: "30 min",
      syllabus: "MA3-GM-03, MAO-WM-01 | GM-A: measure angles up to 360° with a protractor",
      source: "DoE Lesson 7 (adapted)",
      doeLink: "Lesson 7 -- Creating, identifying and investigating angles",
      resources: "Protractors, prepared angle diagrams",
      li: "measure angles of up to 360° using a protractor",
      sc: [
        "I can line up the protractor's centre on the vertex and the baseline on one arm.",
        "I can read the correct scale (inner or outer) to measure the angle.",
        "I can measure reflex angles (measure the other angle and subtract from 360°).",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show a protractor. Ask: where do you put the centre and the zero line?" },
        { label: "Model (12 min):", content: "Place the centre on the vertex, baseline on one arm, read where the other arm crosses. Demonstrate choosing inner vs outer scale, and measuring a reflex angle via 360 − (the smaller angle)." },
        { label: "Guided practice (10 min):", content: "Students measure a set of acute, obtuse and reflex angles with a protractor." },
        { label: "Check (4 min):", content: "Exit question: measure the given angle and say its type." },
      ],
      vocab: "protractor, vertex, arm, baseline, scale, degrees, reflex",
      support: "Pre-mark the vertex and baseline; start with angles on the outer scale only.",
      extension: "Measure reflex angles and check by measuring both angles to confirm they total 360°.",
      assessment: "Students measure angles — links to R2 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["protractors", "angle diagrams"],
    },
    {
      num: 3, band: "R",
      title: "Drawing angles with a protractor",
      outcomes: ["R3"], duration: "30 min",
      syllabus: "MA3-GM-03, MAO-WM-01 | GM-A: create angles up to 360° with a protractor",
      source: "DoE Lessons 6 & 7 (adapted)",
      doeLink: "Lessons 6 & 7 -- Creating, identifying and investigating angles",
      resources: "Protractors, rulers",
      li: "create (draw) angles of up to 360° using a protractor",
      sc: [
        "I can draw a baseline and mark the vertex.",
        "I can use the protractor to mark the correct number of degrees and draw the second arm.",
        "I can draw reflex angles by drawing the smaller angle and marking the reflex side.",
      ],
      steps: [
        { label: "Activate (3 min):", content: "Ask students how they would draw an angle of exactly 60°." },
        { label: "Model (12 min):", content: "Draw a baseline, place the protractor centre on the vertex, mark 60° (or 110°), then join to make the second arm. Show drawing a reflex angle (e.g. 290°)." },
        { label: "Guided practice (11 min):", content: "Students draw angles of given sizes (acute, obtuse and reflex) with a protractor." },
        { label: "Check (4 min):", content: "Exit question: draw a 135° angle and label its type." },
      ],
      vocab: "protractor, draw, create, baseline, vertex, arm, degrees, reflex",
      support: "Provide the baseline and vertex already drawn so students focus on the protractor.",
      extension: "Draw an angle, swap with a partner, and measure each other's angles to check.",
      assessment: "Students draw angles — links to R3 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["protractors", "rulers"],
    },
    {
      num: 4, band: "R",
      title: "Angles on a straight line and at a point",
      outcomes: ["R4"], duration: "30 min",
      syllabus: "MA3-GM-03, MAO-WM-01 | GM-B: 90° / 180° / 360°; perpendicular",
      source: "DoE Lessons 5, 6 & 8 (adapted)",
      doeLink: "Lessons 5, 6 & 8 -- Investigating angles",
      resources: "Angle diagrams, straws or geostrips",
      li: "find missing angles using right angles, angles on a straight line and angles at a point",
      sc: [
        "I know perpendicular lines meet at 90° and angles on a straight line add to 180°.",
        "I know angles at a point add to 360°.",
        "I can find a missing angle by subtracting from 90°, 180° or 360°.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show two angles on a straight line, one is 120°. Ask for the other." },
        { label: "Model (12 min):", content: "Straight line: 180 − 120 = 60°. Right angle: 90 − one part. Point: 360 − the sum of the others. Show perpendicular lines making four 90° angles." },
        { label: "Guided practice (10 min):", content: "Students find missing angles on straight lines, at right angles and at a point." },
        { label: "Check (4 min):", content: "Exit question: three angles at a point are 120°, 150° and ?. Find the missing angle." },
      ],
      vocab: "straight line, point, right angle, perpendicular, adjacent, revolution, missing angle",
      support: "Provide the relevant total (180° or 360°) labelled on the diagram.",
      extension: "Find two unknown equal angles that complete a straight line or point.",
      assessment: "Students find missing angles — links to R4 in the SOLO Show task.",
    },
    {
      num: 5, band: "Y",
      title: "Identifying angles in diagrams",
      outcomes: ["Y1"], duration: "25-30 min",
      syllabus: "MA3-GM-03, MAO-WM-01 | GM-B: identify angle types and parts in diagrams",
      source: "DoE Lessons 5 & 8 (adapted)",
      doeLink: "Lessons 5 & 8 -- Identifying angles in diagrams",
      resources: "Diagrams of intersecting lines",
      li: "identify angle types and the parts of an angle in diagrams",
      sc: [
        "I can find right angles, angles on a straight line and angles at a point in a diagram.",
        "I can name the vertex and the arms of an angle.",
        "I can identify angle types formed when straight lines cross.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show two crossing lines. Ask students to point to a vertex and the arms of one angle." },
        { label: "Model (10 min):", content: "Label the vertex and arms; mark the right angles, straight-line angles (180°) and the angles at the point (360°) in the diagram." },
        { label: "Guided practice (10 min):", content: "Students label angle parts and identify angle types in diagrams of intersecting lines." },
        { label: "Check (4 min):", content: "Exit question: in a diagram of crossing lines, which angles sit on a straight line together?" },
      ],
      vocab: "vertex, arm, intersecting lines, right angle, straight line, point, angle type",
      support: "Provide a labelled example diagram to refer to.",
      extension: "Identify vertically opposite angles in the diagram and explain why they are equal.",
      assessment: "Students identify angles in diagrams — links to Y1 in the SOLO Show task.",
    },
    {
      num: 6, band: "Y",
      title: "Transformations: translate, reflect, rotate",
      outcomes: ["Y2"], duration: "30 min",
      syllabus: "MA3-2DS-01, MAO-WM-01 | 2DS-B: translate/reflect/rotate; size preserved",
      source: "DoE Lessons 3 & 4 (adapted)",
      doeLink: "Lessons 3 & 4 -- Translations, rotations and reflections",
      resources: "Paper shapes, mirrors, grid paper",
      li: "use translate, reflect and rotate to describe transformations of 2D shapes",
      sc: [
        "I can slide a shape (translate), flip it (reflect) and turn it (rotate).",
        "I can use the words translate, reflect and rotate to describe a move.",
        "I know a transformation changes position and orientation but not the size of the shape.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Slide, flip and turn a paper shape. Ask students to name each move." },
        { label: "Model (12 min):", content: "Translate (slide), reflect (flip over a line, like a mirror) and rotate (turn about a point). Show the shape stays the same size and shape each time." },
        { label: "Guided practice (10 min):", content: "Students perform and describe translations, reflections and rotations on grid paper." },
        { label: "Check (4 min):", content: "Exit question: which transformation flips a shape over a line?" },
      ],
      vocab: "translate, reflect, rotate, transformation, position, orientation, size",
      support: "Use a mirror for reflections and a pin to rotate about a point.",
      extension: "Combine two transformations and describe the overall move.",
      assessment: "Students describe transformations — links to Y2 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["paper shapes", "mirrors", "grid paper"],
    },
    {
      num: 7, band: "Y",
      title: "Dissecting and rearranging shapes",
      outcomes: ["Y3"], duration: "25-30 min",
      syllabus: "MA3-2DS-01, MAO-WM-01 | 2DS-B: dissect and rearrange one shape to make another",
      source: "DoE Lesson 3 (adapted)",
      doeLink: "Lesson 3 -- Dissecting and rearranging shapes",
      resources: "Paper shapes, scissors, tangram pieces",
      li: "dissect and rearrange one shape to make another",
      sc: [
        "I can cut a shape into pieces.",
        "I can rearrange the pieces (using slides, flips and turns) to make a new shape.",
        "I know the total area stays the same when I rearrange the pieces.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show a rectangle. Ask: how could we cut it and rearrange it into a different shape?" },
        { label: "Model (10 min):", content: "Cut a rectangle along a diagonal and rearrange the two triangles into a different shape. Note the area is unchanged. Use tangram pieces to make a square then a different figure." },
        { label: "Guided practice (10 min):", content: "Students cut and rearrange shapes to make new shapes, using translations, reflections and rotations." },
        { label: "Check (4 min):", content: "Exit question: if you rearrange the pieces of a shape, does its area change?" },
      ],
      vocab: "dissect, rearrange, pieces, transform, area, translate, reflect, rotate",
      support: "Provide pre-cut pieces (e.g. a tangram) to rearrange.",
      extension: "Dissect a parallelogram and rearrange it into a rectangle; explain what stayed the same.",
      assessment: "Students dissect and rearrange shapes — links to Y3 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["paper shapes", "scissors", "tangram pieces"],
    },
    {
      num: 8, band: "Y",
      title: "Calculating elapsed time",
      outcomes: ["Y4"], duration: "30 min",
      syllabus: "MA3-NSM-02, MAO-WM-01 | NSM-B: elapsed time; bridging; rounding",
      source: "DoE Lesson 1 (adapted)",
      doeLink: "Lesson 1 -- Rounding time calculations",
      resources: "Clock faces, number lines",
      li: "calculate elapsed time using start and finish times and bridging",
      sc: [
        "I can use start and finish times to work out how long something lasts.",
        "I can add and subtract time by bridging to the next hour.",
        "I can round a time answer to the nearest minute or hour.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "A film starts at 2:40 pm and ends at 4:15 pm. How long is it?" },
        { label: "Model (12 min):", content: "Bridge: 2:40 → 3:00 is 20 min; 3:00 → 4:15 is 1 h 15 min; total 1 h 35 min. Show rounding 1 h 33 min to the nearest hour (≈ 1 h 30 min or 2 h)." },
        { label: "Guided practice (10 min):", content: "Students calculate elapsed time using bridging on a number line and round their answers." },
        { label: "Check (4 min):", content: "Exit question: a bus leaves at 9:50 am and arrives at 11:20 am. How long is the trip?" },
      ],
      vocab: "elapsed time, duration, start, finish, bridging, round, hour, minute",
      support: "Use a number line of times and bridge to the next hour first.",
      extension: "Calculate elapsed time that crosses midday or midnight.",
      assessment: "Students calculate elapsed time — links to Y4 in the SOLO Show task.",
    },
    {
      num: 9, band: "Y",
      title: "Time intervals as decimals",
      outcomes: ["Y5"], duration: "25 min",
      syllabus: "MA3-NSM-02, MAO-WM-01 | NSM-B: represent time intervals as decimals",
      source: "DoE Lesson 2 (adapted)",
      doeLink: "Lesson 2 -- Time intervals as decimals",
      resources: "Clock faces, fraction-of-an-hour cards",
      li: "represent commonly used time intervals as decimals",
      sc: [
        "I know 30 minutes is half an hour = 0.5 h.",
        "I know 15 minutes = 0.25 h and 45 minutes = 0.75 h.",
        "I can write a number of minutes as a decimal of an hour (minutes ÷ 60).",
      ],
      steps: [
        { label: "Activate (3 min):", content: "Ask: half an hour is how many minutes? What decimal of an hour is that?" },
        { label: "Model (10 min):", content: "30 min = 30/60 = 0.5 h; 15 min = 0.25 h; 45 min = 0.75 h; 6 min = 0.1 h. Connect to benchmark fractions." },
        { label: "Guided practice (8 min):", content: "Students write common time intervals as decimals of an hour." },
        { label: "Check (4 min):", content: "Exit question: write 45 minutes as a decimal of an hour." },
      ],
      vocab: "interval, decimal, hour, minute, half, quarter, fraction of an hour",
      support: "Provide a table linking 15/30/45 min to 0.25/0.5/0.75 h.",
      extension: "Convert decimals back to minutes (e.g. 0.2 h = 12 min).",
      assessment: "Students represent time as decimals — links to Y5 in the SOLO Show task.",
    },
    {
      num: 10, band: "Y",
      title: "Duration in 12- and 24-hour time",
      outcomes: ["Y6"], duration: "30 min",
      syllabus: "MA3-NSM-02, MAO-WM-01 | NSM-B: 12-/24-hour duration problems",
      source: "DoE Lesson 2 (adapted)",
      doeLink: "Lesson 2 -- Time intervals as decimals (12/24-hour problems)",
      resources: "24-hour time charts, timetables",
      li: "convert between 12- and 24-hour time and solve duration problems",
      sc: [
        "I can convert a 12-hour time (with am/pm) to 24-hour time and back.",
        "I can read a timetable in 24-hour time.",
        "I can solve a duration problem using 24-hour time.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "What is 3:30 pm in 24-hour time? (15:30) How did you work it out?" },
        { label: "Model (12 min):", content: "After 12 noon, add 12 to the hour for 24-hour time (3 pm = 15:00). Read a bus timetable and find the duration between two 24-hour times." },
        { label: "Guided practice (10 min):", content: "Students convert times and solve duration problems using 24-hour notation." },
        { label: "Check (4 min):", content: "Exit question: a train leaves at 13:45 and arrives at 15:20. How long is the journey?" },
      ],
      vocab: "12-hour, 24-hour, am, pm, timetable, duration, convert",
      support: "Provide a 12-to-24-hour conversion chart.",
      extension: "Plan a short journey using a real 24-hour timetable and calculate total travel time.",
      assessment: "Students solve 24-hour duration problems — links to Y6 in the SOLO Show task.",
    },
    {
      num: 11, band: "G",
      title: "Complementary, supplementary and vertically opposite angles",
      outcomes: ["G1"], duration: "30 min",
      syllabus: "MA4-ANG-C-01, MAO-WM-01 | Stage 4: complementary / supplementary / vertically opposite",
      source: "Original mini lesson (Stage 4 extension)",
      li: "use complementary, supplementary and vertically opposite angles to find unknown angles",
      sc: [
        "I know complementary angles add to 90° and supplementary angles add to 180°.",
        "I know vertically opposite angles are equal.",
        "I can find an unknown angle using these relationships.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Two angles add to 90°. If one is 35°, what is the other?" },
        { label: "Model (12 min):", content: "Complementary: 90 − 35 = 55°. Supplementary: 180 − one angle. Show two crossing lines: vertically opposite angles are equal." },
        { label: "Guided practice (10 min):", content: "Students find unknown angles using complementary, supplementary and vertically opposite relationships." },
        { label: "Check (4 min):", content: "Exit question: the supplement of 110° is what angle?" },
      ],
      vocab: "complementary, supplementary, vertically opposite, equal, unknown angle",
      support: "Provide the relationship (90°/180°) labelled on each diagram.",
      extension: "Find several unknown angles in a single diagram of intersecting lines.",
      assessment: "Students apply angle relationships — extends R4/Y1.",
    },
    {
      num: 12, band: "G",
      title: "Angles on parallel lines cut by a transversal",
      outcomes: ["G2"], duration: "30 min",
      syllabus: "MA4-ANG-C-01, MAO-WM-01 | Stage 4: corresponding / alternate / co-interior",
      source: "Original mini lesson (Stage 4 extension)",
      li: "identify corresponding, alternate and co-interior angles on parallel lines",
      sc: [
        "I can identify a transversal crossing two parallel lines.",
        "I know corresponding and alternate angles are equal, and co-interior angles add to 180°.",
        "I can use these to find unknown angles.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show two parallel lines crossed by a transversal. Point out matching (corresponding) angles." },
        { label: "Model (12 min):", content: "Corresponding angles equal; alternate (Z) angles equal; co-interior (C) angles add to 180°. Use them to find unknown angles." },
        { label: "Guided practice (10 min):", content: "Students identify and use corresponding, alternate and co-interior angles to find unknowns." },
        { label: "Check (4 min):", content: "Exit question: a co-interior angle is 70°. What is the other co-interior angle?" },
      ],
      vocab: "parallel, transversal, corresponding, alternate, co-interior, equal, supplementary",
      support: "Colour-code each angle pair on the diagram.",
      extension: "Find every angle in a parallel-line diagram given just one angle.",
      assessment: "Students use parallel-line angle relationships — extends Y1.",
    },
    {
      num: 13, band: "G",
      title: "Solving numerical angle problems",
      outcomes: ["G3"], duration: "30 min",
      syllabus: "MA4-ANG-C-01, MAO-WM-01 | Stage 4: solve numerical angle problems with reasoning",
      source: "Original mini lesson (Stage 4 extension)",
      li: "solve numerical angle problems by combining angle relationships and giving reasons",
      sc: [
        "I can choose the right angle relationship to use.",
        "I can combine relationships to find an unknown angle in steps.",
        "I can give a reason for each step.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "A diagram has an unknown angle that needs two steps. What relationships could help?" },
        { label: "Model (12 min):", content: "Work a multi-step problem: use angles on a straight line (180°) to find one angle, then vertically opposite to find another, giving a reason each time." },
        { label: "Guided practice (10 min):", content: "Students solve multi-step angle problems, writing a reason for each step." },
        { label: "Check (4 min):", content: "Exit question: find x using two angle relationships and state your reasons." },
      ],
      vocab: "reasoning, relationship, straight line, point, vertically opposite, supplementary, reason",
      support: "Prompt with 'which angles add to 180° or 360° here?' for each step.",
      extension: "Create a multi-step angle puzzle for a partner and provide a worked solution.",
      assessment: "Students solve numerical angle problems — extends R4/G1.",
    },
  ],
};
