const PREFIXES = [
  { id:"ad", stage:"s3e", form:"ad", display:"ad-", meaning:"towards; to", allowedPos:["noun","adj","verb"], altForms:["ac","af","ag","al","an","ap","ar","as","at"], examples:["<u>ad</u>here","<u>ad</u>join","<u>ad</u>mit","<u>ad</u>vance","<u>ad</u>apt","<u>ad</u>venture"] },
  { id:"anti", stage:"s2l", form:"anti", display:"anti-", meaning:"against", allowedPos:["noun","adj","verb"], examples:["<u>anti</u>social","<u>anti</u>clockwise","<u>anti</u>biotic","<u>anti</u>septic","<u>anti</u>freeze","<u>anti</u>dote"] },
  { id:"con", stage:"s3e", form:"con", display:"con-", meaning:"with or together", allowedPos:["noun","adj","verb"], altForms:["com","col","cor","co"], examples:["<u>con</u>nect","<u>con</u>struct","<u>con</u>tract","<u>con</u>trol","<u>con</u>tribute","<u>con</u>firm"] },
  { id:"contra", stage:"s3e", form:"contra", display:"contra-", meaning:"against; opposite", allowedPos:["noun","adj","verb"], examples:["<u>contra</u>dict","<u>contra</u>st","<u>contra</u>vene","<u>contra</u>band","<u>contra</u>dict<u>ion</u>","<u>contra</u>ry"] },
  { id:"de", stage:"s2e", form:"de", display:"de-", meaning:"undo; remove; down", allowedPos:["verb"], examples:["<u>de</u>activate","<u>de</u>compose","<u>de</u>rail","<u>de</u>frost","<u>de</u>value","<u>de</u>code"] },
  { id:"dis", stage:"s2e", form:"dis", display:"dis-", meaning:"not; opposite; apart", allowedPos:["noun","adj","verb"], examples:["<u>dis</u>agree","<u>dis</u>connect","<u>dis</u>like","<u>dis</u>appear","<u>dis</u>cover","<u>dis</u>honest"] },
  { id:"en", stage:"s2e", form:"en", display:"en-", meaning:"cause to; make", allowedPos:["verb"], altForms:["em"], examples:["<u>en</u>able","<u>en</u>rich","<u>en</u>large","<u>en</u>courage","<u>en</u>force","<u>en</u>sure"] },
  { id:"em", stage:"s3e", form:"em", display:"em-", meaning:"cause to; make", allowedPos:["verb"], examples:["<u>em</u>power","<u>em</u>bed","<u>em</u>brace","<u>em</u>bark","<u>em</u>bolden","<u>em</u>phasise"] },
  { id:"ex", stage:"s3e", form:"ex", display:"ex-", meaning:"out of; former", allowedPos:["noun","adj"], examples:["<u>ex</u>port","<u>ex</u>clude","<u>ex</u>hale","<u>ex</u>plore","<u>ex</u>plain","<u>ex</u>pand"] },
  { id:"e", stage:"s4", form:"e", display:"e-", meaning:"electronic; online", allowedPos:["noun","adj"], examples:["<u>e</u>mail","<u>e</u>book","<u>e</u>commerce","<u>e</u>learning","<u>e</u>sport","<u>e</u>card"] },
  { id:"extra", stage:"s3e", form:"extra", display:"extra-", meaning:"beyond", allowedPos:["noun","adj"], examples:["<u>extra</u>ordinary","<u>extra</u>curricular","<u>extra</u>large","<u>extra</u>terrestrial","<u>extra</u>time","<u>extra</u>special"] },
  { id:"fore", stage:"s3e", form:"fore", display:"fore-", meaning:"before", allowedPos:["noun","adj"], examples:["<u>fore</u>cast","<u>fore</u>head","<u>fore</u>warn","<u>fore</u>see","<u>fore</u>sight","<u>fore</u>ground"] },
  { id:"hyper", stage:"s3e", form:"hyper", display:"hyper-", meaning:"over; excessive", allowedPos:["adj","noun"], examples:["<u>hyper</u>active","<u>hyper</u>link","<u>hyper</u>sensitive","<u>hyper</u>text","<u>hyper</u>ventilate","<u>hyper</u>bole"] },
  { id:"in", stage:"s2e", form:"in", display:"in-", meaning:"not; into", allowedPos:["adj","verb"], altForms:["im","il","ir"], examples:["<u>in</u>correct","<u>in</u>visible","<u>in</u>ject","<u>in</u>complete","<u>in</u>active","<u>in</u>valid"] },
  { id:"inter", stage:"s3e", form:"inter", display:"inter-", meaning:"between", allowedPos:["noun","adj","verb"], examples:["<u>inter</u>act","<u>inter</u>national","<u>inter</u>connect","<u>inter</u>rupt","<u>inter</u>net","<u>inter</u>view"] },
  { id:"mal", stage:"s3e", form:"mal", display:"mal-", meaning:"bad", allowedPos:["noun","adj"], examples:["<u>mal</u>function","<u>mal</u>nourished","<u>mal</u>content","<u>mal</u>treat","<u>mal</u>practice","<u>mal</u>odour"] },
  { id:"mega", stage:"s3e", form:"mega", display:"mega-", meaning:"large", allowedPos:["noun","adj"], examples:["<u>mega</u>phone","<u>mega</u>store","<u>mega</u>byte","<u>mega</u>star","<u>mega</u>pixel","<u>mega</u>hit"] },
  { id:"micro", stage:"s3e", form:"micro", display:"micro-", meaning:"small", allowedPos:["noun","adj"], examples:["<u>micro</u>scope","<u>micro</u>chip","<u>micro</u>wave","<u>micro</u>phone","<u>micro</u>soft","<u>micro</u>organism"] },
  { id:"mid", stage:"s2e", form:"mid", display:"mid-", meaning:"middle", allowedPos:["noun","adj"], examples:["<u>mid</u>day","<u>mid</u>night","<u>mid</u>field","<u>mid</u>term","<u>mid</u>point","<u>mid</u>air"] },
  { id:"mis", stage:"s2e", form:"mis", display:"mis-", meaning:"wrong", allowedPos:["verb"], examples:["<u>mis</u>read","<u>mis</u>take","<u>mis</u>place","<u>mis</u>understand","<u>mis</u>behave","<u>mis</u>spell"] },
  { id:"multi", stage:"s2l", form:"multi", display:"multi-", meaning:"many", allowedPos:["noun","adj"], examples:["<u>multi</u>colour","<u>multi</u>media","<u>multi</u>purpose","<u>multi</u>player","<u>multi</u>task","<u>multi</u>cultural"] },
  { id:"non", stage:"s2e", form:"non", display:"non-", meaning:"not", allowedPos:["noun","adj"], examples:["<u>non</u>fiction","<u>non</u>stop","<u>non</u>violent","<u>non</u>sense","<u>non</u>renewable","<u>non</u>profit"] },
  { id:"over", stage:"s2l", form:"over", display:"over-", meaning:"too much", allowedPos:["verb","adj"], examples:["<u>over</u>cook","<u>over</u>load","<u>over</u>react","<u>over</u>power","<u>over</u>estimate","<u>over</u>confident"] },
  { id:"post", stage:"s3e", form:"post", display:"post-", meaning:"after", allowedPos:["noun","adj"], examples:["<u>post</u>war","<u>post</u>pone","<u>post</u>season","<u>post</u>graduate","<u>post</u>script","<u>post</u>modern"] },
  { id:"pre", stage:"s2e", form:"pre", display:"pre-", meaning:"before", allowedPos:["noun","adj","verb"], examples:["<u>pre</u>view","<u>pre</u>dict","<u>pre</u>pare","<u>pre</u>school","<u>pre</u>heat","<u>pre</u>caution"] },
  { id:"pro", stage:"s3e", form:"pro", display:"pro-", meaning:"in favour of; forward", allowedPos:["noun","adj"], examples:["<u>pro</u>active","<u>pro</u>mote","<u>pro</u>government","<u>pro</u>gress","<u>pro</u>tect","<u>pro</u>duce"] },
  { id:"re", stage:"s2e", form:"re", display:"re-", meaning:"again", allowedPos:["verb"], examples:["<u>re</u>write","<u>re</u>build","<u>re</u>turn","<u>re</u>play","<u>re</u>load","<u>re</u>think"] },
  { id:"semi", stage:"s2e", form:"semi", display:"semi-", meaning:"half", allowedPos:["noun","adj"], examples:["<u>semi</u>circle","<u>semi</u>final","<u>semi</u>colon","<u>semi</u>detached","<u>semi</u>precious","<u>semi</u>darkness"] },
  { id:"sub", stage:"s2e", form:"sub", display:"sub-", meaning:"under; below", allowedPos:["noun","adj","verb"], altForms:["suc","suf","sug","sup","sus","subt"], examples:["<u>sub</u>marine","<u>sub</u>tract","<u>sub</u>heading","<u>sub</u>way","<u>sub</u>urban","<u>sub</u>stitute"] },
  { id:"super", stage:"s2l", form:"super", display:"super-", meaning:"above; beyond", allowedPos:["noun","adj","verb"], examples:["<u>super</u>market","<u>super</u>human","<u>super</u>charge","<u>super</u>hero","<u>super</u>natural","<u>super</u>power"] },
  { id:"trans", stage:"s2e", form:"trans", display:"trans-", meaning:"across", allowedPos:["noun","adj","verb"], examples:["<u>trans</u>port","<u>trans</u>fer","<u>trans</u>form","<u>trans</u>late","<u>trans</u>parent","<u>trans</u>action"] },
  { id:"un", stage:"s2e", form:"un", display:"un-", meaning:"not", allowedPos:["adj","verb"], examples:["<u>un</u>happy","<u>un</u>lock","<u>un</u>fair","<u>un</u>kind","<u>un</u>usual","<u>un</u>safe"] },
  { id:"under", stage:"s2l", form:"under", display:"under-", meaning:"below", allowedPos:["noun","adj","verb"], examples:["<u>under</u>line","<u>under</u>pay","<u>under</u>ground","<u>under</u>water","<u>under</u>estimate","<u>under</u>cover"] },
  { id:"ob", stage:"s3l", form:"ob", display:"ob-", meaning:"against; in the way of; towards", allowedPos:["noun","adj","verb"], altForms:["oc","of","op","os","obt"], examples:["<u>ob</u>ject","<u>ob</u>serve","<u>ob</u>struct","<u>ob</u>tain","<u>ob</u>stacle","<u>ob</u>vious"] },
  { id:"a", stage:"s4", form:"a", display:"a-", meaning:"not; without", allowedPos:["adj","noun"], examples:["<u>a</u>moral","<u>a</u>typical","<u>a</u>sexual","<u>a</u>symmetric","<u>a</u>social","<u>a</u>political"] },
  { id:"tele", stage:"s2l", form:"tele", display:"tele-", meaning:"far; distant", allowedPos:["noun","adj","verb"], examples:["<u>tele</u>scope","<u>tele</u>graph","<u>tele</u>gram","<u>tele</u>phone","<u>tele</u>vision","<u>tele</u>path"] },
  { id:"peri", stage:"s3l", form:"peri", display:"peri-", meaning:"around", allowedPos:["noun","adj"], examples:["<u>peri</u>scope","<u>peri</u>meter","<u>peri</u>pheral","<u>peri</u>od","<u>peri</u>odic","<u>peri</u>winkle"] },
  { id:"gyro", stage:"s3l", form:"gyro", display:"gyro-", meaning:"circle; spinning", allowedPos:["noun"], examples:["<u>gyro</u>scope","<u>gyro</u>compass","<u>gyro</u>scopic","<u>gyro</u>stat","<u>gyro</u>pilot","<u>gyro</u>plane"] },
  { id:"endo", stage:"s4", form:"endo", display:"endo-", meaning:"within; inside", allowedPos:["noun","adj"], examples:["<u>endo</u>scope","<u>endo</u>crine","<u>endo</u>skeleton","<u>endo</u>derm","<u>endo</u>thermic","<u>endo</u>thelium"] },
  { id:"horo", stage:"s4", form:"horo", display:"horo-", meaning:"time; hour", allowedPos:["noun"], examples:["<u>horo</u>scope","<u>horo</u>logy","<u>horo</u>logical","<u>horo</u>logist","<u>horo</u>meter","<u>horo</u>metric"] },
  { id:"stetho", stage:"s4", form:"stetho", display:"stetho-", meaning:"chest", allowedPos:["noun"], examples:["<u>stetho</u>scope","<u>stetho</u>scopic","<u>stetho</u>scopically","<u>stetho</u>phonometer","<u>stetho</u>graph","<u>stetho</u>meter"] },
  { id:"kaleido", stage:"s4", form:"kaleido", display:"kaleido-", meaning:"beautiful form", allowedPos:["noun"], examples:["<u>kaleido</u>scope","<u>kaleido</u>scopic","<u>kaleido</u>scopically","<u>kaleido</u>phonics","<u>kaleido</u>phone","<u>kaleido</u>vision"] },
  { id:"be", stage:"s2l", form:"be", display:"be-", meaning:"to make; cause to be", allowedPos:["verb","adj"], examples:["<u>be</u>friend","<u>be</u>little","<u>be</u>witch","<u>be</u>long","<u>be</u>come","<u>be</u>have"] },
  { id:"hypo", stage:"s3e", form:"hypo", display:"hypo-", meaning:"under; below; less than normal", allowedPos:["noun","adj"], examples:["<u>hypo</u>thermia","<u>hypo</u>dermic","<u>hypo</u>thesis","<u>hypo</u>glycaemia","<u>hypo</u>crite","<u>hypo</u>thetical"] },
  { id:"circum", stage:"s3e", form:"circum", display:"circum-", meaning:"around", allowedPos:["noun","verb","adj"], examples:["<u>circum</u>ference","<u>circum</u>navigate","<u>circum</u>stance","<u>circum</u>spect","<u>circum</u>polar","<u>circum</u>vent"] },
  { id:"uni", stage:"s3e", form:"uni", display:"uni-", meaning:"one; single", allowedPos:["noun","adj","verb"], examples:["<u>uni</u>form","<u>uni</u>verse","<u>uni</u>te","<u>uni</u>cycle","<u>uni</u>corn","<u>uni</u>versal"] },
  { id:"arch", stage:"s3l", form:"arch", display:"arch-", meaning:"chief; most important", allowedPos:["noun","adj"], examples:["<u>arch</u>enemy","<u>arch</u>bishop","<u>arch</u>rival","<u>arch</u>angel","<u>arch</u>villain","<u>arch</u>duke"] }
];

const SUFFIXES = [
  { id:"s", stage:"s2e", form:"s", display:"-s", meaning:"plural or present tense", allowedPos:["noun","verb"], hint:"books, runs", examples:["book<u>s</u>","run<u>s</u>","car<u>s</u>","tree<u>s</u>","jump<u>s</u>","friend<u>s</u>"] },
  { id:"es", stage:"s2e", form:"es", display:"-es", meaning:"plural or present tense", allowedPos:["noun","verb"], hint:"boxes, watches", examples:["box<u>es</u>","watch<u>es</u>","dish<u>es</u>","brush<u>es</u>","class<u>es</u>","reach<u>es</u>"] },
  { id:"ed", stage:"s2e", form:"ed", display:"-ed", meaning:"past tense", allowedPos:["verb"], hint:"played, developed", examples:["play<u>ed</u>","jump<u>ed</u>","develop<u>ed</u>","paint<u>ed</u>","walk<u>ed</u>","help<u>ed</u>"] },
  { id:"ing", stage:"s2e", form:"ing", display:"-ing", meaning:"happening now", allowedPos:["verb"], hint:"building, running", examples:["build<u>ing</u>","runn<u>ing</u>","teach<u>ing</u>","read<u>ing</u>","play<u>ing</u>","think<u>ing</u>"] },
  { id:"en", stage:"s2e", form:"en", display:"-en", meaning:"made of; to make", allowedPos:["adj","verb"], hint:"wooden, widen", examples:["wood<u>en</u>","wid<u>en</u>","strength<u>en</u>","bright<u>en</u>","gold<u>en</u>","sharp<u>en</u>"] },
  { id:"er", stage:"s2e", form:"er", display:"-er", meaning:"person who; more", allowedPos:["verb","adj"], hint:"teacher, faster", examples:["teach<u>er</u>","fast<u>er</u>","farm<u>er</u>","play<u>er</u>","build<u>er</u>","help<u>er</u>"] },
  { id:"or", stage:"s2e", form:"or", display:"-or", meaning:"person who", allowedPos:["verb","noun"], hint:"actor, inventor", examples:["act<u>or</u>","invent<u>or</u>","edit<u>or</u>","direct<u>or</u>","inspect<u>or</u>","operat<u>or</u>"] },
  { id:"est", stage:"s2e", form:"est", display:"-est", meaning:"most", allowedPos:["adj"], hint:"fastest", examples:["fast<u>est</u>","tall<u>est</u>","bright<u>est</u>","kind<u>est</u>","dark<u>est</u>","strong<u>est</u>"] },
  { id:"ly", stage:"s2e", form:"ly", display:"-ly", meaning:"in a way", allowedPos:["adj"], hint:"quickly", examples:["quick<u>ly</u>","calm<u>ly</u>","brave<u>ly</u>","kind<u>ly</u>","safe<u>ly</u>","soft<u>ly</u>"] },
  { id:"ion", stage:"s2l", form:"ion", display:"-ion", meaning:"act or result of", allowedPos:["verb"], hint:"action, creation", examples:["act<u>ion</u>","creat<u>ion</u>","collect<u>ion</u>","inspect<u>ion</u>","discuss<u>ion</u>","invent<u>ion</u>"] },
  { id:"able", stage:"s2l", form:"able", display:"-able", meaning:"able to", allowedPos:["verb"], hint:"usable, movable", examples:["use<u>able</u>","move<u>able</u>","enjoy<u>able</u>","wash<u>able</u>","comfort<u>able</u>","read<u>able</u>"] },
  { id:"ible", stage:"s2l", form:"ible", display:"-ible", meaning:"able to", allowedPos:["verb"], hint:"possible pattern", examples:["vis<u>ible</u>","cred<u>ible</u>","flex<u>ible</u>","poss<u>ible</u>","aud<u>ible</u>","incred<u>ible</u>"] },
  { id:"y", stage:"s2e", form:"y", display:"-y", meaning:"characterised by", allowedPos:["noun"], hint:"rainy", examples:["rain<u>y</u>","cloud<u>y</u>","mess<u>y</u>","wind<u>y</u>","sand<u>y</u>","stick<u>y</u>"] },
  { id:"ful", stage:"s2e", form:"ful", display:"-ful", meaning:"full of", allowedPos:["noun"], hint:"helpful", examples:["help<u>ful</u>","care<u>ful</u>","joy<u>ful</u>","hope<u>ful</u>","power<u>ful</u>","beauty<u>ful</u>"] },
  { id:"less", stage:"s2e", form:"less", display:"-less", meaning:"without", allowedPos:["noun"], hint:"careless", examples:["care<u>less</u>","help<u>less</u>","fear<u>less</u>","hope<u>less</u>","harm<u>less</u>","use<u>less</u>"] },
  { id:"ish", stage:"s2e", form:"ish", display:"-ish", meaning:"somewhat; like", allowedPos:["noun","adj"], hint:"childish", examples:["child<u>ish</u>","green<u>ish</u>","fool<u>ish</u>","self<u>ish</u>","red<u>ish</u>","tall<u>ish</u>"] },
  { id:"ness", stage:"s2e", form:"ness", display:"-ness", meaning:"state of", allowedPos:["adj"], hint:"kindness", examples:["kind<u>ness</u>","happi<u>ness</u>","dark<u>ness</u>","bright<u>ness</u>","weak<u>ness</u>","fair<u>ness</u>"] },
  { id:"ment", stage:"s2e", form:"ment", display:"-ment", meaning:"result of action", allowedPos:["verb"], hint:"development", examples:["develop<u>ment</u>","move<u>ment</u>","excite<u>ment</u>","agree<u>ment</u>","enjoy<u>ment</u>","treat<u>ment</u>"] },
  { id:"al", stage:"s2l", form:"al", display:"-al", meaning:"related to", allowedPos:["noun","verb"], hint:"signal", examples:["sign<u>al</u>","music<u>al</u>","logic<u>al</u>","tradition<u>al</u>","nation<u>al</u>","natur<u>al</u>"] },
  { id:"ial", stage:"s2l", form:"ial", display:"-ial", meaning:"related to", allowedPos:["noun","verb"], hint:"essential pattern", examples:["essent<u>ial</u>","spec<u>ial</u>","industr<u>ial</u>","mater<u>ial</u>","offic<u>ial</u>","commerc<u>ial</u>"] },
  { id:"ty", stage:"s3e", form:"ty", display:"-ty", meaning:"state or quality", allowedPos:["adj"], hint:"safety pattern", examples:["safe<u>ty</u>","cruel<u>ty</u>","royal<u>ty</u>","beau<u>ty</u>","loyal<u>ty</u>","liber<u>ty</u>"] },
  { id:"ity", stage:"s3e", form:"ity", display:"-ity", meaning:"state or quality", allowedPos:["adj"], hint:"responsibility pattern", examples:["abil<u>ity</u>","qual<u>ity</u>","responsibil<u>ity</u>","creativ<u>ity</u>","familiar<u>ity</u>","popular<u>ity</u>"] },
  { id:"ous", stage:"s2l", form:"ous", display:"-ous", meaning:"full of", allowedPos:["noun","verb"], hint:"dangerous pattern", examples:["danger<u>ous</u>","fame<u>ous</u>","poison<u>ous</u>","wonder<u>ous</u>","humour<u>ous</u>","marvel<u>ous</u>"] },
  { id:"ee", stage:"s3e", form:"ee", display:"-ee", meaning:"person who receives", allowedPos:["verb"], hint:"employee pattern", examples:["employ<u>ee</u>","train<u>ee</u>","nomin<u>ee</u>","refug<u>ee</u>","trust<u>ee</u>","intervi<u>ee</u>"] },
  { id:"ist", stage:"s2l", form:"ist", display:"-ist", meaning:"person who", allowedPos:["noun","verb"], hint:"artist", examples:["art<u>ist</u>","scient<u>ist</u>","pian<u>ist</u>","special<u>ist</u>","journal<u>ist</u>","novel<u>ist</u>"] },
  { id:"ance", stage:"s3e", form:"ance", display:"-ance", meaning:"state of", allowedPos:["verb"], hint:"appearance", examples:["appear<u>ance</u>","perform<u>ance</u>","import<u>ance</u>","assist<u>ance</u>","resist<u>ance</u>","toler<u>ance</u>"] },
  { id:"ence", stage:"s3e", form:"ence", display:"-ence", meaning:"state of", allowedPos:["verb"], hint:"existence pattern", examples:["exist<u>ence</u>","depend<u>ence</u>","differ<u>ence</u>","confid<u>ence</u>","evid<u>ence</u>","experi<u>ence</u>"] },
  { id:"ant", stage:"s3e", form:"ant", display:"-ant", meaning:"person or thing that", allowedPos:["verb"], hint:"assistant", examples:["assist<u>ant</u>","occup<u>ant</u>","import<u>ant</u>","hesit<u>ant</u>","domin<u>ant</u>","pleas<u>ant</u>"] },
  { id:"ent", stage:"s3e", form:"ent", display:"-ent", meaning:"person or thing that", allowedPos:["verb"], hint:"student pattern", examples:["stud<u>ent</u>","differ<u>ent</u>","respond<u>ent</u>","pati<u>ent</u>","confid<u>ent</u>","excell<u>ent</u>"] },
  { id:"ate", stage:"s3e", form:"ate", display:"-ate", meaning:"to make; to become", allowedPos:["noun","adj"], hint:"activate pattern", examples:["activ<u>ate</u>","motiv<u>ate</u>","separ<u>ate</u>","creat<u>e</u>","celebr<u>ate</u>","commun<u>icate</u>"] },
  { id:"eer", stage:"s3e", form:"eer", display:"-eer", meaning:"person who", allowedPos:["noun","verb"], hint:"engineer pattern", examples:["engine<u>eer</u>","mountain<u>eer</u>","auction<u>eer</u>","volunt<u>eer</u>","pion<u>eer</u>","puppet<u>eer</u>"] },
  { id:"fy", stage:"s3l", form:"fy", display:"-fy", meaning:"make", allowedPos:["noun","adj"], hint:"simplify pattern", examples:["simpli<u>fy</u>","beauti<u>fy</u>","classi<u>fy</u>","testi<u>fy</u>","solidi<u>fy</u>","magni<u>fy</u>"] },
  { id:"ify", stage:"s3l", form:"ify", display:"-ify", meaning:"make", allowedPos:["noun","adj"], hint:"signify", examples:["sign<u>ify</u>","clar<u>ify</u>","ident<u>ify</u>","just<u>ify</u>","noti<u>fy</u>","qual<u>ify</u>"] },
  { id:"ific", stage:"s3l", form:"ific", display:"-ific", meaning:"making; doing", allowedPos:["noun","verb"], hint:"sign + ific + ant = significant", examples:["spec<u>ific</u>","terr<u>ific</u>","pac<u>ific</u>","scient<u>ific</u>","prolif<u>ic</u>","magn<u>ific</u>ent"] },
  { id:"hood", stage:"s2e", form:"hood", display:"-hood", meaning:"state of", allowedPos:["noun"], hint:"childhood", examples:["child<u>hood</u>","parent<u>hood</u>","brother<u>hood</u>","neighbour<u>hood</u>","adult<u>hood</u>","falsehood"] },
  { id:"ian", stage:"s2l", form:"ian", display:"-ian", meaning:"person connected to", allowedPos:["noun"], hint:"musician pattern", examples:["music<u>ian</u>","librar<u>ian</u>","histor<u>ian</u>","technic<u>ian</u>","magic<u>ian</u>","vegetar<u>ian</u>"] },
  { id:"ic", stage:"s2l", form:"ic", display:"-ic", meaning:"related to", allowedPos:["noun","verb"], hint:"historic pattern", examples:["hero<u>ic</u>","histor<u>ic</u>","bas<u>ic</u>","magnet<u>ic</u>","academ<u>ic</u>","artist<u>ic</u>"] },
  { id:"ive", stage:"s3e", form:"ive", display:"-ive", meaning:"having quality of", allowedPos:["verb","noun"], hint:"active, creative", examples:["act<u>ive</u>","creat<u>ive</u>","support<u>ive</u>","protect<u>ive</u>","effect<u>ive</u>","attract<u>ive</u>"] },
  { id:"ize", stage:"s3e", form:"ize", display:"-ize", meaning:"make", allowedPos:["noun","adj"], hint:"organise uses -ise in Australia", examples:["modern<u>ize</u>","real<u>ize</u>","apolog<u>ize</u>","custom<u>ize</u>","minim<u>ize</u>","categor<u>ize</u>"] },
  { id:"like", stage:"s2e", form:"like", display:"-like", meaning:"like; similar to", allowedPos:["noun"], hint:"childlike", examples:["child<u>like</u>","dream<u>like</u>","human<u>like</u>","war<u>like</u>","life<u>like</u>","crystal<u>like</u>"] },
  { id:"logy", stage:"s3e", form:"logy", display:"-logy", meaning:"study of", allowedPos:["noun"], hint:"biology pattern", examples:["bio<u>logy</u>","geo<u>logy</u>","techno<u>logy</u>","zoo<u>logy</u>","archae<u>ology</u>","psycho<u>logy</u>"] },
  { id:"ologist", stage:"s3e", form:"ologist", display:"-ologist", meaning:"person who studies", allowedPos:["noun"], hint:"biologist pattern", examples:["bi<u>ologist</u>","ge<u>ologist</u>","archae<u>ologist</u>","zo<u>ologist</u>","psych<u>ologist</u>","eco<u>logist</u>"] },
  { id:"ship", stage:"s2e", form:"ship", display:"-ship", meaning:"state or skill", allowedPos:["noun"], hint:"friendship", examples:["friend<u>ship</u>","leader<u>ship</u>","partner<u>ship</u>","member<u>ship</u>","scholar<u>ship</u>","champion<u>ship</u>"] },
  { id:"ure", stage:"s2l", form:"ure", display:"-ure", meaning:"result of", allowedPos:["verb"], hint:"closure pattern", examples:["clos<u>ure</u>","fract<u>ure</u>","press<u>ure</u>","pleas<u>ure</u>","meas<u>ure</u>","struct<u>ure</u>"] },
  { id:"age", stage:"s3e", form:"age", display:"-age", meaning:"result of; state of", allowedPos:["verb","noun"], hint:"storage, package", examples:["stor<u>age</u>","pack<u>age</u>","short<u>age</u>","pass<u>age</u>","cov<u>erage</u>","heri<u>tage</u>"] },
  { id:"ory", stage:"s3e", form:"ory", display:"-ory", meaning:"a place of; characterised by", allowedPos:["verb","noun"], hint:"laboratory, factory", examples:["laborat<u>ory</u>","fact<u>ory</u>","satisfact<u>ory</u>","hist<u>ory</u>","territ<u>ory</u>","dorm<u>itory</u>"] },
  { id:"ary", stage:"s3e", form:"ary", display:"-ary", meaning:"relating to; place associated with", allowedPos:["noun","adj"], hint:"dictionary, library", examples:["diction<u>ary</u>","legend<u>ary</u>","ordin<u>ary</u>","libr<u>ary</u>","vision<u>ary</u>","tempor<u>ary</u>"] },
  { id:"ise", stage:"s3e", form:"ise", display:"-ise", meaning:"to make; to become", allowedPos:["noun","adj","verb"], hint:"Australian spelling of -ize", examples:["organ<u>ise</u>","hospital<u>ise</u>","stabil<u>ise</u>","modern<u>ise</u>","special<u>ise</u>","categor<u>ise</u>"] },
  { id:"ious", stage:"s3e", form:"ious", display:"-ious", meaning:"having qualities of", allowedPos:["noun","verb"], hint:"curious, precious", examples:["cur<u>ious</u>","prec<u>ious</u>","delic<u>ious</u>","ambit<u>ious</u>","nutrit<u>ious</u>","suspic<u>ious</u>"] },
  { id:"eous", stage:"s3e", form:"eous", display:"-eous", meaning:"having qualities of", allowedPos:["noun","verb"], hint:"courageous, gorgeous", examples:["courag<u>eous</u>","gorg<u>eous</u>","outrag<u>eous</u>","advantag<u>eous</u>","simultane<u>ous</u>","homogen<u>eous</u>"] },
  { id:"ative", stage:"s3e", form:"ative", display:"-ative", meaning:"tendency or quality", allowedPos:["verb","noun"], hint:"creative, talkative", examples:["cre<u>ative</u>","talk<u>ative</u>","imagin<u>ative</u>","inform<u>ative</u>","illustr<u>ative</u>","represent<u>ative</u>"] },
  { id:"tion", stage:"s3e", form:"tion", display:"-tion", meaning:"act or process of", allowedPos:["verb"], hint:"most common -ion form", examples:["ac<u>tion</u>","crea<u>tion</u>","na<u>tion</u>","ques<u>tion</u>","direc<u>tion</u>","connec<u>tion</u>"] },
  { id:"sion", stage:"s3e", form:"sion", display:"-sion", meaning:"act or process of", allowedPos:["verb"], hint:"vision, tension", examples:["vi<u>sion</u>","ten<u>sion</u>","mis<u>sion</u>","pas<u>sion</u>","expan<u>sion</u>","expres<u>sion</u>"] },
  { id:"ation", stage:"s3e", form:"ation", display:"-ation", meaning:"act or process of", allowedPos:["verb"], hint:"creation, education", examples:["cre<u>ation</u>","educ<u>ation</u>","inform<u>ation</u>","celebr<u>ation</u>","organis<u>ation</u>","imagin<u>ation</u>"] },
  { id:"pathy", stage:"s4", form:"pathy", display:"-pathy", meaning:"feeling; suffering", allowedPos:["noun"], hint:"sympathy, empathy", examples:["sym<u>pathy</u>","em<u>pathy</u>","tele<u>pathy</u>","anti<u>pathy</u>","idio<u>pathy</u>","socio<u>pathy</u>"] }
];

const CORE_BASES = [
  { id:"act", stage:"s2e", form:"act", meaning:"do", pos:["verb","noun"], examples:["<u>act</u>","<u>act</u>ion","re<u>act</u>","inter<u>act</u>","<u>act</u>ive","<u>act</u>or"] },
  { id:"appear", stage:"s2l", form:"appear", meaning:"come into view", pos:["verb"], examples:["<u>appear</u>","dis<u>appear</u>","appear<u>ance</u>","re<u>appear</u>","<u>appear</u>ed","<u>appear</u>ing"] },
  { id:"apply", stage:"s2l", form:"apply", meaning:"put to use", pos:["verb"], examples:["<u>apply</u>","re<u>apply</u>","apply<u>ing</u>","applic<u>ation</u>","applic<u>ant</u>","applic<u>able</u>"] },
  { id:"argue", stage:"s2l", form:"argue", meaning:"give reasons", pos:["verb"], examples:["<u>argue</u>","argu<u>ment</u>","argu<u>able</u>","<u>argue</u>d","<u>argue</u>ing","counter<u>argue</u>"] },
  { id:"assist", stage:"s3e", form:"assist", meaning:"help", pos:["verb"], examples:["<u>assist</u>","assist<u>ant</u>","assist<u>ance</u>","<u>assist</u>ed","<u>assist</u>ing","<u>assist</u>ive"] },
  { id:"attract", stage:"s2l", form:"attract", meaning:"pull towards", pos:["verb"], examples:["<u>attract</u>","attract<u>ion</u>","attract<u>ive</u>","<u>attract</u>ed","un<u>attract</u>ive","<u>attract</u>or"] },
  { id:"behave", stage:"s2l", form:"behave", meaning:"act in a way", pos:["verb"], examples:["<u>behave</u>","mis<u>behave</u>","behav<i>i</i>our","<u>behave</u>d","<u>behave</u>ing","well-<u>behave</u>d"] },
  { id:"believe", stage:"s2l", form:"believe", meaning:"think something is true", pos:["verb"], examples:["<u>believe</u>","un<u>believe</u>able","believ<u>er</u>","<u>believe</u>d","<u>believe</u>r","dis<u>believe</u>"] },
  { id:"build", stage:"s2e", form:"build", meaning:"make by putting parts together", pos:["verb"], examples:["<u>build</u>","re<u>build</u>","build<u>ing</u>","<u>build</u>er","un<u>build</u>","<u>build</u>s"] },
  { id:"care", stage:"s2e", form:"care", meaning:"look after; attention", pos:["verb","noun"], examples:["<u>care</u>","care<u>ful</u>","care<u>less</u>","care<u>taker</u>","<u>care</u>r","self-<u>care</u>"] },
  { id:"collect", stage:"s2e", form:"collect", meaning:"gather together", pos:["verb"], examples:["<u>collect</u>","collect<u>ion</u>","re<u>collect</u>","<u>collect</u>or","<u>collect</u>ive","<u>collect</u>ibles"] },
  { id:"communicate", stage:"s3e", form:"communicate", meaning:"share information", pos:["verb"], examples:["<u>communicate</u>","communicat<u>ion</u>","communicat<u>or</u>","mis<u>communicate</u>","communic<u>ative</u>","<u>communicate</u>d"] },
  { id:"connect", stage:"s2e", form:"connect", meaning:"join together", pos:["verb"], examples:["<u>connect</u>","connect<u>ion</u>","dis<u>connect</u>","re<u>connect</u>","inter<u>connect</u>","<u>connect</u>ed"] },
  { id:"construct", stage:"s2e", form:"construct", meaning:"build", pos:["verb"], examples:["<u>construct</u>","construct<u>ion</u>","re<u>construct</u>","de<u>construct</u>","<u>construct</u>ive","<u>construct</u>or"] },
  { id:"create", stage:"s2e", form:"create", meaning:"make", pos:["verb"], examples:["<u>create</u>","creat<u>ion</u>","creat<u>ive</u>","<u>create</u>d","<u>create</u>r","re<u>create</u>"] },
  { id:"decide", stage:"s2l", form:"decide", meaning:"choose after thinking", pos:["verb"], examples:["<u>decide</u>","decis<u>ion</u>","decis<u>ive</u>","un<u>decide</u>d","<u>decide</u>dly","in<u>decide</u>nt"] },
  { id:"develop", stage:"s2l", form:"develop", meaning:"grow or improve", pos:["verb"], examples:["<u>develop</u>","develop<u>ment</u>","develop<u>ed</u>","<u>develop</u>er","<u>develop</u>ing","un<u>develop</u>ed"] },
  { id:"direct", stage:"s2l", form:"direct", meaning:"guide; control", pos:["verb","adj"], examples:["<u>direct</u>","re<u>direct</u>","direct<u>ion</u>","<u>direct</u>or","in<u>direct</u>","<u>direct</u>ly"] },
  { id:"educate", stage:"s3e", form:"educate", meaning:"teach", pos:["verb"], examples:["<u>educate</u>","educat<u>ion</u>","educat<u>or</u>","educat<u>ional</u>","<u>educate</u>d","un<u>educate</u>d"] },
  { id:"employ", stage:"s2l", form:"employ", meaning:"give work to; use", pos:["verb"], examples:["<u>employ</u>","employ<u>ee</u>","employ<u>ment</u>","<u>employ</u>er","un<u>employ</u>ed","self-<u>employ</u>ed"] },
  { id:"encourage", stage:"s2l", form:"encourage", meaning:"support; give confidence", pos:["verb"], examples:["<u>encourage</u>","encourage<u>ment</u>","discourage","<u>encourage</u>d","<u>encourage</u>ing","dis<u>encourage</u>ment"] },
  { id:"enjoy", stage:"s2e", form:"enjoy", meaning:"like; take pleasure in", pos:["verb"], examples:["<u>enjoy</u>","enjoy<u>able</u>","enjoy<u>ment</u>","<u>enjoy</u>ed","<u>enjoy</u>ing","un<u>enjoy</u>able"] },
  { id:"excite", stage:"s2e", form:"excite", meaning:"make interested or happy", pos:["verb"], examples:["<u>excite</u>","excit<u>ed</u>","excit<u>ement</u>","<u>excite</u>s","excit<u>ing</u>","over<u>excite</u>d"] },
  { id:"expect", stage:"s2e", form:"expect", meaning:"think will happen", pos:["verb"], examples:["<u>expect</u>","expect<u>ed</u>","un<u>expect</u>ed","expect<u>ation</u>","<u>expect</u>ing","<u>expect</u>ant"] },
  { id:"explore", stage:"s2e", form:"explore", meaning:"investigate", pos:["verb"], examples:["<u>explore</u>","explor<u>er</u>","explorat<u>ion</u>","<u>explore</u>d","<u>explore</u>s","re<u>explore</u>"] },
  { id:"express", stage:"s2e", form:"express", meaning:"show or say", pos:["verb"], examples:["<u>express</u>","express<u>ion</u>","express<u>ive</u>","<u>express</u>ed","<u>express</u>ly","in<u>express</u>ible"] },
  { id:"extend", stage:"s2e", form:"extend", meaning:"make longer; stretch", pos:["verb"], examples:["<u>extend</u>","extend<u>ed</u>","extens<u>ion</u>","<u>extend</u>able","<u>extend</u>ing","over<u>extend</u>ed"] },
  { id:"form", stage:"s2e", form:"form", meaning:"make; shape", pos:["verb","noun"], examples:["<u>form</u>","trans<u>form</u>","form<u>ation</u>","re<u>form</u>","uni<u>form</u>","plat<u>form</u>"] },
  { id:"friend", stage:"s2e", form:"friend", meaning:"a person you like and trust", pos:["noun"], examples:["<u>friend</u>","friend<u>ly</u>","friend<u>ship</u>","be<u>friend</u>","un<u>friend</u>ly","<u>friend</u>less"] },
  { id:"govern", stage:"s2e", form:"govern", meaning:"rule; manage", pos:["verb"], examples:["<u>govern</u>","govern<u>ment</u>","govern<u>or</u>","govern<u>ance</u>","mis<u>govern</u>","<u>govern</u>ing"] },
  { id:"grow", stage:"s2e", form:"grow", meaning:"increase; get bigger", pos:["verb"], examples:["<u>grow</u>","grow<u>th</u>","over<u>grow</u>n","<u>grow</u>er","<u>grow</u>ing","out<u>grow</u>"] },
  { id:"help", stage:"s2e", form:"help", meaning:"give support", pos:["verb","noun"], examples:["<u>help</u>","help<u>ful</u>","help<u>less</u>","<u>help</u>er","<u>help</u>ing","self-<u>help</u>"] },
  { id:"inform", stage:"s2e", form:"inform", meaning:"tell; give information", pos:["verb"], examples:["<u>inform</u>","inform<u>ation</u>","mis<u>inform</u>","<u>inform</u>ed","<u>inform</u>ative","un<u>inform</u>ed"] },
  { id:"inspire", stage:"s2l", form:"inspire", meaning:"encourage; motivate", pos:["verb"], examples:["<u>inspire</u>","inspirat<u>ion</u>","inspir<u>ing</u>","<u>inspire</u>d","<u>inspire</u>s","re<u>inspire</u>"] },
  { id:"introduce", stage:"s2l", form:"introduce", meaning:"bring in; present", pos:["verb"], examples:["<u>introduce</u>","introduct<u>ion</u>","re<u>introduce</u>","<u>introduce</u>d","introduct<u>ory</u>","<u>introduce</u>r"] },
  { id:"invest", stage:"s2e", form:"invest", meaning:"put money into", pos:["verb"], examples:["<u>invest</u>","invest<u>or</u>","invest<u>ment</u>","<u>invest</u>ed","over<u>invest</u>","re<u>invest</u>"] },
  { id:"join", stage:"s2e", form:"join", meaning:"connect", pos:["verb"], examples:["<u>join</u>","re<u>join</u>","join<u>ed</u>","<u>join</u>ing","<u>join</u>er","<u>join</u>t"] },
  { id:"judge", stage:"s2e", form:"judge", meaning:"decide; form an opinion", pos:["verb","noun"], examples:["<u>judge</u>","judg<u>ment</u>","mis<u>judge</u>","<u>judge</u>d","judg<u>ing</u>","poor<u>judge</u>ment"] },
  { id:"learn", stage:"s2e", form:"learn", meaning:"gain knowledge", pos:["verb"], examples:["<u>learn</u>","learn<u>er</u>","learn<u>ing</u>","<u>learn</u>ed","re<u>learn</u>","un<u>learn</u>"] },
  { id:"locate", stage:"s2l", form:"locate", meaning:"find where something is", pos:["verb"], examples:["<u>locate</u>","locat<u>ion</u>","re<u>locate</u>","<u>locate</u>d","dis<u>locate</u>","locat<u>or</u>"] },
  { id:"manage", stage:"s2e", form:"manage", meaning:"control; run", pos:["verb"], examples:["<u>manage</u>","manag<u>er</u>","manag<u>ement</u>","mis<u>manage</u>","manag<u>eable</u>","<u>manage</u>d"] },
  { id:"measure", stage:"s2e", form:"measure", meaning:"find size or amount", pos:["verb","noun"], examples:["<u>measure</u>","measure<u>ment</u>","re<u>measure</u>","<u>measure</u>d","<u>measure</u>s","un<u>measure</u>d"] },
  { id:"migrate", stage:"s3e", form:"migrate", meaning:"move to another place", pos:["verb"], examples:["<u>migrate</u>","migrat<u>ion</u>","im<u>migrate</u>","<u>migrate</u>d","migrant","e<u>migrate</u>"] },
  { id:"motivate", stage:"s3e", form:"motivate", meaning:"make someone want to act", pos:["verb"], examples:["<u>motivate</u>","motivat<u>ion</u>","un<u>motivated</u>","<u>motivate</u>d","motivat<u>ional</u>","<u>motivate</u>s"] },
  { id:"move", stage:"s2e", form:"move", meaning:"go from one place to another", pos:["verb"], examples:["<u>move</u>","move<u>ment</u>","re<u>move</u>","<u>move</u>able","<u>move</u>r","im<u>move</u>able"] },
  { id:"observe", stage:"s3e", form:"observe", meaning:"watch carefully", pos:["verb"], examples:["<u>observe</u>","observ<u>er</u>","observat<u>ion</u>","<u>observe</u>d","observ<u>able</u>","observ<u>ant</u>"] },
  { id:"operate", stage:"s3e", form:"operate", meaning:"work; run", pos:["verb"], examples:["<u>operate</u>","operat<u>ion</u>","co<u>operate</u>","<u>operate</u>d","operat<u>or</u>","operat<u>ional</u>"] },
  { id:"organise", stage:"s2l", form:"organise", meaning:"plan and arrange", pos:["verb"], examples:["<u>organise</u>","organis<u>er</u>","organis<u>ation</u>","<u>organise</u>d","re<u>organise</u>","dis<u>organise</u>d"] },
  { id:"participate", stage:"s3e", form:"participate", meaning:"take part", pos:["verb"], examples:["<u>participate</u>","participat<u>ion</u>","participat<u>ing</u>","participan<u>t</u>","<u>participate</u>d","non-participat<u>ion</u>"] },
  { id:"perform", stage:"s2l", form:"perform", meaning:"do; carry out", pos:["verb"], examples:["<u>perform</u>","perform<u>ance</u>","out<u>perform</u>","<u>perform</u>er","<u>perform</u>ing","<u>perform</u>ed"] },
  { id:"persuade", stage:"s3e", form:"persuade", meaning:"convince", pos:["verb"], examples:["<u>persuade</u>","persuas<u>ion</u>","persuas<u>ive</u>","<u>persuade</u>d","<u>persuade</u>s","un<u>persuade</u>d"] },
  { id:"predict", stage:"s2e", form:"predict", meaning:"say before it happens", pos:["verb"], examples:["<u>predict</u>","predict<u>ion</u>","un<u>predict</u>able","<u>predict</u>ed","<u>predict</u>or","<u>predict</u>ive"] },
  { id:"prepare", stage:"s2e", form:"prepare", meaning:"get ready", pos:["verb"], examples:["<u>prepare</u>","preparat<u>ion</u>","un<u>prepared</u>","<u>prepare</u>d","<u>prepare</u>s","preparat<u>ory</u>"] },
  { id:"prevent", stage:"s2e", form:"prevent", meaning:"stop from happening", pos:["verb"], examples:["<u>prevent</u>","prevent<u>ion</u>","prevent<u>ive</u>","<u>prevent</u>ed","<u>prevent</u>able","<u>prevent</u>er"] },
  { id:"produce", stage:"s2e", form:"produce", meaning:"make", pos:["verb"], examples:["<u>produce</u>","produc<u>er</u>","product<u>ion</u>","product<u>ive</u>","re<u>produce</u>","over<u>produce</u>"] },
  { id:"protect", stage:"s2e", form:"protect", meaning:"keep safe", pos:["verb"], examples:["<u>protect</u>","protect<u>ion</u>","protect<u>ive</u>","<u>protect</u>or","<u>protect</u>ed","un<u>protect</u>ed"] },
  { id:"react", stage:"s2e", form:"react", meaning:"respond", pos:["verb"], examples:["re<u>act</u>","react<u>ion</u>","react<u>ive</u>","over<u>react</u>","re<u>act</u>or","re<u>act</u>ed"] },
  { id:"reduce", stage:"s2l", form:"reduce", meaning:"make smaller", pos:["verb"], examples:["<u>reduce</u>","reduct<u>ion</u>","reduc<u>ed</u>","reduc<u>ible</u>","ir<u>reduce</u>ible","<u>reduce</u>s"] },
  { id:"reflect", stage:"s2e", form:"reflect", meaning:"think back; show", pos:["verb"], examples:["re<u>flect</u>","reflect<u>ion</u>","reflect<u>ive</u>","reflect<u>or</u>","re<u>flect</u>ed","self-reflect<u>ion</u>"] },
  { id:"reject", stage:"s2e", form:"reject", meaning:"refuse", pos:["verb"], examples:["re<u>ject</u>","reject<u>ion</u>","reject<u>ed</u>","<u>reject</u>s","self-re<u>ject</u>ion","re<u>ject</u>able"] },
  { id:"relate", stage:"s2e", form:"relate", meaning:"connect; link", pos:["verb"], examples:["<u>relate</u>","relat<u>ion</u>","relat<u>ed</u>","un<u>relate</u>d","relat<u>ionship</u>","relat<u>ive</u>"] },
  { id:"remove", stage:"s2e", form:"remove", meaning:"take away", pos:["verb"], examples:["re<u>move</u>","remov<u>al</u>","re<u>moved</u>","remov<u>able</u>","re<u>move</u>r","ir<u>remove</u>able"] },
  { id:"repair", stage:"s2e", form:"repair", meaning:"fix", pos:["verb"], examples:["re<u>pair</u>","repair<u>ed</u>","repair<u>er</u>","repair<u>able</u>","ir<u>repair</u>able","repair<u>ing</u>"] },
  { id:"replace", stage:"s2e", form:"replace", meaning:"put in place of", pos:["verb"], examples:["re<u>place</u>","replace<u>ment</u>","re<u>placed</u>","replace<u>able</u>","ir<u>replace</u>able","re<u>place</u>r"] },
  { id:"report", stage:"s2e", form:"report", meaning:"tell; write information", pos:["verb","noun"], examples:["re<u>port</u>","report<u>er</u>","report<u>ing</u>","report<u>ed</u>","under<u>report</u>","news<u>report</u>"] },
  { id:"respect", stage:"s2e", form:"respect", meaning:"treat well; value", pos:["verb","noun"], examples:["re<u>spect</u>","respect<u>ful</u>","dis<u>respect</u>","respect<u>able</u>","<u>respect</u>ed","ir<u>respect</u>ive"] },
  { id:"respond", stage:"s2e", form:"respond", meaning:"answer", pos:["verb"], examples:["re<u>spond</u>","respond<u>ed</u>","respond<u>ent</u>","<u>respond</u>er","<u>respond</u>ing","re<u>spond</u>s"] },
  { id:"return", stage:"s2e", form:"return", meaning:"go back; give back", pos:["verb"], examples:["re<u>turn</u>","return<u>ed</u>","return<u>ing</u>","re<u>turn</u>able","re<u>turn</u>s","non-re<u>turn</u>able"] },
  { id:"reveal", stage:"s2l", form:"reveal", meaning:"show; make known", pos:["verb"], examples:["re<u>veal</u>","re<u>veal</u>ed","un<u>reveal</u>ed","re<u>veal</u>ing","re<u>veal</u>s","re<u>veal</u>ation"] },
  { id:"review", stage:"s2e", form:"review", meaning:"look again", pos:["verb","noun"], examples:["re<u>view</u>","review<u>er</u>","review<u>ing</u>","peer re<u>view</u>","re<u>view</u>ed","pre<u>view</u>"] },
  { id:"revise", stage:"s2e", form:"revise", meaning:"improve; study again", pos:["verb"], examples:["re<u>vise</u>","revis<u>ion</u>","revis<u>ed</u>","revis<u>er</u>","re<u>vise</u>s","revis<u>ory</u>"] },
  { id:"rotate", stage:"s3e", form:"rotate", meaning:"turn around", pos:["verb"], examples:["<u>rotate</u>","rotat<u>ion</u>","rotat<u>ing</u>","rotat<u>ory</u>","<u>rotate</u>d","<u>rotate</u>s"] },
  { id:"solve", stage:"s2e", form:"solve", meaning:"find an answer", pos:["verb"], examples:["<u>solve</u>","solv<u>ed</u>","solv<u>ing</u>","<u>solve</u>r","un<u>solve</u>d","resolv<u>e</u>"] },
  { id:"structure", stage:"s2l", form:"structure", meaning:"arrange parts", pos:["noun","verb"], examples:["<u>structure</u>","re<u>structure</u>","structure<u>d</u>","un<u>structure</u>d","infra<u>structure</u>","<u>structure</u>s"] },
  { id:"suggest", stage:"s2l", form:"suggest", meaning:"offer an idea", pos:["verb"], examples:["sug<u>gest</u>","suggest<u>ion</u>","suggest<u>ed</u>","suggest<u>ive</u>","sug<u>gest</u>s","self-sug<u>gest</u>ion"] },
  { id:"support", stage:"s2e", form:"support", meaning:"help; hold up", pos:["verb","noun"], examples:["sup<u>port</u>","support<u>ive</u>","support<u>er</u>","<u>support</u>ed","un<u>support</u>ed","support<u>able</u>"] },
  { id:"transport", stage:"s2e", form:"transport", meaning:"carry from place to place", pos:["verb","noun"], examples:["trans<u>port</u>","transport<u>ed</u>","transport<u>ation</u>","<u>transport</u>er","public <u>transport</u>","transport<u>able</u>"] },
  { id:"trust", stage:"s2e", form:"trust", meaning:"believe someone will do the right thing", pos:["verb","noun"], examples:["<u>trust</u>","<u>trust</u>ed","trust<u>worthy</u>","mis<u>trust</u>","dis<u>trust</u>","<u>trust</u>ful"] },
  { id:"use", stage:"s2e", form:"use", meaning:"do something with", pos:["verb","noun"], examples:["<u>use</u>","use<u>ful</u>","mis<u>use</u>","<u>use</u>less","re<u>use</u>","<u>use</u>r"] },
  { id:"value", stage:"s2e", form:"value", meaning:"how much something is worth", pos:["noun","verb"], examples:["<u>value</u>","de<u>value</u>","valu<u>ed</u>","valu<u>able</u>","over<u>value</u>","<u>value</u>s"] },
  { id:"visit", stage:"s2e", form:"visit", meaning:"go to see", pos:["verb","noun"], examples:["<u>visit</u>","visit<u>or</u>","re<u>visit</u>","<u>visit</u>ed","<u>visit</u>ing","<u>visit</u>ation"] },
  { id:"watch", stage:"s2e", form:"watch", meaning:"look at for a time", pos:["verb","noun"], examples:["<u>watch</u>","watch<u>er</u>","watch<u>ing</u>","over<u>watch</u>","<u>watch</u>ful","<u>watch</u>ed"] },
  { id:"write", stage:"s2e", form:"write", meaning:"put words on a page", pos:["verb"], examples:["<u>write</u>","re<u>write</u>","writ<u>ing</u>","<u>write</u>r","over<u>write</u>","hand<u>write</u>"] },

  { id:"legal", stage:"s2l", form:"legal", meaning:"allowed by law", pos:["adj"], examples:["<u>legal</u>","il<u>legal</u>","legal<u>ity</u>","<u>legal</u>ly","<u>legal</u>ise","non-<u>legal</u>"] },
  { id:"logical", stage:"s2l", form:"logical", meaning:"making sense", pos:["adj"], examples:["<u>logical</u>","il<u>logical</u>","logic","<u>logical</u>ly","bio<u>logical</u>","psycho<u>logical</u>"] },
  { id:"literate", stage:"s2l", form:"literate", meaning:"able to read and write", pos:["adj"], examples:["<u>literate</u>","il<u>literate</u>","literacy","<u>literate</u>ly","semi-<u>literate</u>","numeri<u>cally literate</u>"] },
  { id:"regular", stage:"s2l", form:"regular", meaning:"usual; even pattern", pos:["adj"], examples:["<u>regular</u>","ir<u>regular</u>","regular<u>ly</u>","<u>regular</u>ity","<u>regular</u>ise","semi-<u>regular</u>"] },
  { id:"rational", stage:"s2l", form:"rational", meaning:"reasonable; based on logic", pos:["adj"], examples:["<u>rational</u>","ir<u>rational</u>","rational<u>ity</u>","<u>rational</u>ly","<u>rational</u>ise","<u>rational</u>ism"] },
  { id:"responsible", stage:"s3e", form:"responsible", meaning:"can be trusted to do the right thing", pos:["adj"], examples:["<u>responsible</u>","ir<u>responsible</u>","responsibil<u>ity</u>","<u>responsible</u>ly","un<u>responsible</u>","<u>responsible</u>ness"] },
  { id:"typical", stage:"s2l", form:"typical", meaning:"usual; common", pos:["adj"], examples:["<u>typical</u>","a<u>typical</u>","typic<u>ally</u>","un<u>typical</u>","<u>typical</u>ness","non-<u>typical</u>"] },
  { id:"hero", stage:"s2l", form:"hero", meaning:"a very brave person", pos:["noun"], examples:["<u>hero</u>","hero<u>ic</u>","heroes","super<u>hero</u>","<u>hero</u>ine","<u>hero</u>ism"] },
  { id:"market", stage:"s2e", form:"market", meaning:"place to buy and sell", pos:["noun"], examples:["<u>market</u>","super<u>market</u>","market<u>ing</u>","<u>market</u>place","<u>market</u>er","hyper<u>market</u>"] },
  { id:"power", stage:"s2e", form:"power", meaning:"strength; control; energy", pos:["noun"], examples:["<u>power</u>","em<u>power</u>","power<u>ful</u>","over<u>power</u>","<u>power</u>less","super<u>power</u>"] },
  { id:"fast", stage:"s2e", form:"fast", meaning:"quick", pos:["adj"], examples:["<u>fast</u>","fast<u>er</u>","fast<u>est</u>","<u>fast</u>en","<u>fast</u>ness","break<u>fast</u>"] }
];

const ANGLO_BASE_INFO = {
  teach:{ stage:"s2e", meaning:"to show someone how to do something", pos:["verb"], examples:["<u>teach</u>","teach<u>er</u>","teach<u>ing</u>","<u>teach</u>es","re<u>teach</u>","<u>teach</u>able"] },
  meet:{ stage:"s2e", meaning:"to come together; to see someone", pos:["verb"], examples:["<u>meet</u>","meet<u>ing</u>","re<u>meet</u>","<u>meet</u>s","<u>meet</u>up","<u>meet</u>ings"] },
  rest:{ stage:"s2e", meaning:"to relax; to stop work for a while", pos:["verb","noun"], examples:["<u>rest</u>","rest<u>ful</u>","rest<u>ed</u>","un<u>rest</u>","<u>rest</u>less","<u>rest</u>ing"] },
  go:{ stage:"s2e", meaning:"to move from one place to another", pos:["verb"], examples:["<u>go</u>","under<u>go</u>","go<u>ing</u>","fore<u>go</u>","out<u>go</u>ing","out<u>go</u>s"] },
  tall:{ stage:"s2e", meaning:"having great height", pos:["adj"], examples:["<u>tall</u>","tall<u>er</u>","tall<u>est</u>","tall<u>ness</u>","tall<u>ish</u>","<u>tall</u>-order"] },
  help:{ stage:"s2e", meaning:"to assist; to make easier", pos:["verb","noun"], examples:["<u>help</u>","help<u>ful</u>","help<u>less</u>","<u>help</u>er","<u>help</u>ing","self-<u>help</u>"] },
  ask:{ stage:"s2e", meaning:"to question; to request", pos:["verb"], examples:["<u>ask</u>","ask<u>ed</u>","ask<u>ing</u>","over<u>ask</u>","<u>ask</u>er","<u>ask</u>s"] },
  eat:{ stage:"s2e", meaning:"to consume food", pos:["verb"], examples:["<u>eat</u>","eat<u>ing</u>","over<u>eat</u>","<u>eat</u>en","<u>eat</u>er","out<u>eat</u>"] },
  train:{ stage:"s2e", meaning:"to practise to improve; to teach", pos:["verb","noun"], examples:["<u>train</u>","train<u>er</u>","train<u>ing</u>","re<u>train</u>","<u>train</u>ee","<u>train</u>ed"] },
  usual:{ stage:"s2e", meaning:"common; normal", pos:["adj"], examples:["<u>usual</u>","un<u>usual</u>","usual<u>ly</u>","<u>usual</u>ness","non-<u>usual</u>","as per <u>usual</u>"] },
  end:{ stage:"s2e", meaning:"to finish; the final part", pos:["verb","noun"], examples:["<u>end</u>","end<u>ing</u>","end<u>less</u>","<u>end</u>ed","un<u>end</u>ing","week<u>end</u>"] },
  turn:{ stage:"s2e", meaning:"to change direction; to rotate", pos:["verb","noun"], examples:["<u>turn</u>","re<u>turn</u>","turn<u>ing</u>","over<u>turn</u>","<u>turn</u>ed","up<u>turn</u>"] },
  open:{ stage:"s2e", meaning:"not closed; to make not closed", pos:["adj","verb"], examples:["<u>open</u>","re<u>open</u>","open<u>ing</u>","wide-<u>open</u>","<u>open</u>ly","<u>open</u>ness"] },
  make:{ stage:"s2e", meaning:"to create; to build", pos:["verb"], examples:["<u>make</u>","re<u>make</u>","make<u>r</u>","<u>make</u>shift","home<u>make</u>r","<u>make</u>-believe"] },
  jump:{ stage:"s2e", meaning:"to push off the ground into the air", pos:["verb","noun"], examples:["<u>jump</u>","jump<u>ed</u>","jump<u>ing</u>","<u>jump</u>er","out<u>jump</u>","over<u>jump</u>"] },
  bad:{ stage:"s2e", meaning:"not good; poor quality", pos:["adj"], examples:["<u>bad</u>","bad<u>ly</u>","bad<u>ness</u>","bad<u>ly</u>","<u>bad</u>ger","too <u>bad</u>"] },
  lock:{ stage:"s2e", meaning:"to fasten with a key; a fastening device", pos:["verb","noun"], examples:["<u>lock</u>","un<u>lock</u>","lock<u>ed</u>","dead<u>lock</u>","over<u>lock</u>","<u>lock</u>smith"] },
  move:{ stage:"s2e", meaning:"to change position; to go", pos:["verb"], examples:["<u>move</u>","move<u>ment</u>","re<u>move</u>","<u>move</u>able","im<u>move</u>able","<u>move</u>r"] },
  like:{ stage:"s2e", meaning:"to enjoy; to prefer", pos:["verb"], examples:["<u>like</u>","dis<u>like</u>","like<u>able</u>","<u>like</u>ly","un<u>like</u>ly","<u>like</u>ness"] },
  care:{ stage:"s2e", meaning:"to look after; to feel concern", pos:["verb","noun"], examples:["<u>care</u>","care<u>ful</u>","care<u>less</u>","care<u>taker</u>","self-<u>care</u>","<u>care</u>r"] },
  happy:{ stage:"s2e", meaning:"feeling joy; pleased", pos:["adj"], examples:["<u>happy</u>","un<u>happy</u>","happi<u>ness</u>","<u>happy</u>-go-lucky","over<u>happy</u>","happi<u>ly</u>"] },
  push:{ stage:"s2e", meaning:"to press forward with force", pos:["verb","noun"], examples:["<u>push</u>","push<u>ed</u>","push<u>ing</u>","<u>push</u>er","out<u>push</u>","over<u>push</u>"] },
  zip:{ stage:"s2e", meaning:"to fasten with a zip; to move quickly", pos:["verb","noun"], examples:["<u>zip</u>","zip<u>ped</u>","zip<u>per</u>","un<u>zip</u>","<u>zip</u>s","re<u>zip</u>"] },
  take:{ stage:"s2e", meaning:"to get; to carry; to accept", pos:["verb"], examples:["<u>take</u>","re<u>take</u>","take<u>n</u>","over<u>take</u>","under<u>take</u>","mis<u>take</u>"] },
  see:{ stage:"s2e", meaning:"to look at; to notice", pos:["verb"], examples:["<u>see</u>","fore<u>see</u>","see<u>ing</u>","over<u>see</u>","<u>see</u>able","out<u>see</u>"] },
  brisk:{ stage:"s2e", meaning:"quick and energetic", pos:["adj"], examples:["<u>brisk</u>","brisk<u>ly</u>","brisk<u>ness</u>","<u>brisk</u>er","<u>brisk</u>est","<u>brisk</u>ish"] },
  wake:{ stage:"s2e", meaning:"to stop sleeping", pos:["verb"], examples:["<u>wake</u>","wake<u>ful</u>","wake<u>n</u>","<u>wake</u>-up","re<u>wake</u>n","<u>wake</u>s"] },
  send:{ stage:"s2e", meaning:"to cause to go to a place; to post", pos:["verb"], examples:["<u>send</u>","send<u>er</u>","send<u>ing</u>","re<u>send</u>","over<u>send</u>","<u>send</u>s"] },
  round:{ stage:"s2e", meaning:"shaped like a circle", pos:["adj"], examples:["<u>round</u>","round<u>ed</u>","round<u>ness</u>","<u>round</u>about","all-<u>round</u>","<u>round</u>up"] },
  cloud:{ stage:"s2e", meaning:"a mass of water droplets in the sky", pos:["noun"], examples:["<u>cloud</u>","cloud<u>y</u>","<u>cloud</u>s","over<u>cloud</u>ed","<u>cloud</u>less","rain<u>cloud</u>"] },
  pay:{ stage:"s2e", meaning:"to give money for something", pos:["verb"], examples:["<u>pay</u>","re<u>pay</u>","pay<u>ment</u>","over<u>pay</u>","under<u>pay</u>","<u>pay</u>day"] },
  lift:{ stage:"s2e", meaning:"to raise; to pick up", pos:["verb","noun"], examples:["<u>lift</u>","lift<u>ed</u>","lift<u>ing</u>","air<u>lift</u>","face<u>lift</u>","<u>lift</u>off"] },
  pack:{ stage:"s2e", meaning:"to put things together for carrying; a bundle", pos:["verb","noun"], examples:["<u>pack</u>","pack<u>ed</u>","back<u>pack</u>","<u>pack</u>age","over<u>pack</u>","un<u>pack</u>"] },
  sound:{ stage:"s2e", meaning:"something you hear; noise", pos:["noun"], examples:["<u>sound</u>","sound<u>less</u>","sound<u>ing</u>","<u>sound</u>track","ultra<u>sound</u>","<u>sound</u>proof"] },
  correct:{ stage:"s2e", meaning:"right; accurate", pos:["adj","verb"], examples:["<u>correct</u>","in<u>correct</u>","correct<u>ion</u>","correct<u>ly</u>","correct<u>or</u>","self-correct<u>ing</u>"] },
  part:{ stage:"s2e", meaning:"a piece of something; a section", pos:["noun"], examples:["<u>part</u>","part<u>ly</u>","part<u>ner</u>","counter<u>part</u>","<u>part</u>way","de<u>part</u>"] },
  live:{ stage:"s2e", meaning:"to be alive; to reside", pos:["verb","adj"], examples:["<u>live</u>","out<u>live</u>","live<u>ly</u>","<u>live</u>s","live<u>lihood</u>","<u>live</u>stock"] },
  sad:{ stage:"s2e", meaning:"unhappy; feeling sorrow", pos:["adj"], examples:["<u>sad</u>","sad<u>ly</u>","sad<u>ness</u>","<u>sad</u>den","<u>sad</u>der","<u>sad</u>dest"] },
  trust:{ stage:"s2e", meaning:"to believe someone is reliable; belief", pos:["verb","noun"], examples:["<u>trust</u>","trust<u>ed</u>","trust<u>worthy</u>","mis<u>trust</u>","dis<u>trust</u>","<u>trust</u>ful"] },
  merge:{ stage:"s2e", meaning:"to join together into one", pos:["verb"], examples:["<u>merge</u>","merge<u>r</u>","sub<u>merge</u>","re<u>merge</u>","<u>merge</u>d","<u>merge</u>s"] },
  run:{ stage:"s2e", meaning:"to move quickly on foot", pos:["verb","noun"], examples:["<u>run</u>","run<u>ning</u>","run<u>s</u>","out<u>run</u>","over<u>run</u>","<u>run</u>ner"] },
  plan:{ stage:"s2e", meaning:"to organise what you will do", pos:["verb","noun"], examples:["<u>plan</u>","plan<u>ned</u>","plan<u>ning</u>","<u>plan</u>ner","over<u>plan</u>","re<u>plan</u>"] },
  hop:{ stage:"s2e", meaning:"to jump on one foot", pos:["verb","noun"], examples:["<u>hop</u>","hop<u>ped</u>","hop<u>ing</u>","<u>hop</u>s","over<u>hop</u>","<u>hop</u>scotch"] },
  play:{ stage:"s2e", meaning:"to take part in a game; to have fun", pos:["verb","noun"], examples:["<u>play</u>","re<u>play</u>","play<u>ful</u>","<u>play</u>er","out<u>play</u>","word<u>play</u>"] },
  work:{ stage:"s2e", meaning:"to do a job; effort", pos:["verb","noun"], examples:["<u>work</u>","re<u>work</u>","work<u>er</u>","over<u>work</u>","<u>work</u>shop","net<u>work</u>"] },
  read:{ stage:"s2e", meaning:"to look at and understand words", pos:["verb"], examples:["<u>read</u>","re<u>read</u>","read<u>er</u>","un<u>read</u>","mis<u>read</u>","proof<u>read</u>"] },
  think:{ stage:"s2e", meaning:"to use your mind", pos:["verb"], examples:["<u>think</u>","re<u>think</u>","think<u>er</u>","over<u>think</u>","<u>think</u>ing","un<u>think</u>able"] },
  kind:{ stage:"s2e", meaning:"friendly and caring", pos:["adj","noun"], examples:["<u>kind</u>","un<u>kind</u>","kind<u>ness</u>","kind<u>ly</u>","<u>kind</u>hearted","kind<u>ness</u>"] },
  hope:{ stage:"s2e", meaning:"to wish for something good", pos:["verb","noun"], examples:["<u>hope</u>","hope<u>ful</u>","hope<u>less</u>","<u>hope</u>lessly","<u>hope</u>s","high <u>hope</u>s"] },
  fear:{ stage:"s2e", meaning:"to be afraid of", pos:["verb","noun"], examples:["<u>fear</u>","fear<u>ful</u>","fear<u>less</u>","<u>fear</u>some","out<u>fear</u>","over<u>come</u> <u>fear</u>"] },
  thank:{ stage:"s2e", meaning:"to show you are grateful", pos:["verb","noun"], examples:["<u>thank</u>","thank<u>ful</u>","thank<u>less</u>","<u>thank</u>s","un<u>thank</u>ed","<u>thank</u>sgiving"] },
  harm:{ stage:"s2e", meaning:"to hurt or damage", pos:["verb","noun"], examples:["<u>harm</u>","harm<u>ful</u>","harm<u>less</u>","<u>harm</u>ed","<u>harm</u>ing","no <u>harm</u> done"] },
  taste:{ stage:"s2e", meaning:"the flavour of something", pos:["verb","noun"], examples:["<u>taste</u>","taste<u>ful</u>","taste<u>less</u>","<u>taste</u>d","<u>taste</u>r","fore<u>taste</u>"] },
  doubt:{ stage:"s2e", meaning:"to be unsure about", pos:["verb","noun"], examples:["<u>doubt</u>","doubt<u>ful</u>","un<u>doubt</u>ed","<u>doubt</u>less","<u>doubt</u>er","beyond <u>doubt</u>"] },
  count:{ stage:"s2e", meaning:"to find the total; to matter", pos:["verb","noun"], examples:["<u>count</u>","re<u>count</u>","count<u>er</u>","mis<u>count</u>","<u>count</u>less","<u>count</u>down"] },
  start:{ stage:"s2e", meaning:"to begin", pos:["verb","noun"], examples:["<u>start</u>","re<u>start</u>","start<u>er</u>","head<u>start</u>","out<u>start</u>","false <u>start</u>"] },
  stop:{ stage:"s2e", meaning:"to no longer move or happen", pos:["verb","noun"], examples:["<u>stop</u>","stop<u>ped</u>","non<u>stop</u>","over<u>stop</u>","<u>stop</u>gap","<u>stop</u>page"] },
  hold:{ stage:"s2e", meaning:"to keep in your hands; to contain", pos:["verb","noun"], examples:["<u>hold</u>","hold<u>er</u>","up<u>hold</u>","with<u>hold</u>","<u>hold</u>back","strong<u>hold</u>"] },
  fill:{ stage:"s2e", meaning:"to make full", pos:["verb","noun"], examples:["<u>fill</u>","re<u>fill</u>","fill<u>er</u>","over<u>fill</u>","back<u>fill</u>","<u>fill</u>ing"] },
  print:{ stage:"s2e", meaning:"to put words or pictures on paper", pos:["verb","noun"], examples:["<u>print</u>","re<u>print</u>","print<u>er</u>","mis<u>print</u>","over<u>print</u>","<u>print</u>out"] },
  heat:{ stage:"s2e", meaning:"warmth; to make warm", pos:["verb","noun"], examples:["<u>heat</u>","pre<u>heat</u>","heat<u>er</u>","over<u>heat</u>","re<u>heat</u>","<u>heat</u>wave"] },
  paint:{ stage:"s2e", meaning:"to colour a surface; a coloured liquid", pos:["verb","noun"], examples:["<u>paint</u>","re<u>paint</u>","paint<u>er</u>","over<u>paint</u>","under<u>paint</u>","<u>paint</u>brush"] },
  load:{ stage:"s2e", meaning:"to put things onto; a heavy weight", pos:["verb","noun"], examples:["<u>load</u>","re<u>load</u>","over<u>load</u>","down<u>load</u>","up<u>load</u>","un<u>load</u>"] },
  order:{ stage:"s2e", meaning:"to arrange; a command", pos:["verb","noun"], examples:["<u>order</u>","re<u>order</u>","dis<u>order</u>","in <u>order</u>","<u>order</u>ed","<u>order</u>ly"] },
  spell:{ stage:"s2e", meaning:"to write or say letters in order", pos:["verb","noun"], examples:["<u>spell</u>","mis<u>spell</u>","spell<u>ing</u>","<u>spell</u>bound","<u>spell</u>er","<u>spell</u>check"] },
  clean:{ stage:"s2e", meaning:"free from dirt", pos:["adj","verb"], examples:["<u>clean</u>","clean<u>er</u>","un<u>clean</u>","clean<u>ly</u>","clean<u>up</u>","spring-<u>clean</u>"] },
  sharp:{ stage:"s2e", meaning:"having a fine edge or point", pos:["adj"], examples:["<u>sharp</u>","sharp<u>en</u>","sharp<u>ly</u>","<u>sharp</u>ness","over<u>sharp</u>en","<u>sharp</u>-eyed"] },
  bright:{ stage:"s2e", meaning:"giving out a lot of light; clever", pos:["adj"], examples:["<u>bright</u>","bright<u>en</u>","bright<u>ly</u>","<u>bright</u>ness","<u>bright</u>er","<u>bright</u>est"] },
  fair:{ stage:"s2e", meaning:"treating people equally; just", pos:["adj","noun"], examples:["<u>fair</u>","un<u>fair</u>","fair<u>ly</u>","fair<u>ness</u>","<u>fair</u>ly","fair-<u>minded</u>"] },
  safe:{ stage:"s2e", meaning:"free from danger", pos:["adj","noun"], examples:["<u>safe</u>","safe<u>ly</u>","safe<u>ty</u>","un<u>safe</u>","<u>safe</u>guard","<u>safe</u>keeper"] },
  deep:{ stage:"s2e", meaning:"going far down or in", pos:["adj"], examples:["<u>deep</u>","deep<u>en</u>","deep<u>ly</u>","<u>deep</u>ness","<u>deep</u>er","<u>deep</u>-sea"] },
  weak:{ stage:"s2e", meaning:"not strong", pos:["adj"], examples:["<u>weak</u>","weak<u>en</u>","weak<u>ness</u>","<u>weak</u>ling","<u>weak</u>er","<u>weak</u>-willed"] },
  soft:{ stage:"s2e", meaning:"not hard or rough", pos:["adj"], examples:["<u>soft</u>","soft<u>en</u>","soft<u>ly</u>","<u>soft</u>ness","<u>soft</u>ware","over<u>soft</u>en"] },
  dark:{ stage:"s2e", meaning:"with little or no light", pos:["adj","noun"], examples:["<u>dark</u>","dark<u>en</u>","dark<u>ness</u>","<u>dark</u>er","<u>dark</u>est","mid<u>dark</u>ness"] },
  sweet:{ stage:"s2e", meaning:"tasting like sugar; pleasant", pos:["adj","noun"], examples:["<u>sweet</u>","sweet<u>en</u>","sweet<u>ly</u>","<u>sweet</u>ness","<u>sweet</u>heart","bitter<u>sweet</u>"] },
  quick:{ stage:"s2e", meaning:"moving fast; done in a short time", pos:["adj"], examples:["<u>quick</u>","quick<u>en</u>","quick<u>ly</u>","<u>quick</u>ness","<u>quick</u>er","<u>quick</u>-fire"] },
  slow:{ stage:"s2e", meaning:"not fast", pos:["adj","verb"], examples:["<u>slow</u>","slow<u>ly</u>","slow<u>ness</u>","<u>slow</u>er","<u>slow</u>down","<u>slow</u>poke"] },
  warm:{ stage:"s2e", meaning:"fairly hot; friendly", pos:["adj","verb"], examples:["<u>warm</u>","warm<u>th</u>","warm<u>ly</u>","<u>warm</u>-hearted","over<u>warm</u>","<u>warm</u>-up"] },
  fresh:{ stage:"s2e", meaning:"new; recently made", pos:["adj"], examples:["<u>fresh</u>","re<u>fresh</u>","fresh<u>ly</u>","<u>fresh</u>ness","<u>fresh</u>en","<u>fresh</u>water"] },
  hard:{ stage:"s2e", meaning:"not soft; difficult", pos:["adj"], examples:["<u>hard</u>","hard<u>en</u>","hard<u>ly</u>","<u>hard</u>ness","<u>hard</u>ship","over<u>hard</u>en"] },
  price:{ stage:"s2e", meaning:"the amount of money something costs", pos:["noun","verb"], examples:["<u>price</u>","price<u>less</u>","over<u>price</u>","under<u>price</u>","<u>price</u>d","<u>price</u>tag"] },
  cover:{ stage:"s2e", meaning:"to put something over; to include", pos:["verb","noun"], examples:["<u>cover</u>","dis<u>cover</u>","un<u>cover</u>","re<u>cover</u>","under<u>cover</u>","<u>cover</u>age"] },
  land:{ stage:"s2e", meaning:"an area of ground; to arrive", pos:["noun","verb"], examples:["<u>land</u>","<u>land</u>ing","mid<u>land</u>","over<u>land</u>","<u>land</u>lord","<u>land</u>scape"] },
  test:{ stage:"s2e", meaning:"to check or try out", pos:["verb","noun"], examples:["<u>test</u>","test<u>er</u>","re<u>test</u>","<u>test</u>ed","over<u>test</u>","<u>test</u>ing"] },
  grace:{ stage:"s2e", meaning:"beauty of movement; a prayer", pos:["noun","verb"], examples:["<u>grace</u>","grace<u>ful</u>","dis<u>grace</u>","grace<u>fully</u>","un<u>grace</u>ful","<u>grace</u>s"] },
  comfort:{ stage:"s3e", meaning:"a state of ease; to soothe", pos:["noun","verb"], examples:["<u>comfort</u>","dis<u>comfort</u>","comfort<u>able</u>","<u>comfort</u>ed","un<u>comfort</u>able","<u>comfort</u>er"] },
  agree:{ stage:"s2e", meaning:"to have the same opinion", pos:["verb"], examples:["<u>agree</u>","dis<u>agree</u>","agree<u>ment</u>","<u>agree</u>able","<u>agree</u>s","dis<u>agree</u>ment"] },
  colour:{ stage:"s2e", meaning:"the property of light; to add colour", pos:["noun","verb"], examples:["<u>colour</u>","dis<u>colour</u>","colour<u>ful</u>","multi<u>colour</u>","<u>colour</u>less","<u>colour</u>ed"] }
};

const ANGLO_BASE_LIST = [
  "teach","meet","rest","go","tall","help","ask","eat","train","usual","end","turn","open","make","jump","bad","lock",
  "move","like","care","happy","push","zip","take","see","brisk","wake","send","round","cloud","pay","lift","pack",
  "sound","correct","part","live","sad","trust","merge","run","plan","hop",
  "play","work","read","think","kind","hope","fear","thank","harm","taste","doubt","count","start","stop","hold",
  "fill","print","heat","paint","load","order","spell","clean","sharp","bright","fair","safe","deep","weak","soft",
  "dark","sweet","quick","slow","warm","fresh","hard","price","cover","land","test","grace","comfort","agree","colour"
];

const ANGLO_BASES = ANGLO_BASE_LIST.map((w,i)=>({
  id:`anglo_${i}`,
  stage:(ANGLO_BASE_INFO[w]?.stage || null),
  form:w,
  display:w,
  meaning:(ANGLO_BASE_INFO[w]?.meaning || ""),
  pos:(ANGLO_BASE_INFO[w]?.pos || ["noun","adj","verb"]),
  examples:(ANGLO_BASE_INFO[w]?.examples || [])
}));

const LATIN_BASE_INFO = {
  rupt:{ stage:"s3l", meaning:"break", pos:["verb"], examples:["e<u>rupt</u>","inter<u>rupt</u>","<u>rupt</u>ure","cor<u>rupt</u>","dis<u>rupt</u>","bank<u>rupt</u>"] },
  tract:{ stage:"s3e", meaning:"pull; draw", pos:["verb"], examples:["at<u>tract</u>","con<u>tract</u>","sub<u>tract</u>","ex<u>tract</u>","dis<u>tract</u>","re<u>tract</u>"] },
  form:{ stage:"s2e", meaning:"shape; make", pos:["noun","verb"], examples:["<u>form</u>","trans<u>form</u>","form<u>ation</u>","re<u>form</u>","uni<u>form</u>","plat<u>form</u>"] },
  cred:{ stage:"s2e", meaning:"believe; trust", pos:["verb"], examples:["<u>cred</u>it","in<u>cred</u>ible","cred<u>ible</u>","ac<u>cred</u>it","<u>cred</u>ential","dis<u>cred</u>it"] },
  dic:{ stage:"s2l", meaning:"say; speak", pos:["verb"], examples:["pre<u>dic</u>t","bene<u>dic</u>tion","contra<u>dic</u>t","in<u>dic</u>ate","de<u>dic</u>ate","ver<u>dic</u>t"] },
  dict:{ stage:"s2l", meaning:"say; tell", pos:["verb"], examples:["pre<u>dict</u>","<u>dict</u>ionary","contra<u>dict</u>","e<u>dict</u>","in<u>dict</u>","addict"] },
  struct:{ stage:"s2l", meaning:"build", pos:["verb"], examples:["con<u>struct</u>","<u>struct</u>ure","in<u>struct</u>ion","de<u>struct</u>ion","re<u>struct</u>ure","ob<u>struct</u>"] },
  scrib:{ stage:"s2l", meaning:"write", pos:["verb"], examples:["de<u>scrib</u>e","in<u>scrib</u>e","manu<u>scrib</u>t","pre<u>scrib</u>e","sub<u>scrib</u>e","tran<u>scrib</u>e"] },
  script:{ stage:"s2l", meaning:"written; writing", pos:["noun"], examples:["<u>script</u>","de<u>script</u>ion","manu<u>script</u>","sub<u>script</u>","pre<u>script</u>ion","tran<u>script</u>"] },
  port:{ stage:"s2e", meaning:"carry", pos:["verb"], examples:["trans<u>port</u>","im<u>port</u>","port<u>able</u>","ex<u>port</u>","re<u>port</u>","sup<u>port</u>"] },
  aud:{ stage:"s2e", meaning:"hear", pos:["verb"], examples:["<u>aud</u>io","<u>aud</u>ience","<u>aud</u>ible","<u>aud</u>itorium","<u>aud</u>ition","in<u>aud</u>ible"] },
  flex:{ stage:"s3l", meaning:"bend", pos:["verb"], examples:["<u>flex</u>ible","re<u>flex</u>","<u>flex</u>ion","in<u>flex</u>ible","<u>flex</u>or","<u>flex</u>ibility"] },
  flect:{ stage:"s3l", meaning:"bend", pos:["verb"], examples:["re<u>flect</u>","de<u>flect</u>","in<u>flect</u>ion","in<u>flect</u>","pro<u>flect</u>","circum<u>flect</u>"] },
  ject:{ stage:"s2l", meaning:"throw", pos:["verb"], examples:["re<u>ject</u>","pro<u>ject</u>","e<u>ject</u>","ob<u>ject</u>","sub<u>ject</u>","in<u>ject</u>"] },
  spec:{ stage:"s2l", meaning:"look; see", pos:["verb"], examples:["in<u>spec</u>t","spec<u>ial</u>","retro<u>spec</u>t","sus<u>pect</u>","re<u>spec</u>t","spec<u>tacle</u>"] },
  spect:{ stage:"s2l", meaning:"look; watch", pos:["verb"], examples:["in<u>spect</u>","<u>spect</u>ator","retro<u>spect</u>","ex<u>pect</u>","re<u>spect</u>","circum<u>spect</u>"] },
  spic:{ stage:"s3l", meaning:"look; see", pos:["verb"], examples:["sus<u>pic</u>ion","aus<u>pic</u>ious","per<u>spic</u>uous","con<u>spic</u>uous","sus<u>picion</u>","auspice"] },
  miss:{ stage:"s3e", meaning:"send", pos:["verb"], examples:["dis<u>miss</u>","<u>miss</u>ion","re<u>miss</u>","sub<u>miss</u>ion","per<u>miss</u>ion","ad<u>miss</u>ion"] },
  mit:{ stage:"s3e", meaning:"send", pos:["verb"], examples:["sub<u>mit</u>","per<u>mit</u>","com<u>mit</u>","ad<u>mit</u>","emit","trans<u>mit</u>"] },
  sci:{ stage:"s3l", meaning:"know", pos:["verb"], examples:["<u>sci</u>ence","con<u>sci</u>ous","omni<u>sci</u>ent","<u>sci</u>entist","un<u>sci</u>entific","con<u>sci</u>ence"] },
  pend:{ stage:"s3l", meaning:"hang; weigh", pos:["verb"], examples:["de<u>pend</u>","sus<u>pend</u>","<u>pend</u>ulum","ap<u>pend</u>","com<u>pend</u>ium","im<u>pend</u>ing"] },
  pens:{ stage:"s3l", meaning:"weigh; think", pos:["verb"], examples:["com<u>pens</u>ate","ex<u>pens</u>e","dis<u>pens</u>e","sus<u>pens</u>e","pro<u>pens</u>ity","<u>pens</u>ion"] },
  vis:{ stage:"s2l", meaning:"see", pos:["verb"], examples:["tele<u>vis</u>ion","<u>vis</u>ible","re<u>vis</u>e","in<u>vis</u>ible","<u>vis</u>it","su<u>per</u>vise"] },
  vid:{ stage:"s2l", meaning:"see", pos:["verb"], examples:["e<u>vid</u>ent","pro<u>vid</u>e","indi<u>vid</u>ual","<u>vid</u>eo","<u>vid</u>eo<u>call</u>","<u>vid</u>eographer"] },
  fer:{ stage:"s3e", meaning:"carry; bring", pos:["verb"], examples:["trans<u>fer</u>","of<u>fer</u>","pre<u>fer</u>","dif<u>fer</u>","re<u>fer</u>","con<u>fer</u>"] },
  vers:{ stage:"s3e", meaning:"turn", pos:["verb"], examples:["re<u>vers</u>e","con<u>vers</u>e","uni<u>vers</u>e","di<u>vers</u>e","a<u>vers</u>ion","in<u>vers</u>e"] },
  vert:{ stage:"s3e", meaning:"turn", pos:["verb"], examples:["con<u>vert</u>","in<u>vert</u>","re<u>vert</u>","di<u>vert</u>","sub<u>vert</u>","ad<u>vert</u>"] },
  duc:{ stage:"s3e", meaning:"lead", pos:["verb"], examples:["pro<u>duc</u>e","intro<u>duc</u>e","edu<u>c</u>ate","re<u>duc</u>e","se<u>duc</u>e","in<u>duc</u>e"] },
  duct:{ stage:"s3e", meaning:"lead", pos:["verb"], examples:["con<u>duct</u>","pro<u>duct</u>","re<u>duct</u>ion","intro<u>duct</u>ion","de<u>duct</u>","ab<u>duct</u>"] },
  sec:{ stage:"s2l", meaning:"cut", pos:["verb"], examples:["bi<u>sec</u>t","di<u>sec</u>t","in<u>sec</u>t","tri<u>sec</u>t","<u>sec</u>tion","cross-<u>sec</u>tion"] },
  sect:{ stage:"s2l", meaning:"cut", pos:["verb"], examples:["bi<u>sect</u>","dis<u>sect</u>","<u>sect</u>ion","inter<u>sect</u>","tran<u>sect</u>","vivi<u>sect</u>ion"] },
  claus:{ stage:"s3l", meaning:"close", pos:["verb"], examples:["<u>claus</u>e","con<u>clus</u>ion","ex<u>clus</u>ive","in<u>clus</u>ion","<u>claus</u>trophobia","ex<u>clus</u>ion"] },
  clos:{ stage:"s3l", meaning:"close", pos:["verb"], examples:["<u>clos</u>e","en<u>clos</u>e","dis<u>clos</u>e","<u>clos</u>ure","fore<u>clos</u>e","<u>clos</u>ed"] },
  vit:{ stage:"s3l", meaning:"life", pos:["noun"], examples:["<u>vit</u>al","<u>vit</u>amin","in<u>vit</u>e","<u>vit</u>ality","<u>vit</u>alise","<u>vit</u>als"] },
  viv:{ stage:"s3l", meaning:"live", pos:["verb"], examples:["sur<u>viv</u>e","re<u>viv</u>e","<u>viv</u>id","<u>viv</u>acious","<u>viv</u>ify","<u>viv</u>isection"] },

  cept:{ stage:"s3l", meaning:"take; receive", pos:["verb"], examples:["ac<u>cept</u>","re<u>cept</u>ion","ex<u>cept</u>","con<u>cept</u>","per<u>cept</u>ion","in<u>cept</u>"] },
  cess:{ stage:"s3l", meaning:"go; yield; give way", pos:["verb"], examples:["ac<u>cess</u>","pro<u>cess</u>","re<u>cess</u>","suc<u>cess</u>","ex<u>cess</u>","ab<u>scess</u>"] },
  fect:{ stage:"s3l", meaning:"make; do", pos:["verb"], examples:["per<u>fect</u>","af<u>fect</u>","ef<u>fect</u>","de<u>fect</u>","in<u>fect</u>","re<u>flect</u>"] },
  fix:{ stage:"s3e", meaning:"fasten; attach", pos:["verb"], examples:["<u>fix</u>","pre<u>fix</u>","suf<u>fix</u>","cru<u>fix</u>","af<u>fix</u>","<u>fix</u>ture"] },
  sign:{ stage:"s3e", meaning:"mark; signal", pos:["verb","noun"], examples:["<u>sign</u>","<u>sign</u>al","de<u>sign</u>","as<u>sign</u>","re<u>sign</u>","<u>sign</u>ature"] },
  tend:{ stage:"s3l", meaning:"stretch; reach", pos:["verb"], examples:["ex<u>tend</u>","at<u>tend</u>","pre<u>tend</u>","in<u>tend</u>","con<u>tend</u>","dis<u>tend</u>"] },
  press:{ stage:"s3e", meaning:"press; push", pos:["verb"], examples:["<u>press</u>","com<u>press</u>","ex<u>press</u>","im<u>press</u>","de<u>press</u>","sup<u>press</u>"] },
  gress:{ stage:"s3l", meaning:"step; go", pos:["verb"], examples:["pro<u>gress</u>","di<u>gress</u>","re<u>gress</u>","con<u>gress</u>","ag<u>gress</u>ion","trans<u>gress</u>"] },
  cede:{ stage:"s3l", meaning:"go; yield", pos:["verb"], examples:["pro<u>cede</u>","re<u>cede</u>","con<u>cede</u>","se<u>cede</u>","pre<u>cede</u>","ac<u>cede</u>"] },
  claim:{ stage:"s3l", meaning:"call out; cry", pos:["verb","noun"], examples:["pro<u>claim</u>","ex<u>claim</u>","re<u>claim</u>","dis<u>claim</u>","ac<u>claim</u>","de<u>claim</u>"] },
  prove:{ stage:"s3l", meaning:"test; show", pos:["verb"], examples:["ap<u>prove</u>","im<u>prove</u>","<u>prove</u>n","dis<u>prove</u>","<u>prove</u>r","un<u>prove</u>n"] },
  ply:{ stage:"s3l", meaning:"fold; bend", pos:["verb"], examples:["ap<u>ply</u>","re<u>ply</u>","mul<u>tiply</u>","im<u>ply</u>","com<u>ply</u>","sup<u>ply</u>"] },
  spire:{ stage:"s3l", meaning:"breathe; live", pos:["verb"], examples:["in<u>spire</u>","re<u>spire</u>","con<u>spire</u>","ex<u>spire</u>","per<u>spire</u>","a<u>spire</u>"] },
  grad:{ stage:"s3l", meaning:"step; go", pos:["verb","noun"], examples:["<u>grad</u>e","<u>grad</u>ual","up<u>grad</u>e","de<u>grad</u>e","<u>grad</u>uate","re<u>tro</u><u>grad</u>e"] },
  mot:{ stage:"s3l", meaning:"move", pos:["verb","noun"], examples:["<u>mot</u>ion","<u>mot</u>or","pro<u>mot</u>e","e<u>mot</u>ion","re<u>mot</u>e","lo<u>com</u>otive"] }
};

const LATIN_BASE_LIST = [
  "rupt","tract","form","cred","dic","dict","struct","scrib","script","port","aud","flex","flect","ject","spec","spect","spic",
  "miss","mit","sci","pend","pens","vis","vid","fer","vers","vert","duc","duct","sec","sect","claus","clos","vit","viv",
  "cept","cess","fect","fix","sign","tend","press","gress","cede","claim","prove","ply","spire",
  "grad","mot"
];

const LATIN_BASES = LATIN_BASE_LIST.map((w,i)=>({
  id:`latin_${i}`,
  stage:(LATIN_BASE_INFO[w]?.stage || null),
  form:w,
  display:w,
  meaning:(LATIN_BASE_INFO[w]?.meaning || ""),
  pos:(LATIN_BASE_INFO[w]?.pos || ["noun","adj","verb"]),
  examples:(LATIN_BASE_INFO[w]?.examples || [])
}));

const GREEK_BASE_INFO = {
  graph:{ stage:"s3e", meaning:"write; drawing", pos:["verb","noun"], examples:["<u>graph</u>","auto<u>graph</u>","bio<u>graph</u>y","photo<u>graph</u>","para<u>graph</u>","geo<u>graph</u>y"] },
  gram:{ stage:"s3e", meaning:"written; something written", pos:["adj","noun"], examples:["tele<u>gram</u>","ana<u>gram</u>","pro<u>gram</u>","dia<u>gram</u>","mono<u>gram</u>","holo<u>gram</u>"] },
  micro:{ stage:"s3e", meaning:"small", pos:["adj"], examples:["<u>micro</u>scope","<u>micro</u>chip","<u>micro</u>wave","<u>micro</u>phone","<u>micro</u>organism","<u>micro</u>film"] },
  hydr:{ stage:"s3e", meaning:"water", pos:["noun"], examples:["de<u>hydr</u>ate","<u>hydr</u>ant","<u>hydr</u>ology","<u>hydr</u>ogen","<u>hydr</u>osphere","<u>hydr</u>otherapy"] },
  hydro:{ stage:"s3e", meaning:"water", pos:["noun"], examples:["<u>hydro</u>logy","<u>hydro</u>electric","<u>hydro</u>plane","<u>hydro</u>gen","<u>hydro</u>therapy","<u>hydro</u>foil"] },
  therm:{ stage:"s3e", meaning:"heat", pos:["noun"], examples:["<u>therm</u>al","geo<u>therm</u>al","<u>therm</u>ometer","hypo<u>therm</u>ia","<u>therm</u>os","endo<u>therm</u>ic"] },
  thermo:{ stage:"s3e", meaning:"heat", pos:["noun"], examples:["<u>thermo</u>meter","<u>thermo</u>stat","<u>thermo</u>s","<u>thermo</u>dynamic","<u>thermo</u>plastic","<u>thermo</u>nuclear"] },
  phon:{ stage:"s3e", meaning:"sound; voice", pos:["noun"], examples:["micro<u>phon</u>e","tele<u>phon</u>e","sym<u>phon</u>y","mega<u>phon</u>e","xyl<u>ophon</u>e","head<u>phon</u>es"] },
  logy:{ stage:"s3e", meaning:"study of", pos:["noun"], examples:["bio<u>logy</u>","geo<u>logy</u>","techno<u>logy</u>","zoo<u>logy</u>","psycho<u>logy</u>","anthro<u>pology</u>"] },
  chron:{ stage:"s3e", meaning:"time", pos:["noun"], examples:["syn<u>chron</u>ise","ana<u>chron</u>ism","<u>chron</u>ic","<u>chron</u>icle","<u>chron</u>ological","syn<u>chron</u>ous"] },
  chrono:{ stage:"s3e", meaning:"time", pos:["noun"], examples:["<u>chrono</u>logy","<u>chrono</u>meter","<u>chrono</u>logical","<u>chrono</u>logy","<u>chrono</u>type","<u>chrono</u>biology"] },
  photo:{ stage:"s3e", meaning:"light", pos:["noun"], examples:["<u>photo</u>graph","<u>photo</u>copy","<u>photo</u>synthesis","<u>photo</u>electric","<u>photo</u>n","<u>photo</u>journalist"] },
  scope:{ stage:"s3e", meaning:"look; view; examine", pos:["noun","verb"], examples:["tele<u>scope</u>","micro<u>scope</u>","peri<u>scope</u>","endo<u>scope</u>","stethoscope","horo<u>scope</u>"] },
  meter:{ stage:"s3e", meaning:"measure", pos:["noun","verb"], examples:["thermo<u>meter</u>","kilo<u>meter</u>","speedo<u>meter</u>","baro<u>meter</u>","alti<u>meter</u>","diame<u>ter</u>"] },
  aero:{ stage:"s4", meaning:"air", pos:["noun"], examples:["<u>aero</u>plane","<u>aero</u>bics","<u>aero</u>dynamic","<u>aero</u>sol","<u>aero</u>nautics","<u>aero</u>batic"] }
};

const GREEK_BASE_LIST = [
  "graph","gram","micro","hydr","hydro","therm","thermo","phon","logy","chron","chrono","photo","scope","meter","aero"
];

const GREEK_BASES = GREEK_BASE_LIST.map((w,i)=>({
  id:`greek_${i}`,
  stage:(GREEK_BASE_INFO[w]?.stage || null),
  form:w,
  display:w,
  meaning:(GREEK_BASE_INFO[w]?.meaning || ""),
  pos:(GREEK_BASE_INFO[w]?.pos || ["noun","adj","verb"]),
  examples:(GREEK_BASE_INFO[w]?.examples || [])
}));

window.MORPHEMES = {
  prefixes: PREFIXES,
  suffixes: SUFFIXES,
  bases: [
    ...CORE_BASES.map(b => ({ ...b, display:b.form, group:"core" })),
    ...ANGLO_BASES.map(b => ({ ...b, group:"anglo" })),
    ...LATIN_BASES.map(b => ({ ...b, group:"latin" })),
    ...GREEK_BASES.map(b => ({ ...b, group:"greek" }))
  ]
};
window.PREFIXES = PREFIXES;
window.SUFFIXES = SUFFIXES;
