const PREFIXES = [
  { id:"ad", form:"ad", display:"ad-", meaning:"towards; to", allowedPos:["noun","adj","verb"], altForms:["ac","af","al","ap","as","at"] },
  { id:"anti", form:"anti", display:"anti-", meaning:"against", allowedPos:["noun","adj","verb"] },
  { id:"con", form:"con", display:"con-", meaning:"with or together", allowedPos:["noun","adj","verb"], altForms:["com"] },
  { id:"contra", form:"contra", display:"contra-", meaning:"against; opposite", allowedPos:["noun","adj","verb"] },
  { id:"de", form:"de", display:"de-", meaning:"undo; remove; down", allowedPos:["verb"] },
  { id:"dis", form:"dis", display:"dis-", meaning:"not; opposite; apart", allowedPos:["noun","adj","verb"] },
  { id:"en", form:"en", display:"en-", meaning:"cause to; make", allowedPos:["verb"], altForms:["em"] },
  { id:"em", form:"em", display:"em-", meaning:"cause to; make", allowedPos:["verb"] },
  { id:"ex", form:"ex", display:"ex-", meaning:"out of; former", allowedPos:["noun","adj"] },
  { id:"e", form:"e", display:"e-", meaning:"electronic; online", allowedPos:["noun","adj"] },
  { id:"extra", form:"extra", display:"extra-", meaning:"beyond", allowedPos:["noun","adj"] },
  { id:"fore", form:"fore", display:"fore-", meaning:"before", allowedPos:["noun","adj"] },
  { id:"hyper", form:"hyper", display:"hyper-", meaning:"over; excessive", allowedPos:["adj","noun"] },
  { id:"in", form:"in", display:"in-", meaning:"not; into", allowedPos:["adj","verb"], altForms:["im","il","ir"] },
  { id:"inter", form:"inter", display:"inter-", meaning:"between", allowedPos:["noun","adj","verb"] },
  { id:"mal", form:"mal", display:"mal-", meaning:"bad", allowedPos:["noun","adj"] },
  { id:"mega", form:"mega", display:"mega-", meaning:"large", allowedPos:["noun","adj"] },
  { id:"micro", form:"micro", display:"micro-", meaning:"small", allowedPos:["noun","adj"] },
  { id:"mid", form:"mid", display:"mid-", meaning:"middle", allowedPos:["noun","adj"] },
  { id:"mis", form:"mis", display:"mis-", meaning:"wrong", allowedPos:["verb"] },
  { id:"multi", form:"multi", display:"multi-", meaning:"many", allowedPos:["noun","adj"] },
  { id:"non", form:"non", display:"non-", meaning:"not", allowedPos:["noun","adj"] },
  { id:"over", form:"over", display:"over-", meaning:"too much", allowedPos:["verb","adj"] },
  { id:"post", form:"post", display:"post-", meaning:"after", allowedPos:["noun","adj"] },
  { id:"pre", form:"pre", display:"pre-", meaning:"before", allowedPos:["noun","adj","verb"] },
  { id:"pro", form:"pro", display:"pro-", meaning:"in favour of; forward", allowedPos:["noun","adj"] },
  { id:"re", form:"re", display:"re-", meaning:"again", allowedPos:["verb"] },
  { id:"semi", form:"semi", display:"semi-", meaning:"half", allowedPos:["noun","adj"] },
  { id:"sub", form:"sub", display:"sub-", meaning:"under; below", allowedPos:["noun","adj","verb"], altForms:["suc","suf","sug","sup","sus","subt"] },
  { id:"super", form:"super", display:"super-", meaning:"above; beyond", allowedPos:["noun","adj","verb"] },
  { id:"trans", form:"trans", display:"trans-", meaning:"across", allowedPos:["noun","adj","verb"] },
  { id:"un", form:"un", display:"un-", meaning:"not", allowedPos:["adj","verb"] },
  { id:"under", form:"under", display:"under-", meaning:"below", allowedPos:["noun","adj","verb"] },
  { id:"ob", form:"ob", display:"ob-", meaning:"against; in the way of; towards", allowedPos:["noun","adj","verb"], altForms:["oc","of","op","os","obt"] },
  { id:"a", form:"a", display:"a-", meaning:"not; without", allowedPos:["adj","noun"] }
];

const SUFFIXES = [
  { id:"s", form:"s", display:"-s", meaning:"plural or present tense", allowedPos:["noun","verb"], hint:"books, runs" },
  { id:"es", form:"es", display:"-es", meaning:"plural or present tense", allowedPos:["noun","verb"], hint:"boxes, watches" },
  { id:"ed", form:"ed", display:"-ed", meaning:"past tense", allowedPos:["verb"], hint:"played, developed" },
  { id:"ing", form:"ing", display:"-ing", meaning:"happening now", allowedPos:["verb"], hint:"building, running" },
  { id:"en", form:"en", display:"-en", meaning:"made of; to make", allowedPos:["adj","verb"], hint:"wooden, widen" },
  { id:"er", form:"er", display:"-er", meaning:"person who; more", allowedPos:["verb","adj"], hint:"teacher, faster" },
  { id:"or", form:"or", display:"-or", meaning:"person who", allowedPos:["verb","noun"], hint:"actor, inventor" },
  { id:"est", form:"est", display:"-est", meaning:"most", allowedPos:["adj"], hint:"fastest" },
  { id:"ly", form:"ly", display:"-ly", meaning:"in a way", allowedPos:["adj"], hint:"quickly" },
  { id:"ion", form:"ion", display:"-ion", meaning:"act or result of", allowedPos:["verb"], hint:"action, creation" },
  { id:"able", form:"able", display:"-able", meaning:"able to", allowedPos:["verb"], hint:"usable, movable" },
  { id:"ible", form:"ible", display:"-ible", meaning:"able to", allowedPos:["verb"], hint:"possible pattern" },
  { id:"y", form:"y", display:"-y", meaning:"characterised by", allowedPos:["noun"], hint:"rainy" },
  { id:"ful", form:"ful", display:"-ful", meaning:"full of", allowedPos:["noun"], hint:"helpful" },
  { id:"less", form:"less", display:"-less", meaning:"without", allowedPos:["noun"], hint:"careless" },
  { id:"ish", form:"ish", display:"-ish", meaning:"somewhat; like", allowedPos:["noun","adj"], hint:"childish" },
  { id:"ness", form:"ness", display:"-ness", meaning:"state of", allowedPos:["adj"], hint:"kindness" },
  { id:"ment", form:"ment", display:"-ment", meaning:"result of action", allowedPos:["verb"], hint:"development" },
  { id:"al", form:"al", display:"-al", meaning:"related to", allowedPos:["noun","verb"], hint:"signal" },
  { id:"ial", form:"ial", display:"-ial", meaning:"related to", allowedPos:["noun","verb"], hint:"essential pattern" },
  { id:"ty", form:"ty", display:"-ty", meaning:"state or quality", allowedPos:["adj"], hint:"safety pattern" },
  { id:"ity", form:"ity", display:"-ity", meaning:"state or quality", allowedPos:["adj"], hint:"responsibility pattern" },
  { id:"ous", form:"ous", display:"-ous", meaning:"full of", allowedPos:["noun","verb"], hint:"dangerous pattern" },
  { id:"ee", form:"ee", display:"-ee", meaning:"person who receives", allowedPos:["verb"], hint:"employee pattern" },
  { id:"ist", form:"ist", display:"-ist", meaning:"person who", allowedPos:["noun","verb"], hint:"artist" },
  { id:"ance", form:"ance", display:"-ance", meaning:"state of", allowedPos:["verb"], hint:"appearance" },
  { id:"ence", form:"ence", display:"-ence", meaning:"state of", allowedPos:["verb"], hint:"existence pattern" },
  { id:"ant", form:"ant", display:"-ant", meaning:"person or thing that", allowedPos:["verb"], hint:"assistant" },
  { id:"ent", form:"ent", display:"-ent", meaning:"person or thing that", allowedPos:["verb"], hint:"student pattern" },
  { id:"ate", form:"ate", display:"-ate", meaning:"to make; to become", allowedPos:["noun","adj"], hint:"activate pattern" },
  { id:"eer", form:"eer", display:"-eer", meaning:"person who", allowedPos:["noun","verb"], hint:"engineer pattern" },
  { id:"fy", form:"fy", display:"-fy", meaning:"make", allowedPos:["noun","adj"], hint:"simplify pattern" },
  { id:"ify", form:"ify", display:"-ify", meaning:"make", allowedPos:["noun","adj"], hint:"signify" },
  { id:"ific", form:"ific", display:"-ific", meaning:"making; doing", allowedPos:["noun","verb"], hint:"sign + ific + ant = significant" },
  { id:"hood", form:"hood", display:"-hood", meaning:"state of", allowedPos:["noun"], hint:"childhood" },
  { id:"ian", form:"ian", display:"-ian", meaning:"person connected to", allowedPos:["noun"], hint:"musician pattern" },
  { id:"ic", form:"ic", display:"-ic", meaning:"related to", allowedPos:["noun","verb"], hint:"historic pattern" },
  { id:"ive", form:"ive", display:"-ive", meaning:"having quality of", allowedPos:["verb","noun"], hint:"active, creative" },
  { id:"ize", form:"ize", display:"-ize", meaning:"make", allowedPos:["noun","adj"], hint:"organise uses -ise in Australia" },
  { id:"like", form:"like", display:"-like", meaning:"like; similar to", allowedPos:["noun"], hint:"childlike" },
  { id:"logy", form:"logy", display:"-logy", meaning:"study of", allowedPos:["noun"], hint:"biology pattern" },
  { id:"ologist", form:"ologist", display:"-ologist", meaning:"person who studies", allowedPos:["noun"], hint:"biologist pattern" },
  { id:"ship", form:"ship", display:"-ship", meaning:"state or skill", allowedPos:["noun"], hint:"friendship" },
  { id:"ure", form:"ure", display:"-ure", meaning:"result of", allowedPos:["verb"], hint:"closure pattern" }
];

const CORE_BASES = [
  { id:"act", form:"act", meaning:"do", pos:["verb","noun"] },
  { id:"appear", form:"appear", meaning:"come into view", pos:["verb"] },
  { id:"apply", form:"apply", meaning:"put to use", pos:["verb"] },
  { id:"argue", form:"argue", meaning:"give reasons", pos:["verb"] },
  { id:"assist", form:"assist", meaning:"help", pos:["verb"] },
  { id:"attract", form:"attract", meaning:"pull towards", pos:["verb"] },
  { id:"behave", form:"behave", meaning:"act in a way", pos:["verb"] },
  { id:"believe", form:"believe", meaning:"think something is true", pos:["verb"] },
  { id:"build", form:"build", meaning:"make by putting parts together", pos:["verb"] },
  { id:"care", form:"care", meaning:"look after; attention", pos:["verb","noun"] },
  { id:"collect", form:"collect", meaning:"gather together", pos:["verb"] },
  { id:"communicate", form:"communicate", meaning:"share information", pos:["verb"] },
  { id:"connect", form:"connect", meaning:"join together", pos:["verb"] },
  { id:"construct", form:"construct", meaning:"build", pos:["verb"] },
  { id:"create", form:"create", meaning:"make", pos:["verb"] },
  { id:"decide", form:"decide", meaning:"choose after thinking", pos:["verb"] },
  { id:"develop", form:"develop", meaning:"grow or improve", pos:["verb"] },
  { id:"direct", form:"direct", meaning:"guide; control", pos:["verb","adj"] },
  { id:"educate", form:"educate", meaning:"teach", pos:["verb"] },
  { id:"employ", form:"employ", meaning:"give work to; use", pos:["verb"] },
  { id:"encourage", form:"encourage", meaning:"support; give confidence", pos:["verb"] },
  { id:"enjoy", form:"enjoy", meaning:"like; take pleasure in", pos:["verb"] },
  { id:"excite", form:"excite", meaning:"make interested or happy", pos:["verb"] },
  { id:"expect", form:"expect", meaning:"think will happen", pos:["verb"] },
  { id:"explore", form:"explore", meaning:"investigate", pos:["verb"] },
  { id:"express", form:"express", meaning:"show or say", pos:["verb"] },
  { id:"extend", form:"extend", meaning:"make longer; stretch", pos:["verb"] },
  { id:"form", form:"form", meaning:"make; shape", pos:["verb","noun"] },
  { id:"friend", form:"friend", meaning:"a person you like and trust", pos:["noun"] },
  { id:"govern", form:"govern", meaning:"rule; manage", pos:["verb"] },
  { id:"grow", form:"grow", meaning:"increase; get bigger", pos:["verb"] },
  { id:"help", form:"help", meaning:"give support", pos:["verb","noun"] },
  { id:"inform", form:"inform", meaning:"tell; give information", pos:["verb"] },
  { id:"inspire", form:"inspire", meaning:"encourage; motivate", pos:["verb"] },
  { id:"introduce", form:"introduce", meaning:"bring in; present", pos:["verb"] },
  { id:"invest", form:"invest", meaning:"put money into", pos:["verb"] },
  { id:"join", form:"join", meaning:"connect", pos:["verb"] },
  { id:"judge", form:"judge", meaning:"decide; form an opinion", pos:["verb","noun"] },
  { id:"learn", form:"learn", meaning:"gain knowledge", pos:["verb"] },
  { id:"locate", form:"locate", meaning:"find where something is", pos:["verb"] },
  { id:"manage", form:"manage", meaning:"control; run", pos:["verb"] },
  { id:"measure", form:"measure", meaning:"find size or amount", pos:["verb","noun"] },
  { id:"migrate", form:"migrate", meaning:"move to another place", pos:["verb"] },
  { id:"motivate", form:"motivate", meaning:"make someone want to act", pos:["verb"] },
  { id:"move", form:"move", meaning:"go from one place to another", pos:["verb"] },
  { id:"observe", form:"observe", meaning:"watch carefully", pos:["verb"] },
  { id:"operate", form:"operate", meaning:"work; run", pos:["verb"] },
  { id:"organise", form:"organise", meaning:"plan and arrange", pos:["verb"] },
  { id:"participate", form:"participate", meaning:"take part", pos:["verb"] },
  { id:"perform", form:"perform", meaning:"do; carry out", pos:["verb"] },
  { id:"persuade", form:"persuade", meaning:"convince", pos:["verb"] },
  { id:"predict", form:"predict", meaning:"say before it happens", pos:["verb"] },
  { id:"prepare", form:"prepare", meaning:"get ready", pos:["verb"] },
  { id:"prevent", form:"prevent", meaning:"stop from happening", pos:["verb"] },
  { id:"produce", form:"produce", meaning:"make", pos:["verb"] },
  { id:"protect", form:"protect", meaning:"keep safe", pos:["verb"] },
  { id:"react", form:"react", meaning:"respond", pos:["verb"] },
  { id:"reduce", form:"reduce", meaning:"make smaller", pos:["verb"] },
  { id:"reflect", form:"reflect", meaning:"think back; show", pos:["verb"] },
  { id:"reject", form:"reject", meaning:"refuse", pos:["verb"] },
  { id:"relate", form:"relate", meaning:"connect; link", pos:["verb"] },
  { id:"remove", form:"remove", meaning:"take away", pos:["verb"] },
  { id:"repair", form:"repair", meaning:"fix", pos:["verb"] },
  { id:"replace", form:"replace", meaning:"put in place of", pos:["verb"] },
  { id:"report", form:"report", meaning:"tell; write information", pos:["verb","noun"] },
  { id:"respect", form:"respect", meaning:"treat well; value", pos:["verb","noun"] },
  { id:"respond", form:"respond", meaning:"answer", pos:["verb"] },
  { id:"return", form:"return", meaning:"go back; give back", pos:["verb"] },
  { id:"reveal", form:"reveal", meaning:"show; make known", pos:["verb"] },
  { id:"review", form:"review", meaning:"look again", pos:["verb","noun"] },
  { id:"revise", form:"revise", meaning:"improve; study again", pos:["verb"] },
  { id:"rotate", form:"rotate", meaning:"turn around", pos:["verb"] },
  { id:"solve", form:"solve", meaning:"find an answer", pos:["verb"] },
  { id:"structure", form:"structure", meaning:"arrange parts", pos:["noun","verb"] },
  { id:"suggest", form:"suggest", meaning:"offer an idea", pos:["verb"] },
  { id:"support", form:"support", meaning:"help; hold up", pos:["verb","noun"] },
  { id:"transport", form:"transport", meaning:"carry from place to place", pos:["verb","noun"] },
  { id:"trust", form:"trust", meaning:"believe someone will do the right thing", pos:["verb","noun"] },
  { id:"use", form:"use", meaning:"do something with", pos:["verb","noun"] },
  { id:"value", form:"value", meaning:"how much something is worth", pos:["noun","verb"] },
  { id:"visit", form:"visit", meaning:"go to see", pos:["verb","noun"] },
  { id:"watch", form:"watch", meaning:"look at for a time", pos:["verb","noun"] },
  { id:"write", form:"write", meaning:"put words on a page", pos:["verb"] },

  { id:"legal", form:"legal", meaning:"allowed by law", pos:["adj"] },
  { id:"logical", form:"logical", meaning:"making sense", pos:["adj"] },
  { id:"literate", form:"literate", meaning:"able to read and write", pos:["adj"] },
  { id:"regular", form:"regular", meaning:"usual; even pattern", pos:["adj"] },
  { id:"rational", form:"rational", meaning:"reasonable; based on logic", pos:["adj"] },
  { id:"responsible", form:"responsible", meaning:"can be trusted to do the right thing", pos:["adj"] },
  { id:"typical", form:"typical", meaning:"usual; common", pos:["adj"] },
  { id:"hero", form:"hero", meaning:"a very brave person", pos:["noun"] },
  { id:"market", form:"market", meaning:"place to buy and sell", pos:["noun"] },
  { id:"power", form:"power", meaning:"strength; control; energy", pos:["noun"] },
  { id:"fast", form:"fast", meaning:"quick", pos:["adj"] }
];

const ANGLO_BASE_INFO = {
  teach:{ meaning:"to show someone how to do something", pos:["verb"] },
  meet:{ meaning:"to come together; to see someone", pos:["verb"] },
  rest:{ meaning:"to relax; to stop work for a while", pos:["verb","noun"] },
  go:{ meaning:"to move from one place to another", pos:["verb"] },
  tall:{ meaning:"having great height", pos:["adj"] },
  help:{ meaning:"to assist; to make easier", pos:["verb","noun"] },
  ask:{ meaning:"to question; to request", pos:["verb"] },
  eat:{ meaning:"to consume food", pos:["verb"] },
  train:{ meaning:"to practise to improve; to teach", pos:["verb","noun"] },
  usual:{ meaning:"common; normal", pos:["adj"] },
  end:{ meaning:"to finish; the final part", pos:["verb","noun"] },
  turn:{ meaning:"to change direction; to rotate", pos:["verb","noun"] },
  open:{ meaning:"not closed; to make not closed", pos:["adj","verb"] },
  make:{ meaning:"to create; to build", pos:["verb"] },
  jump:{ meaning:"to push off the ground into the air", pos:["verb","noun"] },
  bad:{ meaning:"not good; poor quality", pos:["adj"] },
  lock:{ meaning:"to fasten with a key; a fastening device", pos:["verb","noun"] },
  move:{ meaning:"to change position; to go", pos:["verb"] },
  like:{ meaning:"to enjoy; to prefer", pos:["verb"] },
  care:{ meaning:"to look after; to feel concern", pos:["verb","noun"] },
  happy:{ meaning:"feeling joy; pleased", pos:["adj"] },
  push:{ meaning:"to press forward with force", pos:["verb","noun"] },
  zip:{ meaning:"to fasten with a zip; to move quickly", pos:["verb","noun"] },
  take:{ meaning:"to get; to carry; to accept", pos:["verb"] },
  see:{ meaning:"to look at; to notice", pos:["verb"] },
  brisk:{ meaning:"quick and energetic", pos:["adj"] },
  wake:{ meaning:"to stop sleeping", pos:["verb"] },
  send:{ meaning:"to cause to go to a place; to post", pos:["verb"] },
  round:{ meaning:"shaped like a circle", pos:["adj"] },
  cloud:{ meaning:"a mass of water droplets in the sky", pos:["noun"] },
  pay:{ meaning:"to give money for something", pos:["verb"] },
  lift:{ meaning:"to raise; to pick up", pos:["verb","noun"] },
  pack:{ meaning:"to put things together for carrying; a bundle", pos:["verb","noun"] },
  sound:{ meaning:"something you hear; noise", pos:["noun"] },
  correct:{ meaning:"right; accurate", pos:["adj","verb"] },
  part:{ meaning:"a piece of something; a section", pos:["noun"] },
  live:{ meaning:"to be alive; to reside", pos:["verb","adj"] },
  sad:{ meaning:"unhappy; feeling sorrow", pos:["adj"] },
  trust:{ meaning:"to believe someone is reliable; belief", pos:["verb","noun"] },
  merge:{ meaning:"to join together into one", pos:["verb"] },
  run:{ meaning:"to move quickly on foot", pos:["verb","noun"] },
  plan:{ meaning:"to organise what you will do", pos:["verb","noun"] },
  hop:{ meaning:"to jump on one foot", pos:["verb","noun"] }
};

const ANGLO_BASE_LIST = [
  "teach","meet","rest","go","tall","help","ask","eat","train","usual","end","turn","open","make","jump","bad","lock",
  "move","like","care","happy","push","zip","take","see","brisk","wake","send","round","cloud","pay","lift","pack",
  "sound","correct","part","live","sad","trust","merge","run","plan","hop"
];

const ANGLO_BASES = ANGLO_BASE_LIST.map((w,i)=>({
  id:`anglo_${i}`,
  form:w,
  display:w,
  meaning:(ANGLO_BASE_INFO[w]?.meaning || ""),
  pos:(ANGLO_BASE_INFO[w]?.pos || ["noun","adj","verb"])
}));

const LATIN_BASE_INFO = {
  rupt:{ meaning:"break", pos:["verb"] },
  tract:{ meaning:"pull; draw", pos:["verb"] },
  form:{ meaning:"shape; make", pos:["noun","verb"] },
  cred:{ meaning:"believe; trust", pos:["verb"] },
  dic:{ meaning:"say; speak", pos:["verb"] },
  dict:{ meaning:"say; tell", pos:["verb"] },
  struct:{ meaning:"build", pos:["verb"] },
  scrib:{ meaning:"write", pos:["verb"] },
  script:{ meaning:"written; writing", pos:["noun"] },
  port:{ meaning:"carry", pos:["verb"] },
  aud:{ meaning:"hear", pos:["verb"] },
  flex:{ meaning:"bend", pos:["verb"] },
  flect:{ meaning:"bend", pos:["verb"] },
  ject:{ meaning:"throw", pos:["verb"] },
  spec:{ meaning:"look; see", pos:["verb"] },
  spect:{ meaning:"look; watch", pos:["verb"] },
  spic:{ meaning:"look; see", pos:["verb"] },
  miss:{ meaning:"send", pos:["verb"] },
  mit:{ meaning:"send", pos:["verb"] },
  sci:{ meaning:"know", pos:["verb"] },
  pend:{ meaning:"hang; weigh", pos:["verb"] },
  pens:{ meaning:"weigh; think", pos:["verb"] },
  vis:{ meaning:"see", pos:["verb"] },
  vid:{ meaning:"see", pos:["verb"] },
  fer:{ meaning:"carry; bring", pos:["verb"] },
  vers:{ meaning:"turn", pos:["verb"] },
  vert:{ meaning:"turn", pos:["verb"] },
  duc:{ meaning:"lead", pos:["verb"] },
  duct:{ meaning:"lead", pos:["verb"] },
  sec:{ meaning:"cut", pos:["verb"] },
  sect:{ meaning:"cut", pos:["verb"] },
  claus:{ meaning:"close", pos:["verb"] },
  clos:{ meaning:"close", pos:["verb"] },
  vit:{ meaning:"life", pos:["noun"] },
  viv:{ meaning:"live", pos:["verb"] },

  cept:{ meaning:"take; receive", pos:["verb"] },
  cess:{ meaning:"go; yield; give way", pos:["verb"] },
  fect:{ meaning:"make; do", pos:["verb"] },
  fix:{ meaning:"fasten; attach", pos:["verb"] },
  sign:{ meaning:"mark; signal", pos:["verb","noun"] },
  tend:{ meaning:"stretch; reach", pos:["verb"] },
  press:{ meaning:"press; push", pos:["verb"] },
  gress:{ meaning:"step; go", pos:["verb"] },
  cede:{ meaning:"go; yield", pos:["verb"] },
  claim:{ meaning:"call out; cry", pos:["verb","noun"] },
  prove:{ meaning:"test; show", pos:["verb"] },
  ply:{ meaning:"fold; bend", pos:["verb"] },
  spire:{ meaning:"breathe; live", pos:["verb"] }
};

const LATIN_BASE_LIST = [
  "rupt","tract","form","cred","dic","dict","struct","scrib","script","port","aud","flex","flect","ject","spec","spect","spic",
  "miss","mit","sci","pend","pens","vis","vid","fer","vers","vert","duc","duct","sec","sect","claus","clos","vit","viv",
  "cept","cess","fect","fix","sign","tend","press","gress","cede","claim","prove","ply","spire"
];

const LATIN_BASES = LATIN_BASE_LIST.map((w,i)=>({
  id:`latin_${i}`,
  form:w,
  display:w,
  meaning:(LATIN_BASE_INFO[w]?.meaning || ""),
  pos:(LATIN_BASE_INFO[w]?.pos || ["noun","adj","verb"])
}));

const GREEK_BASE_INFO = {
  graph:{ meaning:"write; drawing", pos:["verb","noun"] },
  gram:{ meaning:"written; something written", pos:["adj","noun"] },
  micro:{ meaning:"small", pos:["adj"] },
  hydr:{ meaning:"water", pos:["noun"] },
  hydro:{ meaning:"water", pos:["noun"] },
  therm:{ meaning:"heat", pos:["noun"] },
  thermo:{ meaning:"heat", pos:["noun"] },
  phon:{ meaning:"sound; voice", pos:["noun"] },
  logy:{ meaning:"study of", pos:["noun"] },
  chron:{ meaning:"time", pos:["noun"] },
  chrono:{ meaning:"time", pos:["noun"] },
  photo:{ meaning:"light", pos:["noun"] },
  scope:{ meaning:"look; view; examine", pos:["noun","verb"] },
  meter:{ meaning:"measure", pos:["noun","verb"] },
  aero:{ meaning:"air", pos:["noun"] }
};

const GREEK_BASE_LIST = [
  "graph","gram","micro","hydr","hydro","therm","thermo","phon","logy","chron","chrono","photo","scope","meter","aero"
];

const GREEK_BASES = GREEK_BASE_LIST.map((w,i)=>({
  id:`greek_${i}`,
  form:w,
  display:w,
  meaning:(GREEK_BASE_INFO[w]?.meaning || ""),
  pos:(GREEK_BASE_INFO[w]?.pos || ["noun","adj","verb"])
}));

window.MORPHEMES = {
  prefixes: PREFIXES,
  suffixes: SUFFIXES,
  bases: [
    ...CORE_BASES.map(b => ({ ...b, display:b.form, group:"core" })),
    ...ANGLO_BASES.map(b => ({ ...b, group:"anglo" })),
    ...LATIN_BASES.map(b => ({ ...b, group:"latin" })),
    ...GREEK_BASES.map(b => ({ ...b, group:"greek" }))
  ]
};
