const PREFIXES = [
  { id:"ad", form:"ad", display:"ad-", meaning:"towards; to", allowedPos:["noun","adj","verb"], altForms:["ac","af","ag","al","an","ap","ar","as","at"], examples:["<u>ad</u>here","<u>ad</u>join","<u>ad</u>mit"] },
  { id:"anti", form:"anti", display:"anti-", meaning:"against", allowedPos:["noun","adj","verb"], examples:["<u>anti</u>social","<u>anti</u>clockwise","<u>anti</u>biotic"] },
  { id:"con", form:"con", display:"con-", meaning:"with or together", allowedPos:["noun","adj","verb"], altForms:["com","col","cor","co"], examples:["<u>con</u>nect","<u>con</u>struct","<u>con</u>tract"] },
  { id:"contra", form:"contra", display:"contra-", meaning:"against; opposite", allowedPos:["noun","adj","verb"], examples:["<u>contra</u>dict","<u>contra</u>st","<u>contra</u>vene"] },
  { id:"de", form:"de", display:"de-", meaning:"undo; remove; down", allowedPos:["verb"], examples:["<u>de</u>activate","<u>de</u>compose","<u>de</u>rail"] },
  { id:"dis", form:"dis", display:"dis-", meaning:"not; opposite; apart", allowedPos:["noun","adj","verb"], examples:["<u>dis</u>agree","<u>dis</u>connect","<u>dis</u>like"] },
  { id:"en", form:"en", display:"en-", meaning:"cause to; make", allowedPos:["verb"], altForms:["em"], examples:["<u>en</u>able","<u>en</u>rich","<u>en</u>large"] },
  { id:"em", form:"em", display:"em-", meaning:"cause to; make", allowedPos:["verb"], examples:["<u>em</u>power","<u>em</u>bed","<u>em</u>brace"] },
  { id:"ex", form:"ex", display:"ex-", meaning:"out of; former", allowedPos:["noun","adj"], examples:["<u>ex</u>port","<u>ex</u>clude","<u>ex</u>hale"] },
  { id:"e", form:"e", display:"e-", meaning:"electronic; online", allowedPos:["noun","adj"], examples:["<u>e</u>mail","<u>e</u>book","<u>e</u>commerce"] },
  { id:"extra", form:"extra", display:"extra-", meaning:"beyond", allowedPos:["noun","adj"], examples:["<u>extra</u>ordinary","<u>extra</u>curricular","<u>extra</u>large"] },
  { id:"fore", form:"fore", display:"fore-", meaning:"before", allowedPos:["noun","adj"], examples:["<u>fore</u>cast","<u>fore</u>head","<u>fore</u>warn"] },
  { id:"hyper", form:"hyper", display:"hyper-", meaning:"over; excessive", allowedPos:["adj","noun"], examples:["<u>hyper</u>active","<u>hyper</u>link","<u>hyper</u>sensitive"] },
  { id:"in", form:"in", display:"in-", meaning:"not; into", allowedPos:["adj","verb"], altForms:["im","il","ir"], examples:["<u>in</u>correct","<u>in</u>visible","<u>in</u>ject"] },
  { id:"inter", form:"inter", display:"inter-", meaning:"between", allowedPos:["noun","adj","verb"], examples:["<u>inter</u>act","<u>inter</u>national","<u>inter</u>connect"] },
  { id:"mal", form:"mal", display:"mal-", meaning:"bad", allowedPos:["noun","adj"], examples:["<u>mal</u>function","<u>mal</u>nourished","<u>mal</u>content"] },
  { id:"mega", form:"mega", display:"mega-", meaning:"large", allowedPos:["noun","adj"], examples:["<u>mega</u>phone","<u>mega</u>store","<u>mega</u>byte"] },
  { id:"micro", form:"micro", display:"micro-", meaning:"small", allowedPos:["noun","adj"], examples:["<u>micro</u>scope","<u>micro</u>chip","<u>micro</u>wave"] },
  { id:"mid", form:"mid", display:"mid-", meaning:"middle", allowedPos:["noun","adj"], examples:["<u>mid</u>day","<u>mid</u>night","<u>mid</u>field"] },
  { id:"mis", form:"mis", display:"mis-", meaning:"wrong", allowedPos:["verb"], examples:["<u>mis</u>read","<u>mis</u>take","<u>mis</u>place"] },
  { id:"multi", form:"multi", display:"multi-", meaning:"many", allowedPos:["noun","adj"], examples:["<u>multi</u>colour","<u>multi</u>media","<u>multi</u>purpose"] },
  { id:"non", form:"non", display:"non-", meaning:"not", allowedPos:["noun","adj"], examples:["<u>non</u>fiction","<u>non</u>stop","<u>non</u>violent"] },
  { id:"over", form:"over", display:"over-", meaning:"too much", allowedPos:["verb","adj"], examples:["<u>over</u>cook","<u>over</u>load","<u>over</u>react"] },
  { id:"post", form:"post", display:"post-", meaning:"after", allowedPos:["noun","adj"], examples:["<u>post</u>war","<u>post</u>pone","<u>post</u>season"] },
  { id:"pre", form:"pre", display:"pre-", meaning:"before", allowedPos:["noun","adj","verb"], examples:["<u>pre</u>view","<u>pre</u>dict","<u>pre</u>pare"] },
  { id:"pro", form:"pro", display:"pro-", meaning:"in favour of; forward", allowedPos:["noun","adj"], examples:["<u>pro</u>active","<u>pro</u>mote","<u>pro</u>government"] },
  { id:"re", form:"re", display:"re-", meaning:"again", allowedPos:["verb"], examples:["<u>re</u>write","<u>re</u>build","<u>re</u>turn"] },
  { id:"semi", form:"semi", display:"semi-", meaning:"half", allowedPos:["noun","adj"], examples:["<u>semi</u>circle","<u>semi</u>final","<u>semi</u>colon"] },
  { id:"sub", form:"sub", display:"sub-", meaning:"under; below", allowedPos:["noun","adj","verb"], altForms:["suc","suf","sug","sup","sus","subt"], examples:["<u>sub</u>marine","<u>sub</u>tract","<u>sub</u>heading"] },
  { id:"super", form:"super", display:"super-", meaning:"above; beyond", allowedPos:["noun","adj","verb"], examples:["<u>super</u>market","<u>super</u>human","<u>super</u>charge"] },
  { id:"trans", form:"trans", display:"trans-", meaning:"across", allowedPos:["noun","adj","verb"], examples:["<u>trans</u>port","<u>trans</u>fer","<u>trans</u>form"] },
  { id:"un", form:"un", display:"un-", meaning:"not", allowedPos:["adj","verb"], examples:["<u>un</u>happy","<u>un</u>lock","<u>un</u>fair"] },
  { id:"under", form:"under", display:"under-", meaning:"below", allowedPos:["noun","adj","verb"], examples:["<u>under</u>line","<u>under</u>pay","<u>under</u>ground"] },
  { id:"ob", form:"ob", display:"ob-", meaning:"against; in the way of; towards", allowedPos:["noun","adj","verb"], altForms:["oc","of","op","os","obt"], examples:["<u>ob</u>ject","<u>ob</u>serve","<u>ob</u>struct"] },
  { id:"a", form:"a", display:"a-", meaning:"not; without", allowedPos:["adj","noun"], examples:["<u>a</u>moral","<u>a</u>typical","<u>a</u>sexual"] },
  { id:"tele", form:"tele", display:"tele-", meaning:"far; distant", allowedPos:["noun","adj","verb"], examples:["<u>tele</u>scope","<u>tele</u>graph","<u>tele</u>gram"] },
  { id:"peri", form:"peri", display:"peri-", meaning:"around", allowedPos:["noun","adj"], examples:["<u>peri</u>scope","<u>peri</u>meter","<u>peri</u>pheral"] },
  { id:"gyro", form:"gyro", display:"gyro-", meaning:"circle; spinning", allowedPos:["noun"], examples:["<u>gyro</u>scope","<u>gyro</u>compass"] },
  { id:"endo", form:"endo", display:"endo-", meaning:"within; inside", allowedPos:["noun","adj"], examples:["<u>endo</u>scope","<u>endo</u>crine","<u>endo</u>skeleton"] },
  { id:"horo", form:"horo", display:"horo-", meaning:"time; hour", allowedPos:["noun"], examples:["<u>horo</u>scope","<u>horo</u>logy"] },
  { id:"stetho", form:"stetho", display:"stetho-", meaning:"chest", allowedPos:["noun"], examples:["<u>stetho</u>scope"] },
  { id:"kaleido", form:"kaleido", display:"kaleido-", meaning:"beautiful form", allowedPos:["noun"], examples:["<u>kaleido</u>scope"] }
];

const SUFFIXES = [
  { id:"s", form:"s", display:"-s", meaning:"plural or present tense", allowedPos:["noun","verb"], hint:"books, runs", examples:["book<u>s</u>","run<u>s</u>","car<u>s</u>"] },
  { id:"es", form:"es", display:"-es", meaning:"plural or present tense", allowedPos:["noun","verb"], hint:"boxes, watches", examples:["box<u>es</u>","watch<u>es</u>","dish<u>es</u>"] },
  { id:"ed", form:"ed", display:"-ed", meaning:"past tense", allowedPos:["verb"], hint:"played, developed", examples:["play<u>ed</u>","jump<u>ed</u>","develop<u>ed</u>"] },
  { id:"ing", form:"ing", display:"-ing", meaning:"happening now", allowedPos:["verb"], hint:"building, running", examples:["build<u>ing</u>","runn<u>ing</u>","teach<u>ing</u>"] },
  { id:"en", form:"en", display:"-en", meaning:"made of; to make", allowedPos:["adj","verb"], hint:"wooden, widen", examples:["wood<u>en</u>","wid<u>en</u>","strength<u>en</u>"] },
  { id:"er", form:"er", display:"-er", meaning:"person who; more", allowedPos:["verb","adj"], hint:"teacher, faster", examples:["teach<u>er</u>","fast<u>er</u>","farm<u>er</u>"] },
  { id:"or", form:"or", display:"-or", meaning:"person who", allowedPos:["verb","noun"], hint:"actor, inventor", examples:["act<u>or</u>","invent<u>or</u>","edit<u>or</u>"] },
  { id:"est", form:"est", display:"-est", meaning:"most", allowedPos:["adj"], hint:"fastest", examples:["fast<u>est</u>","tall<u>est</u>","bright<u>est</u>"] },
  { id:"ly", form:"ly", display:"-ly", meaning:"in a way", allowedPos:["adj"], hint:"quickly", examples:["quick<u>ly</u>","calm<u>ly</u>","brave<u>ly</u>"] },
  { id:"ion", form:"ion", display:"-ion", meaning:"act or result of", allowedPos:["verb"], hint:"action, creation", examples:["act<u>ion</u>","creat<u>ion</u>","collect<u>ion</u>"] },
  { id:"able", form:"able", display:"-able", meaning:"able to", allowedPos:["verb"], hint:"usable, movable", examples:["use<u>able</u>","move<u>able</u>","enjoy<u>able</u>"] },
  { id:"ible", form:"ible", display:"-ible", meaning:"able to", allowedPos:["verb"], hint:"possible pattern", examples:["vis<u>ible</u>","cred<u>ible</u>","flex<u>ible</u>"] },
  { id:"y", form:"y", display:"-y", meaning:"characterised by", allowedPos:["noun"], hint:"rainy", examples:["rain<u>y</u>","cloud<u>y</u>","mess<u>y</u>"] },
  { id:"ful", form:"ful", display:"-ful", meaning:"full of", allowedPos:["noun"], hint:"helpful", examples:["help<u>ful</u>","care<u>ful</u>","joy<u>ful</u>"] },
  { id:"less", form:"less", display:"-less", meaning:"without", allowedPos:["noun"], hint:"careless", examples:["care<u>less</u>","help<u>less</u>","fear<u>less</u>"] },
  { id:"ish", form:"ish", display:"-ish", meaning:"somewhat; like", allowedPos:["noun","adj"], hint:"childish", examples:["child<u>ish</u>","green<u>ish</u>","fool<u>ish</u>"] },
  { id:"ness", form:"ness", display:"-ness", meaning:"state of", allowedPos:["adj"], hint:"kindness", examples:["kind<u>ness</u>","happy<u>ness</u>","dark<u>ness</u>"] },
  { id:"ment", form:"ment", display:"-ment", meaning:"result of action", allowedPos:["verb"], hint:"development", examples:["develop<u>ment</u>","move<u>ment</u>","excite<u>ment</u>"] },
  { id:"al", form:"al", display:"-al", meaning:"related to", allowedPos:["noun","verb"], hint:"signal", examples:["sign<u>al</u>","music<u>al</u>","logic<u>al</u>"] },
  { id:"ial", form:"ial", display:"-ial", meaning:"related to", allowedPos:["noun","verb"], hint:"essential pattern", examples:["essent<u>ial</u>","spec<u>ial</u>","industr<u>ial</u>"] },
  { id:"ty", form:"ty", display:"-ty", meaning:"state or quality", allowedPos:["adj"], hint:"safety pattern", examples:["safe<u>ty</u>","cruel<u>ty</u>","royal<u>ty</u>"] },
  { id:"ity", form:"ity", display:"-ity", meaning:"state or quality", allowedPos:["adj"], hint:"responsibility pattern", examples:["abil<u>ity</u>","qual<u>ity</u>","responsibil<u>ity</u>"] },
  { id:"ous", form:"ous", display:"-ous", meaning:"full of", allowedPos:["noun","verb"], hint:"dangerous pattern", examples:["danger<u>ous</u>","fame<u>ous</u>","poison<u>ous</u>"] },
  { id:"ee", form:"ee", display:"-ee", meaning:"person who receives", allowedPos:["verb"], hint:"employee pattern", examples:["employ<u>ee</u>","train<u>ee</u>","nomin<u>ee</u>"] },
  { id:"ist", form:"ist", display:"-ist", meaning:"person who", allowedPos:["noun","verb"], hint:"artist", examples:["art<u>ist</u>","scient<u>ist</u>","pian<u>ist</u>"] },
  { id:"ance", form:"ance", display:"-ance", meaning:"state of", allowedPos:["verb"], hint:"appearance", examples:["appear<u>ance</u>","perform<u>ance</u>","import<u>ance</u>"] },
  { id:"ence", form:"ence", display:"-ence", meaning:"state of", allowedPos:["verb"], hint:"existence pattern", examples:["exist<u>ence</u>","depend<u>ence</u>","differ<u>ence</u>"] },
  { id:"ant", form:"ant", display:"-ant", meaning:"person or thing that", allowedPos:["verb"], hint:"assistant", examples:["assist<u>ant</u>","occup<u>ant</u>","import<u>ant</u>"] },
  { id:"ent", form:"ent", display:"-ent", meaning:"person or thing that", allowedPos:["verb"], hint:"student pattern", examples:["stud<u>ent</u>","differ<u>ent</u>","respond<u>ent</u>"] },
  { id:"ate", form:"ate", display:"-ate", meaning:"to make; to become", allowedPos:["noun","adj"], hint:"activate pattern", examples:["activ<u>ate</u>","motiv<u>ate</u>","separ<u>ate</u>"] },
  { id:"eer", form:"eer", display:"-eer", meaning:"person who", allowedPos:["noun","verb"], hint:"engineer pattern", examples:["engine<u>eer</u>","mountain<u>eer</u>","auction<u>eer</u>"] },
  { id:"fy", form:"fy", display:"-fy", meaning:"make", allowedPos:["noun","adj"], hint:"simplify pattern", examples:["simpli<u>fy</u>","beauti<u>fy</u>","classi<u>fy</u>"] },
  { id:"ify", form:"ify", display:"-ify", meaning:"make", allowedPos:["noun","adj"], hint:"signify", examples:["sign<u>ify</u>","clar<u>ify</u>","ident<u>ify</u>"] },
  { id:"ific", form:"ific", display:"-ific", meaning:"making; doing", allowedPos:["noun","verb"], hint:"sign + ific + ant = significant", examples:["spec<u>ific</u>","terr<u>ific</u>","pac<u>ific</u>"] },
  { id:"hood", form:"hood", display:"-hood", meaning:"state of", allowedPos:["noun"], hint:"childhood", examples:["child<u>hood</u>","parent<u>hood</u>","brother<u>hood</u>"] },
  { id:"ian", form:"ian", display:"-ian", meaning:"person connected to", allowedPos:["noun"], hint:"musician pattern", examples:["music<u>ian</u>","librar<u>ian</u>","histor<u>ian</u>"] },
  { id:"ic", form:"ic", display:"-ic", meaning:"related to", allowedPos:["noun","verb"], hint:"historic pattern", examples:["hero<u>ic</u>","histor<u>ic</u>","bas<u>ic</u>"] },
  { id:"ive", form:"ive", display:"-ive", meaning:"having quality of", allowedPos:["verb","noun"], hint:"active, creative", examples:["act<u>ive</u>","creat<u>ive</u>","support<u>ive</u>"] },
  { id:"ize", form:"ize", display:"-ize", meaning:"make", allowedPos:["noun","adj"], hint:"organise uses -ise in Australia", examples:["modern<u>ize</u>","real<u>ize</u>","apolog<u>ize</u>"] },
  { id:"like", form:"like", display:"-like", meaning:"like; similar to", allowedPos:["noun"], hint:"childlike", examples:["child<u>like</u>","dream<u>like</u>","human<u>like</u>"] },
  { id:"logy", form:"logy", display:"-logy", meaning:"study of", allowedPos:["noun"], hint:"biology pattern", examples:["bio<u>logy</u>","geo<u>logy</u>","techno<u>logy</u>"] },
  { id:"ologist", form:"ologist", display:"-ologist", meaning:"person who studies", allowedPos:["noun"], hint:"biologist pattern", examples:["bi<u>ologist</u>","ge<u>ologist</u>","archae<u>ologist</u>"] },
  { id:"ship", form:"ship", display:"-ship", meaning:"state or skill", allowedPos:["noun"], hint:"friendship", examples:["friend<u>ship</u>","leader<u>ship</u>","partner<u>ship</u>"] },
  { id:"ure", form:"ure", display:"-ure", meaning:"result of", allowedPos:["verb"], hint:"closure pattern", examples:["clos<u>ure</u>","fract<u>ure</u>","press<u>ure</u>"] }
];

const CORE_BASES = [
  { id:"act", form:"act", meaning:"do", pos:["verb","noun"], examples:["<u>act</u>","<u>act</u>ion","re<u>act</u>"] },
  { id:"appear", form:"appear", meaning:"come into view", pos:["verb"], examples:["<u>appear</u>","dis<u>appear</u>","appear<u>ance</u>"] },
  { id:"apply", form:"apply", meaning:"put to use", pos:["verb"], examples:["<u>apply</u>","re<u>apply</u>","apply<u>ing</u>"] },
  { id:"argue", form:"argue", meaning:"give reasons", pos:["verb"], examples:["<u>argue</u>","argu<u>ment</u>","argu<u>able</u>"] },
  { id:"assist", form:"assist", meaning:"help", pos:["verb"], examples:["<u>assist</u>","assist<u>ant</u>","assist<u>ance</u>"] },
  { id:"attract", form:"attract", meaning:"pull towards", pos:["verb"], examples:["<u>attract</u>","attract<u>ion</u>","attract<u>ive</u>"] },
  { id:"behave", form:"behave", meaning:"act in a way", pos:["verb"], examples:["<u>behave</u>","mis<u>behave</u>","behav<i>i</i>our"] },
  { id:"believe", form:"believe", meaning:"think something is true", pos:["verb"], examples:["<u>believe</u>","un<u>believe</u>able","believ<u>er</u>"] },
  { id:"build", form:"build", meaning:"make by putting parts together", pos:["verb"], examples:["<u>build</u>","re<u>build</u>","build<u>ing</u>"] },
  { id:"care", form:"care", meaning:"look after; attention", pos:["verb","noun"], examples:["<u>care</u>","care<u>ful</u>","care<u>less</u>"] },
  { id:"collect", form:"collect", meaning:"gather together", pos:["verb"], examples:["<u>collect</u>","collect<u>ion</u>","re<u>collect</u>"] },
  { id:"communicate", form:"communicate", meaning:"share information", pos:["verb"], examples:["<u>communicate</u>","communicat<u>ion</u>","communicat<u>or</u>"] },
  { id:"connect", form:"connect", meaning:"join together", pos:["verb"], examples:["<u>connect</u>","connect<u>ion</u>","dis<u>connect</u>"] },
  { id:"construct", form:"construct", meaning:"build", pos:["verb"], examples:["<u>construct</u>","construct<u>ion</u>","re<u>construct</u>"] },
  { id:"create", form:"create", meaning:"make", pos:["verb"], examples:["<u>create</u>","creat<u>ion</u>","creat<u>ive</u>"] },
  { id:"decide", form:"decide", meaning:"choose after thinking", pos:["verb"], examples:["<u>decide</u>","decis<u>ion</u>","decis<u>ive</u>"] },
  { id:"develop", form:"develop", meaning:"grow or improve", pos:["verb"], examples:["<u>develop</u>","develop<u>ment</u>","develop<u>ed</u>"] },
  { id:"direct", form:"direct", meaning:"guide; control", pos:["verb","adj"], examples:["<u>direct</u>","re<u>direct</u>","direct<u>ion</u>"] },
  { id:"educate", form:"educate", meaning:"teach", pos:["verb"], examples:["<u>educate</u>","educat<u>ion</u>","educat<u>or</u>"] },
  { id:"employ", form:"employ", meaning:"give work to; use", pos:["verb"], examples:["<u>employ</u>","employ<u>ee</u>","employ<u>ment</u>"] },
  { id:"encourage", form:"encourage", meaning:"support; give confidence", pos:["verb"], examples:["<u>encourage</u>","encourage<u>ment</u>","discourage"] },
  { id:"enjoy", form:"enjoy", meaning:"like; take pleasure in", pos:["verb"], examples:["<u>enjoy</u>","enjoy<u>able</u>","enjoy<u>ment</u>"] },
  { id:"excite", form:"excite", meaning:"make interested or happy", pos:["verb"], examples:["<u>excite</u>","excit<u>ed</u>","excit<u>ement</u>"] },
  { id:"expect", form:"expect", meaning:"think will happen", pos:["verb"], examples:["<u>expect</u>","expect<u>ed</u>","un<u>expect</u>ed"] },
  { id:"explore", form:"explore", meaning:"investigate", pos:["verb"], examples:["<u>explore</u>","explor<u>er</u>","explorat<u>ion</u>"] },
  { id:"express", form:"express", meaning:"show or say", pos:["verb"], examples:["<u>express</u>","express<u>ion</u>","express<u>ive</u>"] },
  { id:"extend", form:"extend", meaning:"make longer; stretch", pos:["verb"], examples:["<u>extend</u>","extend<u>ed</u>","extens<u>ion</u>"] },
  { id:"form", form:"form", meaning:"make; shape", pos:["verb","noun"], examples:["<u>form</u>","trans<u>form</u>","form<u>ation</u>"] },
  { id:"friend", form:"friend", meaning:"a person you like and trust", pos:["noun"], examples:["<u>friend</u>","friend<u>ly</u>","friend<u>ship</u>"] },
  { id:"govern", form:"govern", meaning:"rule; manage", pos:["verb"], examples:["<u>govern</u>","govern<u>ment</u>","govern<u>or</u>"] },
  { id:"grow", form:"grow", meaning:"increase; get bigger", pos:["verb"], examples:["<u>grow</u>","grow<u>th</u>","over<u>grow</u>n"] },
  { id:"help", form:"help", meaning:"give support", pos:["verb","noun"], examples:["<u>help</u>","help<u>ful</u>","help<u>less</u>"] },
  { id:"inform", form:"inform", meaning:"tell; give information", pos:["verb"], examples:["<u>inform</u>","inform<u>ation</u>","mis<u>inform</u>"] },
  { id:"inspire", form:"inspire", meaning:"encourage; motivate", pos:["verb"], examples:["<u>inspire</u>","inspirat<u>ion</u>","inspir<u>ing</u>"] },
  { id:"introduce", form:"introduce", meaning:"bring in; present", pos:["verb"], examples:["<u>introduce</u>","introduct<u>ion</u>","re<u>introduce</u>"] },
  { id:"invest", form:"invest", meaning:"put money into", pos:["verb"], examples:["<u>invest</u>","invest<u>or</u>","invest<u>ment</u>"] },
  { id:"join", form:"join", meaning:"connect", pos:["verb"], examples:["<u>join</u>","re<u>join</u>","join<u>ed</u>"] },
  { id:"judge", form:"judge", meaning:"decide; form an opinion", pos:["verb","noun"], examples:["<u>judge</u>","judg<u>ment</u>","judg<u>e</u>"] },
  { id:"learn", form:"learn", meaning:"gain knowledge", pos:["verb"], examples:["<u>learn</u>","learn<u>er</u>","learn<u>ing</u>"] },
  { id:"locate", form:"locate", meaning:"find where something is", pos:["verb"], examples:["<u>locate</u>","locat<u>ion</u>","re<u>locate</u>"] },
  { id:"manage", form:"manage", meaning:"control; run", pos:["verb"], examples:["<u>manage</u>","manag<u>er</u>","manag<u>ement</u>"] },
  { id:"measure", form:"measure", meaning:"find size or amount", pos:["verb","noun"], examples:["<u>measure</u>","measure<u>ment</u>","re<u>measure</u>"] },
  { id:"migrate", form:"migrate", meaning:"move to another place", pos:["verb"], examples:["<u>migrate</u>","migrat<u>ion</u>","im<u>migrate</u>"] },
  { id:"motivate", form:"motivate", meaning:"make someone want to act", pos:["verb"], examples:["<u>motivate</u>","motivat<u>ion</u>","un<u>motivated</u>"] },
  { id:"move", form:"move", meaning:"go from one place to another", pos:["verb"], examples:["<u>move</u>","move<u>ment</u>","re<u>move</u>"] },
  { id:"observe", form:"observe", meaning:"watch carefully", pos:["verb"], examples:["<u>observe</u>","observ<u>er</u>","observat<u>ion</u>"] },
  { id:"operate", form:"operate", meaning:"work; run", pos:["verb"], examples:["<u>operate</u>","operat<u>ion</u>","co<u>operate</u>"] },
  { id:"organise", form:"organise", meaning:"plan and arrange", pos:["verb"], examples:["<u>organise</u>","organis<u>er</u>","organis<u>ation</u>"] },
  { id:"participate", form:"participate", meaning:"take part", pos:["verb"], examples:["<u>participate</u>","participat<u>ion</u>","participat<u>ing</u>"] },
  { id:"perform", form:"perform", meaning:"do; carry out", pos:["verb"], examples:["<u>perform</u>","perform<u>ance</u>","out<u>perform</u>"] },
  { id:"persuade", form:"persuade", meaning:"convince", pos:["verb"], examples:["<u>persuade</u>","persuas<u>ion</u>","persuas<u>ive</u>"] },
  { id:"predict", form:"predict", meaning:"say before it happens", pos:["verb"], examples:["<u>predict</u>","predict<u>ion</u>","un<u>predict</u>able"] },
  { id:"prepare", form:"prepare", meaning:"get ready", pos:["verb"], examples:["<u>prepare</u>","preparat<u>ion</u>","un<u>prepared</u>"] },
  { id:"prevent", form:"prevent", meaning:"stop from happening", pos:["verb"], examples:["<u>prevent</u>","prevent<u>ion</u>","prevent<u>ive</u>"] },
  { id:"produce", form:"produce", meaning:"make", pos:["verb"], examples:["<u>produce</u>","produc<u>er</u>","product<u>ion</u>"] },
  { id:"protect", form:"protect", meaning:"keep safe", pos:["verb"], examples:["<u>protect</u>","protect<u>ion</u>","protect<u>ive</u>"] },
  { id:"react", form:"react", meaning:"respond", pos:["verb"], examples:["re<u>act</u>","react<u>ion</u>","react<u>ive</u>"] },
  { id:"reduce", form:"reduce", meaning:"make smaller", pos:["verb"], examples:["<u>reduce</u>","reduct<u>ion</u>","reduc<u>ed</u>"] },
  { id:"reflect", form:"reflect", meaning:"think back; show", pos:["verb"], examples:["re<u>flect</u>","reflect<u>ion</u>","reflect<u>ive</u>"] },
  { id:"reject", form:"reject", meaning:"refuse", pos:["verb"], examples:["re<u>ject</u>","reject<u>ion</u>","reject<u>ed</u>"] },
  { id:"relate", form:"relate", meaning:"connect; link", pos:["verb"], examples:["<u>relate</u>","relat<u>ion</u>","relat<u>ed</u>"] },
  { id:"remove", form:"remove", meaning:"take away", pos:["verb"], examples:["re<u>move</u>","remov<u>al</u>","re<u>moved</u>"] },
  { id:"repair", form:"repair", meaning:"fix", pos:["verb"], examples:["re<u>pair</u>","repair<u>ed</u>","repair<u>er</u>"] },
  { id:"replace", form:"replace", meaning:"put in place of", pos:["verb"], examples:["re<u>place</u>","replace<u>ment</u>","re<u>placed</u>"] },
  { id:"report", form:"report", meaning:"tell; write information", pos:["verb","noun"], examples:["re<u>port</u>","report<u>er</u>","report<u>ing</u>"] },
  { id:"respect", form:"respect", meaning:"treat well; value", pos:["verb","noun"], examples:["re<u>spect</u>","respect<u>ful</u>","dis<u>respect</u>"] },
  { id:"respond", form:"respond", meaning:"answer", pos:["verb"], examples:["re<u>spond</u>","respond<u>ed</u>","respond<u>ent</u>"] },
  { id:"return", form:"return", meaning:"go back; give back", pos:["verb"], examples:["re<u>turn</u>","return<u>ed</u>","return<u>ing</u>"] },
  { id:"reveal", form:"reveal", meaning:"show; make known", pos:["verb"], examples:["re<u>veal</u>","revealed","unrevealed"] },
  { id:"review", form:"review", meaning:"look again", pos:["verb","noun"], examples:["re<u>view</u>","review<u>er</u>","review<u>ing</u>"] },
  { id:"revise", form:"revise", meaning:"improve; study again", pos:["verb"], examples:["re<u>vise</u>","revis<u>ion</u>","revis<u>ed</u>"] },
  { id:"rotate", form:"rotate", meaning:"turn around", pos:["verb"], examples:["<u>rotate</u>","rotat<u>ion</u>","rotat<u>ing</u>"] },
  { id:"solve", form:"solve", meaning:"find an answer", pos:["verb"], examples:["<u>solve</u>","solv<u>ed</u>","solv<u>ing</u>"] },
  { id:"structure", form:"structure", meaning:"arrange parts", pos:["noun","verb"], examples:["<u>structure</u>","re<u>structure</u>","structure<u>d</u>"] },
  { id:"suggest", form:"suggest", meaning:"offer an idea", pos:["verb"], examples:["sug<u>gest</u>","suggest<u>ion</u>","suggest<u>ed</u>"] },
  { id:"support", form:"support", meaning:"help; hold up", pos:["verb","noun"], examples:["sup<u>port</u>","support<u>ive</u>","support<u>er</u>"] },
  { id:"transport", form:"transport", meaning:"carry from place to place", pos:["verb","noun"], examples:["trans<u>port</u>","transport<u>ed</u>","transport<u>ation</u>"] },
  { id:"trust", form:"trust", meaning:"believe someone will do the right thing", pos:["verb","noun"], examples:["<u>trust</u>","trusted","trust<u>worthy</u>"] },
  { id:"use", form:"use", meaning:"do something with", pos:["verb","noun"], examples:["<u>use</u>","use<u>ful</u>","mis<u>use</u>"] },
  { id:"value", form:"value", meaning:"how much something is worth", pos:["noun","verb"], examples:["<u>value</u>","de<u>value</u>","valu<u>ed</u>"] },
  { id:"visit", form:"visit", meaning:"go to see", pos:["verb","noun"], examples:["<u>visit</u>","visit<u>or</u>","re<u>visit</u>"] },
  { id:"watch", form:"watch", meaning:"look at for a time", pos:["verb","noun"], examples:["<u>watch</u>","watch<u>er</u>","watch<u>ing</u>"] },
  { id:"write", form:"write", meaning:"put words on a page", pos:["verb"], examples:["<u>write</u>","re<u>write</u>","writ<u>ing</u>"] },

  { id:"legal", form:"legal", meaning:"allowed by law", pos:["adj"], examples:["<u>legal</u>","il<u>legal</u>","legal<u>ity</u>"] },
  { id:"logical", form:"logical", meaning:"making sense", pos:["adj"], examples:["<u>logical</u>","il<u>logical</u>","logic"] },
  { id:"literate", form:"literate", meaning:"able to read and write", pos:["adj"], examples:["<u>literate</u>","il<u>literate</u>","literacy"] },
  { id:"regular", form:"regular", meaning:"usual; even pattern", pos:["adj"], examples:["<u>regular</u>","ir<u>regular</u>","regular<u>ly</u>"] },
  { id:"rational", form:"rational", meaning:"reasonable; based on logic", pos:["adj"], examples:["<u>rational</u>","ir<u>rational</u>","rational<u>ity</u>"] },
  { id:"responsible", form:"responsible", meaning:"can be trusted to do the right thing", pos:["adj"], examples:["<u>responsible</u>","ir<u>responsible</u>","responsibil<u>ity</u>"] },
  { id:"typical", form:"typical", meaning:"usual; common", pos:["adj"], examples:["<u>typical</u>","a<u>typical</u>","typic<u>ally</u>"] },
  { id:"hero", form:"hero", meaning:"a very brave person", pos:["noun"], examples:["<u>hero</u>","hero<u>ic</u>","heroes"] },
  { id:"market", form:"market", meaning:"place to buy and sell", pos:["noun"], examples:["<u>market</u>","super<u>market</u>","market<u>ing</u>"] },
  { id:"power", form:"power", meaning:"strength; control; energy", pos:["noun"], examples:["<u>power</u>","em<u>power</u>","power<u>ful</u>"] },
  { id:"fast", form:"fast", meaning:"quick", pos:["adj"], examples:["<u>fast</u>","fast<u>er</u>","fast<u>est</u>"] }
];

const ANGLO_BASE_INFO = {
  teach:{ meaning:"to show someone how to do something", pos:["verb"], examples:["<u>teach</u>","teach<u>er</u>","teach<u>ing</u>"] },
  meet:{ meaning:"to come together; to see someone", pos:["verb"], examples:["<u>meet</u>","meet<u>ing</u>","re<u>meet</u>"] },
  rest:{ meaning:"to relax; to stop work for a while", pos:["verb","noun"], examples:["<u>rest</u>","rest<u>ful</u>","rest<u>ed</u>"] },
  go:{ meaning:"to move from one place to another", pos:["verb"], examples:["<u>go</u>","under<u>go</u>","go<u>ing</u>"] },
  tall:{ meaning:"having great height", pos:["adj"], examples:["<u>tall</u>","tall<u>er</u>","tall<u>est</u>"] },
  help:{ meaning:"to assist; to make easier", pos:["verb","noun"], examples:["<u>help</u>","help<u>ful</u>","help<u>less</u>"] },
  ask:{ meaning:"to question; to request", pos:["verb"], examples:["<u>ask</u>","ask<u>ed</u>","ask<u>ing</u>"] },
  eat:{ meaning:"to consume food", pos:["verb"], examples:["<u>eat</u>","eat<u>ing</u>","over<u>eat</u>"] },
  train:{ meaning:"to practise to improve; to teach", pos:["verb","noun"], examples:["<u>train</u>","train<u>er</u>","train<u>ing</u>"] },
  usual:{ meaning:"common; normal", pos:["adj"], examples:["<u>usual</u>","un<u>usual</u>","usual<u>ly</u>"] },
  end:{ meaning:"to finish; the final part", pos:["verb","noun"], examples:["<u>end</u>","end<u>ing</u>","end<u>less</u>"] },
  turn:{ meaning:"to change direction; to rotate", pos:["verb","noun"], examples:["<u>turn</u>","re<u>turn</u>","turn<u>ing</u>"] },
  open:{ meaning:"not closed; to make not closed", pos:["adj","verb"], examples:["<u>open</u>","re<u>open</u>","open<u>ing</u>"] },
  make:{ meaning:"to create; to build", pos:["verb"], examples:["<u>make</u>","re<u>make</u>","make<u>r</u>"] },
  jump:{ meaning:"to push off the ground into the air", pos:["verb","noun"], examples:["<u>jump</u>","jump<u>ed</u>","jump<u>ing</u>"] },
  bad:{ meaning:"not good; poor quality", pos:["adj"], examples:["<u>bad</u>","bad<u>ly</u>","badness"] },
  lock:{ meaning:"to fasten with a key; a fastening device", pos:["verb","noun"], examples:["<u>lock</u>","un<u>lock</u>","lock<u>ed</u>"] },
  move:{ meaning:"to change position; to go", pos:["verb"], examples:["<u>move</u>","move<u>ment</u>","re<u>move</u>"] },
  like:{ meaning:"to enjoy; to prefer", pos:["verb"], examples:["<u>like</u>","dis<u>like</u>","like<u>able</u>"] },
  care:{ meaning:"to look after; to feel concern", pos:["verb","noun"], examples:["<u>care</u>","care<u>ful</u>","care<u>less</u>"] },
  happy:{ meaning:"feeling joy; pleased", pos:["adj"], examples:["<u>happy</u>","un<u>happy</u>","happi<u>ness</u>"] },
  push:{ meaning:"to press forward with force", pos:["verb","noun"], examples:["<u>push</u>","push<u>ed</u>","push<u>ing</u>"] },
  zip:{ meaning:"to fasten with a zip; to move quickly", pos:["verb","noun"], examples:["<u>zip</u>","zip<u>ped</u>","zip<u>per</u>"] },
  take:{ meaning:"to get; to carry; to accept", pos:["verb"], examples:["<u>take</u>","re<u>take</u>","take<u>n</u>"] },
  see:{ meaning:"to look at; to notice", pos:["verb"], examples:["<u>see</u>","fore<u>see</u>","see<u>ing</u>"] },
  brisk:{ meaning:"quick and energetic", pos:["adj"], examples:["<u>brisk</u>","brisk<u>ly</u>","briskness"] },
  wake:{ meaning:"to stop sleeping", pos:["verb"], examples:["<u>wake</u>","wake<u>ful</u>","wake<u>n</u>"] },
  send:{ meaning:"to cause to go to a place; to post", pos:["verb"], examples:["<u>send</u>","send<u>er</u>","send<u>ing</u>"] },
  round:{ meaning:"shaped like a circle", pos:["adj"], examples:["<u>round</u>","round<u>ed</u>","round<u>ness</u>"] },
  cloud:{ meaning:"a mass of water droplets in the sky", pos:["noun"], examples:["<u>cloud</u>","cloud<u>y</u>","clouds"] },
  pay:{ meaning:"to give money for something", pos:["verb"], examples:["<u>pay</u>","re<u>pay</u>","pay<u>ment</u>"] },
  lift:{ meaning:"to raise; to pick up", pos:["verb","noun"], examples:["<u>lift</u>","lift<u>ed</u>","lift<u>ing</u>"] },
  pack:{ meaning:"to put things together for carrying; a bundle", pos:["verb","noun"], examples:["<u>pack</u>","pack<u>ed</u>","back<u>pack</u>"] },
  sound:{ meaning:"something you hear; noise", pos:["noun"], examples:["<u>sound</u>","sound<u>less</u>","sound<u>ing</u>"] },
  correct:{ meaning:"right; accurate", pos:["adj","verb"], examples:["<u>correct</u>","in<u>correct</u>","correct<u>ion</u>"] },
  part:{ meaning:"a piece of something; a section", pos:["noun"], examples:["<u>part</u>","part<u>ly</u>","part<u>ner</u>"] },
  live:{ meaning:"to be alive; to reside", pos:["verb","adj"], examples:["<u>live</u>","out<u>live</u>","live<u>ly</u>"] },
  sad:{ meaning:"unhappy; feeling sorrow", pos:["adj"], examples:["<u>sad</u>","sad<u>ly</u>","sadness"] },
  trust:{ meaning:"to believe someone is reliable; belief", pos:["verb","noun"], examples:["<u>trust</u>","trust<u>ed</u>","trust<u>worthy</u>"] },
  merge:{ meaning:"to join together into one", pos:["verb"], examples:["<u>merge</u>","merge<u>r</u>","sub<u>merge</u>"] },
  run:{ meaning:"to move quickly on foot", pos:["verb","noun"], examples:["<u>run</u>","run<u>ning</u>","run<u>s</u>"] },
  plan:{ meaning:"to organise what you will do", pos:["verb","noun"], examples:["<u>plan</u>","plan<u>ned</u>","plan<u>ning</u>"] },
  hop:{ meaning:"to jump on one foot", pos:["verb","noun"], examples:["<u>hop</u>","hop<u>ped</u>","hop<u>ing</u>"] },
  play:{ meaning:"to take part in a game; to have fun", pos:["verb","noun"], examples:["<u>play</u>","re<u>play</u>","play<u>ful</u>"] },
  work:{ meaning:"to do a job; effort", pos:["verb","noun"], examples:["<u>work</u>","re<u>work</u>","work<u>er</u>"] },
  read:{ meaning:"to look at and understand words", pos:["verb"], examples:["<u>read</u>","re<u>read</u>","read<u>er</u>"] },
  think:{ meaning:"to use your mind", pos:["verb"], examples:["<u>think</u>","re<u>think</u>","think<u>er</u>"] },
  kind:{ meaning:"friendly and caring", pos:["adj","noun"], examples:["<u>kind</u>","un<u>kind</u>","kind<u>ness</u>"] },
  hope:{ meaning:"to wish for something good", pos:["verb","noun"], examples:["<u>hope</u>","hope<u>ful</u>","hope<u>less</u>"] },
  fear:{ meaning:"to be afraid of", pos:["verb","noun"], examples:["<u>fear</u>","fear<u>ful</u>","fear<u>less</u>"] },
  thank:{ meaning:"to show you are grateful", pos:["verb","noun"], examples:["<u>thank</u>","thank<u>ful</u>","thank<u>less</u>"] },
  harm:{ meaning:"to hurt or damage", pos:["verb","noun"], examples:["<u>harm</u>","harm<u>ful</u>","harm<u>less</u>"] },
  taste:{ meaning:"the flavour of something", pos:["verb","noun"], examples:["<u>taste</u>","taste<u>ful</u>","taste<u>less</u>"] },
  doubt:{ meaning:"to be unsure about", pos:["verb","noun"], examples:["<u>doubt</u>","doubt<u>ful</u>","un<u>doubt</u>ed"] },
  count:{ meaning:"to find the total; to matter", pos:["verb","noun"], examples:["<u>count</u>","re<u>count</u>","count<u>er</u>"] },
  start:{ meaning:"to begin", pos:["verb","noun"], examples:["<u>start</u>","re<u>start</u>","start<u>er</u>"] },
  stop:{ meaning:"to no longer move or happen", pos:["verb","noun"], examples:["<u>stop</u>","stop<u>ped</u>","non<u>stop</u>"] },
  hold:{ meaning:"to keep in your hands; to contain", pos:["verb","noun"], examples:["<u>hold</u>","hold<u>er</u>","up<u>hold</u>"] },
  fill:{ meaning:"to make full", pos:["verb","noun"], examples:["<u>fill</u>","re<u>fill</u>","fill<u>er</u>"] },
  print:{ meaning:"to put words or pictures on paper", pos:["verb","noun"], examples:["<u>print</u>","re<u>print</u>","print<u>er</u>"] },
  heat:{ meaning:"warmth; to make warm", pos:["verb","noun"], examples:["<u>heat</u>","pre<u>heat</u>","heat<u>er</u>"] },
  paint:{ meaning:"to colour a surface; a coloured liquid", pos:["verb","noun"], examples:["<u>paint</u>","re<u>paint</u>","paint<u>er</u>"] },
  load:{ meaning:"to put things onto; a heavy weight", pos:["verb","noun"], examples:["<u>load</u>","re<u>load</u>","over<u>load</u>"] },
  order:{ meaning:"to arrange; a command", pos:["verb","noun"], examples:["<u>order</u>","re<u>order</u>","dis<u>order</u>"] },
  spell:{ meaning:"to write or say letters in order", pos:["verb","noun"], examples:["<u>spell</u>","mis<u>spell</u>","spell<u>ing</u>"] },
  clean:{ meaning:"free from dirt", pos:["adj","verb"], examples:["<u>clean</u>","clean<u>er</u>","un<u>clean</u>"] },
  sharp:{ meaning:"having a fine edge or point", pos:["adj"], examples:["<u>sharp</u>","sharp<u>en</u>","sharp<u>ly</u>"] },
  bright:{ meaning:"giving out a lot of light; clever", pos:["adj"], examples:["<u>bright</u>","bright<u>en</u>","bright<u>ly</u>"] },
  fair:{ meaning:"treating people equally; just", pos:["adj","noun"], examples:["<u>fair</u>","un<u>fair</u>","fair<u>ly</u>"] },
  safe:{ meaning:"free from danger", pos:["adj","noun"], examples:["<u>safe</u>","safe<u>ly</u>","safe<u>ty</u>"] },
  deep:{ meaning:"going far down or in", pos:["adj"], examples:["<u>deep</u>","deep<u>en</u>","deep<u>ly</u>"] },
  weak:{ meaning:"not strong", pos:["adj"], examples:["<u>weak</u>","weak<u>en</u>","weak<u>ness</u>"] },
  soft:{ meaning:"not hard or rough", pos:["adj"], examples:["<u>soft</u>","soft<u>en</u>","soft<u>ly</u>"] },
  dark:{ meaning:"with little or no light", pos:["adj","noun"], examples:["<u>dark</u>","dark<u>en</u>","dark<u>ness</u>"] },
  sweet:{ meaning:"tasting like sugar; pleasant", pos:["adj","noun"], examples:["<u>sweet</u>","sweet<u>en</u>","sweet<u>ly</u>"] },
  quick:{ meaning:"moving fast; done in a short time", pos:["adj"], examples:["<u>quick</u>","quick<u>en</u>","quick<u>ly</u>"] },
  slow:{ meaning:"not fast", pos:["adj","verb"], examples:["<u>slow</u>","slow<u>ly</u>","slow<u>ness</u>"] },
  warm:{ meaning:"fairly hot; friendly", pos:["adj","verb"], examples:["<u>warm</u>","warm<u>th</u>","warm<u>ly</u>"] },
  fresh:{ meaning:"new; recently made", pos:["adj"], examples:["<u>fresh</u>","re<u>fresh</u>","fresh<u>ly</u>"] },
  hard:{ meaning:"not soft; difficult", pos:["adj"], examples:["<u>hard</u>","hard<u>en</u>","hard<u>ly</u>"] },
  price:{ meaning:"the amount of money something costs", pos:["noun","verb"], examples:["<u>price</u>","price<u>less</u>","over<u>price</u>"] },
  cover:{ meaning:"to put something over; to include", pos:["verb","noun"], examples:["<u>cover</u>","dis<u>cover</u>","un<u>cover</u>"] },
  land:{ meaning:"an area of ground; to arrive", pos:["noun","verb"], examples:["<u>land</u>","<u>land</u>ing","mid<u>land</u>"] },
  test:{ meaning:"to check or try out", pos:["verb","noun"], examples:["<u>test</u>","test<u>er</u>","re<u>test</u>"] },
  grace:{ meaning:"beauty of movement; a prayer", pos:["noun","verb"], examples:["<u>grace</u>","grace<u>ful</u>","dis<u>grace</u>"] },
  comfort:{ meaning:"a state of ease; to soothe", pos:["noun","verb"], examples:["<u>comfort</u>","dis<u>comfort</u>","comfort<u>able</u>"] },
  agree:{ meaning:"to have the same opinion", pos:["verb"], examples:["<u>agree</u>","dis<u>agree</u>","agree<u>ment</u>"] },
  colour:{ meaning:"the property of light; to add colour", pos:["noun","verb"], examples:["<u>colour</u>","dis<u>colour</u>","colour<u>ful</u>"] }
};

const ANGLO_BASE_LIST = [
  "teach","meet","rest","go","tall","help","ask","eat","train","usual","end","turn","open","make","jump","bad","lock",
  "move","like","care","happy","push","zip","take","see","brisk","wake","send","round","cloud","pay","lift","pack",
  "sound","correct","part","live","sad","trust","merge","run","plan","hop",
  "play","work","read","think","kind","hope","fear","thank","harm","taste","doubt","count","start","stop","hold",
  "fill","print","heat","paint","load","order","spell","clean","sharp","bright","fair","safe","deep","weak","soft",
  "dark","sweet","quick","slow","warm","fresh","hard","price","cover","land","test","grace","comfort","agree","colour"
];

const ANGLO_BASES = ANGLO_BASE_LIST.map((w,i)=>({
  id:`anglo_${i}`,
  form:w,
  display:w,
  meaning:(ANGLO_BASE_INFO[w]?.meaning || ""),
  pos:(ANGLO_BASE_INFO[w]?.pos || ["noun","adj","verb"]),
  examples:(ANGLO_BASE_INFO[w]?.examples || [])
}));

const LATIN_BASE_INFO = {
  rupt:{ meaning:"break", pos:["verb"], examples:["e<u>rupt</u>","inter<u>rupt</u>","<u>rupt</u>ure"] },
  tract:{ meaning:"pull; draw", pos:["verb"], examples:["at<u>tract</u>","con<u>tract</u>","sub<u>tract</u>"] },
  form:{ meaning:"shape; make", pos:["noun","verb"], examples:["<u>form</u>","trans<u>form</u>","form<u>ation</u>"] },
  cred:{ meaning:"believe; trust", pos:["verb"], examples:["<u>cred</u>it","in<u>cred</u>ible","cred<u>ible</u>"] },
  dic:{ meaning:"say; speak", pos:["verb"], examples:["pre<u>dic</u>t","bene<u>dic</u>tion","contra<u>dic</u>t"] },
  dict:{ meaning:"say; tell", pos:["verb"], examples:["pre<u>dict</u>","<u>dict</u>ionary","contra<u>dict</u>"] },
  struct:{ meaning:"build", pos:["verb"], examples:["con<u>struct</u>","<u>struct</u>ure","in<u>struct</u>ion"] },
  scrib:{ meaning:"write", pos:["verb"], examples:["de<u>scrib</u>e","in<u>scrib</u>e","manu<u>scrib</u>t"] },
  script:{ meaning:"written; writing", pos:["noun"], examples:["<u>script</u>","de<u>script</u>ion","manu<u>script</u>"] },
  port:{ meaning:"carry", pos:["verb"], examples:["trans<u>port</u>","im<u>port</u>","port<u>able</u>"] },
  aud:{ meaning:"hear", pos:["verb"], examples:["<u>aud</u>io","<u>aud</u>ience","<u>aud</u>ible"] },
  flex:{ meaning:"bend", pos:["verb"], examples:["<u>flex</u>ible","re<u>flex</u>","<u>flex</u>ion"] },
  flect:{ meaning:"bend", pos:["verb"], examples:["re<u>flect</u>","de<u>flect</u>","in<u>flect</u>ion"] },
  ject:{ meaning:"throw", pos:["verb"], examples:["re<u>ject</u>","pro<u>ject</u>","e<u>ject</u>"] },
  spec:{ meaning:"look; see", pos:["verb"], examples:["in<u>spec</u>t","spec<u>ial</u>","retro<u>spec</u>t"] },
  spect:{ meaning:"look; watch", pos:["verb"], examples:["in<u>spect</u>","<u>spect</u>ator","retro<u>spect</u>"] },
  spic:{ meaning:"look; see", pos:["verb"], examples:["sus<u>pic</u>ion","aus<u>pic</u>ious","per<u>spic</u>uous"] },
  miss:{ meaning:"send", pos:["verb"], examples:["dis<u>miss</u>","<u>miss</u>ion","re<u>miss</u>"] },
  mit:{ meaning:"send", pos:["verb"], examples:["sub<u>mit</u>","per<u>mit</u>","com<u>mit</u>"] },
  sci:{ meaning:"know", pos:["verb"], examples:["<u>sci</u>ence","con<u>sci</u>ous","omni<u>sci</u>ent"] },
  pend:{ meaning:"hang; weigh", pos:["verb"], examples:["de<u>pend</u>","sus<u>pend</u>","<u>pend</u>ulum"] },
  pens:{ meaning:"weigh; think", pos:["verb"], examples:["com<u>pens</u>ate","ex<u>pens</u>e","dis<u>pens</u>e"] },
  vis:{ meaning:"see", pos:["verb"], examples:["tele<u>vis</u>ion","<u>vis</u>ible","re<u>vis</u>e"] },
  vid:{ meaning:"see", pos:["verb"], examples:["e<u>vid</u>ent","pro<u>vid</u>e","indi<u>vid</u>ual"] },
  fer:{ meaning:"carry; bring", pos:["verb"], examples:["trans<u>fer</u>","of<u>fer</u>","pre<u>fer</u>"] },
  vers:{ meaning:"turn", pos:["verb"], examples:["re<u>vers</u>e","con<u>vers</u>e","uni<u>vers</u>e"] },
  vert:{ meaning:"turn", pos:["verb"], examples:["con<u>vert</u>","in<u>vert</u>","re<u>vert</u>"] },
  duc:{ meaning:"lead", pos:["verb"], examples:["pro<u>duc</u>e","intro<u>duc</u>e","edu<u>c</u>ate"] },
  duct:{ meaning:"lead", pos:["verb"], examples:["con<u>duct</u>","pro<u>duct</u>","re<u>duct</u>ion"] },
  sec:{ meaning:"cut", pos:["verb"], examples:["bi<u>sec</u>t","di<u>sec</u>t","in<u>sec</u>t"] },
  sect:{ meaning:"cut", pos:["verb"], examples:["bi<u>sect</u>","dis<u>sect</u>","<u>sect</u>ion"] },
  claus:{ meaning:"close", pos:["verb"], examples:["<u>claus</u>e","con<u>clus</u>ion","ex<u>clus</u>ive"] },
  clos:{ meaning:"close", pos:["verb"], examples:["<u>clos</u>e","en<u>clos</u>e","dis<u>clos</u>e"] },
  vit:{ meaning:"life", pos:["noun"], examples:["<u>vit</u>al","<u>vit</u>amin","in<u>vit</u>e"] },
  viv:{ meaning:"live", pos:["verb"], examples:["sur<u>viv</u>e","re<u>viv</u>e","<u>viv</u>id"] },

  cept:{ meaning:"take; receive", pos:["verb"], examples:["ac<u>cept</u>","re<u>cept</u>ion","ex<u>cept</u>"] },
  cess:{ meaning:"go; yield; give way", pos:["verb"], examples:["ac<u>cess</u>","pro<u>cess</u>","re<u>cess</u>"] },
  fect:{ meaning:"make; do", pos:["verb"], examples:["per<u>fect</u>","af<u>fect</u>","ef<u>fect</u>"] },
  fix:{ meaning:"fasten; attach", pos:["verb"], examples:["<u>fix</u>","pre<u>fix</u>","suf<u>fix</u>"] },
  sign:{ meaning:"mark; signal", pos:["verb","noun"], examples:["<u>sign</u>","<u>sign</u>al","de<u>sign</u>"] },
  tend:{ meaning:"stretch; reach", pos:["verb"], examples:["ex<u>tend</u>","at<u>tend</u>","pre<u>tend</u>"] },
  press:{ meaning:"press; push", pos:["verb"], examples:["<u>press</u>","com<u>press</u>","ex<u>press</u>"] },
  gress:{ meaning:"step; go", pos:["verb"], examples:["pro<u>gress</u>","di<u>gress</u>","re<u>gress</u>"] },
  cede:{ meaning:"go; yield", pos:["verb"], examples:["pro<u>cede</u>","re<u>cede</u>","con<u>cede</u>"] },
  claim:{ meaning:"call out; cry", pos:["verb","noun"], examples:["pro<u>claim</u>","ex<u>claim</u>","re<u>claim</u>"] },
  prove:{ meaning:"test; show", pos:["verb"], examples:["ap<u>prove</u>","im<u>prove</u>","<u>prove</u>n"] },
  ply:{ meaning:"fold; bend", pos:["verb"], examples:["ap<u>ply</u>","re<u>ply</u>","mul<u>tiply</u>"] },
  spire:{ meaning:"breathe; live", pos:["verb"], examples:["in<u>spire</u>","re<u>spire</u>","con<u>spire</u>"] }
};

const LATIN_BASE_LIST = [
  "rupt","tract","form","cred","dic","dict","struct","scrib","script","port","aud","flex","flect","ject","spec","spect","spic",
  "miss","mit","sci","pend","pens","vis","vid","fer","vers","vert","duc","duct","sec","sect","claus","clos","vit","viv",
  "cept","cess","fect","fix","sign","tend","press","gress","cede","claim","prove","ply","spire"
];

const LATIN_BASES = LATIN_BASE_LIST.map((w,i)=>({
  id:`latin_${i}`,
  form:w,
  display:w,
  meaning:(LATIN_BASE_INFO[w]?.meaning || ""),
  pos:(LATIN_BASE_INFO[w]?.pos || ["noun","adj","verb"]),
  examples:(LATIN_BASE_INFO[w]?.examples || [])
}));

const GREEK_BASE_INFO = {
  graph:{ meaning:"write; drawing", pos:["verb","noun"], examples:["<u>graph</u>","auto<u>graph</u>","bio<u>graph</u>y"] },
  gram:{ meaning:"written; something written", pos:["adj","noun"], examples:["tele<u>gram</u>","ana<u>gram</u>","pro<u>gram</u>"] },
  micro:{ meaning:"small", pos:["adj"], examples:["<u>micro</u>scope","<u>micro</u>chip","<u>micro</u>wave"] },
  hydr:{ meaning:"water", pos:["noun"], examples:["de<u>hydr</u>ate","<u>hydr</u>ant","<u>hydr</u>ology"] },
  hydro:{ meaning:"water", pos:["noun"], examples:["<u>hydro</u>logy","<u>hydro</u>electric","<u>hydro</u>plane"] },
  therm:{ meaning:"heat", pos:["noun"], examples:["<u>therm</u>al","geo<u>therm</u>al","<u>therm</u>ometer"] },
  thermo:{ meaning:"heat", pos:["noun"], examples:["<u>thermo</u>meter","<u>thermo</u>stat","<u>thermo</u>s"] },
  phon:{ meaning:"sound; voice", pos:["noun"], examples:["micro<u>phon</u>e","tele<u>phon</u>e","sym<u>phon</u>y"] },
  logy:{ meaning:"study of", pos:["noun"], examples:["bio<u>logy</u>","geo<u>logy</u>","techno<u>logy</u>"] },
  chron:{ meaning:"time", pos:["noun"], examples:["syn<u>chron</u>ise","ana<u>chron</u>ism","<u>chron</u>ic"] },
  chrono:{ meaning:"time", pos:["noun"], examples:["<u>chrono</u>logy","<u>chrono</u>meter","<u>chrono</u>logical"] },
  photo:{ meaning:"light", pos:["noun"], examples:["<u>photo</u>graph","<u>photo</u>copy","<u>photo</u>synthesis"] },
  scope:{ meaning:"look; view; examine", pos:["noun","verb"], examples:["tele<u>scope</u>","micro<u>scope</u>","peri<u>scope</u>"] },
  meter:{ meaning:"measure", pos:["noun","verb"], examples:["thermo<u>meter</u>","kilo<u>meter</u>","speedo<u>meter</u>"] },
  aero:{ meaning:"air", pos:["noun"], examples:["<u>aero</u>plane","<u>aero</u>bics","<u>aero</u>dynamic"] }
};

const GREEK_BASE_LIST = [
  "graph","gram","micro","hydr","hydro","therm","thermo","phon","logy","chron","chrono","photo","scope","meter","aero"
];

const GREEK_BASES = GREEK_BASE_LIST.map((w,i)=>({
  id:`greek_${i}`,
  form:w,
  display:w,
  meaning:(GREEK_BASE_INFO[w]?.meaning || ""),
  pos:(GREEK_BASE_INFO[w]?.pos || ["noun","adj","verb"]),
  examples:(GREEK_BASE_INFO[w]?.examples || [])
}));

window.MORPHEMES = {
  prefixes: PREFIXES,
  suffixes: SUFFIXES,
  bases: [
    ...CORE_BASES.map(b => ({ ...b, display:b.form, group:"core" })),
    ...ANGLO_BASES.map(b => ({ ...b, group:"anglo" })),
    ...LATIN_BASES.map(b => ({ ...b, group:"latin" })),
    ...GREEK_BASES.map(b => ({ ...b, group:"greek" }))
  ]
};
window.PREFIXES = PREFIXES;
window.SUFFIXES = SUFFIXES;
