-- Unit 33 — resource inserts for the Supabase `resources` table (Stage 4).
-- Generated from units/u33/03_resources_staged.csv (every URL verified live in Stage 3).
-- Run in the Supabase SQL editor (anon key cannot write). DO NOT auto-execute.

DELETE FROM resources WHERE unit_id = 'u33';

INSERT INTO resources (unit_id, outcome_id, type, label, url, scope, class_id) VALUES
  ('u33', 'r1', 'video', 'Whole Number Expanded, Word and Standard Form | Math with Mr. J', 'https://www.youtube.com/watch?v=NOx6jlVSSpU', 'global', NULL),
  ('u33', 'r1', 'video', 'How to Write Whole Numbers in Standard Form | Math with Mr. J', 'https://www.youtube.com/watch?v=H6ndRKigay8', 'global', NULL),
  ('u33', 'r1', 'worksheet', 'Corbettmaths — Place Value (PDF)', 'https://corbettmaths.com/wp-content/uploads/2013/02/place-value-pdf.pdf', 'global', NULL),
  ('u33', 'r2', 'video', 'Order of Operations: A Step-By-Step Guide (PEMDAS) | Math with Mr. J', 'https://www.youtube.com/watch?v=x41BCrYh8Kc', 'global', NULL),
  ('u33', 'r2', 'video', 'Order of Operations (No Parentheses or Exponents) | Math with Mr. J', 'https://www.youtube.com/watch?v=BCg1nz5k0HY', 'global', NULL),
  ('u33', 'r2', 'worksheet', 'Corbettmaths — Order of Operations (PDF)', 'https://corbettmaths.com/wp-content/uploads/2013/02/order-of-operations-pdf.pdf', 'global', NULL),
  ('u33', 'r3', 'video', 'Multiplying and Dividing by Powers of 10 | Math with Mr. J', 'https://www.youtube.com/watch?v=HH-yrNS80Cg', 'global', NULL),
  ('u33', 'r3', 'video', 'Place Value to the Thousandths | Miacademy', 'https://www.youtube.com/watch?v=BsZJGMRWEK0', 'global', NULL),
  ('u33', 'r3', 'worksheet', 'Corbettmaths — Dividing by 10, 100, 1000 (PDF)', 'https://corbettmaths.com/wp-content/uploads/2013/02/dividing-by-10-100-1000-pdf.pdf', 'global', NULL),
  ('u33', 'r3', 'worksheet', 'Corbettmaths — Place Value (PDF)', 'https://corbettmaths.com/wp-content/uploads/2013/02/place-value-pdf.pdf', 'global', NULL),
  ('u33', 'r4', 'video', 'How to do Long Division (1-Digit Divisors) | Math with Mr. J', 'https://www.youtube.com/watch?v=up_xKZ6GeUg', 'global', NULL),
  ('u33', 'r4', 'video', 'Long Division: A Step-By-Step Review | Math with Mr. J', 'https://www.youtube.com/watch?v=HJYHNxS64f0', 'global', NULL),
  ('u33', 'r4', 'worksheet', 'Corbettmaths — Division (PDF)', 'https://corbettmaths.com/wp-content/uploads/2018/01/division-pdf.pdf', 'global', NULL),
  ('u33', 'y1', 'video', '3-Digit by 2-Digit Multiplication | Math with Mr. J', 'https://www.youtube.com/watch?v=dNSrfoYLQZU', 'global', NULL),
  ('u33', 'y1', 'video', '2-Digit by 2-Digit Multiplication | Math with Mr. J', 'https://www.youtube.com/watch?v=PZjIT9CH6bM', 'global', NULL),
  ('u33', 'y1', 'video', 'Box Method Multiplication | Math with Mr. J', 'https://www.youtube.com/watch?v=n3q3XzzIGSY', 'global', NULL),
  ('u33', 'y1', 'worksheet', 'Corbettmaths — Multiplication (PDF)', 'https://corbettmaths.com/wp-content/uploads/2013/02/multiplication-pdf.pdf', 'global', NULL),
  ('u33', 'y2', 'video', 'How to Multiply a Whole Number and a Decimal | Math with Mr. J', 'https://www.youtube.com/watch?v=FbZr5br9ZOg', 'global', NULL),
  ('u33', 'y2', 'video', 'Multiply a Whole Number by a Decimal | Math with Mr. J', 'https://www.youtube.com/watch?v=tsOibhsgYoQ', 'global', NULL),
  ('u33', 'y2', 'video', 'Multiplying Decimals | Math with Mr. J', 'https://www.youtube.com/watch?v=cikGV-gh-ig', 'global', NULL),
  ('u33', 'y2', 'worksheet', 'Corbettmaths — Multiplying Decimals (PDF)', 'https://corbettmaths.com/wp-content/uploads/2018/01/multiplying-decimals-textbook-pdf.pdf', 'global', NULL),
  ('u33', 'y3', 'video', 'Unit Rate Word Problem (Double Number Line) | Math with Ms. M', 'https://www.youtube.com/watch?v=Y7koW8jkoOs', 'global', NULL),
  ('u33', 'y3', 'video', 'Solving Unit Rate Problems | Planet Nutshell', 'https://www.youtube.com/watch?v=LbJUEuEqAIg', 'global', NULL),
  ('u33', 'y3', 'worksheet', 'Corbettmaths — Multiplication (PDF)', 'https://corbettmaths.com/wp-content/uploads/2013/02/multiplication-pdf.pdf', 'global', NULL),
  ('u33', 'y4', 'video', 'Input Output Tables: Find Patterns or Rules | Easy Math with Mrs. Easley', 'https://www.youtube.com/watch?v=q0n7FMe1CQk', 'global', NULL),
  ('u33', 'y4', 'video', 'Input & Output Tables: Rules & Missing Values | STEAMspirations', 'https://www.youtube.com/watch?v=Z7UPvsKz4Kw', 'global', NULL),
  ('u33', 'y4', 'video', 'Input Output Tables Song: Finding the Rule | NUMBEROCK', 'https://www.youtube.com/watch?v=d1COIcRoSgo', 'global', NULL),
  ('u33', 'y5', 'video', 'Order of Operations: A Step-By-Step Guide (PEMDAS) | Math with Mr. J', 'https://www.youtube.com/watch?v=x41BCrYh8Kc', 'global', NULL),
  ('u33', 'y5', 'video', 'Order of Operations (No Parentheses or Exponents) | Math with Mr. J', 'https://www.youtube.com/watch?v=BCg1nz5k0HY', 'global', NULL),
  ('u33', 'y5', 'worksheet', 'Corbettmaths — Order of Operations (PDF)', 'https://corbettmaths.com/wp-content/uploads/2013/02/order-of-operations-pdf.pdf', 'global', NULL),
  ('u33', 'y6', 'video', 'How Do You Solve Inverse Operations? (KS2) | Twinkl', 'https://www.youtube.com/watch?v=enw_kJRSt4A', 'global', NULL),
  ('u33', 'y6', 'video', 'Input & Output Tables: Rules & Missing Values | STEAMspirations', 'https://www.youtube.com/watch?v=Z7UPvsKz4Kw', 'global', NULL),
  ('u33', 'y6', 'worksheet', 'Corbettmaths — Multiplication (PDF)', 'https://corbettmaths.com/wp-content/uploads/2013/02/multiplication-pdf.pdf', 'global', NULL),
  ('u33', 'g1', 'video', 'Unit Rate Word Problem (Double Number Line) | Math with Ms. M', 'https://www.youtube.com/watch?v=Y7koW8jkoOs', 'global', NULL),
  ('u33', 'g1', 'video', 'Solving Unit Rate Problems | Planet Nutshell', 'https://www.youtube.com/watch?v=LbJUEuEqAIg', 'global', NULL),
  ('u33', 'g1', 'worksheet', 'Corbettmaths — Best Buys (PDF)', 'https://corbettmaths.com/wp-content/uploads/2013/02/best-buys-pdf1.pdf', 'global', NULL),
  ('u33', 'g2', 'video', 'Unitary Method | Corbettmaths', 'https://www.youtube.com/watch?v=AXkCfkVrjK8', 'global', NULL),
  ('u33', 'g2', 'video', 'Dividing a Quantity in a Given Ratio | Mrs G''s Maths', 'https://www.youtube.com/watch?v=LYk4Xq9P0T0', 'global', NULL),
  ('u33', 'g2', 'video', 'Simplifying Ratios | N.I. Maths Tutor', 'https://www.youtube.com/watch?v=uYjJ5mYPLEM', 'global', NULL),
  ('u33', 'g2', 'worksheet', 'Corbettmaths — Ratio (PDF)', 'https://corbettmaths.com/wp-content/uploads/2013/02/ratio-pdf.pdf', 'global', NULL),
  ('u33', 'g3', 'video', 'Order of Operations with Integers (Positives and Negatives) | Math with Mr. J', 'https://www.youtube.com/watch?v=AtPS0pWthEo', 'global', NULL),
  ('u33', 'g3', 'video', 'An Intro to Order of Operations with Integers | Math with Mr. J', 'https://www.youtube.com/watch?v=efQ1XPqw0s0', 'global', NULL),
  ('u33', 'g3', 'worksheet', 'Corbettmaths — Order of Operations (PDF)', 'https://corbettmaths.com/wp-content/uploads/2013/02/order-of-operations-pdf.pdf', 'global', NULL);
