/**
 * Unit 33 — Multiplicative Strategies, Rates & Order of Operations (Stage 3 Year B).
 * Deliverable B. Built from units/u33/00_rubric_draft.md + 01_mapping_review.md.
 * Matches the UNIT DATA SCHEMA at the bottom of scripts/build_program_template.js.
 *
 * Program has the resource appendix merged (resource_appendix_attached: true); a
 * standalone Unit33_Resource_Appendix.docx is also emitted (Stage 5). Every resource
 * URL verified live in Stage 3 (units/u33/03_resources_staged.csv).
 *
 * Outcome -> Mini Lesson map (DoE teaching order L1-8, then Stage-4 Green cards):
 *   Y4->1 R2->2 R1->3 Y1->4 R4->5 Y6->6 R3->7 Y2->8 Y3->9 Y5->10 G1->11 G2->12 G3->13
 */
module.exports = {
  unit_number: "33",
  unit_title: "Multiplicative Strategies, Rates & Order of Operations",
  term: null,
  duration: "2-3 weeks",

  resource_appendix_attached: true,

  // Every URL verified live in Stage 3 (oEmbed + curl); see units/u33/03_resources_staged.csv.
  resources: {
    r1: [
      { type: "video", label: "Whole Number Expanded, Word and Standard Form | Math with Mr. J", url: "https://www.youtube.com/watch?v=NOx6jlVSSpU" },
      { type: "video", label: "How to Write Whole Numbers in Standard Form | Math with Mr. J", url: "https://www.youtube.com/watch?v=H6ndRKigay8" },
      { type: "worksheet", label: "Corbettmaths — Place Value (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/place-value-pdf.pdf" },
    ],
    r2: [
      { type: "video", label: "Order of Operations: A Step-By-Step Guide (PEMDAS) | Math with Mr. J", url: "https://www.youtube.com/watch?v=x41BCrYh8Kc" },
      { type: "video", label: "Order of Operations (No Parentheses or Exponents) | Math with Mr. J", url: "https://www.youtube.com/watch?v=BCg1nz5k0HY" },
      { type: "worksheet", label: "Corbettmaths — Order of Operations (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/order-of-operations-pdf.pdf" },
    ],
    r3: [
      { type: "video", label: "Multiplying and Dividing by Powers of 10 | Math with Mr. J", url: "https://www.youtube.com/watch?v=HH-yrNS80Cg" },
      { type: "video", label: "Place Value to the Thousandths | Miacademy", url: "https://www.youtube.com/watch?v=BsZJGMRWEK0" },
      { type: "worksheet", label: "Corbettmaths — Dividing by 10, 100, 1000 (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/dividing-by-10-100-1000-pdf.pdf" },
      { type: "worksheet", label: "Corbettmaths — Place Value (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/place-value-pdf.pdf" },
    ],
    r4: [
      { type: "video", label: "How to do Long Division (1-Digit Divisors) | Math with Mr. J", url: "https://www.youtube.com/watch?v=up_xKZ6GeUg" },
      { type: "video", label: "Long Division: A Step-By-Step Review | Math with Mr. J", url: "https://www.youtube.com/watch?v=HJYHNxS64f0" },
      { type: "worksheet", label: "Corbettmaths — Division (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2018/01/division-pdf.pdf" },
    ],
    y1: [
      { type: "video", label: "3-Digit by 2-Digit Multiplication | Math with Mr. J", url: "https://www.youtube.com/watch?v=dNSrfoYLQZU" },
      { type: "video", label: "2-Digit by 2-Digit Multiplication | Math with Mr. J", url: "https://www.youtube.com/watch?v=PZjIT9CH6bM" },
      { type: "video", label: "Box Method Multiplication | Math with Mr. J", url: "https://www.youtube.com/watch?v=n3q3XzzIGSY" },
      { type: "worksheet", label: "Corbettmaths — Multiplication (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/multiplication-pdf.pdf" },
    ],
    y2: [
      { type: "video", label: "How to Multiply a Whole Number and a Decimal | Math with Mr. J", url: "https://www.youtube.com/watch?v=FbZr5br9ZOg" },
      { type: "video", label: "Multiply a Whole Number by a Decimal | Math with Mr. J", url: "https://www.youtube.com/watch?v=tsOibhsgYoQ" },
      { type: "video", label: "Multiplying Decimals | Math with Mr. J", url: "https://www.youtube.com/watch?v=cikGV-gh-ig" },
      { type: "worksheet", label: "Corbettmaths — Multiplying Decimals (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2018/01/multiplying-decimals-textbook-pdf.pdf" },
    ],
    y3: [
      { type: "video", label: "Unit Rate Word Problem (Double Number Line) | Math with Ms. M", url: "https://www.youtube.com/watch?v=Y7koW8jkoOs" },
      { type: "video", label: "Solving Unit Rate Problems | Planet Nutshell", url: "https://www.youtube.com/watch?v=LbJUEuEqAIg" },
      { type: "worksheet", label: "Corbettmaths — Multiplication (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/multiplication-pdf.pdf" },
    ],
    y4: [
      { type: "video", label: "Input Output Tables: Find Patterns or Rules | Easy Math with Mrs. Easley", url: "https://www.youtube.com/watch?v=q0n7FMe1CQk" },
      { type: "video", label: "Input & Output Tables: Rules & Missing Values | STEAMspirations", url: "https://www.youtube.com/watch?v=Z7UPvsKz4Kw" },
      { type: "video", label: "Input Output Tables Song: Finding the Rule | NUMBEROCK", url: "https://www.youtube.com/watch?v=d1COIcRoSgo" },
    ],
    y5: [
      { type: "video", label: "Order of Operations: A Step-By-Step Guide (PEMDAS) | Math with Mr. J", url: "https://www.youtube.com/watch?v=x41BCrYh8Kc" },
      { type: "video", label: "Order of Operations (No Parentheses or Exponents) | Math with Mr. J", url: "https://www.youtube.com/watch?v=BCg1nz5k0HY" },
      { type: "worksheet", label: "Corbettmaths — Order of Operations (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/order-of-operations-pdf.pdf" },
    ],
    y6: [
      { type: "video", label: "How Do You Solve Inverse Operations? (KS2) | Twinkl", url: "https://www.youtube.com/watch?v=enw_kJRSt4A" },
      { type: "video", label: "Input & Output Tables: Rules & Missing Values | STEAMspirations", url: "https://www.youtube.com/watch?v=Z7UPvsKz4Kw" },
      { type: "worksheet", label: "Corbettmaths — Multiplication (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/multiplication-pdf.pdf" },
    ],
    g1: [
      { type: "video", label: "Unit Rate Word Problem (Double Number Line) | Math with Ms. M", url: "https://www.youtube.com/watch?v=Y7koW8jkoOs" },
      { type: "video", label: "Solving Unit Rate Problems | Planet Nutshell", url: "https://www.youtube.com/watch?v=LbJUEuEqAIg" },
      { type: "worksheet", label: "Corbettmaths — Best Buys (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/best-buys-pdf1.pdf" },
    ],
    g2: [
      { type: "video", label: "Unitary Method | Corbettmaths", url: "https://www.youtube.com/watch?v=AXkCfkVrjK8" },
      { type: "video", label: "Dividing a Quantity in a Given Ratio | Mrs G's Maths", url: "https://www.youtube.com/watch?v=LYk4Xq9P0T0" },
      { type: "video", label: "Simplifying Ratios | N.I. Maths Tutor", url: "https://www.youtube.com/watch?v=uYjJ5mYPLEM" },
      { type: "worksheet", label: "Corbettmaths — Ratio (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/ratio-pdf.pdf" },
    ],
    g3: [
      { type: "video", label: "Order of Operations with Integers (Positives and Negatives) | Math with Mr. J", url: "https://www.youtube.com/watch?v=AtPS0pWthEo" },
      { type: "video", label: "An Intro to Order of Operations with Integers | Math with Mr. J", url: "https://www.youtube.com/watch?v=efQ1XPqw0s0" },
      { type: "worksheet", label: "Corbettmaths — Order of Operations (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/order-of-operations-pdf.pdf" },
    ],
  },
  beyond_resources: [
    { type: "video", label: "Unit Rate Word Problem (Double Number Line) | Math with Ms. M", url: "https://www.youtube.com/watch?v=Y7koW8jkoOs" },
    { type: "video", label: "Unitary Method | Corbettmaths", url: "https://www.youtube.com/watch?v=AXkCfkVrjK8" },
    { type: "video", label: "Order of Operations with Integers | Math with Mr. J", url: "https://www.youtube.com/watch?v=AtPS0pWthEo" },
    { type: "worksheet", label: "Corbettmaths — Best Buys (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/best-buys-pdf1.pdf" },
    { type: "worksheet", label: "Corbettmaths — Ratio (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/ratio-pdf.pdf" },
    { type: "website", label: "Maths is Fun — Ratios (interactive)", url: "https://www.mathsisfun.com/numbers/ratio.html" },
    { type: "website", label: "Maths is Fun — Order of Operations (PEMDAS)", url: "https://www.mathsisfun.com/operation-order-pemdas.html" },
  ],

  syllabus_strands_summary: "Multiplicative Relations, extended with Stage 4 Ratios & Rates",
  strand_abbreviations_note: "MR = Multiplicative Relations. RN = Represents Numbers (regrouping). RAT = Ratios and Rates (Stage 4). INT = Computation with integers (Stage 4). A/B = syllabus content groups (B is the multiplicative home content for this Year-B unit).",

  syllabus_outcomes: [
    { code: "MAO-WM-01", descriptor: "Develops understanding and fluency through exploring, applying and communicating mathematical reasoning." },
    { code: "MA3-MR-01", descriptor: "Selects and applies appropriate strategies to solve multiplication and division problems." },
    { code: "MA3-MR-02", descriptor: "Constructs and completes number sentences, applying the order of operations to calculations." },
    { code: "MA3-RN-01", descriptor: "Applies place value to represent and regroup the natural numbers to billions." },
    { code: "MA4-RAT / INT", descriptor: "Stage 4 (group A): solves problems involving rates and ratios (RAT); applies the order of operations to integers (INT)." },
  ],

  content_points: {
    red: {
      heading: "Multiplicative B & place value (recall & single procedures)",
      heading_short: "Red -- Foundation",
      points: [
        "Regroup whole numbers in different forms.",
        "Recognise the need to agree on the order of operations; use grouping symbols ().",
        "Multiply and divide decimals by powers of 10 (relative place value).",
        "Determine why different division questions have the same answer.",
      ],
    },
    yellow: {
      heading: "Multiplicative B (applying, rates & multi-step)",
      heading_short: "Yellow -- On-level",
      points: [
        "Multiply whole numbers up to 4 digits by 1- and 2-digit numbers using efficient strategies.",
        "Use mental strategies to multiply benchmark decimals by single-digit numbers.",
        "Solve word problems involving rates using multiplication and division.",
        "Determine the rule relating the two rows of a table.",
        "Solve real-life problems using the order of operations and grouping symbols.",
        "Identify and use inverse operations to find unknown quantities.",
      ],
    },
    green: {
      heading: "Extended -- Stage 4 Ratios, Rates & Integers",
      heading_short: "Green -- Extension",
      points: [
        "Represent and solve real-life rate problems, converting units and examining best buys (MA4-RAT-C-01).",
        "Simplify ratios and use the unitary method to divide a quantity in a given ratio (MA4-RAT-C-01).",
        "Apply the order of operations to expressions involving integers (MA4-INT-C-01).",
      ],
    },
  },

  working_mathematically: [
    { process: "Communicating", description: "Students describe multiplication and division strategies, rates and order-of-operations conventions using clear mathematical language." },
    { process: "Understanding and fluency", description: "Students multiply large numbers, shift decimals by powers of 10, and apply grouping symbols accurately." },
    { process: "Reasoning", description: "Students reason why different divisions share an answer, determine the rule of a table, and justify the order of operations." },
    { process: "Problem solving", description: "Students solve multi-step word problems involving rates and grouping symbols, and (Stage 4) ratio and integer problems." },
  ],

  outcomes: [
    { code: "R1", desc: "Regroup whole numbers in different forms.", content_point: "RN-A Whole numbers: regroup numbers in different forms | MA3-RN-01 | Year A", lesson_ref: "Mini Lesson 3" },
    { code: "R2", desc: "Recognise the need to agree on the order of operations; use grouping symbols ().", content_point: "MR-B: agree on the order in which to perform operations; use grouping symbols () to indicate operations performed first | MA3-MR-01 / MA3-MR-02 | Year B", lesson_ref: "Mini Lesson 2" },
    { code: "R3", desc: "Multiply and divide decimals by powers of 10.", content_point: "MR-B: compare the relative place value of digits to multiply and divide a decimal by powers of 10 | MA3-MR-01 | Year B", lesson_ref: "Mini Lesson 7" },
    { code: "R4", desc: "Determine why different division questions have the same answer.", content_point: "MR-B: determine why different division questions have the same answer | MA3-MR-01 | Year B", lesson_ref: "Mini Lesson 5" },
    { code: "Y1", desc: "Multiply whole numbers up to 4 digits by 1- and 2-digit numbers using efficient strategies.", content_point: "MR-B: select and use efficient strategies to multiply whole numbers of up to 4 digits by one- and 2-digit numbers | MA3-MR-01 | Year B", lesson_ref: "Mini Lesson 4" },
    { code: "Y2", desc: "Multiply benchmark decimals by single-digit numbers mentally.", content_point: "MR-B: use mental strategies to multiply benchmark decimals by single-digit numbers | MA3-MR-01 | Year B", lesson_ref: "Mini Lesson 8" },
    { code: "Y3", desc: "Solve word problems involving rates using multiplication and division.", content_point: "MR-B: solve word problems involving rates using multiplication and division | MA3-MR-01 | Year B", lesson_ref: "Mini Lesson 9", pairing_note: "Suggested: pair with G1" },
    { code: "Y4", desc: "Determine the rule relating the two rows of a table.", content_point: "MR-B Patterns: determine a rule describing the relationship between the bottom and top numbers in a table | MA3-MR-01 | Year B", lesson_ref: "Mini Lesson 1" },
    { code: "Y5", desc: "Solve real-life problems using the order of operations and grouping symbols.", content_point: "MR-B: investigate the order of operations using real-life contexts; solve problems involving grouping symbols | MA3-MR-01 / MA3-MR-02 | Year B", lesson_ref: "Mini Lesson 10" },
    { code: "Y6", desc: "Identify and use inverse operations to find unknown quantities.", content_point: "MR-B Number sentences: identify and use inverse operations to assist with the solution of number sentences | MA3-MR-02 | Year B", lesson_ref: "Mini Lesson 6" },
    { code: "G1", desc: "Represent and solve real-life rate problems (convert units, best buys).", content_point: "Stage 4 RAT-A: simplified rates; convert units for rates; solve real-life rate problems incl. best buys | MA4-RAT-C-01 | Stage 4 (group A)", lesson_ref: "Mini Lesson 11" },
    { code: "G2", desc: "Simplify ratios and use the unitary method to divide a quantity in a given ratio.", content_point: "Stage 4 RAT-A: compare quantities as ratios; simplify ratios; unitary method; divide a quantity in a given ratio | MA4-RAT-C-01 | Stage 4 (group A)", lesson_ref: "Mini Lesson 12" },
    { code: "G3", desc: "Apply the order of operations to expressions involving integers.", content_point: "Stage 4 INT-A: apply the 4 operations to integers; grouping symbols; order of operations with integers | MA4-INT-C-01 | Stage 4 (group A)", lesson_ref: "Mini Lesson 13" },
  ],

  lessons: [
    {
      num: 1, band: "Y",
      title: "Number patterns and the rule of a table",
      outcomes: ["Y4"], duration: "30 min",
      syllabus: "MA3-MR-01, MAO-WM-01 | MR-B: determine a rule relating the two rows of a table",
      source: "DoE Lesson 1 (adapted)",
      doeLink: "Lesson 1 -- Number patterns and the order of operations",
      resources: "Table-of-values templates, string and craft sticks (fencing-post model), counters",
      li: "determine a rule describing the relationship between the bottom number and the top number in a table",
      sc: [
        "I can look across a table to see how the top number relates to the bottom number.",
        "I can write the rule (e.g. posts = metres + 1, or top = bottom x 5).",
        "I can use the rule to find a missing value.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Model Farmer Pat's fence: one post at the start and one post every metre. Build a table of metres vs posts." },
        { label: "Model (10 min):", content: "From the table, determine the rule relating posts to metres. Test it on each column and use it to predict posts for 100 m." },
        { label: "Guided practice (12 min):", content: "Students find the rule for several tables (including multiplicative rules) and use each rule to find missing values." },
        { label: "Check (4 min):", content: "Exit question: find the rule for 2->10, 3->15, 5->25 and use it to find the value for 8." },
      ],
      vocab: "rule, relationship, table of values, pattern, multiple, term, predict",
      support: "Model the problem with string and craft sticks; draw an extra row and record the first few values visually.",
      extension: "Create a word problem for a partner using a given table of values (e.g. barbed-wire clips and nails).",
      assessment: "Students determine and use the rule of a table — links to Y4 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["table-of-values templates", "string and craft sticks", "counters"],
    },
    {
      num: 2, band: "R",
      title: "Order of operations and grouping symbols",
      outcomes: ["R2"], duration: "25-30 min",
      syllabus: "MA3-MR-01, MA3-MR-02, MAO-WM-01 | MR-B: agree on order of operations; use grouping symbols ()",
      source: "DoE Lessons 1 & 6 (adapted)",
      doeLink: "Lessons 1 & 6 -- The order of operations and grouping symbols",
      resources: "Number-sentence cards, mini whiteboards",
      li: "recognise the need to agree on the order of operations and use grouping symbols to show which operation comes first",
      sc: [
        "I know we must agree on an order to do operations so everyone gets the same answer.",
        "I can use grouping symbols () to show which operation is done first.",
        "I can evaluate a simple number sentence using grouping symbols.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show 3 + 4 x 5. Ask why two people might get 35 or 23, and why we need an agreed order." },
        { label: "Model (10 min):", content: "Establish: do grouping symbols () first, then x and ÷, then + and -. Compare 3 + 4 x 5 = 23 with (3 + 4) x 5 = 35." },
        { label: "Guided practice (10 min):", content: "Students evaluate number sentences with and without grouping symbols and explain what the brackets change." },
        { label: "Check (3 min):", content: "Exit question: evaluate (6 + 2) x 3 and 6 + 2 x 3." },
      ],
      vocab: "order of operations, grouping symbols, brackets, operation, evaluate, number sentence",
      support: "Provide an order-of-operations reminder card; start with one operation plus brackets.",
      extension: "Place grouping symbols in an expression to reach a given target value.",
      assessment: "Students use grouping symbols and the order of operations — links to R2 in the SOLO Show task.",
    },
    {
      num: 3, band: "R",
      title: "Regrouping numbers",
      outcomes: ["R1"], duration: "20-25 min",
      syllabus: "MA3-RN-01, MAO-WM-01 | RN-A: regroup numbers in different forms",
      source: "DoE Lesson 2 (adapted)",
      doeLink: "Lesson 2 -- Multiplication strategies and regrouping",
      resources: "Place-value chart, number expander",
      li: "regroup whole numbers in different forms",
      sc: [
        "I can regroup a number by place value (e.g. 3450 = 3 thousands + 4 hundreds + 5 tens).",
        "I can rename a number in a non-standard form (e.g. 3450 = 345 tens).",
        "I can use regrouping to make a calculation easier.",
      ],
      steps: [
        { label: "Activate (3 min):", content: "Show 3450 on a place-value chart. Ask how many tens are in it." },
        { label: "Model (9 min):", content: "Regroup 3450 as 3 thousands 4 hundreds 5 tens, then as 345 tens, then as 34 hundreds 50 ones. Connect to easier multiplication." },
        { label: "Guided practice (9 min):", content: "Students regroup a set of numbers in different forms and choose a useful regrouping for a calculation." },
        { label: "Check (3 min):", content: "Exit question: regroup 6200 in two different ways." },
      ],
      vocab: "regroup, rename, place value, thousands, hundreds, tens, non-standard form",
      support: "Use a place-value chart and number expander.",
      extension: "Regroup larger numbers (to millions) and use the regrouping to simplify a multiplication.",
      assessment: "Students regroup numbers in different forms — links to R1 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["place-value chart", "number expander"],
    },
    {
      num: 4, band: "Y",
      title: "Multiplying large numbers",
      outcomes: ["Y1"], duration: "30-35 min",
      syllabus: "MA3-MR-01, MAO-WM-01 | MR-B: multiply whole numbers up to 4 digits by 1- and 2-digit numbers",
      source: "DoE Lessons 2, 4 & 8 (adapted)",
      doeLink: "Lessons 2, 4 & 8 -- Multiplication strategies",
      resources: "Grid paper for the area model, place-value chart",
      li: "select and use efficient strategies to multiply whole numbers of up to 4 digits by 1- and 2-digit numbers",
      sc: [
        "I can use the area model and the distributive property to multiply.",
        "I can multiply a 4-digit number by a 1- or 2-digit number.",
        "I can choose an efficient strategy for the numbers involved.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Multiply 1234 x 6 by partitioning (1000 + 200 + 30 + 4) x 6. Establish the distributive property." },
        { label: "Model (12 min):", content: "Use the area model to multiply 1234 x 23 (extend the grid for the extra place value), then record with the algorithm." },
        { label: "Guided practice (14 min):", content: "Students multiply 3- and 4-digit numbers by 1- and 2-digit numbers using the area model and algorithm, choosing efficient strategies." },
        { label: "Check (4 min):", content: "Exit question: find 2456 x 7 and 345 x 24 using an efficient strategy." },
      ],
      vocab: "area model, distributive property, partition, algorithm, multiply, efficient strategy, place value",
      support: "Use the area model for up to 3 digits first; add an extra row/column for the new place value.",
      extension: "Fill in a partially completed area model to find a missing multiplier; use non-standard partitioning.",
      assessment: "Students multiply up to 4-digit numbers efficiently — links to Y1 in the SOLO Show task.",
    },
    {
      num: 5, band: "R",
      title: "Why divisions share an answer",
      outcomes: ["R4"], duration: "20-25 min",
      syllabus: "MA3-MR-01, MAO-WM-01 | MR-B: determine why different division questions have the same answer",
      source: "DoE Lesson 2 (adapted)",
      doeLink: "Lesson 2 -- Division strategies",
      resources: "Counters, place-value chart",
      li: "determine why different division questions can have the same answer",
      sc: [
        "I can see that 600 ÷ 20 and 60 ÷ 2 have the same answer.",
        "I can explain why using the relationship between the numbers.",
        "I can use this to make a division easier.",
      ],
      steps: [
        { label: "Activate (3 min):", content: "Ask whether 600 ÷ 20 and 60 ÷ 2 give the same answer, and why." },
        { label: "Model (9 min):", content: "Show that dividing both numbers by 10 keeps the same quotient. Use this to simplify 840 ÷ 40 to 84 ÷ 4." },
        { label: "Guided practice (9 min):", content: "Students find pairs of divisions with the same answer and explain the relationship, using it to simplify divisions." },
        { label: "Check (3 min):", content: "Exit question: write a division with the same answer as 480 ÷ 60 and explain." },
      ],
      vocab: "division, quotient, divisor, dividend, equivalent, simplify, relationship",
      support: "Use counters to model sharing for small equivalent divisions.",
      extension: "Generate a family of divisions with the same answer and justify the pattern.",
      assessment: "Students explain why different divisions share an answer — links to R4 in the SOLO Show task.",
    },
    {
      num: 6, band: "Y",
      title: "Inverse operations and unknowns",
      outcomes: ["Y6"], duration: "25-30 min",
      syllabus: "MA3-MR-02, MAO-WM-01 | MR-B: identify and use inverse operations to find unknown quantities",
      source: "DoE Lesson 2 (adapted)",
      doeLink: "Lesson 2 -- Inverse operations and number sentences",
      resources: "Number-sentence cards, balance model",
      li: "identify and use inverse operations to find an unknown quantity in a number sentence",
      sc: [
        "I know multiplication and division are inverse operations (and so are addition and subtraction).",
        "I can use the inverse to find a missing number.",
        "I can check my answer by substituting it back.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show 7 x __ = 56. Ask how dividing (the inverse) finds the missing number." },
        { label: "Model (10 min):", content: "Solve __ x 8 = 96 with ÷, and 144 ÷ __ = 12 with x. Check each by substitution." },
        { label: "Guided practice (10 min):", content: "Students complete number sentences with a missing number using inverse operations and check by substituting." },
        { label: "Check (3 min):", content: "Exit question: find the missing number in __ ÷ 6 = 9." },
      ],
      vocab: "inverse operation, multiply, divide, unknown, number sentence, substitute, check",
      support: "Use a fact-family triangle to show the inverse relationship.",
      extension: "Solve two-operation number sentences using inverse operations in reverse order.",
      assessment: "Students use inverse operations to find unknowns — links to Y6 in the SOLO Show task.",
    },
    {
      num: 7, band: "R",
      title: "Decimals and powers of 10",
      outcomes: ["R3"], duration: "25-30 min",
      syllabus: "MA3-MR-01, MAO-WM-01 | MR-B: multiply and divide decimals by powers of 10",
      source: "DoE Lessons 3-5 (adapted)",
      doeLink: "Lessons 3-5 -- Multiplying and dividing decimals by powers of 10",
      resources: "Number slider, place-value chart, decimal cards",
      li: "multiply and divide decimals by powers of 10 by comparing the relative place value of the digits",
      sc: [
        "I know multiplying by 10 makes each digit's place value 10 times larger (shifts left).",
        "I can multiply a decimal by 10, 100 and 1000.",
        "I can divide a decimal by 10, 100 and 1000.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show 3.5 x 10 on a place-value chart. Ask what happens to each digit." },
        { label: "Model (10 min):", content: "Multiply 3.5 x 10 = 35 and 0.24 x 100 = 24; divide 47 ÷ 10 = 4.7 and 6 ÷ 100 = 0.06. Stress it is a place-value shift, not 'adding zeros'." },
        { label: "Guided practice (10 min):", content: "Students multiply and divide decimals by 10, 100 and 1000 using a number slider." },
        { label: "Check (4 min):", content: "Exit question: 2.4 x 100 = ? and 58 ÷ 1000 = ?" },
      ],
      vocab: "power of 10, multiply, divide, place value, shift, decimal, relative place value",
      support: "Use the number slider to physically shift digits; start with x10 and ÷10.",
      extension: "Find two different ways to make a decimal using multiplication or division by powers of 10 (e.g. 0.85 = 8.5 ÷ 10 = 850 ÷ 1000).",
      assessment: "Students multiply and divide decimals by powers of 10 — links to R3 in the SOLO Show task.",
    },
    {
      num: 8, band: "Y",
      title: "Multiplying benchmark decimals",
      outcomes: ["Y2"], duration: "25-30 min",
      syllabus: "MA3-MR-01, MAO-WM-01 | MR-B: use mental strategies to multiply benchmark decimals by single-digit numbers",
      source: "DoE Lessons 4-5 (adapted)",
      doeLink: "Lessons 4-5 -- Multiplying decimals mentally",
      resources: "Number lines, place-value chart",
      li: "use mental strategies to multiply benchmark decimals by single-digit numbers",
      sc: [
        "I can multiply 0.5 by a single digit (half of the number).",
        "I can multiply benchmark decimals like 0.25 and 0.1 by a single digit.",
        "I can estimate and reason about the product.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Ask what 0.5 x 8 is, connecting to 'half of 8'." },
        { label: "Model (10 min):", content: "Multiply 0.5 x 9 (half of 9 = 4.5), 0.1 x 6 (one-tenth of 6 = 0.6), 0.25 x 8 (a quarter of 8 = 2). Reason about each product." },
        { label: "Guided practice (10 min):", content: "Students multiply benchmark decimals by single-digit numbers mentally and estimate products before recording." },
        { label: "Check (3 min):", content: "Exit question: find 0.5 x 7 and 0.25 x 12 mentally." },
      ],
      vocab: "benchmark decimal, half, quarter, tenth, mental strategy, product, estimate",
      support: "Say the calculation aloud using fraction language ('half of...'); find a tenth before multiplying.",
      extension: "Use a 10-sided die to make decimal multiplications (e.g. 5.6 x 9), estimate, then find the product.",
      assessment: "Students multiply benchmark decimals mentally — links to Y2 in the SOLO Show task.",
    },
    {
      num: 9, band: "Y",
      title: "Rate word problems",
      outcomes: ["Y3"], duration: "30-35 min",
      syllabus: "MA3-MR-01, MAO-WM-01 | MR-B: solve word problems involving rates using multiplication and division",
      source: "DoE Lessons 5 & 8 (adapted)",
      doeLink: "Lessons 5 & 8 -- Rate word problems",
      resources: "Vertical double number line, counters",
      li: "solve word problems involving rates using multiplication and division",
      sc: [
        "I can find a rate (e.g. bricks per hour) from given information.",
        "I can use the rate to scale up or down using multiplication or division.",
        "I can solve a rate word problem and check it makes sense.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Rob lays 132 bricks in 2 hours. Ask how many he lays in 1 hour (the rate)." },
        { label: "Model (12 min):", content: "Use a vertical double number line to find the unit rate (66 bricks/hour), then scale to 5 hours and back-solve how long for 264 bricks." },
        { label: "Guided practice (14 min):", content: "Students solve rate problems (bricks/hour, cost/item, distance/time) using a double number line and multiplication/division." },
        { label: "Check (4 min):", content: "Exit question: a tap fills 18 L in 3 minutes — how much in 7 minutes?" },
      ],
      vocab: "rate, per, unit rate, double number line, multiply, divide, scale, proportion",
      support: "Provide a scaffolded double number line with 15-minute intervals marked; work out the one-hour amount first.",
      extension: "Solve multi-step rate problems and create rate word problems for classmates.",
      assessment: "Students solve rate word problems — links to Y3 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["vertical double number line", "counters"],
    },
    {
      num: 10, band: "Y",
      title: "Order of operations in real-life problems",
      outcomes: ["Y5"], duration: "30 min",
      syllabus: "MA3-MR-01, MA3-MR-02, MAO-WM-01 | MR-B: order of operations in real-life contexts; solve problems involving grouping symbols",
      source: "DoE Lessons 3, 6 & 7 (adapted)",
      doeLink: "Lessons 3, 6 & 7 -- Order of operations and grouping symbols in context",
      resources: "Number-sentence cards, 9-sided dice, mini whiteboards",
      li: "investigate the order of operations in real-life contexts and solve problems involving grouping symbols",
      sc: [
        "I can write a number sentence with grouping symbols for a real-life problem.",
        "I can solve a multi-step problem using the order of operations.",
        "I can use grouping symbols to control the order.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "5 plants cost $9 each and 3 cost $12 each. Ask how to write this as one number sentence with grouping symbols." },
        { label: "Model (10 min):", content: "Write (5 x 9) + (3 x 12) and evaluate using the order of operations. Then a legs problem: 6 frogs and 4 spiders -> (6 x 4) + (4 x 8)." },
        { label: "Guided practice (12 min):", content: "Students write and solve real-life problems using grouping symbols and the order of operations; place brackets to hit a target." },
        { label: "Check (4 min):", content: "Exit question: write and evaluate a number sentence for '4 boxes of 6 pencils and 3 loose pencils'." },
      ],
      vocab: "order of operations, grouping symbols, brackets, number sentence, multi-step, real-life context",
      support: "Use counters to calculate each part; help write the number sentence from the words.",
      extension: "Use 4 chosen digits with any operations and grouping symbols to make as many target numbers as possible.",
      assessment: "Students solve real-life order-of-operations and grouping-symbol problems — links to Y5 in the SOLO Show task.",
    },
    {
      num: 11, band: "G",
      title: "Rates in real life (Stage 4)",
      outcomes: ["G1"], duration: "30-35 min",
      syllabus: "MA4-RAT-C-01, MAO-WM-01 | Stage 4 RAT-A: simplified rates; convert units; real-life rates incl. best buys",
      source: "Original mini lesson",
      li: "represent and solve real-life rate problems, converting between units and comparing best buys",
      sc: [
        "I can represent given information as a simplified rate.",
        "I can convert between units for a rate.",
        "I can compare best buys using rates.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "A car travels 240 km in 3 hours. Ask for the rate in km per hour (the simplified rate)." },
        { label: "Model (12 min):", content: "Simplify a rate (240 km / 3 h = 80 km/h), convert a rate's units, and compare two best buys (e.g. $3.00 for 500 g vs $5.00 for 1 kg) using unit price." },
        { label: "Guided practice (12 min):", content: "Students simplify rates, convert rate units, and decide best buys for shopping scenarios (AUD)." },
        { label: "Check (5 min):", content: "Exit question: which is the better buy: 6 for $4.20 or 10 for $6.50?" },
      ],
      vocab: "rate, unit rate, simplify, convert, best buy, unit price, per",
      support: "Provide the unit-rate step pre-worked; compare using price per item.",
      extension: "Solve multi-step best-buy problems and rates involving unit conversions (e.g. mL to L).",
      assessment: "Students represent and solve real-life rate problems — links to G1 in the SOLO Show task.",
    },
    {
      num: 12, band: "G",
      title: "Ratios and the unitary method (Stage 4)",
      outcomes: ["G2"], duration: "30-35 min",
      syllabus: "MA4-RAT-C-01, MAO-WM-01 | Stage 4 RAT-A: compare/simplify ratios; unitary method; divide a quantity in a ratio",
      source: "Original mini lesson",
      li: "simplify ratios and use the unitary method to divide a quantity in a given ratio",
      sc: [
        "I can write and simplify a ratio comparing two quantities.",
        "I can use the unitary method to find one part.",
        "I can divide a quantity in a given ratio.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Mix 2 cups of juice to 3 cups of water. Ask how to write and simplify this ratio." },
        { label: "Model (12 min):", content: "Simplify a ratio (e.g. 4 : 6 = 2 : 3). Use the unitary method to share $40 in the ratio 3 : 5 (8 parts, 1 part = $5)." },
        { label: "Guided practice (12 min):", content: "Students simplify ratios and divide quantities in given ratios using the unitary method." },
        { label: "Check (5 min):", content: "Exit question: divide 24 lollies in the ratio 1 : 3." },
      ],
      vocab: "ratio, simplify, part, unitary method, divide in a ratio, compare, quantity",
      support: "Use counters to model the parts; find the value of one part first.",
      extension: "Solve ratio problems where one part is given and the whole must be found.",
      assessment: "Students simplify ratios and divide quantities in a ratio — links to G2 in the SOLO Show task.",
    },
    {
      num: 13, band: "G",
      title: "Order of operations with integers (Stage 4)",
      outcomes: ["G3"], duration: "30 min",
      syllabus: "MA4-INT-C-01, MAO-WM-01 | Stage 4 INT-A: 4 operations with integers; grouping symbols; order of operations",
      source: "Original mini lesson",
      li: "apply the order of operations to expressions involving integers",
      sc: [
        "I can add, subtract, multiply and divide positive and negative integers.",
        "I can apply the order of operations with grouping symbols.",
        "I can evaluate an expression involving integers.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show -3 + 5. Then 2 - (5 - 8). Ask how grouping symbols and negatives change the order." },
        { label: "Model (11 min):", content: "Apply the order of operations to integer expressions: -4 + 2 x 3, (-6 + 2) x 5, and 12 ÷ (-3) + 4. Work through grouping symbols first." },
        { label: "Guided practice (11 min):", content: "Students evaluate integer expressions with grouping symbols using the order of operations." },
        { label: "Check (4 min):", content: "Exit question: evaluate (-2 + 6) x 3 and -10 + 4 x 2." },
      ],
      vocab: "integer, positive, negative, order of operations, grouping symbols, evaluate, expression",
      support: "Use a number line for adding/subtracting integers; do one operation at a time.",
      extension: "Evaluate multi-step integer expressions with nested grouping symbols.",
      assessment: "Students apply the order of operations to integer expressions — links to G3 in the SOLO Show task.",
    },
  ],
};
