/**
 * Unit 37 — Multiplicative Relations & Measurement (Stage 3 Year B).
 * Deliverable B. Built from units/u37/00_rubric_draft.md + 01_mapping_review.md.
 * Matches the UNIT DATA SCHEMA at the bottom of scripts/build_program_template.js.
 *
 * Products, factors and primes; the area model for multiplication; area of rectangles
 * (metric units) and the same-perimeter/different-dimensions relationship; area of
 * parallelograms and triangles by dissection & rearrangement; the multiplicative (layer)
 * structure of volume; volume of rectangular prisms in cm3 and m3; efficient multi-digit
 * multiplication; and volume problem solving. Green = Stage 4 area, volume and indices.
 *
 * Program has the resource appendix merged (resource_appendix_attached: true); a standalone
 * Unit37_Resource_Appendix.docx is also emitted (Stage 5). Every resource URL verified live
 * in Stage 3 (units/u37/03_resources_staged.csv).
 *
 * Outcome -> Mini Lesson map (teaching sequence, then Stage-4 Green cards):
 *   R1->1 R2->2 R3->3 Y4->4 R4->5 R5->6 Y1->7 Y2->8 R6->9 Y3->10 Y5->11 G1->12 G2->13 G3->14
 */
module.exports = {
  unit_number: "37",
  unit_title: "Multiplicative Relations & Measurement",
  term: null,
  duration: "2-3 weeks",

  resource_appendix_attached: true,

  // Every URL verified live in Stage 3 (28 videos oEmbed-verified, 13 worksheets curl HTTP 200);
  // see units/u37/03_resources_staged.csv.
  resources: {
    r1: [
      { type: "video", label: "Factors | Common Factors | Greatest Common Factor (GCF) | Math with Mr. J", url: "https://www.youtube.com/watch?v=IRHwkNBpG_Q" },
      { type: "video", label: "Multiples vs. Factors | What are Multiples and Factors? | Math with Mr. J", url: "https://www.youtube.com/watch?v=1qPfLkOEuYY" },
      { type: "worksheet", label: "Corbettmaths — Factors (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2018/11/Factors-216-pdf.pdf" },
    ],
    r2: [
      { type: "video", label: "Prime and Composite Numbers | Math with Mr. J", url: "https://www.youtube.com/watch?v=ydm2cxacPIM" },
      { type: "video", label: "What are Prime Numbers? | Math with Mr. J", url: "https://www.youtube.com/watch?v=5gBtzdM5M5k" },
      { type: "worksheet", label: "Corbettmaths — Prime Numbers (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/prime-numbers-pdf.pdf" },
    ],
    r3: [
      { type: "video", label: "Box Method Multiplication | 2-Digits x 2-Digits | Math with Mr. J", url: "https://www.youtube.com/watch?v=n3q3XzzIGSY" },
      { type: "video", label: "Multiplication: A Step-By-Step Review | How to Multiply | Math with Mr. J", url: "https://www.youtube.com/watch?v=g5TmDrXeiR8" },
      { type: "worksheet", label: "Corbettmaths — Multiplication (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/multiplication-pdf.pdf" },
    ],
    r4: [
      { type: "video", label: "How to Find the Area of Rectangles and Squares | Math with Mr. J", url: "https://www.youtube.com/watch?v=_ejDO6aPPzU" },
      { type: "video", label: "How to Find the Area of a Rectangle | Math with Mr. J", url: "https://www.youtube.com/watch?v=vqJmXGIF_1w" },
      { type: "worksheet", label: "Corbettmaths — Area of a Rectangle (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/area-of-a-rectangle-pdf.pdf" },
    ],
    r5: [
      { type: "video", label: "Same Perimeter — Different Areas (Grade 3) | MATH-N-ROLL", url: "https://www.youtube.com/watch?v=0Ho8Az8y4Mw" },
      { type: "video", label: "Same Perimeter — Different Area (Grade 3 Math) | JoAnn's School", url: "https://www.youtube.com/watch?v=R4SNnVceMz4" },
      { type: "worksheet", label: "Corbettmaths — Area of Rectangles (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/area-of-rectangles-pdf.pdf" },
    ],
    r6: [
      { type: "video", label: "Finding Volume with Unit Cubes | How to Find Volume | Math with Mr. J", url: "https://www.youtube.com/watch?v=RxkRlIAucMk" },
      { type: "video", label: "Volume of Rectangular Prisms | Math with Mr. J", url: "https://www.youtube.com/watch?v=By7sVb2IhFs" },
      { type: "worksheet", label: "Corbettmaths — Volume of a Cuboid (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/volume-of-a-cuboid-pdf.pdf" },
    ],
    y1: [
      { type: "video", label: "Area of Parallelograms | How to Find the Area of a Parallelogram | Math with Mr. J", url: "https://www.youtube.com/watch?v=uj6k22WubCk" },
      { type: "video", label: "Area of a Parallelogram (6th Grade Math) | JoAnn's School", url: "https://www.youtube.com/watch?v=pNnZ-WgK0fs" },
      { type: "worksheet", label: "Corbettmaths — Area of a Parallelogram (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/area-of-a-parallelogram-pdf1.pdf" },
    ],
    y2: [
      { type: "video", label: "Finding the Area of a Triangle | A Step-By-Step Guide | Math with Mr. J", url: "https://www.youtube.com/watch?v=-ZPfB1uDjEw" },
      { type: "video", label: "How to Find the Area and Perimeter of a Triangle | Math with Mr. J", url: "https://www.youtube.com/watch?v=JCWJihpZ-Lo" },
      { type: "worksheet", label: "Corbettmaths — Area of a Triangle (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/area-of-a-triangle-pdf.pdf" },
    ],
    y3: [
      { type: "video", label: "Volume of Rectangular Prisms | Math with Mr. J", url: "https://www.youtube.com/watch?v=By7sVb2IhFs" },
      { type: "video", label: "Volume of a Rectangular Prism (Mastery Check) | Math with Mr. J", url: "https://www.youtube.com/watch?v=4i_XprDGeVs" },
      { type: "worksheet", label: "Corbettmaths — Volume of a Cuboid (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/volume-of-a-cuboid-pdf.pdf" },
    ],
    y4: [
      { type: "video", label: "Multiplication: A Step-By-Step Review | How to Multiply | Math with Mr. J", url: "https://www.youtube.com/watch?v=g5TmDrXeiR8" },
      { type: "video", label: "2-Digit Multiplication: A Step-By-Step Review | Math with Mr. J", url: "https://www.youtube.com/watch?v=yiZ3r9T_OJs" },
      { type: "worksheet", label: "Corbettmaths — Multiplication (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/multiplication-pdf.pdf" },
    ],
    y5: [
      { type: "video", label: "Volume of Rectangular Prism Word Problems | Wrestle with Math", url: "https://www.youtube.com/watch?v=gIFR36JiKtI" },
      { type: "video", label: "Volume of Composite Rectangular Prisms | Math with Mr. J", url: "https://www.youtube.com/watch?v=dAKAfcqi3x4" },
      { type: "worksheet", label: "Corbettmaths — Volume of a Cuboid (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/volume-of-a-cuboid-pdf.pdf" },
    ],
    g1: [
      { type: "video", label: "Finding the Area of Composite Figures with Triangles | Math with Mr. J", url: "https://www.youtube.com/watch?v=bo483Varm-U" },
      { type: "video", label: "Finding the Area of a Composite Figure | Area of Composite Rectangles | Math with Mr. J", url: "https://www.youtube.com/watch?v=z4Lat1uOQI4" },
      { type: "worksheet", label: "Corbettmaths — Area of Compound Shapes (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/area-of-compound-shapes-pdf.pdf" },
    ],
    g2: [
      { type: "video", label: "How to Find the Volume of a Triangular Prism | Math with Mr. J", url: "https://www.youtube.com/watch?v=4pV7_NuGO2g" },
      { type: "video", label: "Volume of Composite Rectangular Prisms | Math with Mr. J", url: "https://www.youtube.com/watch?v=dAKAfcqi3x4" },
      { type: "worksheet", label: "Corbettmaths — Volume of a Prism (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/volume-of-a-prism-pdf.pdf" },
    ],
    g3: [
      { type: "video", label: "Prime Factorization | What is Prime Factorization? | Math with Mr. J", url: "https://www.youtube.com/watch?v=EXU4ai9aViE" },
      { type: "video", label: "Prime Factorization of 72 | Math with Mr. J", url: "https://www.youtube.com/watch?v=kg4DP0QRL6c" },
      { type: "worksheet", label: "Corbettmaths — Product of Primes (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/product-of-primes-pdf1.pdf" },
    ],
  },

  beyond_resources: [
    { type: "video", label: "Finding the Area of Composite Figures with Triangles | Math with Mr. J", url: "https://www.youtube.com/watch?v=bo483Varm-U" },
    { type: "video", label: "How to Find the Volume of a Triangular Prism | Math with Mr. J", url: "https://www.youtube.com/watch?v=4pV7_NuGO2g" },
    { type: "video", label: "Prime Factorization of 72 | Math with Mr. J", url: "https://www.youtube.com/watch?v=kg4DP0QRL6c" },
    { type: "worksheet", label: "Corbettmaths — Volume of a Prism (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/volume-of-a-prism-pdf.pdf" },
    { type: "worksheet", label: "Corbettmaths — Area of Compound Shapes (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/area-of-compound-shapes-pdf.pdf" },
  ],

  syllabus_strands_summary: "Multiplicative Relations A & B, Geometric Measure A, 2D Spatial Structure A & B, 3D Spatial Structure B",
  strand_abbreviations_note: "MR = Multiplicative relations. GM = Geometric measure. 2DS = Two-dimensional spatial structure. 3DS = Three-dimensional spatial structure. A/B = syllabus content group (Year A ~ Year 5; Year B ~ Year 6).",

  syllabus_outcomes: [
    { code: "MAO-WM-01", descriptor: "Develops understanding and fluency in mathematics through exploring and connecting mathematical concepts, choosing and applying mathematical techniques to solve problems, and communicating their thinking and reasoning coherently and clearly." },
    { code: "MA3-MR-01", descriptor: "Selects and applies appropriate strategies to solve multiplication and division problems." },
    { code: "MA3-GM-02", descriptor: "Selects and uses the appropriate unit and device to measure lengths and distances including perimeters." },
    { code: "MA3-2DS-02", descriptor: "Selects and uses the appropriate unit to calculate areas, including areas of rectangles." },
    { code: "MA3-2DS-03", descriptor: "Combines, splits and rearranges shapes to determine the area of parallelograms and triangles." },
    { code: "MA3-3DS-02", descriptor: "Selects and uses the appropriate unit to estimate, measure and calculate volumes and capacities." },
  ],

  content_points: {
    red: {
      heading: "Multiplicative relations A, 2D spatial structure A, geometric measure A",
      heading_short: "Red -- Foundation",
      points: [
        "Use the term product; multiply numbers; find factors of a whole number (MR-A).",
        "Determine whether a number is prime, composite or neither (MR-A).",
        "Use the area model to multiply 2-digit by 1-digit numbers (MR-A).",
        "Calculate areas of rectangles in cm2, m2 and km2 (2DS-A).",
        "Recognise same-perimeter rectangles can have different areas (GM-A / 2DS-A).",
        "Find the volume of a rectangular prism by layers; calculate it in cm3 (3DS-B).",
      ],
    },
    yellow: {
      heading: "2D & 3D spatial structure B, multiplicative relations B (applying)",
      heading_short: "Yellow -- On-level",
      points: [
        "Transform a parallelogram into a rectangle by dissection; calculate its area (2DS-B).",
        "Recognise a triangle as half a parallelogram; calculate the area of a triangle (2DS-B).",
        "Explain a cubic metre and calculate volumes of rectangular prisms in m3 (3DS-B).",
        "Select efficient strategies to multiply up to 4-digit numbers by 1- and 2-digit numbers (MR-B).",
        "Solve volume word problems; recognise prisms with the same volume can have different dimensions (3DS-B).",
      ],
    },
    green: {
      heading: "Extended -- Stage 4 Area, Volume & Indices",
      heading_short: "Green -- Extension",
      points: [
        "Apply A = bh (parallelogram) and A = ½bh (triangle); find areas of composite figures (MA4-ARE-C-01).",
        "Use V = base area x height (V = Ah) for prisms with a uniform cross-section, including triangular prisms (MA4-VOL-C-01).",
        "Apply divisibility tests; write a whole number as a product of its prime factors in index notation (MA4-IND-C-01).",
      ],
    },
  },

  working_mathematically: [
    { process: "Communicating", description: "Students use the terms product, factor, prime, area and volume, and record methods for finding areas and volumes in words." },
    { process: "Understanding and fluency", description: "Students multiply whole numbers, calculate areas of rectangles, parallelograms and triangles, and volumes of rectangular prisms in cm3 and m3." },
    { process: "Reasoning", description: "Students reason about prime/composite numbers, why a triangle is half a parallelogram, and the multiplicative (layer) structure of volume." },
    { process: "Problem solving", description: "Students solve area and volume problems, explore same-perimeter and same-volume relationships, and (Stage 4) apply area/volume formulas and prime factorisation." },
  ],

  outcomes: [
    { code: "R1", desc: "Use the term product; multiply 2 or 3 numbers; list the factors of a number.", content_point: "MR-A: use the term product; determine factors for a given whole number | MA3-MR-01 | Year A", lesson_ref: "Mini Lesson 1" },
    { code: "R2", desc: "Determine whether a number is prime, composite or neither.", content_point: "MR-A: determine whether a number is prime, composite or neither (0 or 1) | MA3-MR-01 | Year A", lesson_ref: "Mini Lesson 2" },
    { code: "R3", desc: "Use the area model to multiply a 2-digit number by a 1-digit number.", content_point: "MR-A: use partitioning and place value (area model) to multiply 2-digit by 1-digit numbers | MA3-MR-01 | Year A", lesson_ref: "Mini Lesson 3" },
    { code: "R4", desc: "Calculate the area of a rectangle in square metres (and cm2, km2).", content_point: "2DS-A: calculate areas of rectangles in square centimetres (cm2), square metres (m2) and square kilometres (km2) | MA3-2DS-02 | Year A", lesson_ref: "Mini Lesson 5" },
    { code: "R5", desc: "Show rectangles with the same perimeter can have different dimensions and areas.", content_point: "GM-A / 2DS-A: recognise rectangles with the same perimeter may have different dimensions; compare their areas | MA3-GM-02, MA3-2DS-02 | Year A", lesson_ref: "Mini Lesson 6" },
    { code: "R6", desc: "Find the volume of a rectangular prism (layers) and calculate it in cm3.", content_point: "3DS-B: cubes in one layer x number of layers; record the method; calculate volume in cm3 | MA3-3DS-02 | Year B", lesson_ref: "Mini Lesson 9" },
    { code: "Y1", desc: "Transform a parallelogram into a rectangle and calculate its area.", content_point: "2DS-B: transform a parallelogram into a rectangle to find its area; record the method | MA3-2DS-02, MA3-2DS-03 | Year B", lesson_ref: "Mini Lesson 7" },
    { code: "Y2", desc: "Recognise a triangle as half a parallelogram and calculate its area.", content_point: "2DS-B: compare a triangle to a parallelogram with the same base and height; record a method for the area of a triangle | MA3-2DS-02 | Year B", lesson_ref: "Mini Lesson 8" },
    { code: "Y3", desc: "Explain a cubic metre and calculate volumes of rectangular prisms in m3.", content_point: "3DS-B: estimate and measure volumes in cubic metres; calculate volumes of rectangular prisms in m3 | MA3-3DS-02 | Year B", lesson_ref: "Mini Lesson 10" },
    { code: "Y4", desc: "Select efficient strategies to multiply up to 4-digit by 1- and 2-digit numbers.", content_point: "MR-B: select and use efficient strategies to multiply whole numbers of up to 4 digits by 1- and 2-digit numbers | MA3-MR-01 | Year B", lesson_ref: "Mini Lesson 4" },
    { code: "Y5", desc: "Solve volume word problems; same volume can have different dimensions.", content_point: "3DS-B: calculate volumes of rectangular prisms to solve problems; recognise prisms with the same volume may have different dimensions | MA3-3DS-02 | Year B", lesson_ref: "Mini Lesson 11" },
    { code: "G1", desc: "Apply area formulas for triangles & parallelograms and find composite areas.", content_point: "Stage 4 ARE: A = ½bh (triangle), A = bh (parallelogram); area of composite figures | MA4-ARE-C-01 | Stage 4 (Core)", lesson_ref: "Mini Lesson 12" },
    { code: "G2", desc: "Use V = base area x height (V = Ah) for prisms, including triangular prisms.", content_point: "Stage 4 VOL: uniform cross-section = base area; V = base area x height = Ah | MA4-VOL-C-01 | Stage 4 (Core)", lesson_ref: "Mini Lesson 13" },
    { code: "G3", desc: "Apply divisibility tests; write a number as a product of its prime factors (index notation).", content_point: "Stage 4 IND: divisibility tests for 2,3,4,5,6,10; product of prime factors using index notation | MA4-IND-C-01 | Stage 4 (Core)", lesson_ref: "Mini Lesson 14" },
  ],

  lessons: [
    {
      num: 1, band: "R",
      title: "Products and factors",
      outcomes: ["R1"], duration: "25-30 min",
      syllabus: "MA3-MR-01, MAO-WM-01 | MR-A: use the term product; determine factors of a number",
      source: "DoE Lesson 1 (adapted)",
      doeLink: "Lesson 1 -- Products and factors",
      resources: "Resource 1 - sorted numbers, counters, arrays",
      li: "use the term product and find all the factors of a whole number",
      sc: [
        "I can multiply 2 or 3 numbers and call the answer the product.",
        "I can list all the factors of a number using factor pairs.",
        "I can check a factor by dividing with no remainder.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Write 4 x 3 = 12. Name 12 the product and 4 and 3 the factors. Ask for another way to make 12." },
        { label: "Model (10 min):", content: "Build arrays for 12: 1x12, 2x6, 3x4. List the factor pairs to get all factors of 12: 1,2,3,4,6,12. Show a factor divides with no remainder." },
        { label: "Guided practice (10 min):", content: "Students find all factors of 18, 24 and 36 using factor pairs and record the product of each pair." },
        { label: "Check (4 min):", content: "Exit question: list all the factors of 20. What is the product of 5 and 4?" },
      ],
      vocab: "product, factor, factor pair, multiply, divide, array, whole number",
      support: "Provide counters to build arrays; start with smaller numbers and find pairs together.",
      extension: "Find numbers with exactly two factors, and numbers with many factors (e.g. 36, 48).",
      assessment: "Students list factors and name products — links to R1 in the SOLO Show task.",
    },
    {
      num: 2, band: "R",
      title: "Prime, composite or neither",
      outcomes: ["R2"], duration: "25 min",
      syllabus: "MA3-MR-01, MAO-WM-01 | MR-A: prime, composite or neither",
      source: "DoE Lesson 1 (adapted)",
      doeLink: "Lesson 1 -- Primes",
      resources: "Resource 2 - primes, hundred chart, counters",
      li: "decide whether a number is prime, composite or neither and explain why",
      sc: [
        "I know a prime number has exactly two factors: 1 and itself.",
        "I know a composite number has more than two factors.",
        "I can explain why 0 and 1 are neither prime nor composite.",
      ],
      steps: [
        { label: "Activate (3 min):", content: "Ask: how many factors does 7 have? How many does 8 have? Introduce the words prime and composite." },
        { label: "Model (10 min):", content: "Use arrays: 7 makes only a 1x7 array (prime); 8 makes 1x8 and 2x4 (composite). Show 1 has one factor and 0 cannot be a factor product, so both are neither." },
        { label: "Guided practice (8 min):", content: "Students sort numbers 2-20 into prime, composite or neither and justify each choice by listing factors." },
        { label: "Check (4 min):", content: "Exit question: is 15 prime or composite? Explain using its factors." },
      ],
      vocab: "prime, composite, neither, factor, exactly two factors, justify",
      support: "Give a factor list for each number so students count factors before deciding.",
      extension: "Use a hundred chart to mark primes (Sieve of Eratosthenes) and look for patterns.",
      assessment: "Students classify numbers as prime/composite/neither — links to R2 in the SOLO Show task.",
    },
    {
      num: 3, band: "R",
      title: "The area model for multiplication",
      outcomes: ["R3"], duration: "25-30 min",
      syllabus: "MA3-MR-01, MAO-WM-01 | MR-A: partitioning, place value and the area model",
      source: "DoE Lesson 1 (adapted)",
      doeLink: "Lesson 1 -- Area model multiplication",
      resources: "Grid paper, partitioned rectangles, place value cards",
      li: "use the area model to multiply a 2-digit number by a 1-digit number",
      sc: [
        "I can split a 2-digit number into tens and ones.",
        "I can draw an area model and multiply each part.",
        "I can add the parts to get the total product.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show 23 x 4. Ask students to split 23 into 20 + 3 before multiplying." },
        { label: "Model (10 min):", content: "Draw a rectangle split into 20 and 3. Multiply 20 x 4 = 80 and 3 x 4 = 12, then add: 80 + 12 = 92. Connect to place value and partitioning." },
        { label: "Guided practice (10 min):", content: "Students use the area model for 34 x 3, 26 x 5 and 47 x 6 on grid paper." },
        { label: "Check (4 min):", content: "Exit question: use the area model to work out 38 x 4." },
      ],
      vocab: "area model, partition, tens, ones, place value, product, multiply, add",
      support: "Pre-draw the partitioned rectangle and label the tens and ones for students.",
      extension: "Extend the area model to 3-digit by 1-digit, and 2-digit by 2-digit multiplication.",
      assessment: "Students multiply using the area model — links to R3 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["grid paper", "place value cards"],
    },
    {
      num: 4, band: "Y",
      title: "Efficient multi-digit multiplication",
      outcomes: ["Y4"], duration: "30 min",
      syllabus: "MA3-MR-01, MAO-WM-01 | MR-B: multiply up to 4 digits by 1- and 2-digit numbers",
      source: "DoE Lesson 8 (adapted)",
      doeLink: "Lesson 8 -- Estimating and calculating (efficient strategies)",
      resources: "Resource 20 - better deal, place value chart",
      li: "choose and use an efficient strategy to multiply a number up to 4 digits by a 1- or 2-digit number",
      sc: [
        "I can multiply a 3- or 4-digit number by a 1-digit number.",
        "I can multiply a number by a 2-digit number using place value.",
        "I can estimate first to check my answer is reasonable.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show 1234 x 6. Ask students to estimate (1200 x 6 = 7200) before calculating." },
        { label: "Model (12 min):", content: "Model the standard algorithm / extended area model for 1234 x 6, then 246 x 23 (split 23 into 20 + 3). Compare strategies for efficiency." },
        { label: "Guided practice (10 min):", content: "Students multiply 4-digit by 1-digit and 3-digit by 2-digit numbers, estimating first." },
        { label: "Check (4 min):", content: "Exit question: estimate then calculate 327 x 14." },
      ],
      vocab: "multiply, product, estimate, place value, partition, efficient strategy, algorithm",
      support: "Allow the area model so each partial product is visible; provide a multiplication chart.",
      extension: "Multiply 4-digit by 2-digit numbers and solve multi-step money problems.",
      assessment: "Students multiply large numbers efficiently — links to Y4 in the SOLO Show task.",
    },
    {
      num: 5, band: "R",
      title: "Area of rectangles in metric units",
      outcomes: ["R4"], duration: "25-30 min",
      syllabus: "MA3-2DS-02, MAO-WM-01 | 2DS-A: area of rectangles in cm2, m2, km2",
      source: "DoE Lesson 2 (adapted)",
      doeLink: "Lesson 2 -- Area of rectangles in square metres",
      resources: "Resource 3 - fence it, Resource 4 - fencing dimensions, metre ruler",
      li: "calculate the area of a rectangle in square metres, and choose the right metric unit",
      sc: [
        "I can calculate area using length x width.",
        "I can calculate areas of rectangles in square metres (m2).",
        "I can choose cm2, m2 or km2 to suit the size of the rectangle.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Mark a 1 m x 1 m square on the floor. Ask what one square metre means." },
        { label: "Model (10 min):", content: "Calculate the area of a 4 m x 3 m classroom rug: 4 x 3 = 12 m2. Discuss when to use cm2 (a book cover), m2 (a room) and km2 (a suburb)." },
        { label: "Guided practice (10 min):", content: "Students calculate areas of rectangles in m2 and choose an appropriate unit for given objects." },
        { label: "Check (4 min):", content: "Exit question: a garden bed is 5 m by 2 m. What is its area? What unit did you use?" },
      ],
      vocab: "area, length, width, square metre, m2, cm2, km2, unit, rectangle",
      support: "Provide grid overlays so students can count square metres before using length x width.",
      extension: "Convert between cm2 and m2, and calculate the area of an L-shaped region.",
      assessment: "Students calculate rectangle areas in metric units — links to R4 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["metre ruler", "grid paper", "tape measure"],
    },
    {
      num: 6, band: "R",
      title: "Same perimeter, different dimensions",
      outcomes: ["R5"], duration: "25-30 min",
      syllabus: "MA3-GM-02, MA3-2DS-02, MAO-WM-01 | GM-A / 2DS-A: same perimeter, different area",
      source: "DoE Lesson 2 (adapted)",
      doeLink: "Lesson 2 -- Rectangles with the same perimeter",
      resources: "Resource 4 - fencing dimensions, grid paper, string",
      li: "show that rectangles with the same perimeter can have different dimensions and areas",
      sc: [
        "I can draw different rectangles with the same perimeter.",
        "I can calculate and compare their areas.",
        "I can explain that the same perimeter does not mean the same area.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Give students a loop of string. Ask them to make two different rectangles with the same perimeter." },
        { label: "Model (10 min):", content: "Using a perimeter of 24 m: draw 1x11, 4x8 and 6x6. Calculate areas (11, 32, 36 m2). Show the square gives the largest area." },
        { label: "Guided practice (10 min):", content: "Students list rectangles with a perimeter of 20 m and compare their areas on grid paper." },
        { label: "Check (4 min):", content: "Exit question: two rectangles both have a perimeter of 16 m. Can they have different areas? Show an example." },
      ],
      vocab: "perimeter, dimensions, area, length, width, rectangle, compare, square",
      support: "Provide grid paper with the perimeter pre-counted so students focus on area.",
      extension: "Investigate which rectangle of a fixed perimeter has the maximum area and why.",
      assessment: "Students compare same-perimeter rectangles — links to R5 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["grid paper", "string / loop"],
    },
    {
      num: 7, band: "Y",
      title: "Area of a parallelogram",
      outcomes: ["Y1"], duration: "30 min",
      syllabus: "MA3-2DS-02, MA3-2DS-03, MAO-WM-01 | 2DS-B: transform a parallelogram into a rectangle",
      source: "DoE Lesson 3 (adapted)",
      doeLink: "Lesson 3 -- Calculating the area of a parallelogram",
      resources: "Resource 6 - parallelogram proof, paper parallelograms, scissors",
      li: "transform a parallelogram into a rectangle and calculate its area",
      sc: [
        "I can cut a right-angled piece off a parallelogram and move it to make a rectangle.",
        "I can record a method for finding the area of a parallelogram.",
        "I can calculate the area using base x perpendicular height.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show a parallelogram. Ask: how could we turn this into a rectangle we already know how to measure?" },
        { label: "Model (12 min):", content: "Cut a right-angled triangle off one end of a paper parallelogram and slide it to the other end to form a rectangle. The base and height stay the same, so area = base x height." },
        { label: "Guided practice (10 min):", content: "Students cut and rearrange parallelograms, then calculate areas using base x perpendicular height." },
        { label: "Check (4 min):", content: "Exit question: a parallelogram has base 8 cm and height 5 cm. What is its area?" },
      ],
      vocab: "parallelogram, base, perpendicular height, rectangle, dissect, rearrange, area",
      support: "Pre-cut the parallelogram along the height line so students focus on rearranging.",
      extension: "Find the area when only a slant side is given and explain why height (not slant) is used.",
      assessment: "Students find the area of a parallelogram — links to Y1 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["paper parallelograms", "scissors", "ruler"],
    },
    {
      num: 8, band: "Y",
      title: "Area of a triangle",
      outcomes: ["Y2"], duration: "30 min",
      syllabus: "MA3-2DS-02, MAO-WM-01 | 2DS-B: a triangle is half a parallelogram",
      source: "DoE Lesson 4 (adapted)",
      doeLink: "Lesson 4 -- Calculating the area of a triangle",
      resources: "Resource 8 - triangle area, paper triangles, scissors",
      li: "recognise a triangle as half a parallelogram and calculate its area",
      sc: [
        "I can join two identical triangles to make a parallelogram.",
        "I know a triangle has half the area of a parallelogram with the same base and height.",
        "I can calculate the area of a triangle using ½ x base x height.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Give pairs two identical triangles. Ask them to make a parallelogram from them." },
        { label: "Model (12 min):", content: "Show two copies of a triangle form a parallelogram, so the triangle is half. Area of triangle = ½ x base x height. Work an example: base 10 cm, height 6 cm -> ½ x 10 x 6 = 30 cm2." },
        { label: "Guided practice (10 min):", content: "Students calculate areas of triangles using ½ x base x height, identifying the perpendicular height." },
        { label: "Check (4 min):", content: "Exit question: a triangle has base 12 cm and height 5 cm. What is its area?" },
      ],
      vocab: "triangle, parallelogram, base, perpendicular height, half, area, ½ x base x height",
      support: "Provide pre-cut identical triangles so students can build the parallelogram first.",
      extension: "Find the area of triangles where the height is outside the triangle (obtuse triangles).",
      assessment: "Students find the area of a triangle — links to Y2 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["paper triangles", "scissors", "ruler"],
    },
    {
      num: 9, band: "R",
      title: "Volume of rectangular prisms (cubic centimetres)",
      outcomes: ["R6"], duration: "30 min",
      syllabus: "MA3-3DS-02, MAO-WM-01 | 3DS-B: layer structure of volume; volume in cm3",
      source: "DoE Lessons 5 & 6 (adapted)",
      doeLink: "Lessons 5 & 6 -- Volume of rectangular prisms",
      resources: "Resource 9 - box of boxes, Resource 15 - calculate the volume, centicubes",
      li: "find the volume of a rectangular prism by layers and calculate it in cubic centimetres",
      sc: [
        "I can find the number of cubes in one layer.",
        "I can multiply the cubes in one layer by the number of layers.",
        "I can calculate the volume of a rectangular prism in cubic centimetres (cm3).",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Build one layer of centicubes (e.g. 4 x 3 = 12). Ask how many cubes if we stack 5 layers." },
        { label: "Model (12 min):", content: "Show volume = cubes in one layer x number of layers = 12 x 5 = 60 cm3. Connect to length x width x height (4 x 3 x 5). Record the method in words." },
        { label: "Guided practice (10 min):", content: "Students calculate volumes of rectangular prisms in cm3 using the layer method and L x W x H." },
        { label: "Check (4 min):", content: "Exit question: a prism is 5 cm x 2 cm x 4 cm. What is its volume?" },
      ],
      vocab: "volume, rectangular prism, layer, cubic centimetre, cm3, length, width, height",
      support: "Build the prism with centicubes and count one layer before multiplying.",
      extension: "Find a missing dimension when the volume and two other dimensions are given.",
      assessment: "Students calculate volume in cm3 — links to R6 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["centicubes", "rectangular boxes"],
    },
    {
      num: 10, band: "Y",
      title: "Volume in cubic metres",
      outcomes: ["Y3"], duration: "25-30 min",
      syllabus: "MA3-3DS-02, MAO-WM-01 | 3DS-B: cubic metres; volume of prisms in m3",
      source: "DoE Lesson 7 (adapted)",
      doeLink: "Lesson 7 -- Solving problems involving volume (cubic metres)",
      resources: "Resource 16 - Lisa's landscaping, Resource 17 - estimating volume, metre rulers",
      li: "explain a cubic metre and calculate volumes of rectangular prisms in cubic metres",
      sc: [
        "I can explain a cubic metre (1 m x 1 m x 1 m) as a measure of volume.",
        "I can calculate volumes of rectangular prisms in cubic metres (m3).",
        "I can choose cm3 or m3 to suit the size of the object.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Use metre rulers to outline a cubic metre in a corner of the room. Ask what could fit inside it." },
        { label: "Model (10 min):", content: "Calculate the volume of a 3 m x 2 m x 2 m shipping container: 3 x 2 x 2 = 12 m3. Discuss when m3 is sensible versus cm3." },
        { label: "Guided practice (10 min):", content: "Students calculate volumes of prisms in m3 (soil, water tanks, rooms) and choose appropriate units." },
        { label: "Check (4 min):", content: "Exit question: a sandpit is 2 m x 2 m x 1 m. What is its volume in m3?" },
      ],
      vocab: "volume, cubic metre, m3, cubic centimetre, cm3, rectangular prism, estimate, unit",
      support: "Anchor the size of a cubic metre with the metre-ruler model before calculating.",
      extension: "Estimate the volume of large real spaces (e.g. the classroom) and compare with a calculation.",
      assessment: "Students calculate volume in m3 — links to Y3 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["metre rulers", "tape measure"],
    },
    {
      num: 11, band: "Y",
      title: "Solving problems involving volume",
      outcomes: ["Y5"], duration: "30 min",
      syllabus: "MA3-3DS-02, MAO-WM-01 | 3DS-B: volume problems; same volume, different dimensions",
      source: "DoE Lessons 7 & 8 (adapted)",
      doeLink: "Lessons 7 & 8 -- Solving problems involving volume",
      resources: "Resource 10 - recording boxes, Resource 11 - bigger cubes, centicubes",
      li: "solve volume word problems and show prisms with the same volume can have different dimensions",
      sc: [
        "I can solve a word problem by finding the volume of a rectangular prism.",
        "I can find different prisms that have the same volume.",
        "I can find a missing dimension when I know the volume.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Ask: how many different boxes can hold exactly 24 cubes? Predict before building." },
        { label: "Model (12 min):", content: "Find prisms with volume 24 cm3: 1x1x24, 2x3x4, 2x2x6. Then solve a word problem: a tank holds 36 m3; if it is 3 m x 3 m, how deep is it? (36 ÷ 9 = 4 m)." },
        { label: "Guided practice (10 min):", content: "Students solve volume word problems and list prisms with a given volume." },
        { label: "Check (4 min):", content: "Exit question: a box has a volume of 48 cm3 and a base of 4 cm x 3 cm. How tall is it?" },
      ],
      vocab: "volume, rectangular prism, dimensions, missing dimension, divide, word problem",
      support: "Provide centicubes to build prisms for the given volume before reasoning abstractly.",
      extension: "Find every whole-number prism with a given volume and describe the patterns.",
      assessment: "Students solve volume problems — links to Y5 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["centicubes"],
    },
    {
      num: 12, band: "G",
      title: "Area formulas and composite figures",
      outcomes: ["G1"], duration: "30 min",
      syllabus: "MA4-ARE-C-01, MAO-WM-01 | Stage 4: A = bh, A = ½bh, composite areas",
      source: "Original mini lesson (Stage 4 extension)",
      li: "apply the area formulas for triangles and parallelograms and find the area of composite figures",
      sc: [
        "I can use A = bh to find the area of a parallelogram.",
        "I can use A = ½bh to find the area of a triangle.",
        "I can split a composite shape into rectangles and triangles and add the areas.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Review base x height for a parallelogram and ½ x base x height for a triangle." },
        { label: "Model (12 min):", content: "Apply the formulas to several shapes, then split an L-shape / arrow into a rectangle and a triangle, find each area and add them." },
        { label: "Guided practice (10 min):", content: "Students calculate composite areas by dissecting shapes into rectangles, parallelograms and triangles." },
        { label: "Check (4 min):", content: "Exit question: find the area of a shape made of a 6x4 rectangle with a triangle (base 6, height 3) on top." },
      ],
      vocab: "formula, base, perpendicular height, parallelogram, triangle, composite figure, dissect",
      support: "Provide the shape pre-split with dashed lines so students apply each formula in turn.",
      extension: "Find composite areas that include a missing length students must work out first.",
      assessment: "Students apply area formulas and find composite areas — extends Y1/Y2.",
    },
    {
      num: 13, band: "G",
      title: "Volume of prisms (V = base area x height)",
      outcomes: ["G2"], duration: "30 min",
      syllabus: "MA4-VOL-C-01, MAO-WM-01 | Stage 4: V = Ah for prisms with uniform cross-section",
      source: "Original mini lesson (Stage 4 extension)",
      li: "use V = base area x height to find the volume of prisms, including triangular prisms",
      sc: [
        "I can identify the uniform cross-section of a prism and find its area.",
        "I can use V = base area x height (V = Ah).",
        "I can find the volume of a triangular prism.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show that a rectangular prism is base area x height. Ask what the base area is for a triangular prism." },
        { label: "Model (12 min):", content: "Establish V = Ah. For a triangular prism with a triangle base (base 4, height 3 -> A = 6) and length 10: V = 6 x 10 = 60 cm3." },
        { label: "Guided practice (10 min):", content: "Students find the volume of rectangular and triangular prisms using V = base area x height." },
        { label: "Check (4 min):", content: "Exit question: a triangular prism has a base area of 9 cm2 and length 7 cm. What is its volume?" },
      ],
      vocab: "prism, uniform cross-section, base area, height, length, V = Ah, triangular prism",
      support: "Provide the base area so students focus on multiplying by the length.",
      extension: "Find the volume of prisms with trapezium or compound cross-sections.",
      assessment: "Students apply V = Ah to prisms — extends R6/Y3/Y5.",
    },
    {
      num: 14, band: "G",
      title: "Prime factorisation and divisibility tests",
      outcomes: ["G3"], duration: "30 min",
      syllabus: "MA4-IND-C-01, MAO-WM-01 | Stage 4: divisibility tests; product of primes in index notation",
      source: "Original mini lesson (Stage 4 extension)",
      li: "apply divisibility tests and write a whole number as a product of its prime factors using index notation",
      sc: [
        "I can use divisibility tests for 2, 3, 4, 5, 6 and 10.",
        "I can use a factor tree to find the prime factors of a number.",
        "I can write the product of prime factors using index notation (e.g. 72 = 2³ x 3²).",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Check divisibility: is 84 divisible by 2, 3 and 6? Use the digit-sum test for 3." },
        { label: "Model (12 min):", content: "Build a factor tree for 72: 72 = 8 x 9 = 2x2x2 x 3x3. Write 72 = 2³ x 3² using index notation." },
        { label: "Guided practice (10 min):", content: "Students make factor trees for 36, 60 and 48 and write each as a product of primes in index form." },
        { label: "Check (4 min):", content: "Exit question: write 60 as a product of its prime factors using index notation." },
      ],
      vocab: "prime factor, factor tree, product of primes, index notation, power, divisibility test",
      support: "Provide the first split of the factor tree so students continue to the primes.",
      extension: "Use prime factorisation to find the highest common factor of two numbers.",
      assessment: "Students write numbers as products of primes — extends R1/R2.",
    },
  ],
};
