-- Unit 31 — resource inserts for the Supabase `resources` table (Stage 4).
-- Generated from units/u31/03_resources_staged.csv (every URL verified live in Stage 3).
-- Run in the Supabase SQL editor (anon key cannot write). DO NOT auto-execute.

DELETE FROM resources WHERE unit_id = 'u31';

INSERT INTO resources (unit_id, outcome_id, type, label, url, scope, class_id) VALUES
  ('u31', 'r1', 'video', 'Whole Number Expanded Form, Word Form and Standard Form | Math with Mr. J', 'https://www.youtube.com/watch?v=NOx6jlVSSpU', 'global', NULL),
  ('u31', 'r1', 'video', 'How to Write Whole Numbers in Standard Form | Math with Mr. J', 'https://www.youtube.com/watch?v=H6ndRKigay8', 'global', NULL),
  ('u31', 'r1', 'worksheet', 'Corbettmaths — Place Value (PDF)', 'https://corbettmaths.com/wp-content/uploads/2013/02/place-value-pdf.pdf', 'global', NULL),
  ('u31', 'r2', 'video', 'Place Value to the Thousandths | Miacademy', 'https://www.youtube.com/watch?v=BsZJGMRWEK0', 'global', NULL),
  ('u31', 'r2', 'video', 'Finding the Value of the Underlined Digit (Decimal Place Value) | Math with Mr. J', 'https://www.youtube.com/watch?v=2xGzQXn3WUQ', 'global', NULL),
  ('u31', 'r2', 'video', 'Expanded Form with Decimals | Math with Mr. J', 'https://www.youtube.com/watch?v=GX8o-S6Vxig', 'global', NULL),
  ('u31', 'r2', 'worksheet', 'Corbettmaths — Place Value (PDF)', 'https://corbettmaths.com/wp-content/uploads/2013/02/place-value-pdf.pdf', 'global', NULL),
  ('u31', 'r3', 'video', '2-Digit by 2-Digit Multiplication | Math with Mr. J', 'https://www.youtube.com/watch?v=PZjIT9CH6bM', 'global', NULL),
  ('u31', 'r3', 'video', '3-Digit by 2-Digit Multiplication | Math with Mr. J', 'https://www.youtube.com/watch?v=dNSrfoYLQZU', 'global', NULL),
  ('u31', 'r3', 'video', 'Box Method Multiplication (2-Digits x 2-Digits) | Math with Mr. J', 'https://www.youtube.com/watch?v=n3q3XzzIGSY', 'global', NULL),
  ('u31', 'r3', 'worksheet', 'Corbettmaths — Multiplication (PDF)', 'https://corbettmaths.com/wp-content/uploads/2013/02/multiplication-pdf.pdf', 'global', NULL),
  ('u31', 'r4', 'video', 'How to do Long Division (1-Digit Divisors) | Math with Mr. J', 'https://www.youtube.com/watch?v=up_xKZ6GeUg', 'global', NULL),
  ('u31', 'r4', 'video', 'Long Division: A Step-By-Step Review | Math with Mr. J', 'https://www.youtube.com/watch?v=HJYHNxS64f0', 'global', NULL),
  ('u31', 'r4', 'video', 'Box Method for Long Division (1-Digit Divisors) | Math with Mr. J', 'https://www.youtube.com/watch?v=8JYfVv94hww', 'global', NULL),
  ('u31', 'r4', 'worksheet', 'Corbettmaths — Division (PDF)', 'https://corbettmaths.com/wp-content/uploads/2018/01/division-pdf.pdf', 'global', NULL),
  ('u31', 'y1', 'video', 'Converting Between Fractions, Decimals and Percents (Mini Course) | Math with Mr. J', 'https://www.youtube.com/watch?v=2vjbNZaFz3c', 'global', NULL),
  ('u31', 'y1', 'video', 'Fractions to Percents | Math with Mr. J', 'https://www.youtube.com/watch?v=XXf4wHb2lYc', 'global', NULL),
  ('u31', 'y1', 'video', 'How to Convert Decimals to Percents | Math with Mr. J', 'https://www.youtube.com/watch?v=84WDtZwrGhA', 'global', NULL),
  ('u31', 'y1', 'worksheet', 'Corbettmaths — Fractions, Decimals & Percentages (PDF)', 'https://corbettmaths.com/wp-content/uploads/2013/02/fractions-decimals-percentages-pdf.pdf', 'global', NULL),
  ('u31', 'y2', 'video', 'How to Find a Percent of a Number | Math with Mr. J', 'https://www.youtube.com/watch?v=5CAncQ4TZD4', 'global', NULL),
  ('u31', 'y2', 'worksheet', 'Corbettmaths — Percentage of an Amount (PDF)', 'https://corbettmaths.com/wp-content/uploads/2018/11/Percentages-of-amounts-234-pdf.pdf', 'global', NULL),
  ('u31', 'y2', 'website', 'Maths is Fun — Percentages (interactive)', 'https://www.mathsisfun.com/percentage.html', 'global', NULL),
  ('u31', 'y3', 'video', 'Input Output Tables: Find Patterns or Rules | Easy Math with Mrs. Easley', 'https://www.youtube.com/watch?v=q0n7FMe1CQk', 'global', NULL),
  ('u31', 'y3', 'video', 'Input Output Tables Song: Finding the Rule of a Function | NUMBEROCK', 'https://www.youtube.com/watch?v=d1COIcRoSgo', 'global', NULL),
  ('u31', 'y3', 'video', 'Input & Output Tables: Rules & Missing Values | STEAMspirations', 'https://www.youtube.com/watch?v=Z7UPvsKz4Kw', 'global', NULL),
  ('u31', 'y4', 'video', 'Input Output Tables: Find Patterns or Rules | Easy Math with Mrs. Easley', 'https://www.youtube.com/watch?v=q0n7FMe1CQk', 'global', NULL),
  ('u31', 'y4', 'video', 'Input & Output Tables: Rules & Missing Values | STEAMspirations', 'https://www.youtube.com/watch?v=Z7UPvsKz4Kw', 'global', NULL),
  ('u31', 'y4', 'video', 'Input Output Tables Song: Finding the Rule of a Function | NUMBEROCK', 'https://www.youtube.com/watch?v=d1COIcRoSgo', 'global', NULL),
  ('u31', 'y5', 'video', 'Multiplying and Dividing by Powers of 10 | Math with Mr. J', 'https://www.youtube.com/watch?v=HH-yrNS80Cg', 'global', NULL),
  ('u31', 'y5', 'worksheet', 'Corbettmaths — Place Value (PDF)', 'https://corbettmaths.com/wp-content/uploads/2013/02/place-value-pdf.pdf', 'global', NULL),
  ('u31', 'y5', 'website', 'Maths is Fun — Decimals & Place Value (interactive)', 'https://www.mathsisfun.com/decimals.html', 'global', NULL),
  ('u31', 'y6', 'video', 'How Do You Solve Inverse Operations? (KS2) | Twinkl', 'https://www.youtube.com/watch?v=enw_kJRSt4A', 'global', NULL),
  ('u31', 'y6', 'video', 'Input & Output Tables: Rules & Missing Values | STEAMspirations', 'https://www.youtube.com/watch?v=Z7UPvsKz4Kw', 'global', NULL),
  ('u31', 'y6', 'website', 'Maths is Fun — Introduction to Algebra (interactive)', 'https://www.mathsisfun.com/algebra/introduction.html', 'global', NULL),
  ('u31', 'g1', 'video', 'How to Find a Percent of a Number | Math with Mr. J', 'https://www.youtube.com/watch?v=5CAncQ4TZD4', 'global', NULL),
  ('u31', 'g1', 'video', 'Calculating Percent Increase | Math with Mr. J', 'https://www.youtube.com/watch?v=t4mWCKu44lU', 'global', NULL),
  ('u31', 'g1', 'video', 'Calculating Percent Decrease | Math with Mr. J', 'https://www.youtube.com/watch?v=kS_YxXf6gNA', 'global', NULL),
  ('u31', 'g1', 'worksheet', 'Corbettmaths — Percentage of an Amount (PDF)', 'https://corbettmaths.com/wp-content/uploads/2018/11/Percentages-of-amounts-234-pdf.pdf', 'global', NULL),
  ('u31', 'g2', 'video', 'Order of Operations: A Step-By-Step Guide (PEMDAS) | Math with Mr. J', 'https://www.youtube.com/watch?v=x41BCrYh8Kc', 'global', NULL),
  ('u31', 'g2', 'video', 'Order of Operations with Parentheses and Exponents (PEMDAS) | Math with Mr. J', 'https://www.youtube.com/watch?v=dzwDTEej8MU', 'global', NULL),
  ('u31', 'g2', 'video', 'Order of Operations (No Parentheses or Exponents) | Math with Mr. J', 'https://www.youtube.com/watch?v=BCg1nz5k0HY', 'global', NULL),
  ('u31', 'g2', 'worksheet', 'Corbettmaths — Order of Operations (PDF)', 'https://corbettmaths.com/wp-content/uploads/2013/02/order-of-operations-pdf.pdf', 'global', NULL),
  ('u31', 'g3', 'video', 'An Intro to Solving Two-Step Equations | Math with Mr. J', 'https://www.youtube.com/watch?v=0ackz7dJSYY', 'global', NULL),
  ('u31', 'g3', 'video', 'How to Solve Two-Step Equations | Math with Mr. J', 'https://www.youtube.com/watch?v=7hiNNvqJNos', 'global', NULL),
  ('u31', 'g3', 'video', 'How to Solve Equations (One-Step & Two-Step) | Math with Mr. J', 'https://www.youtube.com/watch?v=9eRF7pJCOUQ', 'global', NULL),
  ('u31', 'g3', 'worksheet', 'Corbettmaths — Equations (PDF)', 'https://corbettmaths.com/wp-content/uploads/2013/02/equations-pdf.pdf', 'global', NULL);
