/**
 * Unit 31 — Number: Place Value, Percentages & Multiplicative Relations (Stage 3 Year B).
 * Deliverable B. Built from units/u31/00_rubric_draft.md + 01_mapping_review.md.
 * Matches the UNIT DATA SCHEMA at the bottom of scripts/build_program_template.js.
 *
 * Program has the resource appendix merged (resource_appendix_attached: true); a
 * standalone Unit31_Resource_Appendix.docx is also emitted (Stage 5). Every resource
 * URL verified live in Stage 3 (units/u31/03_resources_staged.csv).
 *
 * Outcome → Mini Lesson map (DoE teaching order L1-8, with each Green Stage-4 card
 * placed beside the Stage-3 work it extends):
 *   R1→1 R2→2 Y1→3 Y2→4 G1→5 Y3→6 Y4→7 R3→8 R4→9 G2→10 Y5→11 Y6→12 G3→13
 */
module.exports = {
  unit_number: "31",
  unit_title: "Number & Multiplicative Relations",
  term: null,
  duration: "2-3 weeks",

  resource_appendix_attached: true,

  // Every URL verified live in Stage 3 (oEmbed + curl); see units/u31/03_resources_staged.csv.
  resources: {
    r1: [
      { type: "video", label: "Whole Number Expanded Form, Word Form and Standard Form | Math with Mr. J", url: "https://www.youtube.com/watch?v=NOx6jlVSSpU" },
      { type: "video", label: "How to Write Whole Numbers in Standard Form | Math with Mr. J", url: "https://www.youtube.com/watch?v=H6ndRKigay8" },
      { type: "worksheet", label: "Corbettmaths — Place Value (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/place-value-pdf.pdf" },
    ],
    r2: [
      { type: "video", label: "Place Value to the Thousandths | Miacademy", url: "https://www.youtube.com/watch?v=BsZJGMRWEK0" },
      { type: "video", label: "Finding the Value of the Underlined Digit (Decimal Place Value) | Math with Mr. J", url: "https://www.youtube.com/watch?v=2xGzQXn3WUQ" },
      { type: "video", label: "Expanded Form with Decimals | Math with Mr. J", url: "https://www.youtube.com/watch?v=GX8o-S6Vxig" },
      { type: "worksheet", label: "Corbettmaths — Place Value (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/place-value-pdf.pdf" },
    ],
    r3: [
      { type: "video", label: "2-Digit by 2-Digit Multiplication | Math with Mr. J", url: "https://www.youtube.com/watch?v=PZjIT9CH6bM" },
      { type: "video", label: "3-Digit by 2-Digit Multiplication | Math with Mr. J", url: "https://www.youtube.com/watch?v=dNSrfoYLQZU" },
      { type: "video", label: "Box Method Multiplication (2-Digits x 2-Digits) | Math with Mr. J", url: "https://www.youtube.com/watch?v=n3q3XzzIGSY" },
      { type: "worksheet", label: "Corbettmaths — Multiplication (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/multiplication-pdf.pdf" },
    ],
    r4: [
      { type: "video", label: "How to do Long Division (1-Digit Divisors) | Math with Mr. J", url: "https://www.youtube.com/watch?v=up_xKZ6GeUg" },
      { type: "video", label: "Long Division: A Step-By-Step Review | Math with Mr. J", url: "https://www.youtube.com/watch?v=HJYHNxS64f0" },
      { type: "video", label: "Box Method for Long Division (1-Digit Divisors) | Math with Mr. J", url: "https://www.youtube.com/watch?v=8JYfVv94hww" },
      { type: "worksheet", label: "Corbettmaths — Division (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2018/01/division-pdf.pdf" },
    ],
    y1: [
      { type: "video", label: "Converting Between Fractions, Decimals and Percents (Mini Course) | Math with Mr. J", url: "https://www.youtube.com/watch?v=2vjbNZaFz3c" },
      { type: "video", label: "Fractions to Percents | Math with Mr. J", url: "https://www.youtube.com/watch?v=XXf4wHb2lYc" },
      { type: "video", label: "How to Convert Decimals to Percents | Math with Mr. J", url: "https://www.youtube.com/watch?v=84WDtZwrGhA" },
      { type: "worksheet", label: "Corbettmaths — Fractions, Decimals & Percentages (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/fractions-decimals-percentages-pdf.pdf" },
    ],
    y2: [
      { type: "video", label: "How to Find a Percent of a Number | Math with Mr. J", url: "https://www.youtube.com/watch?v=5CAncQ4TZD4" },
      { type: "worksheet", label: "Corbettmaths — Percentage of an Amount (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2018/11/Percentages-of-amounts-234-pdf.pdf" },
      { type: "website", label: "Maths is Fun — Percentages (interactive)", url: "https://www.mathsisfun.com/percentage.html" },
    ],
    y3: [
      { type: "video", label: "Input Output Tables: Find Patterns or Rules | Easy Math with Mrs. Easley", url: "https://www.youtube.com/watch?v=q0n7FMe1CQk" },
      { type: "video", label: "Input Output Tables Song: Finding the Rule of a Function | NUMBEROCK", url: "https://www.youtube.com/watch?v=d1COIcRoSgo" },
      { type: "video", label: "Input & Output Tables: Rules & Missing Values | STEAMspirations", url: "https://www.youtube.com/watch?v=Z7UPvsKz4Kw" },
    ],
    y4: [
      { type: "video", label: "Input Output Tables: Find Patterns or Rules | Easy Math with Mrs. Easley", url: "https://www.youtube.com/watch?v=q0n7FMe1CQk" },
      { type: "video", label: "Input & Output Tables: Rules & Missing Values | STEAMspirations", url: "https://www.youtube.com/watch?v=Z7UPvsKz4Kw" },
      { type: "video", label: "Input Output Tables Song: Finding the Rule of a Function | NUMBEROCK", url: "https://www.youtube.com/watch?v=d1COIcRoSgo" },
    ],
    y5: [
      { type: "video", label: "Multiplying and Dividing by Powers of 10 | Math with Mr. J", url: "https://www.youtube.com/watch?v=HH-yrNS80Cg" },
      { type: "worksheet", label: "Corbettmaths — Place Value (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/place-value-pdf.pdf" },
      { type: "website", label: "Maths is Fun — Decimals & Place Value (interactive)", url: "https://www.mathsisfun.com/decimals.html" },
    ],
    y6: [
      { type: "video", label: "How Do You Solve Inverse Operations? (KS2) | Twinkl", url: "https://www.youtube.com/watch?v=enw_kJRSt4A" },
      { type: "video", label: "Input & Output Tables: Rules & Missing Values | STEAMspirations", url: "https://www.youtube.com/watch?v=Z7UPvsKz4Kw" },
      { type: "website", label: "Maths is Fun — Introduction to Algebra (interactive)", url: "https://www.mathsisfun.com/algebra/introduction.html" },
    ],
    g1: [
      { type: "video", label: "How to Find a Percent of a Number | Math with Mr. J", url: "https://www.youtube.com/watch?v=5CAncQ4TZD4" },
      { type: "video", label: "Calculating Percent Increase | Math with Mr. J", url: "https://www.youtube.com/watch?v=t4mWCKu44lU" },
      { type: "video", label: "Calculating Percent Decrease | Math with Mr. J", url: "https://www.youtube.com/watch?v=kS_YxXf6gNA" },
      { type: "worksheet", label: "Corbettmaths — Percentage of an Amount (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2018/11/Percentages-of-amounts-234-pdf.pdf" },
    ],
    g2: [
      { type: "video", label: "Order of Operations: A Step-By-Step Guide (PEMDAS) | Math with Mr. J", url: "https://www.youtube.com/watch?v=x41BCrYh8Kc" },
      { type: "video", label: "Order of Operations with Parentheses and Exponents (PEMDAS) | Math with Mr. J", url: "https://www.youtube.com/watch?v=dzwDTEej8MU" },
      { type: "video", label: "Order of Operations (No Parentheses or Exponents) | Math with Mr. J", url: "https://www.youtube.com/watch?v=BCg1nz5k0HY" },
      { type: "worksheet", label: "Corbettmaths — Order of Operations (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/order-of-operations-pdf.pdf" },
    ],
    g3: [
      { type: "video", label: "An Intro to Solving Two-Step Equations | Math with Mr. J", url: "https://www.youtube.com/watch?v=0ackz7dJSYY" },
      { type: "video", label: "How to Solve Two-Step Equations | Math with Mr. J", url: "https://www.youtube.com/watch?v=7hiNNvqJNos" },
      { type: "video", label: "How to Solve Equations (One-Step & Two-Step) | Math with Mr. J", url: "https://www.youtube.com/watch?v=9eRF7pJCOUQ" },
      { type: "worksheet", label: "Corbettmaths — Equations (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/equations-pdf.pdf" },
    ],
  },
  beyond_resources: [
    { type: "video", label: "How to Find a Percent of a Number | Math with Mr. J", url: "https://www.youtube.com/watch?v=5CAncQ4TZD4" },
    { type: "video", label: "Calculating Percent Increase | Math with Mr. J", url: "https://www.youtube.com/watch?v=t4mWCKu44lU" },
    { type: "video", label: "Order of Operations: A Step-By-Step Guide (PEMDAS) | Math with Mr. J", url: "https://www.youtube.com/watch?v=x41BCrYh8Kc" },
    { type: "video", label: "An Intro to Solving Two-Step Equations | Math with Mr. J", url: "https://www.youtube.com/watch?v=0ackz7dJSYY" },
    { type: "worksheet", label: "Corbettmaths — Order of Operations (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/order-of-operations-pdf.pdf" },
    { type: "worksheet", label: "Corbettmaths — Equations (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/equations-pdf.pdf" },
    { type: "website", label: "Maths is Fun — Percentage Change (interactive)", url: "https://www.mathsisfun.com/numbers/percentage-change.html" },
    { type: "website", label: "Maths is Fun — Order of Operations (PEMDAS)", url: "https://www.mathsisfun.com/operation-order-pemdas.html" },
    { type: "website", label: "Maths is Fun — Solving Equations (interactive)", url: "https://www.mathsisfun.com/algebra/equations-solving.html" },
    { type: "website", label: "Maths is Fun — Percentages (interactive)", url: "https://www.mathsisfun.com/percentage.html" },
  ],

  syllabus_strands_summary: "Represents Numbers and Multiplicative Relations, extended with Stage 4 Number",
  strand_abbreviations_note: "RN = Represents Numbers (whole numbers, decimals, percentages). MR = Multiplicative Relations (multiplication, division, number sentences). FRC/INT/EQU = Stage 4 Fractions-decimals-percentages / Computation / Equations. A/B = syllabus content groups (A place-value & ×÷ fluency, consolidated; B percentages, pattern rules & number sentences, taught as home content).",

  syllabus_outcomes: [
    { code: "MAO-WM-01", descriptor: "Develops understanding and fluency through exploring, applying and communicating mathematical reasoning." },
    { code: "MA3-RN-01", descriptor: "Applies place value to represent natural numbers to billions." },
    { code: "MA3-RN-02", descriptor: "Compares and orders decimals up to 3 decimal places." },
    { code: "MA3-RN-03", descriptor: "Determines percentages of quantities and benchmark fraction/decimal/percentage equivalents." },
    { code: "MA3-MR-01", descriptor: "Selects and applies strategies to solve multiplication and division problems." },
    { code: "MA3-MR-02", descriptor: "Constructs and completes number sentences, applying the order of operations." },
    // Green band extends to Stage 4 (A): MA4-FRC-C-01 (percentages), MA4-INT-C-01 (order of
    // operations), MA4-EQU-C-01 (equations) — cited per-outcome in the record and lesson cards.
  ],

  content_points: {
    red: {
      heading: "Numbers A & Multiplicative A (place value, decimals, ×/÷)",
      heading_short: "Red -- Foundation",
      points: [
        "Partition, regroup and rename whole numbers to 1 billion in standard and non-standard forms.",
        "Express and interpret decimals to thousandths; name place value to 3 dp; interpret trailing zeros.",
        "Multiply 2- and 3-digit numbers by 2-digit numbers using the area model and algorithm.",
        "Divide a 3+ digit number by a one-digit divisor, interpreting remainders.",
      ],
    },
    yellow: {
      heading: "Numbers B & Multiplicative B (percentages, patterns, sentences)",
      heading_short: "Yellow -- On-level",
      points: [
        "Percentages: % and 100% as the whole; represent common percentages as fractions and decimals.",
        "Find 10% of a quantity (10% is one-tenth of 100%).",
        "Build a table of values from a geometric pattern and describe it as multiplication.",
        "Determine the rule relating the two rows of a table (algebraic reasoning).",
        "Multiply and divide decimals by powers of 10.",
        "Complete number sentences with missing numbers using inverse operations.",
      ],
    },
    green: {
      heading: "Extended -- Stage 4 Number content",
      heading_short: "Green -- Extension",
      points: [
        "Find a percentage of a quantity and calculate percentage increase and decrease (MA4-FRC-C-01).",
        "Apply the order of operations with grouping symbols to the four operations (MA4-INT-C-01).",
        "Solve simple (up to 2-step) linear equations using pronumerals and inverse operations (MA4-EQU-C-01).",
      ],
    },
  },

  working_mathematically: [
    { process: "Communicating", description: "Students describe numbers using place value to billions and thousandths, and describe percentages and pattern rules using multiplication language." },
    { process: "Understanding and fluency", description: "Students partition numbers, read decimals to thousandths, multiply and divide accurately, and shift digits when multiplying/dividing by powers of 10." },
    { process: "Reasoning", description: "Students reason about place-value relationships, determine the rule of a table, and use inverse operations to justify a missing number." },
    { process: "Problem solving", description: "Students solve multiplication and division word problems, find percentages of quantities, and (Stage 4) apply order of operations and solve simple equations." },
  ],

  outcomes: [
    { code: "R1", desc: "Partition, regroup and rename whole numbers to 1 billion.", content_point: "RN-A Whole numbers: 1000 thousands = 1 million, 1000 millions = 1 billion; regroup; partition to 1 billion in non-standard forms | MA3-RN-01", lesson_ref: "Mini Lesson 1" },
    { code: "R2", desc: "Express and interpret decimals to thousandths (place value to 3 dp; trailing zeros).", content_point: "RN-A Decimals: express thousandths as decimals; interpret notation; place value to 3 dp; interpret trailing zeros | MA3-RN-02", lesson_ref: "Mini Lesson 2" },
    { code: "R3", desc: "Multiply 2- and 3-digit numbers by 2-digit numbers (area model, algorithm, word problems).", content_point: "MR-A: factorise; extend area model to 2-digit x 2-digit; multiplication algorithm; multiplication word problems | MA3-MR-01", lesson_ref: "Mini Lesson 8" },
    { code: "R4", desc: "Divide a 3+ digit number by a one-digit divisor, interpreting remainders.", content_point: "MR-A: division word problems; use and interpret remainders; divide using digital technologies | MA3-MR-01", lesson_ref: "Mini Lesson 9" },
    { code: "Y1", desc: "Percentages: % and 100% as the whole; common percentages as fractions and decimals.", content_point: "RN-B Percentages: % means percent and 100% is the whole; represent common percentages of quantities/lengths as fractions and decimals | MA3-RN-03", lesson_ref: "Mini Lesson 3", pairing_note: "Suggested: pair with Y2" },
    { code: "Y2", desc: "Find 10% of a quantity (10% is one-tenth of 100%).", content_point: "RN-B Percentages: recognise 10% is one-tenth of 100% and use this to find 10% of a quantity | MA3-RN-03", lesson_ref: "Mini Lesson 4", pairing_note: "Suggested: pair with Y1" },
    { code: "Y3", desc: "Build a table of values from a geometric pattern and describe it as multiplication.", content_point: "MR-B Patterns: use a geometric pattern of multiples to create a table of values; describe in terms of multiplication | MA3-MR-01", lesson_ref: "Mini Lesson 6", pairing_note: "Suggested: pair with Y4" },
    { code: "Y4", desc: "Determine the rule relating the two rows of a table (algebraic reasoning).", content_point: "MR-B Patterns: determine a rule describing the relationship between the bottom and top numbers in a table | MA3-MR-01", lesson_ref: "Mini Lesson 7", pairing_note: "Suggested: pair with Y3" },
    { code: "Y5", desc: "Multiply and divide decimals by powers of 10.", content_point: "MR-B: compare the relative place value of digits to multiply and divide a decimal by powers of 10 | MA3-MR-01", lesson_ref: "Mini Lesson 11" },
    { code: "Y6", desc: "Complete number sentences with missing numbers using inverse operations.", content_point: "MR-B Number sentences: complete multi-operation sentences by calculating missing numbers; use inverse operations | MA3-MR-02", lesson_ref: "Mini Lesson 12" },
    { code: "G1", desc: "Find a percentage of a quantity; calculate percentage increase and decrease.", content_point: "Stage 4 FRC-A: one quantity as a percentage of another; percentage increase/decrease; solve percentage problems | MA4-FRC-C-01", lesson_ref: "Mini Lesson 5" },
    { code: "G2", desc: "Apply the order of operations with grouping symbols to the four operations.", content_point: "Stage 4 INT-A: apply the 4 operations; grouping symbols; order of operations to evaluate expressions | MA4-INT-C-01", lesson_ref: "Mini Lesson 10" },
    { code: "G3", desc: "Solve simple (up to 2-step) linear equations using pronumerals and inverse operations.", content_point: "Stage 4 EQU-A: represent unknowns with pronumerals; describe number sentences as equations; solve up to 2-step linear equations; word problems | MA4-EQU-C-01", lesson_ref: "Mini Lesson 13" },
  ],

  lessons: [
    {
      num: 1, band: "R",
      title: "Partitioning and renaming numbers to 1 billion",
      outcomes: ["R1"], duration: "25-30 min",
      syllabus: "MA3-RN-01, MAO-WM-01 | RN-A: partition, regroup and rename numbers to 1 billion",
      source: "DoE Lesson 1 (adapted)",
      doeLink: "Lesson 1 -- Regrouping and partitioning numbers",
      resources: "Place-value chart, number expander, MAB or place-value cards",
      li: "partition, regroup and rename whole numbers to 1 billion in standard and non-standard forms",
      sc: [
        "I know 1000 thousands is 1 million and 1000 millions is 1 billion.",
        "I can partition a large number by place value (e.g. 3 450 000 = 3 000 000 + 450 000).",
        "I can rename a number in a non-standard form (e.g. 3 450 000 = 34 hundred-thousands + 5 ten-thousands).",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Build the place-value pattern: ones, thousands, millions, billions. Ask how many thousands make a million." },
        { label: "Model (10 min):", content: "Partition 3 405 000 by place value, then regroup it a non-standard way (e.g. 3405 thousands). Read it aloud and write it in expanded form." },
        { label: "Guided practice (10 min):", content: "Students partition and rename a set of large numbers in standard and non-standard forms using a place-value chart." },
        { label: "Check (3 min):", content: "Exit question: partition 1 250 000 two different ways and state how many thousands are in 5 million." },
      ],
      vocab: "place value, partition, regroup, rename, thousand, million, billion, standard form, non-standard form",
      support: "Use a place-value chart and number expander; start with thousands before extending to millions.",
      extension: "Rename numbers in several non-standard forms and justify which is most useful for a calculation.",
      assessment: "Students partition, regroup and rename numbers to 1 billion — links to R1 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["place-value chart", "number expander", "place-value cards / MAB"],
    },
    {
      num: 2, band: "R",
      title: "Decimals to thousandths",
      outcomes: ["R2"], duration: "25-30 min",
      syllabus: "MA3-RN-02, MAO-WM-01 | RN-A: express and interpret decimals to thousandths; place value to 3 dp; trailing zeros",
      source: "DoE Lesson 2 (adapted)",
      doeLink: "Lesson 2 -- Representing thousandths",
      resources: "Place-value houses, decimal place-value chart, hundredths/thousandths grids",
      li: "express thousandths as decimals, interpret decimals to 3 places and name the place value of each digit",
      sc: [
        "I can express a number of thousandths as a decimal (e.g. 7 thousandths = 0.007).",
        "I can name the place value of each digit in a number like 2.375.",
        "I know a zero at the end of a decimal does not change its value (0.5 = 0.50).",
      ],
      steps: [
        { label: "Activate (3 min):", content: "Extend the place-value chart past hundredths to thousandths. Ask how small a thousandth is." },
        { label: "Model (10 min):", content: "Express 124 thousandths as 0.124, name the place value of each digit in 2.375, and show 0.5 = 0.50 = 0.500." },
        { label: "Guided practice (10 min):", content: "Students express thousandths as decimals, name place values and interpret trailing zeros using place-value houses." },
        { label: "Check (4 min):", content: "Exit question: write 53 thousandths as a decimal; in 4.609 what is the value of the 6 and the 9?" },
      ],
      vocab: "decimal, tenths, hundredths, thousandths, place value, three decimal places, trailing zero, digit",
      support: "Use Resource-style place-value houses; start at hundredths then extend to thousandths.",
      extension: "Compare and order decimals to 3 places and place them on a number line.",
      assessment: "Students express and interpret decimals to thousandths — links to R2 in the SOLO Show task.",
    },
    {
      num: 3, band: "Y",
      title: "Understanding percentages",
      outcomes: ["Y1"], duration: "30 min",
      syllabus: "MA3-RN-03, MAO-WM-01 | RN-B: % means percent, 100% is the whole; common percentages as fractions and decimals",
      source: "DoE Lesson 3 (adapted)",
      doeLink: "Lesson 3 -- Representing percentages",
      resources: "100-grids, percentage bars, fraction/decimal/percentage matching cards",
      li: "understand that % means percent and represent common percentages as fractions and decimals",
      sc: [
        "I know % means 'out of 100' and 100% is the whole amount.",
        "I can shade a percentage on a 100-grid.",
        "I can write common percentages (e.g. 25%, 50%, 75%) as fractions and decimals.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Shade 50% of a 100-grid. Ask what 100% would look like and what % means." },
        { label: "Model (10 min):", content: "Show 25% = 25/100 = 1/4 = 0.25 on a 100-grid and a percentage bar. Repeat for 50% and 10%." },
        { label: "Guided practice (12 min):", content: "Students match common percentages with their fraction and decimal forms and shade them on grids." },
        { label: "Check (4 min):", content: "Exit question: write 75% as a fraction and a decimal; what percentage is the whole?" },
      ],
      vocab: "percent, percentage, per cent, whole, hundred, fraction, decimal, 100-grid",
      support: "Use a pre-divided 100-grid; provide a fraction-decimal-percentage matching strip for benchmarks.",
      extension: "Represent percentages of lengths and quantities, and order a mixed set of fractions, decimals and percentages.",
      assessment: "Students represent common percentages as fractions and decimals — links to Y1 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["100-grids", "percentage bars", "fraction/decimal/percentage cards"],
    },
    {
      num: 4, band: "Y",
      title: "Finding 10% of a quantity",
      outcomes: ["Y2"], duration: "25 min",
      syllabus: "MA3-RN-03, MAO-WM-01 | RN-B: 10% is one-tenth of 100%; find 10% of a quantity",
      source: "DoE Lesson 3 (adapted)",
      doeLink: "Lesson 3 -- Representing percentages (finding 10%)",
      resources: "100-grids, place-value chart",
      li: "use the fact that 10% is one-tenth of 100% to find 10% of a quantity",
      sc: [
        "I know 10% is one-tenth of the whole.",
        "I can find 10% of a quantity by dividing by 10.",
        "I can use 10% to estimate other percentages (e.g. 20% = double 10%).",
      ],
      steps: [
        { label: "Activate (3 min):", content: "Shade 10% of a 100-grid. Ask what fraction that is (one-tenth)." },
        { label: "Model (10 min):", content: "Find 10% of 200 by dividing by 10 (20). Find 10% of $45. Then find 20% as double 10%." },
        { label: "Guided practice (9 min):", content: "Students find 10% of several quantities by dividing by 10, and use it to find 20% and 5%." },
        { label: "Check (3 min):", content: "Exit question: find 10% of 350 and use it to find 20% of 350." },
      ],
      vocab: "10 per cent, one-tenth, divide by 10, quantity, whole, estimate",
      support: "Use a place-value shift (divide by 10) with concrete amounts of money.",
      extension: "Use 10% as a building block to find 30%, 15% or 5% of a quantity.",
      assessment: "Students find 10% of a quantity using the one-tenth relationship — links to Y2 in the SOLO Show task.",
    },
    {
      num: 5, band: "G",
      title: "Percentage of a quantity and percentage change (Stage 4)",
      outcomes: ["G1"], duration: "30-35 min",
      syllabus: "MA4-FRC-C-01, MAO-WM-01 | Stage 4 FRC-A: percentage of a quantity; percentage increase and decrease",
      source: "Original mini lesson",
      li: "find a percentage of a quantity and calculate percentage increases and decreases",
      sc: [
        "I can find a percentage of a quantity (e.g. 15% of 80).",
        "I can express one quantity as a percentage of another.",
        "I can calculate a simple percentage increase or decrease.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Recall finding 10% by dividing by 10 (Mini Lesson 4). Ask how to find 15% using 10% and 5%." },
        { label: "Model (12 min):", content: "Find 15% of 80 (10% = 8, 5% = 4, so 15% = 12). Express 12 out of 80 as a percentage. Calculate a 20% increase on $50 and a 25% discount on $40." },
        { label: "Guided practice (12 min):", content: "Students find percentages of quantities, express one quantity as a percentage of another, and calculate increases/decreases in shopping contexts (AUD)." },
        { label: "Check (4 min):", content: "Exit question: find 25% of 60; a $200 item is reduced by 10% — what is the new price?" },
      ],
      vocab: "percentage, of a quantity, percentage increase, percentage decrease, discount, original amount",
      support: "Build percentages from 10% and 5%; provide a worked frame for increase/decrease.",
      extension: "Calculate the original price before a discount; solve multi-step percentage word problems including GST (10%).",
      assessment: "Students find percentages of quantities and calculate percentage change — links to G1 in the SOLO Show task.",
    },
    {
      num: 6, band: "Y",
      title: "Number patterns from multiples",
      outcomes: ["Y3"], duration: "30 min",
      syllabus: "MA3-MR-01, MAO-WM-01 | MR-B: create a table of values from a geometric pattern; describe as multiplication",
      source: "DoE Lesson 4 (adapted)",
      doeLink: "Lesson 4 -- Multiplicative patterns",
      resources: "Pattern tiles or counters, grid paper, table-of-values templates",
      li: "build a table of values from a geometric pattern and describe the pattern as multiplication",
      sc: [
        "I can build the next terms of a geometric pattern that grows by multiplying.",
        "I can record the pattern in a table of values.",
        "I can describe the pattern in words as multiplication (e.g. each term is 3 times the position).",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show a tile pattern where each step is a multiple (3, 6, 9...). Ask how the pattern grows." },
        { label: "Model (10 min):", content: "Build a pattern with tiles, record term number and tile count in a table, and describe it as 'tiles = 3 x term', emphasising multiplication not addition." },
        { label: "Guided practice (12 min):", content: "Students build/extend a geometric pattern, complete a table of values and describe the pattern in multiplication terms." },
        { label: "Check (4 min):", content: "Exit question: complete the table for a pattern of multiples of 4 and describe it in words." },
      ],
      vocab: "pattern, multiple, term, position, table of values, multiplication, geometric pattern",
      support: "Provide the pattern built for the first 3 terms and a part-filled table.",
      extension: "Compare two patterns with different multiples and describe how their tables differ.",
      assessment: "Students build a table of values and describe a multiplicative pattern — links to Y3 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["pattern tiles or counters", "grid paper", "table-of-values templates"],
    },
    {
      num: 7, band: "Y",
      title: "Finding the rule of a table",
      outcomes: ["Y4"], duration: "25-30 min",
      syllabus: "MA3-MR-01, MAO-WM-01 | MR-B: determine a rule relating the two rows of a table (algebraic reasoning)",
      source: "DoE Lesson 4 (adapted)",
      doeLink: "Lesson 4 -- Multiplicative patterns (finding the rule)",
      resources: "Table-of-values templates, function-machine cards",
      li: "determine a rule describing the relationship between the bottom number and the top number in a table",
      sc: [
        "I can look across a table to see how the top number relates to the bottom number.",
        "I can write the rule as a multiplication (e.g. top = bottom x 5).",
        "I can use the rule to find a missing value.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show a table (1->5, 2->10, 3->15). Ask what you do to the bottom number to get the top." },
        { label: "Model (10 min):", content: "Establish the rule 'top = bottom x 5' and test it on each column. Use it to find the value for bottom = 8." },
        { label: "Guided practice (10 min):", content: "Students find the rule for several tables and use it to complete missing values." },
        { label: "Check (3 min):", content: "Exit question: find the rule for 2->8, 3->12, 5->20 and use it to find the value for 7." },
      ],
      vocab: "rule, relationship, table of values, multiply, times, term, function machine",
      support: "Use a function-machine card showing 'x ?'; restrict to single-step multiplication rules.",
      extension: "Find rules of the form 'multiply then add' and check them against every column.",
      assessment: "Students determine the rule of a table and use it to find missing values — links to Y4 in the SOLO Show task.",
    },
    {
      num: 8, band: "R",
      title: "Multiplying 2- and 3-digit numbers",
      outcomes: ["R3"], duration: "30-35 min",
      syllabus: "MA3-MR-01, MAO-WM-01 | MR-A: factorise; area model; multiplication algorithm; word problems",
      source: "DoE Lesson 5 (adapted)",
      doeLink: "Lesson 5 -- Multiplication word problems",
      resources: "Grid paper for the area model, place-value chart",
      li: "multiply 2- and 3-digit numbers by 2-digit numbers using the area model and the algorithm",
      sc: [
        "I can factorise a number to make a multiplication easier.",
        "I can use the area model to multiply a 2-digit number by a 2-digit number.",
        "I can use the multiplication algorithm and solve word problems.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Factorise to multiply 24 x 5 as 24 x 5 (or 12 x 10). Ask how splitting numbers helps." },
        { label: "Model (12 min):", content: "Model 34 x 26 with the area model (30+4)(20+6), add the partial products, then show the same with the algorithm. Set it in a word-problem context." },
        { label: "Guided practice (14 min):", content: "Students multiply 2- and 3-digit numbers using the area model and the algorithm, then solve a multiplication word problem." },
        { label: "Check (4 min):", content: "Exit question: use the area model or algorithm to find 47 x 23 and write a word problem it could answer." },
      ],
      vocab: "factorise, area model, partial product, algorithm, multiply, 2-digit, 3-digit, word problem",
      support: "Provide a labelled area-model grid; start with 2-digit by 1-digit before 2-digit by 2-digit.",
      extension: "Multiply 3-digit by 2-digit numbers and check using a different strategy (estimation or factorising).",
      assessment: "Students multiply using the area model and algorithm and solve word problems — links to R3 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["grid paper (area model)", "place-value chart"],
    },
    {
      num: 9, band: "R",
      title: "Dividing and interpreting remainders",
      outcomes: ["R4"], duration: "30 min",
      syllabus: "MA3-MR-01, MAO-WM-01 | MR-A: division word problems; interpret remainders; digital technologies",
      source: "DoE Lesson 6 (adapted)",
      doeLink: "Lesson 6 -- Division word problems",
      resources: "Place-value chart, calculators (digital technologies)",
      li: "divide a 3+ digit number by a one-digit divisor and interpret the remainder in context",
      sc: [
        "I can divide a 3-digit (or larger) number by a one-digit divisor.",
        "I can record my strategy and check with multiplication.",
        "I can interpret a remainder in a word problem (round up, round down or as a fraction).",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Share 154 items between 6 groups. Ask what to do with the leftover (remainder)." },
        { label: "Model (10 min):", content: "Model 154 ÷ 6 = 25 r 4, then interpret the remainder in two word problems (e.g. how many full buses vs how much is left over)." },
        { label: "Guided practice (12 min):", content: "Students solve division word problems, interpret the remainder appropriately, and check with a calculator (digital technologies)." },
        { label: "Check (4 min):", content: "Exit question: 250 cupcakes in boxes of 8 — how many full boxes, and how many left over?" },
      ],
      vocab: "divide, divisor, quotient, remainder, interpret, round up, round down, word problem",
      support: "Provide the division partly worked; use concrete sharing for the remainder.",
      extension: "Divide by 2-digit divisors using digital technologies and interpret remainders as fractions or decimals.",
      assessment: "Students divide and interpret remainders in context — links to R4 in the SOLO Show task.",
    },
    {
      num: 10, band: "G",
      title: "Order of operations and grouping symbols (Stage 4)",
      outcomes: ["G2"], duration: "30 min",
      syllabus: "MA4-INT-C-01, MAO-WM-01 | Stage 4 INT-A: apply the 4 operations; grouping symbols; order of operations",
      source: "Original mini lesson",
      li: "apply the order of operations, including grouping symbols, to evaluate expressions",
      sc: [
        "I know the order of operations (brackets, then x and ÷, then + and -).",
        "I can evaluate an expression with more than one operation.",
        "I can use grouping symbols (brackets) to change the order.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show 3 + 4 x 5. Ask whether it is 35 or 23, and why order matters." },
        { label: "Model (11 min):", content: "Establish the order of operations. Evaluate 3 + 4 x 5 = 23, then (3 + 4) x 5 = 35, then a 3-operation expression with brackets." },
        { label: "Guided practice (11 min):", content: "Students evaluate expressions with the four operations and grouping symbols, and insert brackets to make a given target." },
        { label: "Check (4 min):", content: "Exit question: evaluate 20 - (3 + 2) x 2; where would you put brackets in 6 + 4 x 2 to make 20?" },
      ],
      vocab: "order of operations, grouping symbols, brackets, evaluate, expression, operation",
      support: "Provide the order-of-operations reminder; do one operation type at a time before mixing.",
      extension: "Insert brackets to reach a target value and justify; evaluate expressions including division and remainders.",
      assessment: "Students apply the order of operations with grouping symbols — links to G2 in the SOLO Show task.",
    },
    {
      num: 11, band: "Y",
      title: "Multiplying and dividing decimals by powers of 10",
      outcomes: ["Y5"], duration: "25-30 min",
      syllabus: "MA3-MR-01, MAO-WM-01 | MR-B: compare relative place value to multiply/divide a decimal by powers of 10",
      source: "DoE Lesson 7 (adapted)",
      doeLink: "Lesson 7 -- Multiplying and dividing decimals by powers of 10",
      resources: "Place-value chart / slider, decimal cards",
      li: "multiply and divide decimals by powers of 10 by shifting the digits' place value",
      sc: [
        "I know multiplying by 10 makes each digit 10 times larger (shifts left).",
        "I can multiply a decimal by 10, 100 or 1000.",
        "I can divide a decimal by 10, 100 or 1000.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show 3.5 x 10 on a place-value chart. Ask what happens to each digit's place value." },
        { label: "Model (10 min):", content: "Multiply 3.5 x 10 = 35 and 0.24 x 100 = 24 by shifting digits; then divide 47 ÷ 10 = 4.7 and 6 ÷ 100 = 0.06. Stress it is a place-value shift, not 'adding zeros'." },
        { label: "Guided practice (10 min):", content: "Students multiply and divide decimals by 10, 100 and 1000 using a place-value chart/slider." },
        { label: "Check (4 min):", content: "Exit question: 2.4 x 100 = ? and 58 ÷ 1000 = ?" },
      ],
      vocab: "power of 10, multiply, divide, place value, shift, decimal, ten/hundred/thousand times",
      support: "Use a place-value slider to physically shift digits; start with x10 and ÷10.",
      extension: "Multiply and divide by 10 000 and explain the place-value shift; combine with measurement conversions.",
      assessment: "Students multiply and divide decimals by powers of 10 — links to Y5 in the SOLO Show task.",
    },
    {
      num: 12, band: "Y",
      title: "Missing numbers and inverse operations",
      outcomes: ["Y6"], duration: "25-30 min",
      syllabus: "MA3-MR-02, MAO-WM-01 | MR-B: complete multi-operation number sentences; use inverse operations",
      source: "DoE Lesson 8 (adapted)",
      doeLink: "Lesson 8 -- Calculating missing numbers",
      resources: "Number-sentence cards, balance model",
      li: "complete number sentences with missing numbers using inverse operations",
      sc: [
        "I can find a missing number in a number sentence.",
        "I can use the inverse operation to undo an operation.",
        "I can complete a sentence that has more than one operation.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show 7 x __ = 56. Ask how dividing (the inverse) finds the missing number." },
        { label: "Model (10 min):", content: "Solve 7 x __ = 56 using ÷, then a 2-operation sentence (__ x 3 + 4 = 19) by undoing operations in reverse order." },
        { label: "Guided practice (10 min):", content: "Students complete one- and two-operation number sentences using inverse operations, checking by substitution." },
        { label: "Check (4 min):", content: "Exit question: find the missing number in __ ÷ 4 = 12 and in 5 x __ - 3 = 32." },
      ],
      vocab: "number sentence, missing number, inverse operation, undo, balance, equivalent",
      support: "Use a balance model; restrict to single-operation sentences first.",
      extension: "Write a two-operation missing-number sentence for a partner and check using inverse operations.",
      assessment: "Students find missing numbers using inverse operations — links to Y6 in the SOLO Show task.",
    },
    {
      num: 13, band: "G",
      title: "Solving simple equations (Stage 4)",
      outcomes: ["G3"], duration: "30-35 min",
      syllabus: "MA4-EQU-C-01, MAO-WM-01 | Stage 4 EQU-A: pronumerals; equations; solve up to 2-step linear equations",
      source: "Original mini lesson",
      li: "write a number sentence as an equation using a pronumeral and solve simple linear equations",
      sc: [
        "I can use a letter (pronumeral) to stand for an unknown.",
        "I can solve a one-step equation using inverse operations.",
        "I can solve a two-step equation (e.g. 3x + 4 = 19).",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Rewrite '__ x 3 + 4 = 19' (Mini Lesson 12) as 3x + 4 = 19. Introduce x as a pronumeral." },
        { label: "Model (12 min):", content: "Solve x + 7 = 12 (one step), then 3x + 4 = 19 by undoing in reverse (subtract 4, divide by 3), and verify by substitution. Model one word problem as an equation." },
        { label: "Guided practice (12 min):", content: "Students solve one- and two-step equations using inverse operations and verify each solution by substitution." },
        { label: "Check (4 min):", content: "Exit question: solve 2x + 5 = 17 and check your answer." },
      ],
      vocab: "equation, pronumeral, unknown, solve, inverse operation, substitute, verify, two-step",
      support: "Connect each equation back to the missing-number sentence; provide the inverse-operation steps.",
      extension: "Solve equations with pronumerals on both sides; model and solve a word problem with a 2-step equation.",
      assessment: "Students solve simple linear equations using inverse operations — links to G3 in the SOLO Show task.",
    },
  ],
};
