/**
 * Unit 38 — Chance & Data (Stage 3 Year B).
 * Deliverable B. Built from units/u38/00_rubric_draft.md + 01_mapping_review.md.
 * Matches the UNIT DATA SCHEMA at the bottom of scripts/build_program_template.js.
 *
 * Collecting and tabulating data; assigning probabilities to outcomes (incl. not-equally-likely)
 * using fractions and benchmark FDP; frequency vs probability; creating random generators;
 * observed vs expected frequencies and randomness over small/large trials; fairness of chance
 * games; sampling with replacement; interpreting and comparing data displays; and identifying
 * bias and misleading data in the media. Green = Stage 4 Probability & Data classification.
 *
 * Program has the resource appendix merged (resource_appendix_attached: true); a standalone
 * Unit38_Resource_Appendix.docx is also emitted (Stage 5). Every resource URL verified live
 * in Stage 3 (units/u38/03_resources_staged.csv).
 *
 * Outcome -> Mini Lesson map (teaching sequence, then Stage-4 Green cards):
 *   R1->1 R2->2 R3->3 R4->4 Y1->5 Y2->6 Y3->7 Y4->8 Y5->9 Y6->10 G1->11 G2->12 G3->13
 */
module.exports = {
  unit_number: "38",
  unit_title: "Chance & Data",
  term: null,
  duration: "2-3 weeks",

  resource_appendix_attached: true,

  // Every URL verified live in Stage 3 (26 videos oEmbed-verified, 9 worksheets curl HTTP 200);
  // see units/u38/03_resources_staged.csv.
  resources: {
    r1: [
      { type: "video", label: "What Is a Statistical Question? | Math Defined", url: "https://www.youtube.com/watch?v=QZjbwzbCCNE" },
      { type: "video", label: "Surveys in Statistics | LearnFree", url: "https://www.youtube.com/watch?v=Y_EQfy-uk0Y" },
      { type: "worksheet", label: "Corbettmaths — Bar Charts / Tally Charts / Pictograms (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/bar-charts-tally-charts-and-pictograms-pdf.pdf" },
    ],
    r2: [
      { type: "video", label: "How to Make a Frequency Table | Math with Mr. J", url: "https://www.youtube.com/watch?v=dcUiY2CidIQ" },
      { type: "video", label: "How to Read a Frequency Table | Math with Mr. J", url: "https://www.youtube.com/watch?v=g_pyxyJjgM8" },
      { type: "worksheet", label: "Corbettmaths — Drawing Bar Charts (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/drawing-bar-charts-pdf.pdf" },
    ],
    r3: [
      { type: "video", label: "An Intro to Probability | Basic Probability | Math with Mr. J", url: "https://www.youtube.com/watch?v=6IdNYdA6no8" },
      { type: "video", label: "Finding Probability | Basic Probability | Math with Mr. J", url: "https://www.youtube.com/watch?v=QEdHtF1CKRQ" },
      { type: "worksheet", label: "Corbettmaths — Probability (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/probability-pdf.pdf" },
    ],
    r4: [
      { type: "video", label: "Theoretical vs. Experimental Probability | Math with Mr. J", url: "https://www.youtube.com/watch?v=Ay5pnC-0bVI" },
      { type: "video", label: "Frequency Tables and Dot Plots | Math with Mr. J", url: "https://www.youtube.com/watch?v=ZQ5cXMx3Db0" },
      { type: "worksheet", label: "Corbettmaths — Relative Frequency (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/relative-frequency-pdf.pdf" },
    ],
    y1: [
      { type: "video", label: "An Intro to Finding Probability | Math with Mr. J", url: "https://www.youtube.com/watch?v=zE-Y_QCHOt8" },
      { type: "video", label: "Theoretical Probability — Possible Outcomes Using A Spinner | mrmaisonet", url: "https://www.youtube.com/watch?v=3QmNvODlnt8" },
      { type: "worksheet", label: "Corbettmaths — Probability (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/probability-pdf.pdf" },
    ],
    y2: [
      { type: "video", label: "Theoretical vs. Experimental Probability | Math with Mr. J", url: "https://www.youtube.com/watch?v=Ay5pnC-0bVI" },
      { type: "video", label: "Experimental vs. Theoretical Probability Explained! | Mario's Math Tutoring", url: "https://www.youtube.com/watch?v=J0ijhF-cdFU" },
      { type: "worksheet", label: "Corbettmaths — Relative Frequency (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/relative-frequency-pdf.pdf" },
    ],
    y3: [
      { type: "video", label: "Fair and Unfair Games | Andrea Knechtel", url: "https://www.youtube.com/watch?v=-X5vAmWQDuE" },
      { type: "video", label: "Fair and Unfair Games (Project Maths) | TheMathsTutor.ie", url: "https://www.youtube.com/watch?v=pDOfqsdZ7Hs" },
      { type: "worksheet", label: "Corbettmaths — Probability (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/probability-pdf.pdf" },
    ],
    y4: [
      { type: "video", label: "Sampling and Estimation | Dietmar Schaffner", url: "https://www.youtube.com/watch?v=XiU7srCwokU" },
      { type: "video", label: "Probability — Drawing Counters from a Bag | Tambuwal Maths Class", url: "https://www.youtube.com/watch?v=-4JgsyckoLM" },
      { type: "worksheet", label: "Corbettmaths — Relative Frequency (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/relative-frequency-pdf.pdf" },
    ],
    y5: [
      { type: "video", label: "Averages (Mean/Median/Mode) & Range | Math with Mr. J", url: "https://www.youtube.com/watch?v=e3uY2LraXts" },
      { type: "video", label: "Reading Graphs (Simplifying Math) | Buffington", url: "https://www.youtube.com/watch?v=C0-eJfOg3nc" },
      { type: "worksheet", label: "Corbettmaths — Two-Way Tables (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/two-way-tables-pdf.pdf" },
    ],
    y6: [
      { type: "video", label: "How to Spot a Misleading Graph | TED-Ed (Lea Gaslowitz)", url: "https://www.youtube.com/watch?v=E91bGT9BjYk" },
      { type: "video", label: "Misleading Graphs | Corbettmaths", url: "https://www.youtube.com/watch?v=-rYUi_dfhY0" },
      { type: "worksheet", label: "Corbettmaths — Reading Bar Charts (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2018/12/Reading-Bar-Charts.pdf" },
    ],
    g1: [
      { type: "video", label: "Introduction to Probability — Sample Space & Tree Diagrams | The Organic Chemistry Tutor", url: "https://www.youtube.com/watch?v=SkidyDQuupA" },
      { type: "video", label: "An Intro to Probability | Basic Probability | Math with Mr. J", url: "https://www.youtube.com/watch?v=6IdNYdA6no8" },
      { type: "worksheet", label: "Corbettmaths — Listing Outcomes (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/listing-outcomes-pdf.pdf" },
    ],
    g2: [
      { type: "video", label: "Complementary Events in Probability | Math and Stats Help", url: "https://www.youtube.com/watch?v=hJbj7UQIJNw" },
      { type: "video", label: "Theoretical vs. Experimental Probability | Math with Mr. J", url: "https://www.youtube.com/watch?v=Ay5pnC-0bVI" },
      { type: "worksheet", label: "Corbettmaths — Relative Frequency (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/relative-frequency-pdf.pdf" },
    ],
    g3: [
      { type: "video", label: "Types of Data: Categorical and Numerical | EJFullerton", url: "https://www.youtube.com/watch?v=Vem8Ro-cHIU" },
      { type: "video", label: "Types of Data: Categorical vs Numerical Data | 365 Data Science", url: "https://www.youtube.com/watch?v=DUcXZ08IdMo" },
      { type: "worksheet", label: "Corbettmaths — Averages and Range (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/averages-and-range-pdf.pdf" },
    ],
  },

  beyond_resources: [
    { type: "video", label: "Introduction to Probability — Sample Space & Tree Diagrams | The Organic Chemistry Tutor", url: "https://www.youtube.com/watch?v=SkidyDQuupA" },
    { type: "video", label: "Complementary Events in Probability | Math and Stats Help", url: "https://www.youtube.com/watch?v=hJbj7UQIJNw" },
    { type: "video", label: "Types of Data: Categorical vs Numerical Data | 365 Data Science", url: "https://www.youtube.com/watch?v=DUcXZ08IdMo" },
    { type: "worksheet", label: "Corbettmaths — Listing Outcomes (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/listing-outcomes-pdf.pdf" },
    { type: "worksheet", label: "Corbettmaths — Relative Frequency (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/relative-frequency-pdf.pdf" },
  ],

  syllabus_strands_summary: "Chance B, Data A and B",
  strand_abbreviations_note: "CHAN = Chance. DATA = Data. A/B = syllabus content group (Year A ~ Year 5; Year B ~ Year 6).",

  syllabus_outcomes: [
    { code: "MAO-WM-01", descriptor: "Develops understanding and fluency in mathematics through exploring and connecting mathematical concepts, choosing and applying mathematical techniques to solve problems, and communicating their thinking and reasoning coherently and clearly." },
    { code: "MA3-CHAN-01", descriptor: "Conducts chance experiments and quantifies the probability." },
    { code: "MA3-DATA-01", descriptor: "Constructs graphs using many-to-one scales (collects and organises data, and creates and interprets tables and graphs)." },
    { code: "MA3-DATA-02", descriptor: "Interprets data displays, including timelines and line graphs." },
  ],

  content_points: {
    red: {
      heading: "Data A + foundational chance (Chance B)",
      heading_short: "Red -- Foundation",
      points: [
        "Collect categorical and numerical data by observation or survey (Data A).",
        "Tabulate and organise collected data, with or without spreadsheets (Data A).",
        "Assign probabilities to outcomes (incl. not equally likely) using fractions and benchmark FDP (Chance B).",
        "Use the term frequency; distinguish the frequency of an outcome from its probability (Chance B).",
      ],
    },
    yellow: {
      heading: "Chance B & Data B (applying)",
      heading_short: "Yellow -- On-level",
      points: [
        "Create random generators to follow specified probabilities or proportions.",
        "Compare observed and expected frequencies; explain differences and randomness over small/large trials.",
        "Discuss the fairness of simple chance games and the idea of randomness.",
        "Estimate the make-up of a large collection by sampling with replacement.",
        "Interpret side-by-side column graphs; compare displays by range, mode and shape of distribution.",
        "Interpret media/factual data displays; identify bias and misleading representations.",
      ],
    },
    green: {
      heading: "Extended -- Stage 4 Probability & Data",
      heading_short: "Green -- Extension",
      points: [
        "List the sample space and find P(event) = favourable outcomes / total outcomes (MA4-PRO-C-01).",
        "Find observed probability as a relative frequency; use complementary events P(not A) = 1 - P(A) (MA4-PRO-C-01).",
        "Classify variables (numerical/categorical, discrete/continuous) and choose a suitable graph (MA4-DAT-C-01).",
      ],
    },
  },

  working_mathematically: [
    { process: "Communicating", description: "Students describe probabilities using fractions, use the terms frequency and randomness, and explain what data displays show." },
    { process: "Understanding and fluency", description: "Students collect and tabulate data, assign probabilities as fractions, and read frequency tables and graphs." },
    { process: "Reasoning", description: "Students reason about fairness and randomness, why observed results differ from expected, and where data may be biased or misleading." },
    { process: "Problem solving", description: "Students design random generators, run chance experiments, sample with replacement, and (Stage 4) find theoretical and complementary probabilities." },
  ],

  outcomes: [
    { code: "R1", desc: "Collect categorical and numerical data by observation or survey.", content_point: "DATA-A: collect ordinal/nominal categorical and discrete numerical data through observation or survey | MA3-DATA-01 | Year A", lesson_ref: "Mini Lesson 1" },
    { code: "R2", desc: "Record and organise collected data in a table.", content_point: "DATA-A: tabulate collected data with and without digital technologies such as spreadsheets | MA3-DATA-01 | Year A", lesson_ref: "Mini Lesson 2" },
    { code: "R3", desc: "Assign probabilities to outcomes using fractions and benchmark FDP.", content_point: "CHAN-B: record outcomes (incl. not equally likely) and assign probabilities using fractions; use benchmark FDP for likelihood | MA3-CHAN-01 | Year B", lesson_ref: "Mini Lesson 3" },
    { code: "R4", desc: "Use the term frequency; distinguish frequency from probability.", content_point: "CHAN-B: use the term frequency; distinguish the frequency of an outcome from the probability of an outcome | MA3-CHAN-01 | Year B", lesson_ref: "Mini Lesson 4" },
    { code: "Y1", desc: "Create random generators to follow set probabilities or proportions.", content_point: "CHAN-B: create random generators to follow specified probabilities or proportions | MA3-CHAN-01 | Year B", lesson_ref: "Mini Lesson 5" },
    { code: "Y2", desc: "Compare observed and expected results; randomness over small/large trials.", content_point: "CHAN-B: explain why observed frequencies differ from expected; discuss differences after small and large numbers of trials | MA3-CHAN-01 | Year B", lesson_ref: "Mini Lesson 6" },
    { code: "Y3", desc: "Discuss the fairness of simple chance games and randomness.", content_point: "CHAN-B: discuss the fairness of simple games involving chance and the idea of randomness | MA3-CHAN-01 | Year B", lesson_ref: "Mini Lesson 7" },
    { code: "Y4", desc: "Estimate the make-up of a large collection by sampling with replacement.", content_point: "CHAN-B: determine the likely make-up of a large collection by sampling objects and returning them before the next sample | MA3-CHAN-01 | Year B", lesson_ref: "Mini Lesson 8" },
    { code: "Y5", desc: "Interpret and compare data displays (column graphs, range, mode, shape).", content_point: "DATA-B: interpret side-by-side column graphs; compare displays by range, mode and shape of distribution | MA3-DATA-02 | Year B", lesson_ref: "Mini Lesson 9" },
    { code: "Y6", desc: "Interpret media data; identify bias and misleading displays.", content_point: "DATA-B: interpret data in digital media/factual texts; identify sources of bias and misleading representations | MA3-DATA-02 | Year B", lesson_ref: "Mini Lesson 10" },
    { code: "G1", desc: "List the sample space and find P(event) = favourable / total.", content_point: "Stage 4 PRO: list the sample space; P(event) = favourable outcomes / total outcomes; probabilities range 0-1 | MA4-PRO-C-01 | Stage 4 (Core)", lesson_ref: "Mini Lesson 11" },
    { code: "G2", desc: "Relative frequency and complementary events P(not A) = 1 - P(A).", content_point: "Stage 4 PRO: observed probability as relative frequency; complementary events sum to 1; solve complementary-event problems | MA4-PRO-C-01 | Stage 4 (Core)", lesson_ref: "Mini Lesson 12" },
    { code: "G3", desc: "Classify variables and choose a suitable graph.", content_point: "Stage 4 DAT: classify variables numerical/categorical, discrete/continuous; select the best graph and justify | MA4-DAT-C-01 | Stage 4 (Core)", lesson_ref: "Mini Lesson 13" },
  ],

  lessons: [
    {
      num: 1, band: "R",
      title: "Collecting data by observation and survey",
      outcomes: ["R1"], duration: "25-30 min",
      syllabus: "MA3-DATA-01, MAO-WM-01 | DATA-A: collect categorical and numerical data",
      source: "DoE Lesson 2 (adapted)",
      doeLink: "Lesson 2 -- Data collection and probability",
      resources: "Survey question cards, tally sheets, clipboards",
      li: "collect categorical and numerical data by observation or by conducting a survey",
      sc: [
        "I can write a survey question that gives data that varies.",
        "I can collect data by observing or asking a survey.",
        "I can tell the difference between categorical and numerical data.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Ask: 'What is your favourite sport?' vs 'How tall am I?' Which gives data that varies (a statistical question)?" },
        { label: "Model (10 min):", content: "Demonstrate a quick class survey with a tally; show categorical data (favourite colour) and numerical data (number of pets)." },
        { label: "Guided practice (10 min):", content: "Students collect data for a chosen question by observation or survey and tally the results." },
        { label: "Check (4 min):", content: "Exit question: is 'favourite fruit' categorical or numerical data?" },
      ],
      vocab: "data, categorical, numerical, observation, survey, tally, statistical question",
      support: "Provide ready-made survey questions and a pre-drawn tally sheet.",
      extension: "Compare data collected by observation with data collected by survey and discuss reliability.",
      assessment: "Students collect data — links to R1 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["tally sheets", "survey question cards"],
    },
    {
      num: 2, band: "R",
      title: "Organising data in a table",
      outcomes: ["R2"], duration: "25 min",
      syllabus: "MA3-DATA-01, MAO-WM-01 | DATA-A: tabulate collected data",
      source: "DoE Lesson 5 (adapted)",
      doeLink: "Lesson 5 -- Conducting chance experiments (recording data)",
      resources: "Frequency-table templates, spreadsheet (optional)",
      li: "record and organise collected data in a frequency table",
      sc: [
        "I can put collected data into a tally and frequency table.",
        "I can read how many times each result occurred from the table.",
        "I can organise data with or without a spreadsheet.",
      ],
      steps: [
        { label: "Activate (3 min):", content: "Show a messy list of results. Ask: how could we organise this so it's easy to read?" },
        { label: "Model (10 min):", content: "Turn a tally into a frequency table; add a total row. Show the same data in a spreadsheet column." },
        { label: "Guided practice (8 min):", content: "Students organise a set of results into a frequency table and check the total." },
        { label: "Check (4 min):", content: "Exit question: from a frequency table, which result happened most often?" },
      ],
      vocab: "table, tally, frequency, frequency table, total, spreadsheet, organise",
      support: "Provide a part-completed frequency table to finish.",
      extension: "Build the frequency table in a spreadsheet and create a quick column graph from it.",
      assessment: "Students tabulate data — links to R2 in the SOLO Show task.",
    },
    {
      num: 3, band: "R",
      title: "Probability as a fraction",
      outcomes: ["R3"], duration: "25-30 min",
      syllabus: "MA3-CHAN-01, MAO-WM-01 | CHAN-B: assign probabilities using fractions; benchmark FDP",
      source: "DoE Lesson 1 (adapted)",
      doeLink: "Lesson 1 -- Fraction chance generators",
      resources: "Spinners, bags of coloured counters, dice",
      li: "assign a probability to an outcome using a fraction, and say how likely it is",
      sc: [
        "I can write the probability of an outcome as a fraction (favourable ÷ total).",
        "I can find probabilities when outcomes are not equally likely.",
        "I can use benchmarks (½, ¼, 50%, 0.5) to describe how likely an outcome is.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show a bag with 3 red and 1 blue counter. Ask: what is the chance of red? Of blue?" },
        { label: "Model (10 min):", content: "P(red) = 3/4, P(blue) = 1/4. Connect to benchmarks: 3/4 = 75%; ½ = 50% = 0.5. Show a spinner with unequal sections." },
        { label: "Guided practice (10 min):", content: "Students assign probabilities as fractions for spinners and bags where outcomes are not equally likely." },
        { label: "Check (4 min):", content: "Exit question: a bag has 2 green and 3 yellow. What is P(green)?" },
      ],
      vocab: "probability, outcome, fraction, favourable, likely, benchmark, per cent",
      support: "Use a small number of equally likely outcomes first (e.g. 4 sections).",
      extension: "Find P(not an outcome) and show the probabilities of all outcomes add to 1.",
      assessment: "Students assign probabilities as fractions — links to R3 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["spinners", "bags of counters", "dice"],
    },
    {
      num: 4, band: "R",
      title: "Frequency and probability",
      outcomes: ["R4"], duration: "25 min",
      syllabus: "MA3-CHAN-01, MAO-WM-01 | CHAN-B: the term frequency; frequency vs probability",
      source: "DoE Lessons 3 & 4 (adapted)",
      doeLink: "Lessons 3 & 4 -- Compare observed frequencies with expected results",
      resources: "Dice, tally sheets",
      li: "use the term frequency and tell the difference between frequency and probability",
      sc: [
        "I can use the word frequency for how many times an outcome happens.",
        "I know probability is how likely an outcome is, written as a fraction.",
        "I can tell the difference between the frequency and the probability of an outcome.",
      ],
      steps: [
        { label: "Activate (3 min):", content: "Roll a die 10 times and tally. Ask: how many times did a 6 come up (frequency)?" },
        { label: "Model (10 min):", content: "Frequency = the count from the experiment. Probability = the expected chance, P(6) = 1/6. Compare the two for the same outcome." },
        { label: "Guided practice (8 min):", content: "Students record frequencies from a short experiment and state the probability of each outcome." },
        { label: "Check (4 min):", content: "Exit question: if a 3 came up 4 times in 12 rolls, what is its frequency? Its probability?" },
      ],
      vocab: "frequency, probability, outcome, count, trial, experiment, likely",
      support: "Keep the experiment short (e.g. 6 trials) and tally together.",
      extension: "Convert frequencies to a relative frequency fraction (count ÷ total trials).",
      assessment: "Students distinguish frequency from probability — links to R4 in the SOLO Show task.",
    },
    {
      num: 5, band: "Y",
      title: "Creating random generators",
      outcomes: ["Y1"], duration: "30 min",
      syllabus: "MA3-CHAN-01, MAO-WM-01 | CHAN-B: create random generators for set probabilities",
      source: "DoE Lesson 2 (adapted)",
      doeLink: "Lesson 2 -- Data collection and probability",
      resources: "Blank spinners, counters, bags",
      li: "design a random generator that follows a set of probabilities or proportions",
      sc: [
        "I can design a spinner or bag to match given probabilities.",
        "I can choose how many of each colour to use for a set proportion.",
        "I can check my generator gives the probabilities I wanted.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Challenge: design a spinner where red is twice as likely as blue. How?" },
        { label: "Model (12 min):", content: "For P(red) = 2/3 and P(blue) = 1/3, make a spinner with 2 red sections and 1 blue, or a bag with 4 red and 2 blue counters." },
        { label: "Guided practice (10 min):", content: "Students design generators (spinners/bags) to match given probabilities and explain their choices." },
        { label: "Check (4 min):", content: "Exit question: design a bag where P(green) = ¼." },
      ],
      vocab: "random generator, spinner, probability, proportion, sections, outcome, design",
      support: "Provide a spinner already divided into equal sections to colour.",
      extension: "Design a generator with three outcomes in the ratio 1 : 2 : 3.",
      assessment: "Students create random generators — links to Y1 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["blank spinners", "bags", "counters"],
    },
    {
      num: 6, band: "Y",
      title: "Observed vs expected results",
      outcomes: ["Y2"], duration: "30 min",
      syllabus: "MA3-CHAN-01, MAO-WM-01 | CHAN-B: observed vs expected; randomness; small/large trials",
      source: "DoE Lessons 3 & 4 (adapted)",
      doeLink: "Lessons 3 & 4 -- Compare observed frequencies with expected results",
      resources: "Dice, coins, tally sheets",
      li: "compare observed results with expected results and explain why they differ",
      sc: [
        "I can predict the expected results of a chance experiment.",
        "I can run the experiment and compare observed with expected.",
        "I can explain that with more trials the observed results get closer to expected (randomness).",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Flip a coin 10 times. Did you get exactly 5 heads? Why might it differ from expected?" },
        { label: "Model (12 min):", content: "Expected: P(heads) = ½, so ~5 of 10. Observed may be 6 or 3 — that's randomness. Combine the class results (many trials) and see it get closer to half." },
        { label: "Guided practice (10 min):", content: "Students run a dice/coin experiment with small then large numbers of trials and compare observed with expected." },
        { label: "Check (4 min):", content: "Exit question: why do more trials usually make observed results closer to expected?" },
      ],
      vocab: "observed, expected, frequency, probability, trial, randomness, sample size",
      support: "Pool results with a partner to reach more trials quickly.",
      extension: "Graph how the observed proportion of heads changes as trials increase.",
      assessment: "Students compare observed and expected results — links to Y2 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["dice", "coins", "tally sheets"],
    },
    {
      num: 7, band: "Y",
      title: "Fairness and randomness in chance games",
      outcomes: ["Y3"], duration: "25-30 min",
      syllabus: "MA3-CHAN-01, MAO-WM-01 | CHAN-B: fairness of chance games; randomness",
      source: "DoE Lesson 4 (adapted)",
      doeLink: "Lesson 4 -- Fairness, chance and probability",
      resources: "Dice, spinners, coloured counters",
      li: "discuss whether a simple chance game is fair using the idea of randomness",
      sc: [
        "I can work out each player's probability of winning.",
        "I can decide whether a game is fair (equal chances) or unfair.",
        "I can suggest how to make an unfair game fair.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Game: Player A wins on 1-2, Player B on 3-6. Is this fair? Why not?" },
        { label: "Model (10 min):", content: "P(A) = 2/6, P(B) = 4/6 — unfair. Discuss how to make it fair (A wins on 1-3, B on 4-6). Link to randomness." },
        { label: "Guided practice (10 min):", content: "Students play simple chance games, work out the probabilities, and judge fairness." },
        { label: "Check (4 min):", content: "Exit question: is a game where you win only on a 6 fair for both players? Explain." },
      ],
      vocab: "fair, unfair, chance, probability, randomness, equal, outcome",
      support: "Use games with two equally likely outcomes first (coin flip).",
      extension: "Design a fair three-player game and prove it is fair using probabilities.",
      assessment: "Students judge fairness of chance games — links to Y3 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["dice", "spinners", "counters"],
    },
    {
      num: 8, band: "Y",
      title: "Sampling with replacement",
      outcomes: ["Y4"], duration: "30 min",
      syllabus: "MA3-CHAN-01, MAO-WM-01 | CHAN-B: estimate a large collection by sampling with replacement",
      source: "DoE Lesson 5 (adapted)",
      doeLink: "Lesson 5 -- Conducting chance experiments with small and large numbers of trials",
      resources: "Bag of mixed coloured counters, tally sheets",
      li: "estimate the make-up of a large hidden collection by sampling with replacement",
      sc: [
        "I can take a sample, record it, and return it before sampling again.",
        "I can use the proportions in my samples to estimate the whole collection.",
        "I know more samples give a better estimate.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show a sealed bag of counters. Ask: without tipping it out, how could we estimate how many are red?" },
        { label: "Model (12 min):", content: "Draw one counter, record the colour, put it back, repeat. After 20 draws, if 12 were red, estimate ~12/20 = 3/5 of the bag is red." },
        { label: "Guided practice (10 min):", content: "Students sample with replacement, tally results, and estimate the make-up of the collection." },
        { label: "Check (4 min):", content: "Exit question: why do we put the counter back each time before sampling again?" },
      ],
      vocab: "sample, sampling with replacement, proportion, estimate, collection, frequency",
      support: "Use a bag with only two colours and a small number of draws.",
      extension: "Compare estimates from 10 samples vs 50 samples and discuss which is more reliable.",
      assessment: "Students sample with replacement — links to Y4 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["bag of mixed counters", "tally sheets"],
    },
    {
      num: 9, band: "Y",
      title: "Interpreting and comparing data displays",
      outcomes: ["Y5"], duration: "30 min",
      syllabus: "MA3-DATA-02, MAO-WM-01 | DATA-B: side-by-side column graphs; range, mode, shape",
      source: "DoE Lessons 7 & 8 (adapted)",
      doeLink: "Lessons 7 & 8 -- Interpreting and comparing a range of data displays",
      resources: "Printed side-by-side column graphs, data sets",
      li: "interpret side-by-side column graphs and compare displays using range, mode and shape",
      sc: [
        "I can read values from a side-by-side column graph for two groups.",
        "I can find the range and the mode (most frequent value) of a data set.",
        "I can compare two displays by their shape, range and mode.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show a side-by-side column graph (boys vs girls favourite sport). Ask a comparison question." },
        { label: "Model (12 min):", content: "Read values for each group; find the mode (tallest column) and the range (highest − lowest). Compare the shape of two displays." },
        { label: "Guided practice (10 min):", content: "Students interpret side-by-side column graphs and compare data sets by range and mode." },
        { label: "Check (4 min):", content: "Exit question: for 3, 5, 5, 8, what is the mode and the range?" },
      ],
      vocab: "column graph, side-by-side, range, mode, distribution, shape, compare",
      support: "Provide the range and mode definitions and a worked example to follow.",
      extension: "Compare three displays and describe how the shape of the distribution differs.",
      assessment: "Students interpret and compare data displays — links to Y5 in the SOLO Show task.",
    },
    {
      num: 10, band: "Y",
      title: "Bias and misleading data in the media",
      outcomes: ["Y6"], duration: "25-30 min",
      syllabus: "MA3-DATA-02, MAO-WM-01 | DATA-B: interpret media data; bias; misleading displays",
      source: "DoE Lessons 6 & 7 (adapted)",
      doeLink: "Lessons 6 & 7 -- Interpret data presented in digital media and elsewhere",
      resources: "Media graphs (newspaper/online), factual texts",
      li: "interpret data displays in the media and identify bias or misleading features",
      sc: [
        "I can read and explain a data display from the media or a factual text.",
        "I can spot a source of bias in how data is shown.",
        "I can recognise when a graph is misleading (e.g. a stretched or cut axis).",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show a graph with a y-axis that doesn't start at 0. Ask: does this make a small difference look big?" },
        { label: "Model (10 min):", content: "Read a media graph; point out misleading features (broken axis, uneven scale, cherry-picked data) and possible bias." },
        { label: "Guided practice (10 min):", content: "Students analyse media data displays and identify bias or misleading features." },
        { label: "Check (4 min):", content: "Exit question: name one way a graph can be made to mislead the reader." },
      ],
      vocab: "media, data display, bias, misleading, axis, scale, interpret",
      support: "Provide clearly misleading examples with the feature highlighted.",
      extension: "Redraw a misleading graph fairly and explain what changed.",
      assessment: "Students identify bias and misleading data — links to Y6 in the SOLO Show task.",
    },
    {
      num: 11, band: "G",
      title: "Sample space and theoretical probability",
      outcomes: ["G1"], duration: "30 min",
      syllabus: "MA4-PRO-C-01, MAO-WM-01 | Stage 4: sample space; P(event) = favourable / total",
      source: "Original mini lesson (Stage 4 extension)",
      li: "list the sample space and find P(event) = favourable outcomes / total outcomes",
      sc: [
        "I can list the sample space (all possible outcomes) for an experiment.",
        "I can write P(event) = favourable outcomes ÷ total outcomes.",
        "I know probabilities range from 0 (impossible) to 1 (certain).",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Roll a die. What are all the possible outcomes? That set is the sample space." },
        { label: "Model (12 min):", content: "Sample space {1,2,3,4,5,6}. P(even) = 3/6 = ½. Show the 0-to-1 probability scale; impossible = 0, certain = 1." },
        { label: "Guided practice (10 min):", content: "Students list sample spaces and calculate P(event) as a fraction for dice, spinners and cards." },
        { label: "Check (4 min):", content: "Exit question: a spinner has 8 equal sections, 3 red. What is P(red)?" },
      ],
      vocab: "sample space, outcome, event, favourable, probability, impossible, certain",
      support: "Provide the sample space already listed so students focus on P(event).",
      extension: "Verify that the probabilities of all outcomes in the sample space add to 1.",
      assessment: "Students find theoretical probabilities — extends R3.",
    },
    {
      num: 12, band: "G",
      title: "Relative frequency and complementary events",
      outcomes: ["G2"], duration: "30 min",
      syllabus: "MA4-PRO-C-01, MAO-WM-01 | Stage 4: relative frequency; complementary events",
      source: "Original mini lesson (Stage 4 extension)",
      li: "find an observed probability as a relative frequency and use complementary events",
      sc: [
        "I can find an observed (experimental) probability as a relative frequency (count ÷ trials).",
        "I can find the complement of an event.",
        "I can use P(not A) = 1 − P(A).",
      ],
      steps: [
        { label: "Activate (4 min):", content: "In 50 spins, red came up 20 times. What is the observed probability of red?" },
        { label: "Model (12 min):", content: "Relative frequency = 20/50 = 2/5. The complement of 'red' is 'not red'; P(not red) = 1 − 2/5 = 3/5. They add to 1." },
        { label: "Guided practice (10 min):", content: "Students calculate relative frequencies and complementary probabilities from experiments." },
        { label: "Check (4 min):", content: "Exit question: if P(win) = ¼, what is P(not win)?" },
      ],
      vocab: "relative frequency, observed probability, complement, complementary events, trials",
      support: "Provide the trial counts so students focus on forming the fraction.",
      extension: "Solve a multi-step problem combining relative frequency and complementary events.",
      assessment: "Students use relative frequency and complements — extends Y2.",
    },
    {
      num: 13, band: "G",
      title: "Classify data and choose the right graph",
      outcomes: ["G3"], duration: "30 min",
      syllabus: "MA4-DAT-C-01, MAO-WM-01 | Stage 4: classify variables; choose a suitable graph",
      source: "Original mini lesson (Stage 4 extension)",
      li: "classify variables as numerical or categorical and choose a graph that suits the data",
      sc: [
        "I can classify a variable as numerical (discrete/continuous) or categorical (nominal/ordinal).",
        "I can choose a graph that suits the type of data.",
        "I can justify why my chosen graph is appropriate.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Sort: shoe size, eye colour, height, favourite subject — which are numerical, which categorical?" },
        { label: "Model (12 min):", content: "Numerical = numbers (discrete: counts; continuous: measures). Categorical = groups (nominal/ordinal). Match each to a sensible graph (column graph, dot plot, line graph)." },
        { label: "Guided practice (10 min):", content: "Students classify variables and choose (and justify) a suitable graph for each." },
        { label: "Check (4 min):", content: "Exit question: 'number of pets' — numerical or categorical? Which graph suits it?" },
      ],
      vocab: "variable, numerical, categorical, discrete, continuous, nominal, ordinal, graph",
      support: "Provide a sorting table with the categories labelled.",
      extension: "Justify why one graph type would mislead for a given data set.",
      assessment: "Students classify data and choose graphs — extends R1/R2/Y5.",
    },
  ],
};
