/**
 * Unit 32 — 2D Space & Area (Stage 3 Year B) — teacher program data.
 * Deliverable B. Built from units/u32/00_rubric_draft.md + 01_mapping_review.md.
 * Matches the UNIT DATA SCHEMA at the bottom of scripts/build_program_template.js.
 *
 * Program has the resource appendix merged (resource_appendix_attached: true); a
 * standalone Unit32_Resource_Appendix.docx is also emitted (Stage 5). Every resource
 * URL verified live in Stage 3 (units/u32/03_resources_staged.csv).
 *
 * Outcome → Mini Lesson map (DoE teaching order L1-8, then the Stage-4 Area Green cards):
 *   R1->1 R2->2 R3->3 Y1->4 R4->5 Y2->6 Y3->7 Y4->8 Y5->9 G1->10 G2->11 G3->12
 */
module.exports = {
  unit_number: "32",
  unit_title: "2D Space & Area",
  term: null,
  duration: "2-3 weeks",

  resource_appendix_attached: true,

  // Every URL verified live in Stage 3 (oEmbed + curl); see units/u32/03_resources_staged.csv.
  resources: {
    r1: [
      { type: "video", label: "Intro to Symmetry (Part 1): Lines of Symmetry | Math with Mr. J", url: "https://www.youtube.com/watch?v=dAqDwuHOi4g" },
      { type: "video", label: "Intro to Symmetry (Part 2): Lines of Symmetry | Math with Mr. J", url: "https://www.youtube.com/watch?v=Ae6kn4BqqrA" },
      { type: "video", label: "Line and Rotational Symmetry | Mr Morley Maths", url: "https://www.youtube.com/watch?v=RnqgIR8pljg" },
      { type: "worksheet", label: "Corbettmaths — Symmetry (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/symmetry-pdf.pdf" },
    ],
    r2: [
      { type: "video", label: "What is a Polygon? An Introductory Guide | Math with Mr. J", url: "https://www.youtube.com/watch?v=mGrst2zkCl8" },
      { type: "video", label: "How Do You Identify Regular and Irregular Polygons? (KS2) | Twinkl", url: "https://www.youtube.com/watch?v=osr-fLanREs" },
      { type: "video", label: "Regular & Irregular Polygons | IconMath", url: "https://www.youtube.com/watch?v=UN57vvrMrY4" },
    ],
    r3: [
      { type: "video", label: "3 Types of Transformations: Translations, Reflections & Rotations | Turtlediary", url: "https://www.youtube.com/watch?v=VJTxv-tRKj0" },
      { type: "video", label: "Transformations: Translations, Reflections and Rotations | Math Defined", url: "https://www.youtube.com/watch?v=YD3HIMUae_4" },
      { type: "worksheet", label: "Corbettmaths — Translations (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/translations-pdf.pdf" },
      { type: "worksheet", label: "Corbettmaths — Reflections (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/reflections-pdf.pdf" },
    ],
    r4: [
      { type: "video", label: "Finding Factors of Numbers: What are Factors? | Primary School Made Easy", url: "https://www.youtube.com/watch?v=f6LhwjjOsbg" },
      { type: "video", label: "What are Factors and How are They Used? (KS2) | Twinkl", url: "https://www.youtube.com/watch?v=rJcxEktyuRY" },
      { type: "worksheet", label: "Corbettmaths — Factors (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2018/11/Factors-216-pdf.pdf" },
    ],
    y1: [
      { type: "video", label: "3 Types of Transformations: Translations, Reflections & Rotations | Turtlediary", url: "https://www.youtube.com/watch?v=VJTxv-tRKj0" },
      { type: "video", label: "Transformations: Translations, Reflections and Rotations | Math Defined", url: "https://www.youtube.com/watch?v=YD3HIMUae_4" },
      { type: "worksheet", label: "Corbettmaths — Rotations (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/rotations-pdf.pdf" },
    ],
    y2: [
      { type: "video", label: "Finding the Area of a Composite Figure (Rectangles) | Math with Mr. J", url: "https://www.youtube.com/watch?v=z4Lat1uOQI4" },
      { type: "video", label: "Finding the Area of Composite Figures with Triangles | Math with Mr. J", url: "https://www.youtube.com/watch?v=bo483Varm-U" },
      { type: "worksheet", label: "Corbettmaths — Area of an L-Shape (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/area-of-an-l-shape-pdf.pdf" },
      { type: "worksheet", label: "Corbettmaths — Area of Compound Shapes (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/area-of-compound-shapes-pdf.pdf" },
    ],
    y3: [
      { type: "video", label: "Area of a Parallelogram and a Triangle | Virtual Elementary School", url: "https://www.youtube.com/watch?v=l9ZagUlu8T4" },
      { type: "video", label: "Find the Area of Triangles and Parallelograms | your math tutor", url: "https://www.youtube.com/watch?v=IXxBaMWUUR4" },
      { type: "worksheet", label: "Corbettmaths — Area of a Parallelogram (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/area-of-a-parallelogram-pdf.pdf" },
    ],
    y4: [
      { type: "video", label: "Area of a Parallelogram and a Triangle | Virtual Elementary School", url: "https://www.youtube.com/watch?v=l9ZagUlu8T4" },
      { type: "video", label: "Find the Area of Triangles and Parallelograms | your math tutor", url: "https://www.youtube.com/watch?v=IXxBaMWUUR4" },
      { type: "worksheet", label: "Corbettmaths — Area of a Triangle (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/area-of-a-triangle-pdf.pdf" },
    ],
    y5: [
      { type: "video", label: "How to Find Area: Rectangles, Triangles & More | Math with Mr. J", url: "https://www.youtube.com/watch?v=LpyzdO2fXtA" },
      { type: "video", label: "Area of a Parallelogram and a Triangle | Virtual Elementary School", url: "https://www.youtube.com/watch?v=l9ZagUlu8T4" },
      { type: "worksheet", label: "Corbettmaths — Area of a Triangle (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/area-of-a-triangle-pdf.pdf" },
    ],
    g1: [
      { type: "video", label: "How to Find Area: Rectangles, Triangles & More | Math with Mr. J", url: "https://www.youtube.com/watch?v=LpyzdO2fXtA" },
      { type: "video", label: "Area of a Parallelogram and a Triangle | Virtual Elementary School", url: "https://www.youtube.com/watch?v=l9ZagUlu8T4" },
      { type: "worksheet", label: "Corbettmaths — Area of a Rectangle (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/area-of-a-rectangle-pdf.pdf" },
      { type: "worksheet", label: "Corbettmaths — Area of a Parallelogram (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/area-of-a-parallelogram-pdf.pdf" },
    ],
    g2: [
      { type: "video", label: "Area of a Parallelogram and a Triangle | Virtual Elementary School", url: "https://www.youtube.com/watch?v=l9ZagUlu8T4" },
      { type: "video", label: "Find the Area of Triangles and Parallelograms | your math tutor", url: "https://www.youtube.com/watch?v=IXxBaMWUUR4" },
      { type: "worksheet", label: "Corbettmaths — Area of a Triangle (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/area-of-a-triangle-pdf.pdf" },
    ],
    g3: [
      { type: "video", label: "Finding the Area of Composite Figures with Triangles | Math with Mr. J", url: "https://www.youtube.com/watch?v=bo483Varm-U" },
      { type: "video", label: "Finding the Area of a Composite Figure (Rectangles) | Math with Mr. J", url: "https://www.youtube.com/watch?v=z4Lat1uOQI4" },
      { type: "worksheet", label: "Corbettmaths — Area of Compound Shapes (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/area-of-compound-shapes-pdf.pdf" },
      { type: "worksheet", label: "Corbettmaths — Area of an L-Shape (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/area-of-an-l-shape-pdf.pdf" },
    ],
  },
  beyond_resources: [
    { type: "video", label: "How to Find Area: Rectangles, Triangles & More | Math with Mr. J", url: "https://www.youtube.com/watch?v=LpyzdO2fXtA" },
    { type: "video", label: "Area of a Parallelogram and a Triangle | Virtual Elementary School", url: "https://www.youtube.com/watch?v=l9ZagUlu8T4" },
    { type: "video", label: "Finding the Area of Composite Figures with Triangles | Math with Mr. J", url: "https://www.youtube.com/watch?v=bo483Varm-U" },
    { type: "worksheet", label: "Corbettmaths — Area of a Parallelogram (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/area-of-a-parallelogram-pdf.pdf" },
    { type: "worksheet", label: "Corbettmaths — Area of a Triangle (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/area-of-a-triangle-pdf.pdf" },
    { type: "worksheet", label: "Corbettmaths — Area of Compound Shapes (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/area-of-compound-shapes-pdf.pdf" },
    { type: "website", label: "Maths is Fun — Area (formulas & interactive)", url: "https://www.mathsisfun.com/geometry/area.html" },
    { type: "website", label: "Maths is Fun — Parallelogram (interactive)", url: "https://www.mathsisfun.com/geometry/parallelogram.html" },
    { type: "website", label: "Maths is Fun — Area of Irregular Polygons (interactive)", url: "https://www.mathsisfun.com/geometry/area-irregular-polygons.html" },
    { type: "website", label: "Maths is Fun — Symmetry (interactive)", url: "https://www.mathsisfun.com/geometry/symmetry.html" },
  ],

  syllabus_strands_summary: "2D space and Area, extended with Stage 4 Area",
  strand_abbreviations_note: "2DS = Two-dimensional spatial structure (shapes, transformations, area). MR = Multiplicative Relations (factors). ARE = Area (Stage 4). A/B = syllabus content groups (A classify shapes & symmetry; B transform & find area by rearrangement, taught as home content).",

  syllabus_outcomes: [
    { code: "MAO-WM-01", descriptor: "Develops understanding and fluency through exploring, applying and communicating mathematical reasoning." },
    { code: "MA3-2DS-01", descriptor: "Investigates and classifies two-dimensional shapes, including triangles and quadrilaterals, based on their properties." },
    { code: "MA3-2DS-02", descriptor: "Selects and uses the appropriate unit to calculate areas, including areas of rectangles." },
    { code: "MA3-2DS-03", descriptor: "Combines, splits and rearranges shapes to determine the area of parallelograms and triangles." },
    { code: "MA4-ARE-C-01", descriptor: "Stage 4 (group A): applies knowledge of area and composite area to solve problems, using the formulas for rectangles, parallelograms and triangles." },
  ],

  content_points: {
    red: {
      heading: "2D shapes A & transformation terms (recall & vocabulary)",
      heading_short: "Red -- Foundation",
      points: [
        "Investigate the line and rotational symmetry of quadrilaterals.",
        "Identify regular and irregular polygons.",
        "Use translate, reflect and rotate to describe transformations; recognise they preserve size.",
        "Determine the factors of a whole number.",
      ],
    },
    yellow: {
      heading: "Transformations B & Area B (applying & spatial reasoning)",
      heading_short: "Yellow -- On-level",
      points: [
        "Dissect and rearrange one shape to make another.",
        "Find the area of a composite (L-shape) figure in different ways.",
        "Transform a parallelogram into a rectangle to find its area; record a method.",
        "Compare a triangle's area to a parallelogram with the same base and height.",
        "Establish that a triangle is half a parallelogram and record a method for any triangle.",
      ],
    },
    green: {
      heading: "Extended -- Stage 4 Area formulas",
      heading_short: "Green -- Extension",
      points: [
        "Apply A = lb (rectangle) and A = bh (parallelogram, base x perpendicular height) (MA4-ARE-C-01).",
        "Develop and apply A = 1/2 bh for the area of a triangle (MA4-ARE-C-01).",
        "Calculate the area of composite figures by dissecting into rectangles, parallelograms and triangles (MA4-ARE-C-01).",
      ],
    },
  },

  working_mathematically: [
    { process: "Communicating", description: "Students describe shapes using symmetry and the language of translate, reflect and rotate, and record methods for finding areas in words." },
    { process: "Understanding and fluency", description: "Students identify symmetry and polygons, dissect and rearrange shapes, and find the areas of composite figures, parallelograms and triangles." },
    { process: "Reasoning", description: "Students reason that transformations preserve size, and that a triangle is half a parallelogram with the same base and height." },
    { process: "Problem solving", description: "Students find areas in more than one way, and (Stage 4) apply area formulas to rectangles, parallelograms, triangles and composite figures." },
  ],

  outcomes: [
    { code: "R1", desc: "Investigate the line and rotational symmetry of quadrilaterals.", content_point: "2DS-A 2D shapes: investigate the line and rotational symmetry properties of quadrilaterals | MA3-2DS-01 | Year A", lesson_ref: "Mini Lesson 1", pairing_note: "Suggested: pair with R2" },
    { code: "R2", desc: "Identify regular and irregular polygons.", content_point: "2DS-A 2D shapes: identify regular and irregular polygons | MA3-2DS-01 | Year A", lesson_ref: "Mini Lesson 2", pairing_note: "Suggested: pair with R1" },
    { code: "R3", desc: "Describe translations, reflections and rotations; recognise they preserve size.", content_point: "2DS-B 2D shapes: use translate/reflect/rotate to describe transformations; transformations change position/orientation but not size | MA3-2DS-01 | Year B", lesson_ref: "Mini Lesson 3" },
    { code: "R4", desc: "Determine the factors of a whole number.", content_point: "MR-A: determine factors for a given whole number (supports dissecting composite areas) | MA3-MR-01 | Year A", lesson_ref: "Mini Lesson 5" },
    { code: "Y1", desc: "Dissect and rearrange one shape to make another.", content_point: "2DS-B 2D shapes: dissect and rearrange one shape to make another | MA3-2DS-01 | Year B", lesson_ref: "Mini Lesson 4" },
    { code: "Y2", desc: "Find the area of a composite (L-shape) figure in different ways.", content_point: "2DS-B Area: find different ways to calculate the area of a composite L-shape figure | MA3-2DS-02 / MA3-2DS-03 | Year B", lesson_ref: "Mini Lesson 6" },
    { code: "Y3", desc: "Transform a parallelogram into a rectangle to find its area; record a method.", content_point: "2DS-B Area: show how to transform a parallelogram into a rectangle to find its area; record a method for any parallelogram | MA3-2DS-03 | Year B", lesson_ref: "Mini Lesson 7", pairing_note: "Suggested: pair with Y4/Y5" },
    { code: "Y4", desc: "Compare a triangle's area to a parallelogram with the same base and height.", content_point: "2DS-B Area: investigate the area of a triangle by comparing it to a parallelogram with the same base length and height | MA3-2DS-03 | Year B", lesson_ref: "Mini Lesson 8", pairing_note: "Suggested: pair with Y5" },
    { code: "Y5", desc: "Establish that a triangle is half a parallelogram; record a method for any triangle.", content_point: "2DS-B Area: establish the triangle-parallelogram relationship (duplicate and rotate); record a method for any triangle | MA3-2DS-03 | Year B", lesson_ref: "Mini Lesson 9", pairing_note: "Suggested: pair with Y4" },
    { code: "G1", desc: "Apply the area formulas for a rectangle (A = lb) and a parallelogram (A = bh).", content_point: "Stage 4 ARE-A: A = lb (rectangle/square); A = bh (parallelogram, base x perpendicular height) | MA4-ARE-C-01 | Stage 4 (group A)", lesson_ref: "Mini Lesson 10" },
    { code: "G2", desc: "Develop and apply the area formula for a triangle (A = 1/2 bh).", content_point: "Stage 4 ARE-A: develop and apply A = 1/2 bh for the area of a triangle | MA4-ARE-C-01 | Stage 4 (group A)", lesson_ref: "Mini Lesson 11" },
    { code: "G3", desc: "Calculate the area of composite figures by dissecting into rectangles, parallelograms and triangles.", content_point: "Stage 4 ARE-A: area of composite figures dissected into rectangles/squares/parallelograms/triangles | MA4-ARE-C-01 | Stage 4 (group A)", lesson_ref: "Mini Lesson 12" },
  ],

  lessons: [
    {
      num: 1, band: "R",
      title: "Symmetry of quadrilaterals",
      outcomes: ["R1"], duration: "25-30 min",
      syllabus: "MA3-2DS-01, MAO-WM-01 | 2DS-A: line and rotational symmetry of quadrilaterals",
      source: "DoE Lesson 1 (adapted)",
      doeLink: "Lesson 1 -- Line and rotational symmetry",
      resources: "Quadrilateral cut-outs, mirrors, tracing paper, paper to fold",
      li: "find the lines of symmetry and the order of rotational symmetry of quadrilaterals",
      sc: [
        "I can find the lines of symmetry of a square, rectangle and other quadrilaterals by folding.",
        "I can turn a shape to find its order of rotational symmetry.",
        "I can compare the symmetry of different quadrilaterals.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Fold a square to find its lines of symmetry. Ask how many it has, and whether a parallelogram has any." },
        { label: "Model (10 min):", content: "Find lines of symmetry by folding, then rotational symmetry by tracing a shape and turning it to count how many times it matches in a full turn." },
        { label: "Guided practice (10 min):", content: "Students investigate the line and rotational symmetry of a set of quadrilaterals, recording lines of symmetry and order of rotational symmetry." },
        { label: "Check (3 min):", content: "Exit question: how many lines of symmetry does a rectangle have, and what is its order of rotational symmetry?" },
      ],
      vocab: "symmetry, line of symmetry, rotational symmetry, order of rotational symmetry, quadrilateral, fold, turn",
      support: "Use a mirror and pre-cut shapes; fold to find lines of symmetry before rotating.",
      extension: "Compare the symmetry of all the special quadrilaterals and order them by number of lines of symmetry.",
      assessment: "Students investigate line and rotational symmetry of quadrilaterals — links to R1 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["quadrilateral cut-outs", "mirrors", "tracing paper"],
    },
    {
      num: 2, band: "R",
      title: "Regular and irregular polygons",
      outcomes: ["R2"], duration: "20-25 min",
      syllabus: "MA3-2DS-01, MAO-WM-01 | 2DS-A: identify regular and irregular polygons",
      source: "DoE Lesson 1 (adapted)",
      doeLink: "Lesson 1 -- Line and rotational symmetry (regular & irregular polygons)",
      resources: "Polygon cards, rulers, protractors",
      li: "identify polygons as regular or irregular",
      sc: [
        "I know a regular polygon has all sides and all angles equal.",
        "I can identify a polygon as regular or irregular.",
        "I can name polygons by their number of sides.",
      ],
      steps: [
        { label: "Activate (3 min):", content: "Show a square and a non-square rectangle. Ask which is 'regular' and why." },
        { label: "Model (9 min):", content: "Define regular (all sides and angles equal). Sort polygons into regular and irregular, checking sides and angles." },
        { label: "Guided practice (8 min):", content: "Students sort a set of polygons into regular and irregular and justify each choice." },
        { label: "Check (3 min):", content: "Exit question: is a rhombus a regular polygon? Explain." },
      ],
      vocab: "polygon, regular, irregular, sides, angles, equal, pentagon, hexagon, octagon",
      support: "Provide a checklist (all sides equal? all angles equal?) to test each polygon.",
      extension: "Explain why a rhombus and a rectangle are irregular even though they look symmetric.",
      assessment: "Students identify regular and irregular polygons with justification — links to R2 in the SOLO Show task.",
    },
    {
      num: 3, band: "R",
      title: "Translate, reflect and rotate",
      outcomes: ["R3"], duration: "25-30 min",
      syllabus: "MA3-2DS-01, MAO-WM-01 | 2DS-B: terms translate/reflect/rotate; transformations preserve size",
      source: "DoE Lesson 2 (adapted)",
      doeLink: "Lesson 2 -- Transformation changes position and orientation but not size",
      resources: "Cut-out shapes, grid paper, mirror",
      li: "use the terms translate, reflect and rotate to describe transformations and recognise they do not change size",
      sc: [
        "I can use translate (slide), reflect (flip) and rotate (turn) to describe how a shape has moved.",
        "I know a transformation changes a shape's position and orientation.",
        "I know a translation, reflection or rotation does not change a shape's size.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Slide, flip and turn a cut-out shape. Ask students to name each move." },
        { label: "Model (10 min):", content: "Model translate, reflect and rotate on grid paper, naming each. Check the shape is the same size before and after each transformation." },
        { label: "Guided practice (10 min):", content: "Students perform and label translations, reflections and rotations of a shape and confirm the size is unchanged." },
        { label: "Check (3 min):", content: "Exit question: name the transformation that flips a shape over a line, and state what stays the same." },
      ],
      vocab: "translate, slide, reflect, flip, rotate, turn, transformation, position, orientation, size",
      support: "Use physical cut-out shapes to perform each move before describing it.",
      extension: "Describe a sequence of two transformations that returns a shape to its start.",
      assessment: "Students describe transformations and recognise they preserve size — links to R3 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["cut-out shapes", "grid paper", "mirror"],
    },
    {
      num: 4, band: "Y",
      title: "Dissecting and rearranging shapes",
      outcomes: ["Y1"], duration: "30 min",
      syllabus: "MA3-2DS-01, MAO-WM-01 | 2DS-B: dissect and rearrange one shape to make another",
      source: "DoE Lesson 3 (adapted)",
      doeLink: "Lesson 3 -- Dissect and rearrange one shape to make another",
      resources: "Shapes to cut, scissors, grid paper, tangram sets",
      li: "dissect a shape and rearrange the pieces using transformations to make another shape",
      sc: [
        "I can cut a shape into pieces.",
        "I can translate, reflect and rotate the pieces to make a new shape.",
        "I know the total area stays the same when I rearrange the pieces.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Cut a rectangle along a diagonal. Ask what shapes the two pieces could make when rearranged." },
        { label: "Model (10 min):", content: "Dissect a shape and rearrange the pieces (sliding, flipping, turning) to form another shape, noting the area is conserved." },
        { label: "Guided practice (12 min):", content: "Students dissect shapes and rearrange them to make a target shape (tangram-style), describing the transformations used." },
        { label: "Check (4 min):", content: "Exit question: cut a square into two pieces and rearrange them into a triangle — what stays the same?" },
      ],
      vocab: "dissect, rearrange, transformation, translate, reflect, rotate, area, conserved",
      support: "Provide pre-cut pieces and a target outline to fill.",
      extension: "Find more than one way to dissect and rearrange a shape into the same target.",
      assessment: "Students dissect and rearrange shapes using transformations — links to Y1 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["shapes to cut", "scissors", "tangram sets", "grid paper"],
    },
    {
      num: 5, band: "R",
      title: "Factors of a whole number",
      outcomes: ["R4"], duration: "20-25 min",
      syllabus: "MA3-MR-01, MAO-WM-01 | MR-A: determine factors for a given whole number",
      source: "DoE Lesson 5 (adapted)",
      doeLink: "Lesson 5 -- Area of composite shapes (using factors)",
      resources: "Counters or square tiles, grid paper",
      li: "find all the factors of a given whole number",
      sc: [
        "I can find factor pairs of a number.",
        "I can list all the factors of a whole number.",
        "I can use factors to find possible side lengths of a rectangle with a given area.",
      ],
      steps: [
        { label: "Activate (3 min):", content: "Arrange 12 tiles into rectangles. Ask what side lengths are possible (factor pairs of 12)." },
        { label: "Model (9 min):", content: "List the factors of 24 by finding factor pairs (1x24, 2x12, 3x8, 4x6). Connect to possible rectangle dimensions for area 24." },
        { label: "Guided practice (10 min):", content: "Students list all factors of several numbers and link them to rectangle dimensions for a given area." },
        { label: "Check (3 min):", content: "Exit question: list all the factors of 18." },
      ],
      vocab: "factor, factor pair, multiple, whole number, dimensions, area",
      support: "Use tiles to build rectangles and read off factor pairs.",
      extension: "Find numbers with exactly two factors (primes) and numbers with many factors.",
      assessment: "Students determine all factors of a whole number — links to R4 in the SOLO Show task.",
    },
    {
      num: 6, band: "Y",
      title: "Area of composite L-shapes",
      outcomes: ["Y2"], duration: "30 min",
      syllabus: "MA3-2DS-02, MA3-2DS-03, MAO-WM-01 | 2DS-B Area: find different ways to calculate the area of a composite L-shape",
      source: "DoE Lessons 4-5 (adapted)",
      doeLink: "Lessons 4-5 -- Area of a composite L-shape figure",
      resources: "Grid paper, L-shape figures, rulers",
      li: "find the area of a composite L-shape figure in more than one way",
      sc: [
        "I can split an L-shape into two rectangles and add their areas.",
        "I can surround an L-shape to make a big rectangle and subtract the missing piece.",
        "I can show the area is the same using both methods.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show an L-shaped figure on a grid. Ask how we could split it to find its area." },
        { label: "Model (10 min):", content: "Find the area two ways: (1) split into two rectangles and add; (2) complete the big rectangle and subtract the cut-out. Confirm both give the same area." },
        { label: "Guided practice (12 min):", content: "Students find the area of several composite L-shapes using both the split and surround-and-subtract methods." },
        { label: "Check (4 min):", content: "Exit question: find the area of this L-shape two different ways." },
      ],
      vocab: "composite figure, L-shape, area, rectangle, split, surround, subtract, square units",
      support: "Provide grid paper to count squares; pre-mark the split line.",
      extension: "Find the area of composite shapes made from three or more rectangles.",
      assessment: "Students find composite-figure areas in more than one way — links to Y2 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["grid paper", "L-shape figures", "rulers"],
    },
    {
      num: 7, band: "Y",
      title: "Area of a parallelogram",
      outcomes: ["Y3"], duration: "30 min",
      syllabus: "MA3-2DS-03, MAO-WM-01 | 2DS-B Area: transform a parallelogram into a rectangle; record a method",
      source: "DoE Lesson 6 (adapted)",
      doeLink: "Lesson 6 -- Transform a parallelogram to find its area",
      resources: "Parallelogram cut-outs, scissors, rulers, grid paper",
      li: "transform a parallelogram into a rectangle to find its area and record a method",
      sc: [
        "I can cut a right-angled triangle off one end of a parallelogram and move it to the other end to make a rectangle.",
        "I can find the area of the rectangle (and so the parallelogram).",
        "I can record a method: area = base x perpendicular height.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show a parallelogram on grid paper. Ask how we could turn it into a rectangle to find its area." },
        { label: "Model (10 min):", content: "Cut a right triangle off one end, translate it to the other end to form a rectangle, and find the area. Record 'area = base x perpendicular height'." },
        { label: "Guided practice (12 min):", content: "Students transform parallelograms into rectangles to find their areas and write the method in words." },
        { label: "Check (4 min):", content: "Exit question: a parallelogram has base 6 cm and perpendicular height 4 cm — what is its area?" },
      ],
      vocab: "parallelogram, rectangle, base, perpendicular height, area, transform, rearrange",
      support: "Provide pre-cut parallelograms with the cut line marked.",
      extension: "Explain why the slant side is not used in the area, only the perpendicular height.",
      assessment: "Students find the area of a parallelogram by rearrangement and record a method — links to Y3 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["parallelogram cut-outs", "scissors", "rulers", "grid paper"],
    },
    {
      num: 8, band: "Y",
      title: "Comparing a triangle to a parallelogram",
      outcomes: ["Y4"], duration: "25-30 min",
      syllabus: "MA3-2DS-03, MAO-WM-01 | 2DS-B Area: compare a triangle's area to a parallelogram with the same base and height",
      source: "DoE Lesson 7 (adapted)",
      doeLink: "Lesson 7 -- Determine the area of a triangle",
      resources: "Matching triangle and parallelogram cut-outs, grid paper",
      li: "investigate the area of a triangle by comparing it to a parallelogram with the same base and height",
      sc: [
        "I can place a triangle on a parallelogram with the same base and height.",
        "I can see the triangle covers half the parallelogram.",
        "I can explain the triangle's area is half the parallelogram's.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show a triangle and a parallelogram with the same base and height. Ask how their areas compare." },
        { label: "Model (10 min):", content: "Overlay the triangle on the parallelogram (same base and height). Show two copies of the triangle exactly cover the parallelogram, so the triangle is half." },
        { label: "Guided practice (10 min):", content: "Students compare several triangles with same-base/height parallelograms and record that the triangle is half the area." },
        { label: "Check (3 min):", content: "Exit question: a parallelogram has area 20 cm2 — what is the area of a triangle with the same base and height?" },
      ],
      vocab: "triangle, parallelogram, base, height, half, area, compare",
      support: "Use matching cut-outs students can physically overlay.",
      extension: "Show the half relationship holds for an obtuse triangle too.",
      assessment: "Students relate a triangle's area to a same-base/height parallelogram — links to Y4 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["matching triangle & parallelogram cut-outs", "grid paper"],
    },
    {
      num: 9, band: "Y",
      title: "Area of a triangle: establishing the method",
      outcomes: ["Y5"], duration: "30 min",
      syllabus: "MA3-2DS-03, MAO-WM-01 | 2DS-B Area: triangle-parallelogram relationship (duplicate & rotate); record a method",
      source: "DoE Lesson 8 (adapted)",
      doeLink: "Lesson 8 -- Relationship between the area of a triangle and a parallelogram",
      resources: "Triangle cut-outs (two copies each), scissors, grid paper",
      li: "establish that a triangle is half a parallelogram and record a method for finding the area of any triangle",
      sc: [
        "I can duplicate and rotate a triangle to form a parallelogram.",
        "I know the triangle is half that parallelogram.",
        "I can record a method: area of a triangle = half x base x perpendicular height.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Take two identical triangles. Ask how to fit them together to make a parallelogram." },
        { label: "Model (10 min):", content: "Duplicate and rotate a triangle to form a parallelogram (base x height). The triangle is half, so area = 1/2 x base x perpendicular height. Record in words." },
        { label: "Guided practice (12 min):", content: "Students build parallelograms from pairs of triangles, then calculate triangle areas using the half-base-height method." },
        { label: "Check (4 min):", content: "Exit question: a triangle has base 8 cm and perpendicular height 5 cm — what is its area?" },
      ],
      vocab: "triangle, parallelogram, duplicate, rotate, base, perpendicular height, half, area, method",
      support: "Provide two pre-cut identical triangles to join into a parallelogram.",
      extension: "Record the method as a formula and use it for triangles in different orientations.",
      assessment: "Students establish and record the area-of-a-triangle method — links to Y5 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["triangle cut-outs (two copies each)", "scissors", "grid paper"],
    },
    {
      num: 10, band: "G",
      title: "Area formulas for rectangles and parallelograms (Stage 4)",
      outcomes: ["G1"], duration: "30-35 min",
      syllabus: "MA4-ARE-C-01, MAO-WM-01 | Stage 4 ARE-A: A = lb (rectangle); A = bh (parallelogram)",
      source: "Original mini lesson",
      li: "apply the area formulas for a rectangle and a parallelogram",
      sc: [
        "I can apply A = l x b to find the area of a rectangle.",
        "I can apply A = b x h to find the area of a parallelogram.",
        "I can solve area problems using these formulas.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Recall area = base x perpendicular height for a parallelogram (Mini Lesson 7). Write it as a formula." },
        { label: "Model (11 min):", content: "Apply A = lb to a rectangle (8 cm x 5 cm = 40 cm2) and A = bh to a parallelogram (base 7 cm, height 4 cm = 28 cm2). Stress 'perpendicular height', not the slant side." },
        { label: "Guided practice (12 min):", content: "Students apply the formulas to a set of rectangles and parallelograms and solve a word problem." },
        { label: "Check (5 min):", content: "Exit question: find the area of a parallelogram with base 9 cm and perpendicular height 6 cm." },
      ],
      vocab: "area, formula, rectangle, parallelogram, length, breadth, base, perpendicular height, square units",
      support: "Provide the formula and a labelled diagram; identify the perpendicular height first.",
      extension: "Find a missing base or height given the area; compare parallelograms with the same area.",
      assessment: "Students apply the rectangle and parallelogram area formulas — links to G1 in the SOLO Show task.",
    },
    {
      num: 11, band: "G",
      title: "Area formula for a triangle (Stage 4)",
      outcomes: ["G2"], duration: "30 min",
      syllabus: "MA4-ARE-C-01, MAO-WM-01 | Stage 4 ARE-A: develop and apply A = 1/2 bh",
      source: "Original mini lesson",
      li: "develop and apply the formula for the area of a triangle",
      sc: [
        "I know a triangle is half a parallelogram with the same base and height.",
        "I can apply A = 1/2 x b x h to find the area of a triangle.",
        "I can solve triangle area problems.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Recall the triangle is half a parallelogram (Mini Lesson 9). Write the formula A = 1/2 bh." },
        { label: "Model (11 min):", content: "Apply A = 1/2 bh to a triangle (base 10 cm, height 6 cm = 30 cm2). Repeat for a right and an obtuse triangle, identifying the perpendicular height each time." },
        { label: "Guided practice (11 min):", content: "Students apply A = 1/2 bh to a set of triangles in different orientations and solve a word problem." },
        { label: "Check (4 min):", content: "Exit question: find the area of a triangle with base 12 cm and perpendicular height 5 cm." },
      ],
      vocab: "triangle, area, formula, base, perpendicular height, half, square units",
      support: "Provide the formula and a labelled triangle; mark the perpendicular height.",
      extension: "Find a missing base or height given the area; find the area of a triangle on a grid by reading base and height.",
      assessment: "Students apply A = 1/2 bh to find triangle areas — links to G2 in the SOLO Show task.",
    },
    {
      num: 12, band: "G",
      title: "Composite areas with formulas (Stage 4)",
      outcomes: ["G3"], duration: "30-35 min",
      syllabus: "MA4-ARE-C-01, MAO-WM-01 | Stage 4 ARE-A: area of composite figures by dissection",
      source: "Original mini lesson",
      li: "calculate the area of composite figures by dissecting them into rectangles, parallelograms and triangles",
      sc: [
        "I can dissect a composite figure into rectangles, parallelograms and triangles.",
        "I can find the area of each part using a formula.",
        "I can add the parts to find the total area.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show a composite shape made of a rectangle and a triangle. Ask how to split it to use formulas." },
        { label: "Model (11 min):", content: "Dissect a composite figure into a rectangle and a triangle, find each area with a formula, and add them. Then a shape needing subtraction." },
        { label: "Guided practice (13 min):", content: "Students dissect and find the area of several composite figures using the area formulas, recording each part." },
        { label: "Check (5 min):", content: "Exit question: find the area of a composite shape made of a 6x4 rectangle and a triangle (base 6, height 3)." },
      ],
      vocab: "composite figure, dissect, rectangle, parallelogram, triangle, area, formula, total",
      support: "Pre-mark the dissection lines; provide the formulas.",
      extension: "Solve composite-area word problems involving real contexts (gardens, floor plans).",
      assessment: "Students find composite areas by dissecting and applying formulas — links to G3 in the SOLO Show task.",
    },
  ],
};
