/**
 * Unit 29 — 3D Space & Volume (Stage 3 Year B) — teacher program data.
 * Deliverable B. Built from the approved Stage 0 rubric
 * (units/u29/00_rubric_draft.md) and the Stage 1 mapping
 * (units/u29/01_mapping_review.md). Matches the UNIT DATA SCHEMA at the
 * bottom of scripts/build_program_template.js.
 *
 * This task keeps the program (Stage 2) and the resource appendix
 * (Stage 5) as SEPARATE docx files, so the program is built with the
 * appendix detached (resource_appendix_attached: false; the program
 * driver strips `resources` before building). `resources` /
 * `beyond_resources` below are consumed only by the standalone appendix
 * build — every URL is verified in Stage 3 (units/u29/03_resources_staged.csv).
 *
 * Outcome → Mini Lesson map (cards run in DoE teaching order: the 3D-space
 * cluster L1-4 first, then the decimal/capacity/volume cluster L5-8, with
 * each Green Stage-4 card placed beside the Stage-3 work it extends):
 *   R1→1  R2→2  Y1→3  Y2→4  Y3→5  G3→6  R3→7  R4→8  Y4→9  Y5→10  Y6→11  G1→12  G2→13
 */
module.exports = {
  unit_number: "29",
  unit_title: "3D Space & Volume",
  term: null,                      // left blank — confirm term placement with Nicholas
  duration: "2-3 weeks",

  resource_appendix_attached: true,

  // Every URL verified live in Stage 3 (oEmbed for YouTube, curl for PDFs/sites);
  // see units/u29/03_resources_staged.csv. Keyed by outcome code (lowercase).
  resources: {
    r1: [
      { type: "video", label: "Faces, Edges and Vertices of a Rectangular Prism | Math with Mr. J", url: "https://www.youtube.com/watch?v=bQBCcWRIHHg" },
      { type: "video", label: "Faces, Edges and Vertices of a Square Pyramid | Math with Mr. J", url: "https://www.youtube.com/watch?v=60guabFsA_c" },
      { type: "video", label: "3D Figures - Prisms and Pyramids | Miacademy", url: "https://www.youtube.com/watch?v=S5hfJi5TkFM" },
      { type: "worksheet", label: "Corbettmaths — Properties of 3D Shapes (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/3d-shapes-pdf.pdf" },
    ],
    r2: [
      { type: "video", label: "Prisms and Pyramids: Types of Prism and Pyramid | TutWay", url: "https://www.youtube.com/watch?v=_QA53bHD9p4" },
      { type: "video", label: "Identifying Prisms and Pyramids | ExampleSquare", url: "https://www.youtube.com/watch?v=JmJpZlj-wPQ" },
      { type: "video", label: "Faces, Edges and Vertices of a Hexagonal Pyramid | Math with Mr. J", url: "https://www.youtube.com/watch?v=Pb_4BZK4oiU" },
      { type: "worksheet", label: "Corbettmaths — Properties of 3D Shapes (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/3d-shapes-pdf.pdf" },
    ],
    r3: [
      { type: "video", label: "Place Value to the Thousandths | Miacademy", url: "https://www.youtube.com/watch?v=BsZJGMRWEK0" },
      { type: "video", label: "Finding the Value of the Underlined Digit (Decimal Place Value) | Math with Mr. J", url: "https://www.youtube.com/watch?v=2xGzQXn3WUQ" },
      { type: "video", label: "Expanded Form with Decimals | Math with Mr. J", url: "https://www.youtube.com/watch?v=GX8o-S6Vxig" },
      { type: "worksheet", label: "Corbettmaths — Place Value (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/place-value-pdf.pdf" },
    ],
    r4: [
      { type: "video", label: "Converting Metric Units for Capacity | Corbettmaths", url: "https://www.youtube.com/watch?v=zGBN0ofKYpQ" },
      { type: "video", label: "Measuring Capacity: Millilitres and Litres | Trinity Primary", url: "https://www.youtube.com/watch?v=yxnJh4Jbclo" },
      { type: "worksheet", label: "Corbettmaths — Metric Units (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/metric-units-pdf.pdf" },
    ],
    y1: [
      { type: "video", label: "What's a Net? | Math with Mr. J", url: "https://www.youtube.com/watch?v=HBSLrN9LWBA" },
      { type: "video", label: "Make Your Own 3D Shapes from Nets! (build demo) | Becky Seres", url: "https://www.youtube.com/watch?v=zPGbFJLzj5c" },
      { type: "worksheet", label: "Corbettmaths — Nets (PDF, print and fold)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/nets-pdf1.pdf" },
    ],
    y2: [
      { type: "video", label: "Views and Elevations (technique demo) | Corbettmaths", url: "https://www.youtube.com/watch?v=BnwoipoGWJ8" },
      { type: "video", label: "Plans and Elevations | Minity Maths", url: "https://www.youtube.com/watch?v=ITt37h7GeJY" },
      { type: "worksheet", label: "Corbettmaths — Views and Elevations (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2015/03/views.pdf" },
    ],
    y3: [
      { type: "video", label: "Make Your Own 3D Shapes from Nets! (build demo) | Becky Seres", url: "https://www.youtube.com/watch?v=zPGbFJLzj5c" },
      { type: "video", label: "What's a Net? (nets to solids) | Math with Mr. J", url: "https://www.youtube.com/watch?v=HBSLrN9LWBA" },
      { type: "worksheet", label: "Corbettmaths — Nets (PDF, print, cut and build)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/nets-pdf1.pdf" },
    ],
    y4: [
      { type: "video", label: "How to Measure Capacity (for Children) | Bodhaguru", url: "https://www.youtube.com/watch?v=wXTG04MxB-E" },
      { type: "video", label: "Capacity for Kids: Measuring Volume | TutWay", url: "https://www.youtube.com/watch?v=xSbsbz7Ovb4" },
      { type: "video", label: "Measuring Capacity: Millilitres and Litres | Trinity Primary", url: "https://www.youtube.com/watch?v=yxnJh4Jbclo" },
      { type: "worksheet", label: "Corbettmaths — Metric Units (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/metric-units-pdf.pdf" },
    ],
    y5: [
      { type: "video", label: "Measuring Capacity and Reading Scales | Maths Everywhere", url: "https://www.youtube.com/watch?v=GFTlete-nMM" },
      { type: "video", label: "Place Value to the Thousandths | Miacademy", url: "https://www.youtube.com/watch?v=BsZJGMRWEK0" },
      { type: "worksheet", label: "Corbettmaths — Reading Scales (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/reading-scales-pdf.pdf" },
    ],
    y6: [
      { type: "video", label: "Archimedes' Eureka: Measuring Volume by Displacement | Manocha Academy", url: "https://www.youtube.com/watch?v=X1VazJC8OLY" },
      { type: "video", label: "Finding the Volume of an Irregular Object by Water Displacement | AllThingsChemistry", url: "https://www.youtube.com/watch?v=7kNiVrL6uV8" },
      { type: "video", label: "Volume by Water Displacement | Eric Pantano", url: "https://www.youtube.com/watch?v=--HL4NiR6OU" },
    ],
    g1: [
      { type: "video", label: "Volume of Rectangular Prisms | Math with Mr. J", url: "https://www.youtube.com/watch?v=By7sVb2IhFs" },
      { type: "video", label: "How to Find the Volume of a Triangular Prism | Math with Mr. J", url: "https://www.youtube.com/watch?v=4pV7_NuGO2g" },
      { type: "worksheet", label: "Corbettmaths — Volume of a Prism (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/volume-of-a-prism-pdf.pdf" },
      { type: "worksheet", label: "Corbettmaths — Volume of a Cuboid (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/volume-of-a-cuboid-pdf.pdf" },
    ],
    g2: [
      { type: "video", label: "1 mL = 1 cm3 (volume-capacity link) | Scott Milam", url: "https://www.youtube.com/watch?v=028tWJGCSdM" },
      { type: "video", label: "Converting Metric Units for Capacity | Corbettmaths", url: "https://www.youtube.com/watch?v=zGBN0ofKYpQ" },
      { type: "worksheet", label: "Corbettmaths — Metric Units (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/metric-units-pdf.pdf" },
    ],
    g3: [
      { type: "video", label: "What Shape is the Cross Section? (parallel and perpendicular) | Tom Teaches Math", url: "https://www.youtube.com/watch?v=MeARCoXD03M" },
      { type: "video", label: "Intro to Cross Sections / Slicing 3D Figures | Mark Wigand", url: "https://www.youtube.com/watch?v=PcPBq0PYjAQ" },
      { type: "video", label: "Views and Elevations | Corbettmaths", url: "https://www.youtube.com/watch?v=BnwoipoGWJ8" },
      { type: "worksheet", label: "Corbettmaths — Views and Elevations (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2015/03/views.pdf" },
    ],
  },
  beyond_resources: [
    { type: "video", label: "Volume of Rectangular Prisms | Math with Mr. J", url: "https://www.youtube.com/watch?v=By7sVb2IhFs" },
    { type: "video", label: "How to Find the Volume of a Triangular Prism | Math with Mr. J", url: "https://www.youtube.com/watch?v=4pV7_NuGO2g" },
    { type: "video", label: "1 mL = 1 cm3 (volume-capacity link) | Scott Milam", url: "https://www.youtube.com/watch?v=028tWJGCSdM" },
    { type: "video", label: "What Shape is the Cross Section? | Tom Teaches Math", url: "https://www.youtube.com/watch?v=MeARCoXD03M" },
    { type: "worksheet", label: "Corbettmaths — Volume of a Prism (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/volume-of-a-prism-pdf.pdf" },
    { type: "worksheet", label: "Corbettmaths — Metric Units (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/metric-units-pdf.pdf" },
    { type: "website", label: "Maths is Fun — Volume (interactive)", url: "https://www.mathsisfun.com/geometry/volume.html" },
    { type: "website", label: "Maths is Fun — Metric Volume & Capacity (interactive)", url: "https://www.mathsisfun.com/measure/metric-volume.html" },
    { type: "website", label: "Maths is Fun — Cross Sections (interactive)", url: "https://www.mathsisfun.com/geometry/cross-sections.html" },
    { type: "website", label: "Maths is Fun — Prisms (interactive)", url: "https://www.mathsisfun.com/geometry/prisms.html" },
  ],

  syllabus_strands_summary: "3D space and Volume/capacity, extended with Stage 4 Volume",
  strand_abbreviations_note: "3DS = Three-dimensional spatial structure (objects, nets, views, construction, volume & capacity). RN = Represents numbers (decimals). VOL = Volume (Stage 4). A/B = syllabus content groups (A consolidated as prior learning, B taught as home content). This unit is almost entirely group A; the one group-B sub-strand is 'Construct prisms and pyramids' (Y3).",

  syllabus_outcomes: [
    { code: "MAO-WM-01", descriptor: "Develops understanding and fluency in mathematics through exploring and connecting mathematical concepts, choosing and applying mathematical techniques to solve problems, and communicating their thinking and reasoning coherently and clearly." },
    { code: "MA3-3DS-01", descriptor: "Visualises, sketches and constructs three-dimensional objects, including prisms and pyramids, making connections to two-dimensional representations." },
    { code: "MA3-3DS-02", descriptor: "Selects and uses the appropriate unit to estimate, measure and calculate volumes and capacities." },
    { code: "MA3-RN-02", descriptor: "Represents and compares decimals up to 3 decimal places, recognising that the place-value system extends beyond hundredths to thousandths." },
    { code: "MA4-VOL-C-01", descriptor: "Stage 4 (group A): applies knowledge of volume and capacity to solve problems involving right prisms and cylinders (formula V = Ah, unit conversion, prism views and cross-sections)." },
  ],

  content_points: {
    red: {
      heading: "3D objects A & Decimals/Capacity A (recall & identification)",
      heading_short: "Red -- Foundation",
      points: [
        "Compare the properties of prisms and pyramids (faces, edges, vertices).",
        "Name prisms and pyramids according to the shape of their base.",
        "Interpret decimal notation for thousandths and name the place value of digits to 3 decimal places.",
        "Recognise the equivalence of whole-number and decimal capacity measurements (e.g. 1500 mL = 1.5 L).",
      ],
    },
    yellow: {
      heading: "3D objects A/B & Volume A (applying & spatial reasoning)",
      heading_short: "Yellow -- On-level",
      points: [
        "Examine whether a diagram is the net of a closed 3D object, and visualise and name the solid a net folds into.",
        "Visualise and sketch 3D objects from different views (top, front and side).",
        "Construct prisms and pyramids: skeletal models and models built from drawings of different views (group B).",
        "Select and use appropriate units to measure the capacities of containers.",
        "Record capacity measurements to 3 decimal places.",
        "Use displacement to investigate and compare the volumes of irregular solids.",
      ],
    },
    green: {
      heading: "Extended -- Stage 4 Volume A content",
      heading_short: "Green -- Extension",
      points: [
        "Find the volume of a prism using V = base area x height (V = Ah) for prisms with a uniform cross-section (MA4-VOL-C-01).",
        "Convert between metric units of volume and capacity (1 cm3 = 1 mL, 1 m3 = 1000 L = 1 kL) and choose appropriate units (MA4-VOL-C-01).",
        "Represent prisms from different 2D views and identify their uniform cross-section equal to the base area (MA4-VOL-C-01).",
      ],
    },
  },

  working_mathematically: [
    { process: "Communicating", description: "Students describe 3D objects (faces, edges, vertices, base shape) and describe capacities using decimal place value and correct metric units." },
    { process: "Understanding and fluency", description: "Students name prisms and pyramids, read and record decimals to thousandths, and measure capacities to 3 decimal places." },
    { process: "Reasoning", description: "Students reason about which net folds to which solid and how an object looks from each view, and justify why two capacities are equivalent." },
    { process: "Problem solving", description: "Students construct models from drawings, use displacement to compare volumes, and (Stage 4) apply V = Ah and unit conversions." },
  ],

  outcomes: [
    { code: "R1", desc: "Compare the properties of prisms and pyramids (faces, edges, vertices).", content_point: "3DS-A 3D objects: compare properties of prisms and pyramids | MA3-3DS-01 | Year A", lesson_ref: "Mini Lesson 1", pairing_note: "Suggested: pair with R2" },
    { code: "R2", desc: "Name prisms and pyramids according to the shape of their base.", content_point: "3DS-A 3D objects: name prisms and pyramids according to the shape of their base | MA3-3DS-01 | Year A", lesson_ref: "Mini Lesson 2", pairing_note: "Suggested: pair with R1" },
    { code: "R3", desc: "Interpret decimal notation for thousandths and name the place value of digits to 3 decimal places.", content_point: "RN-A Decimals: express thousandths as decimals; interpret decimal notation for thousandths; indicate place value to 3 decimal places | MA3-RN-02 | Year A", lesson_ref: "Mini Lesson 7" },
    { code: "R4", desc: "Recognise equivalent whole-number and decimal capacity measurements.", content_point: "3DS-A Volume: recognise the equivalence of whole-number and decimal representations of capacities; interpret decimal notation for capacities | MA3-3DS-02 | Year A", lesson_ref: "Mini Lesson 8" },
    { code: "Y1", desc: "Decide whether a diagram is a net of a closed 3D object, and visualise and name the solid it folds into.", content_point: "3DS-A 3D objects: examine if a diagram is a net of a closed 3D object; visualise and name prisms/pyramids from their nets | MA3-3DS-01 | Year A", lesson_ref: "Mini Lesson 3" },
    { code: "Y2", desc: "Visualise and sketch 3D objects from different views (top, front, side).", content_point: "3DS-A 3D objects: visualise and sketch three-dimensional objects from different views, including top, front and side views | MA3-3DS-01 | Year A", lesson_ref: "Mini Lesson 4", pairing_note: "Suggested: pair with G3" },
    { code: "Y3", desc: "Construct prisms and pyramids: skeletal models and models from drawings of different views.", content_point: "3DS-B 3D objects: create skeletal models of prisms and pyramids; construct 3D models given drawings of different views | MA3-3DS-01 | Year B", lesson_ref: "Mini Lesson 5" },
    { code: "Y4", desc: "Select and use appropriate units to measure the capacities of containers.", content_point: "3DS-A Volume: select and use appropriate units to measure the capacities of a variety of containers | MA3-3DS-02 | Year A", lesson_ref: "Mini Lesson 9" },
    { code: "Y5", desc: "Record capacity measurements to 3 decimal places.", content_point: "3DS-A Volume: record measurements to 3 decimal places | MA3-3DS-02 | Year A", lesson_ref: "Mini Lesson 10" },
    { code: "Y6", desc: "Use displacement to investigate and compare the volumes of irregular solids.", content_point: "3DS-A Volume: recognise volume by observing water-level change; compare volumes of 2+ objects by marking the change in water level | MA3-3DS-02 | Year A", lesson_ref: "Mini Lesson 11" },
    { code: "G1", desc: "Find the volume of a prism using V = base area x height (V = Ah).", content_point: "Stage 4 VOL-A: develop V = base area x height (V = Ah); apply to prisms with uniform cross-sections | MA4-VOL-C-01 | Stage 4 (group A)", lesson_ref: "Mini Lesson 12" },
    { code: "G2", desc: "Convert between metric units of volume and capacity, and choose appropriate units.", content_point: "Stage 4 VOL-A: convert between metric units of volume and capacity (1 cm3 = 1 mL, 1 m3 = 1000 L = 1 kL); choose and justify units | MA4-VOL-C-01 | Stage 4 (group A)", lesson_ref: "Mini Lesson 13" },
    { code: "G3", desc: "Represent prisms from different 2D views and identify their uniform cross-section.", content_point: "Stage 4 VOL-A: represent prisms from top/side/front/back views; identify cross-sections; prisms have a uniform cross-section equal to the base area | MA4-VOL-C-01 | Stage 4 (group A)", lesson_ref: "Mini Lesson 6", pairing_note: "Suggested: pair with Y2" },
  ],

  lessons: [
    {
      num: 1, band: "R",
      title: "Properties of prisms and pyramids",
      outcomes: ["R1"], duration: "25-30 min",
      syllabus: "MA3-3DS-01, MAO-WM-01 | 3DS-A: compare properties of prisms and pyramids",
      source: "DoE Lesson 1 (adapted)",
      doeLink: "Lesson 1 -- Properties of prisms and pyramids",
      resources: "Geometric 3D models (prisms and pyramids), everyday boxes/packages, Resource 1 - prism properties, Resource 2 - guess what",
      li: "compare prisms and pyramids by their faces, edges and vertices",
      sc: [
        "I can count the faces, edges and vertices of a prism or pyramid.",
        "I know a prism has two identical parallel ends (bases) joined by rectangles.",
        "I know a pyramid has one base and triangular faces meeting at an apex.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Hand out 3D models and everyday packages. Ask students to sort them into 'prisms' and 'pyramids' and explain how they decided." },
        { label: "Model (10 min):", content: "Using a triangular prism and a triangular pyramid, count and record faces, edges and vertices together. Draw out the defining features: a prism has two identical parallel bases joined by rectangles; a pyramid has one base and triangular faces meeting at an apex." },
        { label: "Guided practice (10 min):", content: "Students complete a properties table (faces / edges / vertices) for 4-5 prisms and pyramids using the physical models, and write one sentence comparing a prism with a pyramid." },
        { label: "Check (3 min):", content: "Exit question: how many faces, edges and vertices does a square pyramid have, and what makes it a pyramid not a prism?" },
      ],
      vocab: "prism, pyramid, face, edge, vertex, vertices, base, apex, parallel, two-dimensional, three-dimensional",
      support: "Provide a partly-labelled diagram of a triangular prism and triangular pyramid; let students hold and rotate the model while counting.",
      extension: "Investigate the properties of less common solids (e.g. an octagonal prism); look for prisms and pyramids in real structures such as the Egyptian pyramids.",
      assessment: "Students compare prisms and pyramids by faces, edges and vertices with correct reasoning — links to R1 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["geometric 3D models (prisms and pyramids)", "everyday boxes/packages"],
    },
    {
      num: 2, band: "R",
      title: "Naming prisms and pyramids by their base",
      outcomes: ["R2"], duration: "20-25 min",
      syllabus: "MA3-3DS-01, MAO-WM-01 | 3DS-A: name prisms and pyramids according to the shape of their base",
      source: "DoE Lessons 1 & 3 (adapted)",
      doeLink: "Lessons 1 & 3 -- Naming prisms and pyramids",
      resources: "Geometric 3D models, base-shape cards, Resource 6 - sketch and label",
      li: "name a prism or pyramid from the shape of its base",
      sc: [
        "I can identify the base of a prism or pyramid.",
        "I can name a solid from its base shape (e.g. triangular prism, hexagonal pyramid).",
        "I know the base names the solid, and 'prism' or 'pyramid' tells me the type.",
      ],
      steps: [
        { label: "Activate (3 min):", content: "Hold up a hexagonal prism. Ask 'what shape is the base?' and 'is it a prism or a pyramid?' to build the naming rule: base shape + type." },
        { label: "Model (9 min):", content: "Match several models to name cards: triangular prism, rectangular prism, pentagonal prism, square pyramid, triangular pyramid. Emphasise identifying the base first." },
        { label: "Guided practice (8 min):", content: "Students label a set of pictured solids with their full names, and sketch and name one prism and one pyramid of their choice." },
        { label: "Check (3 min):", content: "Exit question: name the solid with a pentagon base and triangular faces meeting at a point." },
      ],
      vocab: "base, prism, pyramid, triangular, rectangular, square, pentagonal, hexagonal, apex",
      support: "Provide a base-shape reference strip (triangle, square, pentagon, hexagon) beside the models.",
      extension: "Name and sketch prisms and pyramids with bases up to an octagon; explain why a cube is a special rectangular prism.",
      assessment: "Students name prisms and pyramids correctly from the base shape — links to R2 in the SOLO Show task.",
    },
    {
      num: 3, band: "Y",
      title: "Nets: is it a net, and what does it fold into?",
      outcomes: ["Y1"], duration: "30-35 min",
      syllabus: "MA3-3DS-01, MAO-WM-01 | 3DS-A: examine if a diagram is a net of a closed 3D object; visualise and name solids from nets",
      source: "DoE Lesson 2 (adapted)",
      doeLink: "Lesson 2 -- Visualise and name nets",
      resources: "Resource 3 - 3D nets, Resource 4 - nets of cubes, Resource 5 - match my net, scissors, tape, geometric models",
      li: "decide whether a diagram is the net of a closed 3D object and name the solid a net folds into",
      sc: [
        "I can decide if a diagram will fold into a closed 3D object with no gaps or overlaps.",
        "I can match a net to the solid it makes.",
        "I can name the prism or pyramid a given net folds into.",
      ],
      steps: [
        { label: "Activate (5 min):", content: "Show two cube nets, one valid and one invalid. Ask students to predict which folds into a closed cube, then test by cutting and folding." },
        { label: "Model (10 min):", content: "Fold a valid net into a closed solid and name it; show a non-net (overlapping/gap) and explain why it fails. Visualise a triangular-prism net and name it before folding to check." },
        { label: "Guided practice (15 min):", content: "Students sort net diagrams into 'is a net' / 'is not a net', match nets to models (Resource 5 - match my net), and name the solid each valid net folds into in their books." },
        { label: "Check (4 min):", content: "Exit question: name the solid this net folds into, and explain how you know the diagram is a valid net." },
      ],
      vocab: "net, fold, face, closed, prism, pyramid, edge, overlap, gap, visualise",
      support: "Give students the simpler cut-out nets to fold first; provide 3D objects and labels to match before working from diagrams alone.",
      extension: "Use Polypad (or grid paper) to create additional valid nets for the same solid and explain why several nets can make the same object.",
      assessment: "Students identify valid nets and name the solids they fold into — links to Y1 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["printed nets (Resource 3 & 4)", "scissors", "tape", "geometric models for matching"],
    },
    {
      num: 4, band: "Y",
      title: "Sketching objects from different views",
      outcomes: ["Y2"], duration: "30 min",
      syllabus: "MA3-3DS-01, MAO-WM-01 | 3DS-A: visualise and sketch 3D objects from different views (top, front, side)",
      source: "DoE Lesson 3 (adapted)",
      doeLink: "Lesson 3 -- Sketching different views of three-dimensional objects",
      resources: "Geometric models, interlocking cubes, Resource 6 - sketch and label, grid/isometric paper",
      li: "visualise an object and sketch its top, front and side views",
      sc: [
        "I can picture an object from the top, the front and the side.",
        "I can sketch each of those views as a 2D drawing.",
        "I can recognise an object from drawings of its different views.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Build a small model from interlocking cubes. Ask what it looks like from directly above, from the front and from the side." },
        { label: "Model (11 min):", content: "Holding a model at eye level, sketch its front view, then turn it to draw the side view, then look down for the top view. Label each sketch with the view it shows." },
        { label: "Guided practice (12 min):", content: "Students sketch the top, front and side views of 2-3 models (Resource 6 - sketch and label), then play 'name the object' from a set of three views." },
        { label: "Check (3 min):", content: "Exit question: sketch the top view of a square pyramid and the front view of a triangular prism." },
      ],
      vocab: "view, top view, front view, side view, two-dimensional, three-dimensional, sketch, orientation",
      support: "Use a model students can physically turn; mark the front face with a sticker so the views stay consistent.",
      extension: "Add a model not already on Resource 6 and sketch and label all three of its views; from three given views, build the object with cubes.",
      assessment: "Students sketch accurate top, front and side views and recognise objects from views — links to Y2 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["geometric models", "interlocking cubes", "grid or isometric paper"],
    },
    {
      num: 5, band: "Y",
      title: "Constructing skeletal and solid models",
      outcomes: ["Y3"], duration: "35-40 min",
      syllabus: "MA3-3DS-01, MAO-WM-01 | 3DS-B: create skeletal models of prisms and pyramids; construct models from drawings of different views",
      source: "DoE Lesson 4 (adapted)",
      doeLink: "Lesson 4 -- Visualising and constructing models",
      resources: "Straws or toothpicks, connectors (plasticine/blu-tack/marshmallows), card, drawings of object views",
      li: "construct skeletal and solid models of prisms and pyramids, including from drawings of different views",
      sc: [
        "I can build a skeletal model showing the edges and vertices of a prism or pyramid.",
        "I can use the right number of edges and vertices for the solid I am building.",
        "I can construct a 3D model from drawings of its top, front and side views.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show a skeletal model of a cube made from straws. Ask how many edges and vertices it needs, linking back to the properties work in Lesson 1." },
        { label: "Model (12 min):", content: "Build a triangular-prism skeleton: count edges (9) and vertices (6), then assemble straws and connectors layer by layer. Then read a set of three views and build the matching solid." },
        { label: "Guided practice (18 min):", content: "Students build a skeletal model of a chosen prism or pyramid, checking the edge and vertex counts, then construct a second model from a given set of drawings of different views." },
        { label: "Check (4 min):", content: "Exit question: how many straws and how many connectors are needed for a square pyramid? Build or sketch it to check." },
      ],
      vocab: "skeletal model, construct, edge, vertex, face, prism, pyramid, view, base",
      support: "Build half of the skeleton with students and let them complete it; provide everyday packages as a guide to the object's properties.",
      extension: "Sketch, name, label and construct more complex skeletal models (e.g. a hexagonal prism); design a model from your own set of three views and challenge a partner to build it.",
      assessment: "Students construct accurate skeletal and solid models, including from drawings of different views — links to Y3 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["straws or toothpicks", "connectors (plasticine/marshmallows/blu-tack)", "card", "printed view drawings"],
    },
    {
      num: 6, band: "G",
      title: "Prism views and the uniform cross-section (Stage 4)",
      outcomes: ["G3"], duration: "30-40 min",
      syllabus: "MA4-VOL-C-01, MAO-WM-01 | Stage 4 VOL-A: represent prisms from different views; identify cross-sections; uniform cross-section equals base area",
      source: "Original mini lesson",
      li: "represent a prism from different 2D views and identify its uniform cross-section",
      sc: [
        "I can draw a prism from its top, side, front and back views.",
        "I can identify and illustrate the cross-section of a prism.",
        "I know a prism has a uniform cross-section that is the same as its base.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Slice a block of modelling clay (a rectangular prism) parallel to its base. Ask what shape every slice makes and whether the slices are all the same." },
        { label: "Model (12 min):", content: "Represent a triangular prism from top, side, front and back views in 2D. Then illustrate its cross-section and establish that the cross-section is uniform and equal to the base area — the idea that leads to V = Ah." },
        { label: "Guided practice (14 min):", content: "Students draw the four views of two prisms, illustrate the cross-section of each, and decide whether a given solid (e.g. a pyramid vs a prism) has a uniform cross-section, justifying their answer." },
        { label: "Check (4 min):", content: "Exit question: what is the cross-section of a hexagonal prism, and is it uniform along the whole solid? Explain." },
      ],
      vocab: "cross-section, uniform, prism, base area, top/side/front/back view, two-dimensional representation",
      support: "Use physical prisms and clay to slice and reveal the cross-section before drawing; provide a part-drawn set of views to complete.",
      extension: "Investigate which everyday solids have a uniform cross-section and which do not (e.g. a cylinder vs a cone); connect the uniform cross-section to V = Ah ready for Mini Lesson 12.",
      assessment: "Students represent prisms from multiple views and identify their uniform cross-section — links to G3 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["geometric prisms", "modelling clay to slice cross-sections", "grid paper"],
    },
    {
      num: 7, band: "R",
      title: "Decimals to thousandths",
      outcomes: ["R3"], duration: "25-30 min",
      syllabus: "MA3-RN-02, MAO-WM-01 | RN-A Decimals: express thousandths as decimals; interpret decimal notation for thousandths; place value to 3 decimal places",
      source: "DoE Lesson 6 (adapted)",
      doeLink: "Lesson 6 -- Connecting decimals to measurements of capacity",
      resources: "Resource 7 - decimal place value houses, Resource 11 - number slide, place-value chart",
      li: "read and interpret decimals to 3 decimal places, naming the place value of each digit",
      sc: [
        "I know the place-value system extends past hundredths to thousandths.",
        "I can name the place value of each digit in a number like 2.375.",
        "I can express a number of thousandths as a decimal (e.g. 7 thousandths = 0.007).",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Build the place-value pattern: tenths, hundredths, thousandths. Ask what comes after hundredths and how small a thousandth is (1/1000)." },
        { label: "Model (10 min):", content: "Using a place-value chart, read 2.375 as 2 ones, 3 tenths, 7 hundredths, 5 thousandths. Express '124 thousandths' as 0.124 and partition 0.806 by place value." },
        { label: "Guided practice (10 min):", content: "Students name the place value of digits in given 3-decimal-place numbers and write thousandths as decimals using Resource 7 - decimal place value houses." },
        { label: "Check (3 min):", content: "Exit question: in 4.609, what is the value of the 6 and the value of the 9? Write 53 thousandths as a decimal." },
      ],
      vocab: "decimal, place value, tenths, hundredths, thousandths, three decimal places, partition, digit",
      support: "Use Resource 7 (decimal place value houses) and limit to 2 decimal places first, then extend to thousandths.",
      extension: "Record place value using both decimal and fractional notation (e.g. tenths = 0.1, hundredths = 0.01, thousandths = 0.001); compare and order numbers to 3 decimal places.",
      assessment: "Students interpret decimal notation to thousandths and name digit place values — links to R3 in the SOLO Show task.",
    },
    {
      num: 8, band: "R",
      title: "Equivalent capacities",
      outcomes: ["R4"], duration: "30 min",
      syllabus: "MA3-3DS-02, MAO-WM-01 | 3DS-A Volume: recognise equivalence of whole-number and decimal capacities; interpret decimal notation for capacities",
      source: "DoE Lesson 5 (adapted)",
      doeLink: "Lesson 5 -- Equivalent capacities",
      resources: "Measuring jug, assorted containers, water, Resource 8 - capacity equivalence cards, Resource 9 - blank equivalence cards",
      li: "recognise when two capacity measurements are equal across whole-number and decimal forms",
      sc: [
        "I know 1 litre = 1000 millilitres.",
        "I can write a capacity in millilitres as an equivalent decimal in litres (e.g. 1500 mL = 1.5 L).",
        "I can match equivalent capacity measurements written in different ways.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Pour 250 mL from a measuring jug and one cup of water into the same bucket. Ask how we could write the total capacity in two different ways." },
        { label: "Model (10 min):", content: "Establish 1 L = 1000 mL. Convert 1500 mL = 1.5 L = 1.500 L and 2750 mL = 2.75 L, reading the decimal as litres. Show 0.5 L = 500 mL the other way." },
        { label: "Guided practice (12 min):", content: "Students match capacity equivalence cards (Resource 8) and complete a table converting between mL and decimal L, justifying one pair in words." },
        { label: "Check (4 min):", content: "Exit question: write 1250 mL as litres, and write 3.4 L as millilitres." },
      ],
      vocab: "capacity, millilitre (mL), litre (L), equivalent, decimal, convert, whole number",
      support: "Use a measuring jug to physically fill and pour equivalent capacities; set aside harder cards so students focus on accessible conversions first.",
      extension: "Give a written justification (numbers, words and a diagram) of why two measurements are equivalent; estimate the capacities of real items such as an aquarium or pool.",
      assessment: "Students recognise and convert equivalent whole-number and decimal capacities — links to R4 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["measuring jug", "assorted containers", "water", "capacity equivalence cards (Resource 8)"],
    },
    {
      num: 9, band: "Y",
      title: "Choosing and using units for capacity",
      outcomes: ["Y4"], duration: "30-35 min",
      syllabus: "MA3-3DS-02, MAO-WM-01 | 3DS-A Volume: select and use appropriate units to measure the capacities of a variety of containers",
      source: "DoE Lessons 6 & 7 (adapted)",
      doeLink: "Lessons 6 & 7 -- Measuring and recording capacities",
      resources: "Measuring cylinders, measuring jugs, assorted containers, water, Resource 10 & 12 - capacity recording tables",
      li: "choose a sensible unit and tool to measure the capacity of a container, and measure accurately",
      sc: [
        "I can choose mL or L to suit the size of a container.",
        "I can choose an appropriate measuring tool (cylinder or jug).",
        "I can measure a container's capacity and record it with the correct unit.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show a teaspoon, a drink bottle and a bucket. Ask which unit (mL or L) suits each, and which tool would measure it best." },
        { label: "Model (10 min):", content: "Estimate then measure the capacity of a container using a measuring cylinder, reading the scale at eye level and recording with the correct unit. Discuss when L is more sensible than mL." },
        { label: "Guided practice (16 min):", content: "In groups, students estimate then measure the capacity of 4-5 containers, choosing the unit and tool each time, and record results in the capacity recording table (Resource 10)." },
        { label: "Check (4 min):", content: "Exit question: which unit and tool would you use to measure a watering can, and why?" },
      ],
      vocab: "capacity, millilitre, litre, measuring cylinder, measuring jug, estimate, appropriate unit, scale",
      support: "Provide containers with clearly different sizes so the unit choice is obvious; pre-fill part of the recording table.",
      extension: "Estimate and research capacities of larger real-world containers (e.g. a fish tank, a backyard pool) and justify the units used.",
      assessment: "Students select appropriate units and tools and measure capacities accurately — links to Y4 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["measuring cylinders", "measuring jugs", "assorted containers", "water", "capacity recording tables"],
    },
    {
      num: 10, band: "Y",
      title: "Recording capacities to 3 decimal places",
      outcomes: ["Y5"], duration: "25-30 min",
      syllabus: "MA3-3DS-02, MAO-WM-01 | 3DS-A Volume: record measurements to 3 decimal places",
      source: "DoE Lesson 7 (adapted)",
      doeLink: "Lesson 7 -- Measuring and recording capacities to 3 decimal places",
      resources: "Graduated measuring cylinders, water, Resource 12 - capacity recording table, Resource 13 - water usage facts",
      li: "read a measuring scale and record a capacity to 3 decimal places",
      sc: [
        "I can read a graduated scale carefully at eye level.",
        "I can record a capacity in litres to 3 decimal places (e.g. 1.275 L).",
        "I can use place value to write millilitres as a 3-decimal-place capacity in litres.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show 1275 mL in a graduated cylinder. Ask how to record it in litres to 3 decimal places, linking to the thousandths work in Lesson 7 (decimals)." },
        { label: "Model (9 min):", content: "Record 1275 mL = 1.275 L and 0.806 L (806 mL), naming the place value of each decimal digit. Read a measured value off the scale and write it to 3 decimal places." },
        { label: "Guided practice (12 min):", content: "Students measure several capacities and record each to 3 decimal places in litres, and convert a column of mL readings to 3-decimal-place litres." },
        { label: "Check (3 min):", content: "Exit question: a cylinder reads 940 mL — record it in litres to 3 decimal places. Record 2.05 L in millilitres." },
      ],
      vocab: "capacity, litre, millilitre, decimal, three decimal places, place value, graduated scale",
      support: "Support recording to 2 decimal places first using Resource 7 (place value houses), then extend to thousandths.",
      extension: "Research water usage for real situations and record the figures to 3 decimal places; record place value using decimal and fractional notation.",
      assessment: "Students record capacities accurately to 3 decimal places — links to Y5 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["graduated measuring cylinders", "water", "capacity recording table"],
    },
    {
      num: 11, band: "Y",
      title: "Investigating volume by displacement",
      outcomes: ["Y6"], duration: "35-40 min",
      syllabus: "MA3-3DS-02, MAO-WM-01 | 3DS-A Volume: recognise volume by water-level change; compare volumes by marking the change in water level",
      source: "DoE Lesson 8 (adapted)",
      doeLink: "Lesson 8 -- Using displacement to investigate volume",
      resources: "Clear container, water, marker, irregular objects to submerge, measuring cylinder, Resource 14 - approximating decimal cards",
      li: "use displacement to show that objects take up space and to compare the volumes of objects",
      sc: [
        "I can show that an object takes up space by watching the water level rise.",
        "I can mark the change in water level when an object is submerged.",
        "I can compare the volumes of two or more objects from how much the water level changes.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Read or recall Mr Archimedes' Bath. Ask what happens to the water when an object is put in, and why." },
        { label: "Model (11 min):", content: "Submerge an object in a clear marked container and mark the new water level. Submerge a larger object and compare the rises — more displacement means more volume. Measure the displaced amount with a cylinder." },
        { label: "Guided practice (18 min):", content: "In groups, students submerge several irregular objects, mark and record the water-level change for each, and order the objects by volume, recording capacities to the nearest measurement." },
        { label: "Check (4 min):", content: "Exit question: two objects are dropped in; object A raises the water more than object B — which has the greater volume, and how do you know?" },
      ],
      vocab: "displacement, volume, water level, submerge, irregular, capacity, millilitre, compare",
      support: "Revisit the displacement concept with the Mr Archimedes' Bath text; support approximating capacities using benchmarks (0.25, 0.5, 0.75) with a fraction strip.",
      extension: "Compare the volume of larger objects (e.g. building blocks in an 8 L tub); calculate volume by displacement using a known ratio (e.g. 30 marbles displace 50 mL, so 60 marbles displace 100 mL).",
      assessment: "Students use displacement to show and compare volumes of irregular objects — links to Y6 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["clear container", "water", "marker", "irregular objects to submerge", "measuring cylinder"],
    },
    {
      num: 12, band: "G",
      title: "Volume of a prism: V = base area x height (Stage 4)",
      outcomes: ["G1"], duration: "35-40 min",
      syllabus: "MA4-VOL-C-01, MAO-WM-01 | Stage 4 VOL-A: develop V = base area x height (V = Ah); apply to prisms with uniform cross-sections",
      source: "Original mini lesson",
      li: "find the volume of a prism using V = base area x height (V = Ah)",
      sc: [
        "I can find the area of the base of a prism.",
        "I can multiply the base area by the height to find the volume.",
        "I can apply V = Ah to rectangular and triangular prisms with a uniform cross-section.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Recall from Mini Lesson 6 that a prism has a uniform cross-section equal to its base. Stack cubic-centimetre layers and ask how many cubes fill a 4 x 3 x 2 box." },
        { label: "Model (12 min):", content: "Develop V = base area x height: for a rectangular prism, base area 12 cm2 x height 2 cm = 24 cm3. Then a triangular prism: base area = half x base x height, then x prism length. Generalise to V = Ah." },
        { label: "Guided practice (14 min):", content: "Students calculate the volume of several rectangular and triangular prisms using V = Ah, recording units as cm3, and solve one word problem (e.g. volume of a fish tank)." },
        { label: "Check (5 min):", content: "Exit question: find the volume of a rectangular prism 5 cm x 4 cm x 3 cm, and a triangular prism with base area 10 cm2 and length 6 cm." },
      ],
      vocab: "volume, prism, base area, height, cubic centimetre (cm3), formula, uniform cross-section, V = Ah",
      support: "Provide the base area pre-calculated and a worked frame 'V = base area x height ='; use cube blocks to build the prism first.",
      extension: "Find a missing dimension given the volume and base area; compare two prisms with the same volume but different dimensions.",
      assessment: "Students apply V = Ah to find the volume of prisms — links to G1 in the SOLO Show task.",
    },
    {
      num: 13, band: "G",
      title: "Converting volume and capacity units (Stage 4)",
      outcomes: ["G2"], duration: "30-35 min",
      syllabus: "MA4-VOL-C-01, MAO-WM-01 | Stage 4 VOL-A: convert between metric units of volume and capacity; choose appropriate units",
      source: "Original mini lesson",
      li: "convert between metric units of volume and capacity and choose an appropriate unit",
      sc: [
        "I know 1 cm3 = 1 mL and 1000 mL = 1 L.",
        "I can convert between cm3, mL, L and m3 (e.g. 1 m3 = 1000 L).",
        "I can choose an appropriate unit for a given volume or capacity and justify it.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Fill a 1 cm x 1 cm x 1 cm cube space and pour in 1 mL of water. Establish the key link 1 cm3 = 1 mL." },
        { label: "Model (11 min):", content: "Build the conversion chain: 1 cm3 = 1 mL, 1000 cm3 = 1 L, 1 m3 = 1000 L = 1 kL. Convert 2500 cm3 to mL and to L; convert 3 m3 to litres. Discuss choosing units for a syringe vs a swimming pool." },
        { label: "Guided practice (12 min):", content: "Students complete a conversion table between cm3, mL, L and m3, and solve two practical problems (e.g. how many litres a 0.5 m3 tank holds)." },
        { label: "Check (4 min):", content: "Exit question: convert 1500 cm3 to litres, and state an appropriate unit for the capacity of a backyard pool." },
      ],
      vocab: "volume, capacity, cubic centimetre (cm3), cubic metre (m3), millilitre, litre, kilolitre, convert, appropriate unit",
      support: "Provide a conversion reference strip and limit to one conversion step at a time (cm3 to mL, then mL to L).",
      extension: "Solve multi-step practical problems combining V = Ah with a unit conversion (e.g. find a tank's volume in m3, then its capacity in litres).",
      assessment: "Students convert between volume and capacity units and choose appropriate units — links to G2 in the SOLO Show task.",
    },
  ],
};
