/**
 * Unit 40 — Integers, Decimals, Percentages & the Cartesian Plane (Stage 3 Year B).
 * Deliverable B. Built from units/u40/00_rubric_draft.md + 01_mapping_review.md.
 * Matches the UNIT DATA SCHEMA at the bottom of scripts/build_program_template.js.
 *
 * Compare/order decimals; integers on a number line; benchmark FDP & finding 10%; ×/÷ decimals by
 * powers of 10; the Cartesian coordinate system (4 quadrants); percentage discounts; add/subtract
 * decimals & multistep word problems; multiplying decimals with estimation; order of operations &
 * brackets. Green = Stage 4 integers, percentages and the Cartesian/linear plane.
 *
 * Program has the resource appendix merged (resource_appendix_attached: true); a standalone
 * Unit40_Resource_Appendix.docx is also emitted (Stage 5). Every resource URL verified live
 * in Stage 3 (units/u40/03_resources_staged.csv). Unit 40 ships CODE-CANONICAL (hardcoded
 * RESOURCES in solo/index.html); 04_insert.sql holds the same rows for optional DB promotion.
 *
 * Outcome -> Mini Lesson map (teaching sequence, then Stage-4 Green cards):
 *   R1->1 R2->2 R3->3 R4->4 R5->5 Y1->6 Y2->7 Y3->8 Y4->9 Y5->10 G1->11 G2->12 G3->13
 */
module.exports = {
  unit_number: "40",
  unit_title: "Integers, Decimals, Percentages & the Cartesian Plane",
  term: null,
  duration: "2-3 weeks",

  resource_appendix_attached: true,

  // Every URL verified live in Stage 3 (24 videos oEmbed-verified, worksheets curl HTTP 200);
  // see units/u40/03_resources_staged.csv.
  resources: {
    r1: [
      { type: "video", label: "Comparing and Ordering Decimals | Math with Mr. J", url: "https://www.youtube.com/watch?v=KWsLyjXKhrM" },
      { type: "video", label: "How to Order Decimals | Math with Mr. J", url: "https://www.youtube.com/watch?v=1dfedgVxA54" },
      { type: "worksheet", label: "Corbettmaths — Ordering Decimals (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/ordering-decimals-pdf.pdf" },
    ],
    r2: [
      { type: "video", label: "Integers on a Number Line — Missing Numbers | Math with Mr. J", url: "https://www.youtube.com/watch?v=lKZp-jEvGqM" },
      { type: "video", label: "How to Compare and Order Integers (Positives & Negatives) | Math with Mr. J", url: "https://www.youtube.com/watch?v=2FbafvAGhZ0" },
      { type: "worksheet", label: "Corbettmaths — Negative Numbers (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2018/11/Negative-Numbers.pdf" },
    ],
    r3: [
      { type: "video", label: "How to Find a Percent of a Number | Math with Mr. J", url: "https://www.youtube.com/watch?v=5CAncQ4TZD4" },
      { type: "video", label: "Converting Between Fractions / Decimals / Percents — Mini Course | Math with Mr. J", url: "https://www.youtube.com/watch?v=2vjbNZaFz3c" },
      { type: "worksheet", label: "Corbettmaths — Fractions / Decimals / Percentages (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/fractions-decimals-percentages-pdf.pdf" },
    ],
    r4: [
      { type: "video", label: "Multiplying and Dividing by Powers of 10 | Math with Mr. J", url: "https://www.youtube.com/watch?v=HH-yrNS80Cg" },
      { type: "video", label: "Dividing by Powers of Ten | Math with Mr. J", url: "https://www.youtube.com/watch?v=E8b5pDvt2AE" },
      { type: "worksheet", label: "Corbettmaths — Place Value (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/place-value-pdf.pdf" },
    ],
    r5: [
      { type: "video", label: "How to Plot Points on a Coordinate Plane — Positive and Negative Coordinates | Math with Mr. J", url: "https://www.youtube.com/watch?v=5NyuamsbLMo" },
      { type: "video", label: "Quadrants of the Coordinate Plane — What are the Four Quadrants? | Math with Mr. J", url: "https://www.youtube.com/watch?v=uc9hWu73Phw" },
      { type: "worksheet", label: "Corbettmaths — Coordinates (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/coordinates-pdf1.pdf" },
    ],
    y1: [
      { type: "video", label: "How to Calculate a Discount and Sale Price | Math with Mr. J", url: "https://www.youtube.com/watch?v=5qxX222sLtE" },
      { type: "video", label: "How to Calculate a Discount without a Calculator | Math with Mr. J", url: "https://www.youtube.com/watch?v=og9bDI2XJfA" },
      { type: "worksheet", label: "Corbettmaths — Percentage of an Amount (Non-Calculator) (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/percentage-of-an-amount-non-calculator-pdf1.pdf" },
    ],
    y2: [
      { type: "video", label: "Adding and Subtracting Decimals (How to) | Math with Mr. J", url: "https://www.youtube.com/watch?v=PnwLv6khwk8" },
      { type: "video", label: "How to Add and Subtract Decimals — Step-by-Step Examples | Math with Mr. J", url: "https://www.youtube.com/watch?v=Cg-_TeiaSa8" },
      { type: "worksheet", label: "Corbettmaths — Ordering Decimals (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/ordering-decimals-pdf.pdf" },
    ],
    y3: [
      { type: "video", label: "Multi-Step Problems With All Operations (Road Trip Math) | Easy Math with Mrs. Easley", url: "https://www.youtube.com/watch?v=z0LbNsZN71w" },
      { type: "worksheet", label: "Corbettmaths — Order of Operations (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/order-of-operations-pdf.pdf" },
      { type: "worksheet", label: "Corbettmaths — Place Value (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/place-value-pdf.pdf" },
    ],
    y4: [
      { type: "video", label: "Multiply a Whole Number by a Decimal | Math with Mr. J", url: "https://www.youtube.com/watch?v=tsOibhsgYoQ" },
      { type: "video", label: "How to Multiply a Whole Number and a Decimal | Math with Mr. J", url: "https://www.youtube.com/watch?v=FbZr5br9ZOg" },
      { type: "worksheet", label: "Corbettmaths — Multiplying and Dividing Decimals (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/decimals-multiplying-and-dividing.pdf" },
    ],
    y5: [
      { type: "video", label: "Order of Operations — A Step-By-Step Guide | PEMDAS | Math with Mr. J", url: "https://www.youtube.com/watch?v=x41BCrYh8Kc" },
      { type: "video", label: "Order of Operations — Parentheses / Brackets / Braces | PEMDAS | Math with Mr. J", url: "https://www.youtube.com/watch?v=u7Lack4Tmx8" },
      { type: "worksheet", label: "Corbettmaths — Order of Operations (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/order-of-operations-pdf.pdf" },
    ],
    g1: [
      { type: "video", label: "How to Add Negative Numbers (Integers) | Math with Mr. J", url: "https://www.youtube.com/watch?v=1VFj_coqKQU" },
      { type: "video", label: "Subtracting Integers Using a Number Line | Math with Mr. J", url: "https://www.youtube.com/watch?v=Dfytkh_lYME" },
      { type: "worksheet", label: "Corbettmaths — Negative Numbers (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2018/11/Negative-Numbers.pdf" },
    ],
    g2: [
      { type: "video", label: "Percent Change — A Step-By-Step Guide | Math with Mr. J", url: "https://www.youtube.com/watch?v=ZL2ILv98IZU" },
      { type: "video", label: "How to Find a Percent of a Number | Math with Mr. J", url: "https://www.youtube.com/watch?v=5CAncQ4TZD4" },
      { type: "worksheet", label: "Corbettmaths — Percentage Change (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/percentage-change-pdf.pdf" },
    ],
    g3: [
      { type: "video", label: "Plotting Points on a Coordinate Plane — All 4 Quadrants | Math with Mr. J", url: "https://www.youtube.com/watch?v=pl9nSVzRWvA" },
      { type: "video", label: "Graphing Linear Equations (using a Table of Values) | Math Help Videos", url: "https://www.youtube.com/watch?v=ct1dRi7IcQw" },
      { type: "worksheet", label: "Corbettmaths — Drawing Linear Graphs (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/drawing-linear-graphs-pdf.pdf" },
    ],
  },

  beyond_resources: [
    { type: "video", label: "How to Add Negative Numbers (Integers) | Math with Mr. J", url: "https://www.youtube.com/watch?v=1VFj_coqKQU" },
    { type: "video", label: "Percent Change — A Step-By-Step Guide | Math with Mr. J", url: "https://www.youtube.com/watch?v=ZL2ILv98IZU" },
    { type: "video", label: "Graphing Linear Equations (using a Table of Values) | Math Help Videos", url: "https://www.youtube.com/watch?v=ct1dRi7IcQw" },
    { type: "worksheet", label: "Corbettmaths — Negative Numbers (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2018/11/Negative-Numbers.pdf" },
    { type: "worksheet", label: "Corbettmaths — Drawing Linear Graphs (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/drawing-linear-graphs-pdf.pdf" },
  ],

  syllabus_strands_summary: "Represents Numbers A & B, Additive Relations B, Multiplicative Relations B, Geometric Measure A & B",
  strand_abbreviations_note: "RN = Represents numbers. AR = Additive relations. MR = Multiplicative relations. GM = Geometric measure. A/B = syllabus content group (Year A ~ Year 5; Year B ~ Year 6).",

  syllabus_outcomes: [
    { code: "MAO-WM-01", descriptor: "Develops understanding and fluency in mathematics through exploring and connecting mathematical concepts, choosing and applying mathematical techniques to solve problems, and communicating their thinking and reasoning coherently and clearly." },
    { code: "MA3-RN-01", descriptor: "Applies an understanding of place value and the role of zero to represent the properties of numbers." },
    { code: "MA3-RN-03", descriptor: "Determines percentages of quantities, and finds equivalent fractions and decimals for benchmark percentage values." },
    { code: "MA3-AR-01", descriptor: "Selects and applies appropriate strategies to solve addition and subtraction problems." },
    { code: "MA3-MR-01", descriptor: "Selects and applies appropriate strategies to solve multiplication and division problems." },
    { code: "MA3-MR-02", descriptor: "Constructs and completes number sentences involving multiplicative relations, applying the order of operations to calculations." },
    { code: "MA3-GM-01", descriptor: "Locates and describes points on a coordinate plane." },
  ],

  content_points: {
    red: {
      heading: "Decimals (RN-A), Cartesian system (GM-A) + foundational B",
      heading_short: "Red -- Foundation",
      points: [
        "Compare and order decimals to 3 dp; interpret trailing zeros; estimate decimal size (RN-A).",
        "Place negative whole numbers on a number line; negatives from subtraction (RN-B).",
        "Write common percentages as fractions and decimals; find 10% of an amount (RN-B).",
        "Use place value to multiply and divide a decimal by powers of 10 (MR-B).",
        "Grid-map vs number plane; record coordinates in all 4 quadrants (GM-A & B).",
      ],
    },
    yellow: {
      heading: "Percentages, decimal operations & order of operations (applying)",
      heading_short: "Yellow -- On-level",
      points: [
        "Estimate 10%, 25% and 50% discounts and calculate the sale price.",
        "Add and subtract decimals to 3 dp to solve word problems; justify the strategy.",
        "Solve multistep word problems requiring more than one operation.",
        "Multiply benchmark decimals by single-digit numbers; estimate the product.",
        "Use brackets and the order of operations to solve problems.",
      ],
    },
    green: {
      heading: "Extended -- Stage 4 Integers, Percentages & the Cartesian Plane",
      heading_short: "Green -- Extension",
      points: [
        "Compare, order, add and subtract positive and negative integers (MA4-INT-C-01).",
        "Find percentages of quantities; solve percentage increase and decrease problems (MA4-FRC-C-01).",
        "Plot points and linear relationships on the Cartesian plane (MA4-LIN-C-01).",
      ],
    },
  },

  working_mathematically: [
    { process: "Communicating", description: "Students read and write decimals, integers, percentages and coordinates, and explain their strategies." },
    { process: "Understanding and fluency", description: "Students compare/order decimals and integers, find 10%, multiply/divide decimals by powers of 10, and plot coordinates." },
    { process: "Reasoning", description: "Students reason about place value and trailing zeros, why subtraction can give a negative, and which operation order is needed." },
    { process: "Problem solving", description: "Students solve discount, decimal and multistep word problems, and (Stage 4) integer, percentage-change and linear-plotting problems." },
  ],

  outcomes: [
    { code: "R1", desc: "Compare and order decimals to 3 decimal places.", content_point: "RN-A: compare/order decimals to 3 dp; interpret trailing zeros; approximate decimal size; place on a number line | MA3-RN-01 | Year A", lesson_ref: "Mini Lesson 1" },
    { code: "R2", desc: "Place integers on a number line.", content_point: "RN-B: place negative whole numbers on a number line; recognise negatives can result from subtraction | MA3-RN-01 | Year B", lesson_ref: "Mini Lesson 2" },
    { code: "R3", desc: "Benchmark fractions, decimals, percentages & find 10%.", content_point: "RN-B: represent common percentages as fractions/decimals; 10% = one-tenth; find 10% of an amount | MA3-RN-03 | Year B", lesson_ref: "Mini Lesson 3" },
    { code: "R4", desc: "Multiply and divide decimals by powers of 10.", content_point: "MR-B: use place value to multiply and divide a decimal by powers of 10 | MA3-MR-01 | Year B", lesson_ref: "Mini Lesson 4" },
    { code: "R5", desc: "The Cartesian coordinate system (4 quadrants).", content_point: "GM-A & B: grid-map gives an area, the number plane an exact point; record coordinates in all 4 quadrants | MA3-GM-01 | Year A & B", lesson_ref: "Mini Lesson 5" },
    { code: "Y1", desc: "Estimate discounts and calculate sale prices.", content_point: "RN-B: estimate 10%/25%/50% discounts; calculate the sale price after a discount | MA3-RN-03 | Year B", lesson_ref: "Mini Lesson 6" },
    { code: "Y2", desc: "Add and subtract decimals to solve word problems.", content_point: "AR-B: add/subtract decimals to 3 dp in word problems; justify the strategy | MA3-AR-01 | Year B", lesson_ref: "Mini Lesson 7" },
    { code: "Y3", desc: "Solve multistep word problems.", content_point: "AR-B: solve multistep word problems requiring more than one operation | MA3-AR-01 | Year B", lesson_ref: "Mini Lesson 8" },
    { code: "Y4", desc: "Multiply decimals (mental strategies & estimation).", content_point: "MR-B: mentally multiply benchmark decimals by single-digit numbers; estimate the product | MA3-MR-01 | Year B", lesson_ref: "Mini Lesson 9" },
    { code: "Y5", desc: "Order of operations and brackets.", content_point: "MR-B: agree the order of operations; solve problems using grouping symbols | MA3-MR-01, MA3-MR-02 | Year B", lesson_ref: "Mini Lesson 10" },
    { code: "G1", desc: "Add, subtract and order integers.", content_point: "Stage 4 INT: compare/order integers; add and subtract positive and negative integers | MA4-INT-C-01 | Stage 4 (Core)", lesson_ref: "Mini Lesson 11" },
    { code: "G2", desc: "Percentages of quantities and percentage change.", content_point: "Stage 4 FRC: find percentages of quantities; solve percentage increase/decrease problems | MA4-FRC-C-01 | Stage 4 (Core)", lesson_ref: "Mini Lesson 12" },
    { code: "G3", desc: "Plot points and linear relationships on the Cartesian plane.", content_point: "Stage 4 LIN: plot points of given coordinates; plot linear relationships on the Cartesian plane | MA4-LIN-C-01 | Stage 4 (Core)", lesson_ref: "Mini Lesson 13" },
  ],

  lessons: [
    {
      num: 1, band: "R",
      title: "Comparing and ordering decimals",
      outcomes: ["R1"], duration: "25-30 min",
      syllabus: "MA3-RN-01, MAO-WM-01 | RN-A: compare/order decimals to 3 dp",
      source: "DoE Lesson 2 (adapted)",
      doeLink: "Lesson 2 -- Comparing and ordering decimals",
      resources: "Decimal number lines, place value charts",
      li: "compare and order decimals to 3 decimal places",
      sc: [
        "I can compare decimals digit by digit using place value.",
        "I can order decimals to 3 decimal places on a number line.",
        "I know a zero at the end of a decimal (e.g. 0.40) does not change its value.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Which is bigger, 0.4 or 0.39? Ask students to explain using place value." },
        { label: "Model (10 min):", content: "Line up the decimal points; compare tenths, then hundredths, then thousandths. Show 0.4 = 0.40 = 0.400. Place several decimals on a number line." },
        { label: "Guided practice (10 min):", content: "Students order sets of decimals to 3 dp and place them on a number line." },
        { label: "Check (4 min):", content: "Exit question: order 0.7, 0.07, 0.77 and 0.707 from smallest to largest." },
      ],
      vocab: "decimal, place value, tenths, hundredths, thousandths, compare, order, number line",
      support: "Use a place value chart so digits line up under the right column.",
      extension: "Insert a decimal that lies between two given decimals (e.g. between 0.4 and 0.5).",
      assessment: "Students compare and order decimals — links to R1 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["decimal number lines", "place value charts"],
    },
    {
      num: 2, band: "R",
      title: "Integers on a number line",
      outcomes: ["R2"], duration: "25 min",
      syllabus: "MA3-RN-01, MAO-WM-01 | RN-B: negatives on a number line",
      source: "DoE Lesson 1 (adapted)",
      doeLink: "Lesson 1 -- Locating and representing integers",
      resources: "Integer number lines, thermometer model",
      li: "place negative whole numbers on a number line",
      sc: [
        "I can place negative whole numbers on a number line in relation to zero.",
        "I know numbers get smaller as you move left of zero.",
        "I can explain that subtracting a bigger number from a smaller one gives a negative answer.",
      ],
      steps: [
        { label: "Activate (3 min):", content: "Show a thermometer at −3 degrees. Where is that compared to 0?" },
        { label: "Model (10 min):", content: "Draw a number line through zero; place −1, −2, −3 to the left. Show 2 − 5 = −3 by counting back past zero." },
        { label: "Guided practice (8 min):", content: "Students place negative integers on a number line and find results of subtractions that go below zero." },
        { label: "Check (4 min):", content: "Exit question: place −4 on a number line. What is 1 − 4?" },
      ],
      vocab: "integer, negative, positive, zero, number line, less than, subtraction",
      support: "Use a vertical number line (thermometer) so 'below zero' is concrete.",
      extension: "Order a set of positive and negative integers from smallest to largest.",
      assessment: "Students place integers on a number line — links to R2 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["integer number lines"],
    },
    {
      num: 3, band: "R",
      title: "Benchmark fractions, decimals, percentages & 10%",
      outcomes: ["R3"], duration: "25-30 min",
      syllabus: "MA3-RN-03, MAO-WM-01 | RN-B: benchmark FDP; find 10%",
      source: "DoE Lesson 4 (adapted)",
      doeLink: "Lesson 4 -- Connecting fractions, decimals and percentages",
      resources: "Hundred grids, FDP cards",
      li: "connect benchmark fractions, decimals and percentages and find 10% of an amount",
      sc: [
        "I can write common percentages as fractions and decimals (e.g. 50% = ½ = 0.5).",
        "I know 10% is one-tenth of 100%.",
        "I can find 10% of an amount by dividing by 10.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "What is 50% as a fraction and a decimal? What about 10%?" },
        { label: "Model (10 min):", content: "Build a benchmark table: 50% = ½ = 0.5; 25% = ¼ = 0.25; 10% = 1/10 = 0.1. Find 10% of 80 by dividing by 10 (= 8)." },
        { label: "Guided practice (10 min):", content: "Students write percentages as fractions/decimals and find 10% of amounts." },
        { label: "Check (4 min):", content: "Exit question: find 10% of 120. Write 25% as a fraction." },
      ],
      vocab: "percentage, fraction, decimal, benchmark, per cent, one-tenth, of",
      support: "Use a hundred grid so each percentage is visible.",
      extension: "Use 10% to find 20%, 30% and 5% of an amount.",
      assessment: "Students connect FDP and find 10% — links to R3 in the SOLO Show task.",
    },
    {
      num: 4, band: "R",
      title: "Multiply and divide decimals by powers of 10",
      outcomes: ["R4"], duration: "25 min",
      syllabus: "MA3-MR-01, MAO-WM-01 | MR-B: ×/÷ decimals by powers of 10",
      source: "DoE Lesson 6 (adapted)",
      doeLink: "Lesson 6 -- Multiplying and dividing decimals",
      resources: "Place value charts",
      li: "use place value to multiply and divide a decimal by powers of 10",
      sc: [
        "I know multiplying by 10 makes each digit 10 times bigger (shifts left).",
        "I know dividing by 10 makes each digit 10 times smaller (shifts right).",
        "I can multiply and divide decimals by 10, 100 and 1000.",
      ],
      steps: [
        { label: "Activate (3 min):", content: "What is 3.4 × 10? Ask students to explain what happens to the digits." },
        { label: "Model (10 min):", content: "On a place value chart, × 10 shifts digits one place left (3.4 → 34); ÷ 10 shifts one place right (3.4 → 0.34). Extend to × 100 and ÷ 100." },
        { label: "Guided practice (8 min):", content: "Students multiply and divide decimals by 10, 100 and 1000 using place value." },
        { label: "Check (4 min):", content: "Exit question: 2.5 × 100 = ? and 47 ÷ 10 = ?" },
      ],
      vocab: "place value, multiply, divide, powers of 10, shift, tenths, hundredths",
      support: "Use a place value chart and physically move the digits.",
      extension: "Multiply and divide by 1000, and explain the pattern in the number of place shifts.",
      assessment: "Students ×/÷ decimals by powers of 10 — links to R4 in the SOLO Show task.",
    },
    {
      num: 5, band: "R",
      title: "The Cartesian coordinate system",
      outcomes: ["R5"], duration: "30 min",
      syllabus: "MA3-GM-01, MAO-WM-01 | GM-A & B: grid-map vs number plane; 4 quadrants",
      source: "DoE Lesson 8 (adapted)",
      doeLink: "Lesson 8 -- The Cartesian coordinate system",
      resources: "Coordinate grids (4 quadrants), counters",
      li: "read and record coordinates of points in all four quadrants",
      sc: [
        "I know the number plane has an x-axis and a y-axis that cross at the origin (0,0).",
        "I can write a point's coordinates as (x, y), going across then up/down.",
        "I can read and plot points in all four quadrants, including negatives.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Compare a grid-map reference (an area, like B3) with a number-plane point (an exact spot, like (2,3))." },
        { label: "Model (12 min):", content: "Draw the four quadrants; mark the origin. Plot (2,3), (−2,3), (−2,−3) and (2,−3). Always go across (x) first, then up/down (y)." },
        { label: "Guided practice (10 min):", content: "Students read and plot points in all four quadrants on a coordinate grid." },
        { label: "Check (4 min):", content: "Exit question: write the coordinates of a point 3 left and 2 down from the origin." },
      ],
      vocab: "Cartesian plane, x-axis, y-axis, origin, coordinates, quadrant, ordered pair",
      support: "Provide a labelled grid and remind 'across before up'.",
      extension: "Plot points to draw a simple shape and name its vertices' coordinates.",
      assessment: "Students read and record coordinates — links to R5 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["coordinate grids", "counters"],
    },
    {
      num: 6, band: "Y",
      title: "Percentage discounts",
      outcomes: ["Y1"], duration: "30 min",
      syllabus: "MA3-RN-03, MAO-WM-01 | RN-B: estimate discounts; sale price",
      source: "DoE Lesson 5 (adapted)",
      doeLink: "Lesson 5 -- Estimating percentage discounts",
      resources: "Catalogue/price cards (AUD)",
      li: "estimate a discount and calculate the sale price of an item",
      sc: [
        "I can find 10%, 25% and 50% of a price.",
        "I can subtract the discount from the original price to get the sale price.",
        "I can estimate a discount mentally to check my answer.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "A $80 jacket is 25% off. Roughly how much will you save?" },
        { label: "Model (12 min):", content: "25% of $80 = $20, so sale price = $80 − $20 = $60. Show 50% = half, 10% = ÷10. Estimate first, then calculate." },
        { label: "Guided practice (10 min):", content: "Students calculate sale prices after 10%, 25% and 50% discounts (AUD)." },
        { label: "Check (4 min):", content: "Exit question: a $40 game is 10% off. What is the sale price?" },
      ],
      vocab: "percentage, discount, sale price, estimate, original price, per cent, AUD",
      support: "Provide the discount amount so students focus on subtracting from the price.",
      extension: "Find the discount when 20% or 75% off, using 10% and 25% as building blocks.",
      assessment: "Students calculate discounts and sale prices — links to Y1 in the SOLO Show task.",
    },
    {
      num: 7, band: "Y",
      title: "Adding and subtracting decimals",
      outcomes: ["Y2"], duration: "30 min",
      syllabus: "MA3-AR-01, MAO-WM-01 | AR-B: add/subtract decimals; justify",
      source: "DoE Lesson 3 (adapted)",
      doeLink: "Lesson 3 -- Strategies to solve addition and subtraction problems",
      resources: "Number lines, place value charts",
      li: "add and subtract decimals to 3 decimal places to solve word problems",
      sc: [
        "I can line up the decimal points to add or subtract decimals.",
        "I can solve word problems involving adding and subtracting decimals.",
        "I can explain why my strategy works.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Buy items for $3.50 and $2.75. How much altogether?" },
        { label: "Model (12 min):", content: "Line up the decimal points; add place by place ($6.25). Subtract change from $10. Model adding/subtracting on a number line, and justify the strategy." },
        { label: "Guided practice (10 min):", content: "Students solve add/subtract decimal word problems and explain their strategy." },
        { label: "Check (4 min):", content: "Exit question: 7.5 − 3.25 = ? and explain how you did it." },
      ],
      vocab: "decimal, add, subtract, line up, decimal point, strategy, justify, word problem",
      support: "Use a place value chart so the decimal points and columns line up.",
      extension: "Solve a two-step money problem mixing addition and subtraction of decimals.",
      assessment: "Students add and subtract decimals — links to Y2 in the SOLO Show task.",
    },
    {
      num: 8, band: "Y",
      title: "Multistep word problems",
      outcomes: ["Y3"], duration: "30 min",
      syllabus: "MA3-AR-01, MAO-WM-01 | AR-B: multistep word problems",
      source: "DoE Lesson 3 (adapted)",
      doeLink: "Lesson 3 -- Strategies to solve addition and subtraction problems",
      resources: "Word problem cards",
      li: "solve multistep word problems requiring more than one operation",
      sc: [
        "I can break a problem into steps and decide which operation each step needs.",
        "I can carry out the steps in order to reach the answer.",
        "I can check my answer is reasonable.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Read a 2-step problem aloud. Ask: what do we work out first?" },
        { label: "Model (12 min):", content: "Model a multistep problem: e.g. buy 3 items at $4.50, pay with $20 — first multiply (3 × 4.50 = 13.50), then subtract (20 − 13.50 = 6.50)." },
        { label: "Guided practice (10 min):", content: "Students solve multistep word problems, showing each step." },
        { label: "Check (4 min):", content: "Exit question: a 2-step problem with addition then subtraction." },
      ],
      vocab: "multistep, operation, step, multiply, add, subtract, estimate, reasonable",
      support: "Provide a step-by-step planning frame (Step 1 …, Step 2 …).",
      extension: "Write a multistep problem of your own and solve it.",
      assessment: "Students solve multistep word problems — links to Y3 in the SOLO Show task.",
    },
    {
      num: 9, band: "Y",
      title: "Multiplying decimals (mental & estimation)",
      outcomes: ["Y4"], duration: "25-30 min",
      syllabus: "MA3-MR-01, MAO-WM-01 | MR-B: multiply decimals; estimate",
      source: "DoE Lesson 6 (adapted)",
      doeLink: "Lesson 6 -- Multiplying and dividing decimals",
      resources: "Place value charts",
      li: "multiply a decimal by a single-digit number and estimate the product",
      sc: [
        "I can multiply a benchmark decimal (like 0.5 or 2.5) by a single-digit number mentally.",
        "I can estimate a decimal × whole number by rounding.",
        "I can check whether a calculator answer is the right size.",
      ],
      steps: [
        { label: "Activate (3 min):", content: "What is 0.5 × 6? Ask students to explain (half of 6)." },
        { label: "Model (12 min):", content: "0.5 × 6 = 3; 2.5 × 4 = 10. Estimate 3.8 × 5 by rounding to 4 × 5 = 20, then compare with the exact 19.0." },
        { label: "Guided practice (10 min):", content: "Students multiply benchmark decimals by single-digit numbers and estimate products." },
        { label: "Check (4 min):", content: "Exit question: estimate 4.2 × 3, then work out the exact answer." },
      ],
      vocab: "decimal, multiply, product, estimate, round, benchmark, magnitude",
      support: "Start with 0.5 (half) and 0.25 (quarter) of single-digit numbers.",
      extension: "Multiply a 2-decimal-place number by a single digit and estimate first.",
      assessment: "Students multiply decimals and estimate — links to Y4 in the SOLO Show task.",
    },
    {
      num: 10, band: "Y",
      title: "Order of operations and brackets",
      outcomes: ["Y5"], duration: "30 min",
      syllabus: "MA3-MR-01, MA3-MR-02, MAO-WM-01 | MR-B: order of operations; grouping symbols",
      source: "DoE Lesson 7 (adapted)",
      doeLink: "Lesson 7 -- Brackets and the order of operations",
      resources: "Number sentence cards",
      li: "use brackets and the order of operations to solve number problems",
      sc: [
        "I know we agree on an order so everyone gets the same answer.",
        "I can do brackets first, then multiplication/division, then addition/subtraction.",
        "I can solve problems that use grouping symbols.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Work out 2 + 3 × 4 two different ways. Why do we need an agreed order?" },
        { label: "Model (12 min):", content: "Order of operations: brackets, then × and ÷, then + and −. So 2 + 3 × 4 = 14, but (2 + 3) × 4 = 20. Brackets change the answer." },
        { label: "Guided practice (10 min):", content: "Students evaluate number sentences with and without brackets." },
        { label: "Check (4 min):", content: "Exit question: work out 10 − (2 + 3) × 1 and 20 ÷ (5 − 1)." },
      ],
      vocab: "order of operations, brackets, grouping symbols, multiply, divide, add, subtract",
      support: "Provide the operation order as a checklist to follow.",
      extension: "Place brackets in a number sentence to make it equal a given target.",
      assessment: "Students apply the order of operations — links to Y5 in the SOLO Show task.",
    },
    {
      num: 11, band: "G",
      title: "Adding, subtracting and ordering integers",
      outcomes: ["G1"], duration: "30 min",
      syllabus: "MA4-INT-C-01, MAO-WM-01 | Stage 4: compare/order/add/subtract integers",
      source: "Original mini lesson (Stage 4 extension)",
      li: "compare, order, add and subtract positive and negative integers",
      sc: [
        "I can compare and order integers using < and >.",
        "I can add a negative integer (move left on the number line).",
        "I can subtract to cross zero into negative numbers.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Which is greater, −5 or −2? Use a number line to decide." },
        { label: "Model (12 min):", content: "On a number line: 3 + (−5) = −2 (move left 5); −1 − 3 = −4. Order a set like −4, 2, −1, 3." },
        { label: "Guided practice (10 min):", content: "Students compare, order, add and subtract positive and negative integers." },
        { label: "Check (4 min):", content: "Exit question: work out −3 + 5 and 2 − 6." },
      ],
      vocab: "integer, positive, negative, less than, greater than, add, subtract, number line",
      support: "Use a number line for every calculation to make direction concrete.",
      extension: "Solve a real-life integer problem (temperature change or money owed).",
      assessment: "Students work with integers — extends R2.",
    },
    {
      num: 12, band: "G",
      title: "Percentages of quantities and percentage change",
      outcomes: ["G2"], duration: "30 min",
      syllabus: "MA4-FRC-C-01, MAO-WM-01 | Stage 4: percentages of quantities; % change",
      source: "Original mini lesson (Stage 4 extension)",
      li: "find a percentage of a quantity and work out a percentage increase or decrease",
      sc: [
        "I can find any percentage of a quantity (e.g. 15% of 60).",
        "I can increase or decrease a quantity by a percentage.",
        "I can work out the percentage change between two amounts.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Find 15% of 60 by combining 10% (6) and 5% (3)." },
        { label: "Model (12 min):", content: "15% of 60 = 9. Increase $50 by 20%: 20% of 50 = 10, so $60. Decrease by a percentage similarly." },
        { label: "Guided practice (10 min):", content: "Students find percentages of quantities and solve percentage increase/decrease problems." },
        { label: "Check (4 min):", content: "Exit question: increase 80 by 25%." },
      ],
      vocab: "percentage, quantity, of, increase, decrease, percentage change, per cent",
      support: "Build any percentage from 10%, 5% and 1% chunks.",
      extension: "Find the percentage change when a price rises from $40 to $50.",
      assessment: "Students find percentages of quantities and change — extends R3/Y1.",
    },
    {
      num: 13, band: "G",
      title: "Points and linear relationships on the Cartesian plane",
      outcomes: ["G3"], duration: "30 min",
      syllabus: "MA4-LIN-C-01, MAO-WM-01 | Stage 4: plot points; plot linear relationships",
      source: "Original mini lesson (Stage 4 extension)",
      li: "plot points and a simple linear relationship on the Cartesian plane",
      sc: [
        "I can plot points of given coordinates in all four quadrants.",
        "I can complete a table of values for a simple rule (e.g. y = x + 2).",
        "I can plot the points from the table and join them to make a straight line.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Plot (1,3), (2,4), (3,5). What do you notice about the points?" },
        { label: "Model (12 min):", content: "For y = x + 2, build a table: x = 0,1,2,3 → y = 2,3,4,5. Plot the points; they line up — join them into a straight line." },
        { label: "Guided practice (10 min):", content: "Students complete a table of values for a simple rule and plot the line." },
        { label: "Check (4 min):", content: "Exit question: complete the table for y = 2x and plot the points." },
      ],
      vocab: "Cartesian plane, coordinates, table of values, rule, linear, straight line, plot",
      support: "Provide the table partly completed so students plot the points.",
      extension: "Find the rule that produces a given straight line of points.",
      assessment: "Students plot points and a linear relationship — extends R5.",
    },
  ],
};
