-- Seed SOLO Units 26 & 27 student-facing resources into public.resources
-- Mirrors the inline RESOURCES object in solo/index.html (units 24/25 already seeded the same way).
-- Idempotent: clears existing GLOBAL rows for these two units first, then re-inserts.

delete from public.resources where unit_id in ('u26','u27') and scope = 'global';

insert into public.resources (unit_id, outcome_id, type, label, url, scope) values
  ('u26','r1','video','Rounding Numbers | Number and Place Value | Year 5','https://www.youtube.com/watch?v=0LWnthKBypE','global'),
  ('u26','r1','video','Year 6 Number and Place Value — Rounding','https://www.youtube.com/watch?v=_B5duVnWkGQ','global'),
  ('u26','r1','worksheet','Corbettmaths Primary — Rounding Practice Questions (PDF)','https://corbettmathsprimary.com/wp-content/uploads/2018/07/rounding-pdf.pdf','global'),
  ('u26','r1','worksheet','Corbettmaths — Rounding to Decimal Places (PDF)','https://corbettmaths.com/wp-content/uploads/2019/01/Rounding-decimal-places-pdf.pdf','global'),
  ('u26','r2','video','Place Value to the Billions — Elementary Math','https://www.youtube.com/watch?v=Gx3V2nLXfsA','global'),
  ('u26','r2','video','Place Values Chart Up to Millions','https://www.youtube.com/watch?v=1gpAEQOQFkw','global'),
  ('u26','r2','worksheet','Corbettmaths — Place Value Worksheet (PDF)','https://corbettmaths.com/wp-content/uploads/2013/02/place-value-pdf1.pdf','global'),
  ('u26','r3','video','5th Grade Math 3.1 — Thousandths and Place Value','https://www.youtube.com/watch?v=U2mh1LcnwLU','global'),
  ('u26','r3','video','Decimal Place Value — Grade 5','https://www.youtube.com/watch?v=u0mREOY0xso','global'),
  ('u26','r3','worksheet','Corbettmaths — Place Value (Decimals) Worksheet (PDF)','https://corbettmaths.com/wp-content/uploads/2019/10/Place-value.pdf','global'),
  ('u26','r4','video','Comparing Decimals | Math with Mr. J','https://www.youtube.com/watch?v=nhLZcvfdgqs','global'),
  ('u26','r4','video','Ordering Decimals to the Thousandths Place — 5th Grade','https://www.youtube.com/watch?v=g18JRnyAGPI','global'),
  ('u26','r4','worksheet','Corbettmaths — Ordering Decimals (PDF)','https://corbettmaths.com/wp-content/uploads/2022/11/Ordering-Decimals.pdf','global'),
  ('u26','r5','video','Trailing Zeros, Decimals, and Place Value — Why Can I Drop a Zero?','https://www.youtube.com/watch?v=g8rqA_TfCjQ','global'),
  ('u26','r5','worksheet','Corbettmaths — Place Value Operations (PDF)','https://corbettmaths.com/wp-content/uploads/2013/02/place-value-operations-pdf.pdf','global'),
  ('u26','r8','video','Locate Decimals on a Number Line','https://www.youtube.com/watch?v=WcaVC9RCfrM','global'),
  ('u26','r8','worksheet','Corbettmaths — Ordering Decimals (PDF)','https://corbettmaths.com/wp-content/uploads/2022/11/Ordering-Decimals.pdf','global'),
  ('u26','r6','video','Kilometres to Metres with Decimals','https://www.youtube.com/watch?v=SgpkUueyV1M','global'),
  ('u26','r6','video','Converting Metres to Kilometres — Matholia','https://www.youtube.com/watch?v=cPtTd8lIxYs','global'),
  ('u26','r6','worksheet','Corbettmaths — Metric Units Conversions (PDF)','https://corbettmaths.com/wp-content/uploads/2020/05/Metric-Units.pdf','global'),
  ('u26','r9','video','How to Convert Kilograms to Grams and Back','https://www.youtube.com/watch?v=TjyqS2L6K7w','global'),
  ('u26','r9','worksheet','Corbettmaths — Metric Units Conversions (PDF)','https://corbettmaths.com/wp-content/uploads/2020/05/Metric-Units.pdf','global'),
  ('u26','y1','video','Adding and Subtracting Decimals | Math with Mr. J','https://www.youtube.com/watch?v=PnwLv6khwk8','global'),
  ('u26','y1','video','Adding and Subtracting Decimals Word Problems — 5th Grade','https://www.youtube.com/watch?v=v5DnwsFNRdU','global'),
  ('u26','y1','worksheet','Corbettmaths Primary — Adding and Subtracting Decimals (PDF)','https://corbettmathsprimary.com/wp-content/uploads/2018/07/adding-decimals-pdf.pdf','global'),
  ('u26','y1','worksheet','Corbettmaths — Decimals Addition and Subtraction (PDF)','https://corbettmaths.com/wp-content/uploads/2013/02/decimals-addition-subtraction-pdf.pdf','global'),
  ('u26','y2','video','BitMaths — Mental Strategies to Calculate Percentage Discount','https://www.youtube.com/watch?v=mghmKBNO9HM','global'),
  ('u26','y2','video','Grade 6: Calculating Discounts and Sale Prices','https://www.youtube.com/watch?v=qu6hA8dHQ1Q','global'),
  ('u26','y2','worksheet','Corbettmaths — Percentage of an Amount Exam Questions (PDF)','https://corbettmaths.com/wp-content/uploads/2013/02/percentage-of-an-amount-non-calculator-pdf1.pdf','global'),
  ('u26','y3','video','Year 6: Use Negative Numbers in Context','https://www.youtube.com/watch?v=hpIiGvcWyzA','global'),
  ('u26','y3','video','Negative Numbers in Real Life — Temperature and Elevation','https://www.youtube.com/watch?v=qKOojMSCkTA','global'),
  ('u26','y3','video','Negative Numbers Video Lessons for Year 5','https://www.youtube.com/watch?v=1W3LHcHRhd4','global'),
  ('u26','y3','worksheet','Corbettmaths — Negatives: Addition and Subtraction (PDF)','https://corbettmaths.com/wp-content/uploads/2020/05/Negatives-addition-and-subtraction.pdf','global'),
  ('u26','y3','worksheet','Corbettmaths — Arithmetic with Negatives Exam Questions (PDF)','https://corbettmaths.com/wp-content/uploads/2013/02/arithmetic-with-negatives-pdf.pdf','global'),
  ('u26','g1','video','Percent of Change | Percent Increase and Decrease | Math with Mr. J','https://www.youtube.com/watch?v=jAcDJDjQk2g','global'),
  ('u26','g1','video','Percent of Change — Grade 6','https://www.youtube.com/watch?v=x6--MJGKIXU','global'),
  ('u26','g1','worksheet','Corbettmaths — Increasing and Decreasing by a Percentage (PDF)','https://corbettmaths.com/wp-content/uploads/2018/11/Increasing-by-a-Percentage-pdf.pdf','global'),
  ('u26','g2','video','Percentage Changes Without a Calculator — Percentage Profit','https://www.youtube.com/watch?v=aH7d2QfnAmM','global'),
  ('u26','g2','video','Cost Price, Selling Price, Profit and Loss — Grade 5','https://www.youtube.com/watch?v=woosa3Gla44','global'),
  ('u26','g2','worksheet','Corbettmaths — Percentage Change (includes Profit and Loss) (PDF)','https://corbettmaths.com/wp-content/uploads/2018/10/Percentage-Change-pdf.pdf','global'),
  ('u26','g3','video','Year 6 Percentages — Everything You Need to Know','https://www.youtube.com/watch?v=WHvntqMKmYc','global'),
  ('u26','g3','video','Finding a Percent of a Number | Calculating Percentages','https://www.youtube.com/watch?v=AL0-0f9azNo','global'),
  ('u26','g3','worksheet','Corbettmaths — Percentage of an Amount Non-Calculator (PDF)','https://corbettmaths.com/wp-content/uploads/2018/11/Percentages-of-amounts-234-pdf.pdf','global'),
  ('u26','g3','worksheet','Corbettmaths — Percentage of an Amount Calculator (PDF)','https://corbettmaths.com/wp-content/uploads/2013/02/percentages-calc-pdf.pdf','global'),
  ('u26','g4','video','Percent Increase | Percent of Change | Math with Mr. J','https://www.youtube.com/watch?v=qiTxhi_ESQs','global'),
  ('u26','g4','video','Calculating Percent Decrease | Percent Change | Math with Mr. J','https://www.youtube.com/watch?v=kS_YxXf6gNA','global'),
  ('u26','g4','worksheet','Corbettmaths — Percentage Change Textbook Questions (PDF)','https://corbettmaths.com/wp-content/uploads/2020/03/Percentage-Change-Text.pdf','global'),
  ('u26','g5','video','Solving Percent Problems Without a Calculator | Math with Mr. J','https://www.youtube.com/watch?v=IkACdHCLn8Q','global'),
  ('u26','g5','video','What is the Unitary Method — Class 6','https://www.youtube.com/watch?v=ypUSWmgVm2w','global'),
  ('u26','g5','worksheet','Corbettmaths — Unitary Method (PDF)','https://corbettmaths.com/wp-content/uploads/2018/11/Unitary-Method-pdf.pdf','global'),
  ('u26','g6','video','GST — How to Calculate and Add It On (Australian context)','https://www.youtube.com/watch?v=cy7VDmSIc6w','global'),
  ('u26','g6','video','Understanding GST in Australia — Simple Steps to Calculate GST','https://www.youtube.com/watch?v=jsiMI4FHArQ','global'),
  ('u26','g6','worksheet','Corbettmaths — Percentage Change (Profit and Loss calculations) (PDF)','https://corbettmaths.com/wp-content/uploads/2013/02/percentage-change-pdf.pdf','global'),
  ('u26','r7','video','Writing Decimals in Expanded Form | Math with Mr. J','https://www.youtube.com/watch?v=_YYj9mhgZ5c','global'),
  ('u26','r7','video','Partition Decimals into Tenths and Hundredths','https://www.youtube.com/watch?v=uHuh7mcNssM','global'),
  ('u26','r7','worksheet','Corbettmaths — Place Value (Decimals) Worksheet (PDF)','https://corbettmaths.com/wp-content/uploads/2019/10/Place-value.pdf','global'),
  ('u26','y4','video','Estimating Decimal Sums | Math with Mr. J','https://www.youtube.com/watch?v=x05LHZJNKQ0','global'),
  ('u26','y4','video','Adding and Subtracting Decimals — Step-By-Step Review | Math with Mr. J','https://www.youtube.com/watch?v=9rBWUU1vx2o','global'),
  ('u26','y4','worksheet','Corbettmaths — Decimals Addition and Subtraction (PDF)','https://corbettmaths.com/wp-content/uploads/2013/02/decimals-addition-subtraction-pdf.pdf','global'),
  ('u26','y5','video','Metres and Centimetres as Decimals | Periwinkle','https://www.youtube.com/watch?v=HlelrhW6CHM','global'),
  ('u26','y5','video','Decimals in Measuring Units | Grade 5 Math','https://www.youtube.com/watch?v=HOeUcapcNmE','global'),
  ('u26','y5','video','Measuring Lengths — Decimal Notation and Mixed Numbers','https://www.youtube.com/watch?v=FH-HTPFCGdY','global'),
  ('u26','y5','worksheet','Corbettmaths — Metric Units (PDF)','https://corbettmaths.com/wp-content/uploads/2013/02/metric-units-pdf.pdf','global'),
  ('u27','r1','video','2-Digit by 2-Digit Multiplication | Math with Mr. J','https://www.youtube.com/watch?v=PZjIT9CH6bM','global'),
  ('u27','r1','video','Box Method Multiplication | 2-Digits × 2-Digits | Math with Mr. J','https://www.youtube.com/watch?v=n3q3XzzIGSY','global'),
  ('u27','r1','worksheet','Corbettmaths — Multiplication 1 (PDF)','https://corbettmaths.com/wp-content/uploads/2018/01/multiplication-1-pdf.pdf','global'),
  ('u27','r2','video','Multiplication: A Step-By-Step Review | Math with Mr. J','https://www.youtube.com/watch?v=g5TmDrXeiR8','global'),
  ('u27','r2','video','Grade 5 Math Lesson | Multiplication and Division','https://www.youtube.com/watch?v=25rbGL-Tqho','global'),
  ('u27','r3','video','Grade 5 — Multiples, Factors, Primes and Composites | WorksheetCloud','https://www.youtube.com/watch?v=HVBTiNeLhPE','global'),
  ('u27','r3','video','Prime and Composite Numbers','https://www.youtube.com/watch?v=44jD-K2leEM','global'),
  ('u27','r3','video','Mini Maths Lesson: Year 6 — Prime, Composite and Square Numbers','https://www.youtube.com/watch?v=b-XavTWnTMY','global'),
  ('u27','r3','worksheet','Corbettmaths — Multiples, Factors and Primes (PDF)','https://corbettmaths.com/wp-content/uploads/2013/02/multiples-factors-primes-pdf.pdf','global'),
  ('u27','r4','video','Year 5: Recognising Factors, Multiples and Prime Numbers','https://www.youtube.com/watch?v=3KxEwpX6Ags','global'),
  ('u27','r4','worksheet','Corbettmaths — Factors, Multiples and Primes (PDF)','https://corbettmaths.com/wp-content/uploads/2015/03/factors-multiples-primes.pdf','global'),
  ('u27','r5','video','Box Method Multiplication | 3-Digits × 2-Digits | Math with Mr. J','https://www.youtube.com/watch?v=zfYG9lzMmUo','global'),
  ('u27','r5','video','2-Digit Multiplication: A Step-By-Step Review | Math with Mr. J','https://www.youtube.com/watch?v=yiZ3r9T_OJs','global'),
  ('u27','r5','worksheet','Corbettmaths — Multiplication 2 (PDF)','https://corbettmaths.com/wp-content/uploads/2018/01/multiplication-2-pdf.pdf','global'),
  ('u27','y1','video','Division Strategies | Multiplication and Division | Year 5','https://www.youtube.com/watch?v=aTtuFEZVKaM','global'),
  ('u27','y1','video','Learn 5th Grade Math — Long Division Word Problem','https://www.youtube.com/watch?v=xD5Gl-mWRnk','global'),
  ('u27','y1','worksheet','Corbettmaths — Division (PDF)','https://corbettmaths.com/wp-content/uploads/2018/01/division-pdf.pdf','global'),
  ('u27','y2','video','Interpreting Remainders in Division Word Problems','https://www.youtube.com/watch?v=0dPQEKjTFjg','global'),
  ('u27','y2','video','5th Grade Math 2.7 — Interpret the Remainder in Division','https://www.youtube.com/watch?v=FkRmFMwYcTA','global'),
  ('u27','y2','worksheet','Corbettmaths — Division Remainders (PDF)','https://corbettmaths.com/wp-content/uploads/2018/11/Division-Remainders-pdf.pdf','global'),
  ('u27','y3','video','Order of Operations (BODMAS) | Year 5 and 6 Home Learning','https://www.youtube.com/watch?v=VY-Da9ZmFFs','global'),
  ('u27','y3','video','Order of Operations | PEMDAS | 5th Grade Math','https://www.youtube.com/watch?v=OdFXImly2-I','global'),
  ('u27','y3','worksheet','Corbettmaths — Order of Operations Exercise (PDF)','https://corbettmaths.com/wp-content/uploads/2018/11/Order-of-Operations-Exercise-211-pdf.pdf','global'),
  ('u27','y3','worksheet','Corbettmaths — Order of Operations (PDF)','https://corbettmaths.com/wp-content/uploads/2013/02/order-of-operations-pdf.pdf','global'),
  ('u27','y4','video','Inverse Operations — Multiplication and Division | The Maths Guy','https://www.youtube.com/watch?v=RsR8zwWj_Bw','global'),
  ('u27','y4','video','Solve Missing Number Problems for Multiplication and Division','https://www.youtube.com/watch?v=M5upWuCp4KA','global'),
  ('u27','y4','worksheet','Corbettmaths — Division Exam Style Questions (PDF)','https://corbettmaths.com/wp-content/uploads/2013/02/division-pdf1.pdf','global'),
  ('u27','y5','video','How to Multiply and Divide Whole Numbers | Math with Mr. J','https://www.youtube.com/watch?v=gmo5BTdBbmE','global'),
  ('u27','y5','video','Multiplication Strategies — 6 Methods','https://www.youtube.com/watch?v=Ram-TykPgl8','global'),
  ('u27','y6','video','Fractions as Division | MightyOwl Math | 5th Grade','https://www.youtube.com/watch?v=gXotbzp5D0M','global'),
  ('u27','y6','video','Numerator and Denominator of a Fraction | Khan Academy','https://www.youtube.com/watch?v=3XOt1fjWKi8','global'),
  ('u27','g1','video','Year 7 Directed Numbers — All Four Operations','https://www.youtube.com/watch?v=4XC8QqgGWJ0','global'),
  ('u27','g1','video','Multiplying Negative Numbers — Corbettmaths','https://www.youtube.com/watch?v=ElAvJfpGD0w','global'),
  ('u27','g1','video','Directed Numbers | Multiplication and Division','https://www.youtube.com/watch?v=NUqAsCgdArM','global'),
  ('u27','g1','worksheet','Corbettmaths — Negative Numbers: Multiplication and Division (PDF)','https://corbettmaths.com/wp-content/uploads/2018/11/Negatives-multiplication-and-division-pdf.pdf','global'),
  ('u27','g2','video','Order of Operations using BODMAS','https://www.youtube.com/watch?v=-ppkSPdMs5M','global'),
  ('u27','g2','video','How To Use BODMAS for Order of Operations','https://www.youtube.com/watch?v=nHXT8am9X0o','global'),
  ('u27','g2','worksheet','Corbettmaths — Order of Operations (PDF)','https://corbettmaths.com/wp-content/uploads/2013/02/order-of-operations-pdf.pdf','global'),
  ('u27','g2','worksheet','Corbettmaths — Arithmetic with Negatives Exam Questions (PDF)','https://corbettmaths.com/wp-content/uploads/2013/02/arithmetic-with-negatives-pdf.pdf','global'),
  ('u27','g3','video','GRADE 7 MATH — Introduction to Algebra: Algebraic Expressions','https://www.youtube.com/watch?v=A7cB5iglREI','global'),
  ('u27','g3','video','Forming Algebraic Expressions — Corbettmaths','https://www.youtube.com/watch?v=ZIv-ZCRzS80','global'),
  ('u27','g3','video','Adding and Subtracting Algebraic Expressions — with Pronumerals','https://www.youtube.com/watch?v=0keMdSQvAKQ','global'),
  ('u27','g3','worksheet','Corbettmaths — Substitution (PDF)','https://corbettmaths.com/wp-content/uploads/2013/02/substitution-pdf2.pdf','global'),
  ('u27','g4','video','Substitution into Expressions — Corbettmaths','https://www.youtube.com/watch?v=ZkC2FX5TOJ8','global'),
  ('u27','g4','video','Substitution into Expressions (part 2) — Corbettmaths','https://www.youtube.com/watch?v=28DkE4vMN6o','global'),
  ('u27','g4','worksheet','Corbettmaths — Substitution (PDF)','https://corbettmaths.com/wp-content/uploads/2013/02/substitution-pdf2.pdf','global'),
  ('u27','g5','video','Simplifying Algebraic Expressions — Combining Like Terms | Math with Mr. J','https://www.youtube.com/watch?v=1MmhAq-XVN0','global'),
  ('u27','g5','video','Year 7 Maths — Collecting Like Terms','https://www.youtube.com/watch?v=dxn2hdxejAo','global'),
  ('u27','g5','video','Collecting Like Terms — Corbettmaths','https://www.youtube.com/watch?v=zxJNJMDj2Ec','global'),
  ('u27','g5','worksheet','Corbettmaths — Collecting Like Terms (PDF)','https://corbettmaths.com/wp-content/uploads/2013/02/collecting-like-terms-pdf3.pdf','global'),
  ('u27','g6','video','How to Simplify Algebraic Expressions | Grade 7 Math','https://www.youtube.com/watch?v=BqOf_1PI_lo','global'),
  ('u27','g6','video','C1 Simplifying Expressions — Corbettmaths','https://www.youtube.com/watch?v=0Nc22d2mdm8','global'),
  ('u27','g6','worksheet','Corbettmaths — Expanding Brackets (PDF)','https://corbettmaths.com/wp-content/uploads/2019/10/Expanding-Brackets-pdf.pdf','global'),
  ('u27','g6','worksheet','Corbettmaths — Expanding Brackets (Further) (PDF)','https://corbettmaths.com/wp-content/uploads/2013/02/expanding-brackets-pdf1.pdf','global');
