/**
 * Unit 28 — Position & Chance (Stage 3 Year B) — teacher program data.
 * Deliverable B. Built from the approved Stage 0 rubric
 * (SOLO Units/u28/00_rubric_draft.md) and the same syllabus mapping that
 * drives the in-app SOLO content. Matches the UNIT DATA SCHEMA at the
 * bottom of scripts/build_program_template.js.
 *
 * Outcome → Mini Lesson map (lessons run in teaching order: Position
 * cluster first, then Chance cluster):
 *   R1→1  Y1→2  Y2→3  Y3→4  G1→5  R2→6  R3→7  Y4→8  Y5→9  Y6→10  G2→11  G3→12
 */
module.exports = {
  unit_number: "28",
  unit_title: "Position & Chance",
  term: null,                      // left blank — confirm term placement with Nicholas
  duration: "2-3 weeks",

  syllabus_strands_summary: "Geometric Measure (Position) A & B and Chance A & B, extended with Stage 4 Linear Relationships A and Probability A",
  strand_abbreviations_note: "GM = Geometric Measure (Position). CHAN = Chance. LIN = Linear Relationships (Stage 4). PRO = Probability (Stage 4). A/B = syllabus content groups (A consolidated as Year A / prior learning, B taught as Year B / home content).",

  syllabus_outcomes: [
    { code: "MAO-WM-01", descriptor: "Develops understanding and fluency in mathematics through exploring and connecting mathematical concepts, choosing and applying mathematical techniques to solve problems, and communicating their thinking and reasoning coherently and clearly." },
    { code: "MA3-GM-01", descriptor: "Locates and describes points on the Cartesian plane (number plane), using all four quadrants and ordered coordinate pairs." },
    { code: "MA3-CHAN-01", descriptor: "Conducts chance experiments, lists and records outcomes, and represents the probabilities of those outcomes using fractions." },
    { code: "MA4-LIN-C-01", descriptor: "Stage 4 (group A): plots and recognises linear relationships, moving between a rule, a table of values, coordinate pairs and a line on the Cartesian plane." },
    { code: "MA4-PRO-C-01", descriptor: "Stage 4 (group A): lists the sample space and calculates probabilities of single-step chance experiments, and compares theoretical with observed probabilities." },
  ],

  content_points: {
    red: {
      heading: "Position A & Chance A (Stage 3 — Year A consolidation)",
      heading_short: "Red -- Consolidation",
      points: [
        "Identify that the coordinate system numbers the lines, not the spaces, and that the axes meet at the origin (0, 0).",
        "Plot, label and read points in the first quadrant, naming the horizontal position before the vertical.",
        "Recognise that outcomes are equally likely when each has the same chance of occurring.",
        "Represent the probabilities of outcomes of chance experiments using fractions.",
      ],
    },
    yellow: {
      heading: "Position B & Chance B (Stage 3 — Year B home content)",
      heading_short: "Yellow -- On-level",
      points: [
        "Plot, label and read points in all four quadrants of the number plane.",
        "Describe how coordinates change when a point is translated across an axis.",
        "Describe how coordinates change when a point is reflected across an axis.",
        "Create random generators to follow set probabilities, using benchmark fractions, decimals and percentages.",
        "Assign probabilities (fractions, denominators of 2-10) to outcomes that are not equally likely.",
        "Compare expected and observed frequencies over small and large numbers of trials, and sample with replacement.",
      ],
    },
    green: {
      heading: "Extended -- Stage 4 group A content",
      heading_short: "Green -- Extension",
      points: [
        "Plot points with non-whole-number coordinates, and recognise a linear relationship across a rule, table, coordinate pairs and graph (MA4-LIN-C-01).",
        "List the sample space and express P(event) = favourable ÷ total on the 0-1 scale, with all probabilities summing to 1 (MA4-PRO-C-01).",
        "Distinguish theoretical (expected) probability from observed probability (relative frequency) using repeated trials and a random number generator (MA4-PRO-C-01).",
      ],
    },
  },

  working_mathematically: [
    { process: "Communicating", description: "Students describe positions using coordinate language (across before up), and describe chance using the language of equally likely, fractions and the 0-1 scale." },
    { process: "Understanding and fluency", description: "Students fluently plot and read coordinates in four quadrants and assign probabilities as fractions to both equally likely and unequal outcomes." },
    { process: "Reasoning", description: "Students justify how coordinates change under translation and reflection, and explain why observed results vary from expected results, especially with few trials." },
    { process: "Problem solving", description: "Students design random generators to meet set probabilities, run chance experiments, and compare expected with observed frequencies." },
  ],

  outcomes: [
    { code: "R1", desc: "Plot and label points from coordinates in the first quadrant, and read the coordinates of given points.", content_point: "GM-A Position: lines numbered not spaces; origin (0, 0); plot/label and read points in the first quadrant, horizontal position first | MA3-GM-01", lesson_ref: "Mini Lesson 1" },
    { code: "R2", desc: "Recognise when the outcomes of a chance experiment are equally likely.", content_point: "CHAN-A: recognise that outcomes are equally likely when each has the same chance of occurring | MA3-CHAN-01", lesson_ref: "Mini Lesson 6", pairing_note: "Suggested: pair with R3" },
    { code: "R3", desc: "Represent the probability of an outcome of a chance experiment as a fraction.", content_point: "CHAN-A: represent probabilities of outcomes of chance experiments using fractions | MA3-CHAN-01", lesson_ref: "Mini Lesson 7", pairing_note: "Suggested: pair with R2" },
    { code: "Y1", desc: "Plot, label and read points in all four quadrants of the number plane.", content_point: "GM-B Position: plot/label and read points in all 4 quadrants | MA3-GM-01", lesson_ref: "Mini Lesson 2" },
    { code: "Y2", desc: "Describe how a point's coordinates change when it is translated across an axis.", content_point: "GM-B Position: describe coordinate changes when a point is translated across an axis | MA3-GM-01", lesson_ref: "Mini Lesson 3", pairing_note: "Suggested: pair with Y3" },
    { code: "Y3", desc: "Describe how a point's coordinates change when it is reflected across an axis.", content_point: "GM-B Position: describe coordinate changes when a point is reflected across an axis | MA3-GM-01", lesson_ref: "Mini Lesson 4", pairing_note: "Suggested: pair with Y2" },
    { code: "Y4", desc: "Create random generators to follow set probabilities, and assign probabilities using fractions, decimals and percentages.", content_point: "CHAN-B: create random generators to set probabilities/proportions; benchmark fractions, decimals and percentages | MA3-CHAN-01", lesson_ref: "Mini Lesson 8" },
    { code: "Y5", desc: "Assign probabilities as fractions to outcomes that are not equally likely.", content_point: "CHAN-B: record outcomes not equally likely and assign probabilities as fractions (denominators 2, 3, 4, 5, 6, 8, 10) | MA3-CHAN-01", lesson_ref: "Mini Lesson 9" },
    { code: "Y6", desc: "Compare expected and observed frequencies over small and large numbers of trials, and sample with replacement.", content_point: "CHAN-B: compare expected with observed frequencies (small/large trials, digital simulators); sampling with replacement | MA3-CHAN-01", lesson_ref: "Mini Lesson 10" },
    { code: "G1", desc: "Plot points with non-whole coordinates and recognise linear relationships across rules, tables, coordinate pairs and graphs.", content_point: "Stage 4 LIN-A: plot points incl. non-whole coordinates; recognise and move between linear representations | MA4-LIN-C-01", lesson_ref: "Mini Lesson 5" },
    { code: "G2", desc: "List the sample space and express the probability of an event as favourable ÷ total, on the 0-1 scale.", content_point: "Stage 4 PRO-A: list sample space; P(event) = favourable ÷ total; 0-1 scale; probabilities total 1 | MA4-PRO-C-01", lesson_ref: "Mini Lesson 11" },
    { code: "G3", desc: "Compare theoretical (expected) probability with observed probability (relative frequency) from repeated trials.", content_point: "Stage 4 PRO-A: theoretical vs observed probability (relative frequency); random number generator for repeated trials | MA4-PRO-C-01", lesson_ref: "Mini Lesson 12" },
  ],

  lessons: [
    {
      num: 1, band: "R",
      title: "Plotting and reading points in the first quadrant",
      outcomes: ["R1"], duration: "20-30 min",
      syllabus: "MA3-GM-01, MAO-WM-01 | GM-A: origin (0, 0); plot/label and read points in the first quadrant, horizontal first",
      source: "DoE Lesson 1 (adapted)",
      doeLink: "Lesson 1 -- Exploring the Cartesian coordinate system (first quadrant)",
      resources: "First-quadrant grid paper or GeoGebra, Resource: Math with Mr J 'Plotting Points Quadrant 1'",
      li: "plot and label points from coordinates in the first quadrant, and read the coordinates of given points",
      sc: [
        "I can find the origin (0, 0) where the two axes cross.",
        "I can plot a point by going across first, then up.",
        "I can read the coordinates of a given point, writing the horizontal position first.",
      ],
      steps: [
        { label: "Activate (3 min):", content: "Display a blank first-quadrant grid. Ask where to start counting from (the origin) and establish that we number the lines, not the spaces." },
        { label: "Model (10 min):", content: "Model plotting (3, 5): start at the origin, move 3 right along the x-axis, then 5 up. Emphasise the order 'across, then up'. Then model reading a given point back as coordinates." },
        { label: "Guided practice (10 min):", content: "Students plot a set of points to reveal a simple picture/letter on grid paper, and read off the coordinates of 4-5 marked points in their books." },
        { label: "Check (3 min):", content: "Exit question: write the coordinates of two marked points and plot (4, 2). Confirm horizontal-first ordering." },
      ],
      vocab: "Cartesian plane, number plane, axis, x-axis, y-axis, origin, coordinates, horizontal, vertical, plot",
      support: "Provide a partially-labelled grid and a 'right then up' arrow prompt; start with points on the axes before interior points.",
      extension: "Read and plot points where one coordinate is 0; describe the path between two points using across/up language.",
      assessment: "Students plot given coordinates accurately and read points back in correct (across, up) order — links to R1 in the SOLO Show task.",
    },
    {
      num: 2, band: "Y",
      title: "Plotting and reading points in all four quadrants",
      outcomes: ["Y1"], duration: "20-30 min",
      syllabus: "MA3-GM-01, MAO-WM-01 | GM-B: plot/label and read points in all 4 quadrants",
      source: "DoE Lessons 2-4 (adapted)",
      doeLink: "Lessons 2-4 -- Using the four quadrants of the coordinate plane",
      resources: "Four-quadrant grid paper or GeoGebra, Resource: Math with Mr J 'All 4 Quadrants' and 'Quadrants of the Coordinate Plane'",
      li: "plot, label and read points in all four quadrants, using positive and negative coordinates",
      sc: [
        "I know negative x means left and negative y means down.",
        "I can name which quadrant a point is in.",
        "I can plot and read points with negative coordinates.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Extend the axes into negatives. Label the four quadrants and agree that left is negative across, down is negative up." },
        { label: "Model (10 min):", content: "Model plotting (-3, 2) and (2, -4), naming the quadrant each lands in. Read a given point in the third quadrant back as coordinates." },
        { label: "Guided practice (9 min):", content: "Students plot a mix of points across all quadrants and record the quadrant of each; then read off coordinates of marked points including some on the axes." },
        { label: "Check (3 min):", content: "Exit question: name the quadrant of (-5, -2) and plot (-1, 3)." },
      ],
      vocab: "quadrant, first/second/third/fourth quadrant, positive, negative, coordinates, axis, origin",
      support: "Colour-code the four quadrants; provide a sign reminder card (left = -, down = -).",
      extension: "Without plotting, predict the quadrant of a point from the signs of its coordinates and justify the rule.",
      assessment: "Students plot and read points in all four quadrants and correctly identify quadrants — links to Y1 in the SOLO Show task.",
    },
    {
      num: 3, band: "Y",
      title: "Translating points across an axis",
      outcomes: ["Y2"], duration: "25-30 min",
      syllabus: "MA3-GM-01, MAO-WM-01 | GM-B: describe coordinate changes under translation",
      source: "DoE Lesson 3 (adapted)",
      doeLink: "Lesson 3 -- Translating points on the number plane",
      resources: "Grid paper, cut-out shapes/counters to slide, Resource: 'Translating on the Coordinate Plane' (mrmaisonet)",
      li: "describe how a point's coordinates change when it is translated (slid) across the plane",
      sc: [
        "I can slide a point right/left/up/down on the grid.",
        "I know right/left changes the x-coordinate and up/down changes the y-coordinate.",
        "I can write the new coordinates after a translation.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Place a counter on a grid point. Slide it 3 right and ask what changed about its coordinates (only the across number)." },
        { label: "Model (10 min):", content: "Model translating (2, 3) by 4 right and 1 up to (6, 4), recording the change to each coordinate. Stress that the shape/size doesn't change, only position." },
        { label: "Guided practice (10 min):", content: "Using cut-out shapes on grid paper, students physically translate a point/shape and then write the rule (e.g. 'add 4 to x'); record before/after coordinates." },
        { label: "Check (3 min):", content: "Exit question: translate (3, 2) by 5 right, and state which coordinate changed." },
      ],
      vocab: "translate, translation, slide, coordinates, horizontal, vertical, x-coordinate, y-coordinate",
      support: "Use a physical counter and arrows; translate one step at a time (across, then up) before combining.",
      extension: "Given a start and end point, describe the translation (e.g. '5 left, 2 down') as a rule.",
      assessment: "Students predict and record coordinate changes under translation — links to Y2 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["grid paper", "cut-out shapes or counters", "ruler"],
    },
    {
      num: 4, band: "Y",
      title: "Reflecting points across an axis",
      outcomes: ["Y3"], duration: "25-30 min",
      syllabus: "MA3-GM-01, MAO-WM-01 | GM-B: describe coordinate changes under reflection",
      source: "DoE Lesson 4 (adapted)",
      doeLink: "Lesson 4 -- Reflecting points on the number plane",
      resources: "Grid paper, small mirror, tracing paper, Resource: 'Reflecting Points Across the X-Axis and Y-Axis' (Partners in Prime)",
      li: "describe how a point's coordinates change when it is reflected (flipped) across an axis",
      sc: [
        "I can use a mirror to find the reflection of a point across an axis.",
        "I know reflecting across the x-axis changes the sign of the y-coordinate.",
        "I know reflecting across the y-axis changes the sign of the x-coordinate.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Stand a mirror on the x-axis. Ask students to predict where the point (3, 4) lands when flipped, then check with the mirror." },
        { label: "Model (10 min):", content: "Model reflecting (3, 4) across the x-axis to (3, -4), then across the y-axis to (-3, 4). Name which coordinate changed sign each time and why (the one off the mirror line)." },
        { label: "Guided practice (10 min):", content: "Students use a mirror/tracing paper to reflect several points across each axis, recording original and image coordinates and the sign change." },
        { label: "Check (3 min):", content: "Exit question: reflect (5, 2) across the x-axis, and reflect (-2, 5) across the y-axis." },
      ],
      vocab: "reflect, reflection, flip, mirror line, axis, image, x-coordinate, y-coordinate, sign",
      support: "Use a real mirror first; fold grid paper along the axis to physically see the flip before generalising.",
      extension: "Reflect a point across both axes in turn and describe the combined effect on its coordinates.",
      assessment: "Students predict and record coordinate changes under reflection across each axis — links to Y3 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["grid paper", "small mirror", "tracing paper"],
    },
    {
      num: 5, band: "G",
      title: "Non-whole coordinates and linear relationships (Stage 4)",
      outcomes: ["G1"], duration: "30-40 min",
      syllabus: "MA4-LIN-C-01, MAO-WM-01 | Stage 4 LIN-A: plot non-whole coordinates; move between linear representations",
      source: "Original mini lesson",
      li: "plot points with non-whole coordinates and recognise a linear relationship across a rule, table, coordinate pairs and graph",
      sc: [
        "I can plot points such as (2.5, 3) between grid lines.",
        "I can complete a table of values from a rule like y = 2x + 1.",
        "I can recognise that plotting a linear rule gives a straight line.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Ask where (2.5, 3) would sit on a grid (halfway between 2 and 3 across). Establish that coordinates need not be whole numbers." },
        { label: "Model (12 min):", content: "Take the rule y = 2x + 1. Build a table for x = 0-4, write the coordinate pairs, plot them and join — a straight line. Move deliberately between rule, table, pairs and graph." },
        { label: "Guided practice (12 min):", content: "Students complete a table and plot a different linear rule (e.g. y = x + 3), then read a value off the graph and check it against the rule." },
        { label: "Check (4 min):", content: "Exit question: for y = 2x, find y when x = 4, and state the shape the points make when plotted." },
      ],
      vocab: "linear relationship, rule, equation, table of values, coordinate pair, straight line, substitute, plot",
      support: "Provide the table half-completed and a pre-drawn set of axes; restrict to whole-number x values first.",
      extension: "Compare two linear rules on the same axes and find where they meet; introduce a non-whole coordinate point on the line.",
      assessment: "Students move flexibly between a rule, table, coordinate pairs and a straight-line graph — links to G1 in the SOLO Show task.",
    },
    {
      num: 6, band: "R",
      title: "Recognising equally likely outcomes",
      outcomes: ["R2"], duration: "20-30 min",
      syllabus: "MA3-CHAN-01, MAO-WM-01 | CHAN-A: recognise equally likely outcomes",
      source: "DoE Lessons 5-6 (adapted)",
      doeLink: "Lessons 5-6 -- Listing outcomes and equally likely chance",
      resources: "Coins, fair dice, equal-section spinners, Resource: Math with Mr J 'An Intro to Probability'",
      li: "list the outcomes of a chance experiment and recognise when they are equally likely",
      sc: [
        "I can list the possible outcomes of a coin flip, dice roll or spinner.",
        "I can say when outcomes are equally likely (each has the same chance).",
        "I can explain why unequal spinner sections are not equally likely.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Flip a coin and roll a dice; list the outcomes together. Ask whether each outcome has the same chance." },
        { label: "Model (9 min):", content: "Compare a fair dice (equally likely) with a spinner that has one large and several small sections (not equally likely). Define 'equally likely'." },
        { label: "Guided practice (10 min):", content: "Students sort a set of chance devices/spinners into 'equally likely' and 'not equally likely' and justify each choice in their books." },
        { label: "Check (3 min):", content: "Exit question: is a spinner that is half red and half (blue + yellow) equally likely for all colours? Explain." },
      ],
      vocab: "chance, outcome, equally likely, fair, spinner, dice, coin, section",
      support: "Use physical spinners and let students spin repeatedly to feel which outcomes come up more often.",
      extension: "Design two spinners — one with equally likely and one with unequal outcomes — and explain the difference.",
      assessment: "Students correctly identify equally likely vs unequal outcomes with justification — links to R2 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["coins", "fair dice", "equal-section spinners"],
    },
    {
      num: 7, band: "R",
      title: "Representing probabilities as fractions",
      outcomes: ["R3"], duration: "20-30 min",
      syllabus: "MA3-CHAN-01, MAO-WM-01 | CHAN-A: represent probabilities using fractions",
      source: "DoE Lessons 5-7 (adapted)",
      doeLink: "Lessons 5-7 -- Representing probabilities of equally likely outcomes",
      resources: "Dice, equal-section spinners, Resource: 'Calculating Probability as a Fraction' (EasyTeaching)",
      li: "represent the probability of an outcome of a chance experiment as a fraction",
      sc: [
        "I can write probability as (ways it can happen) ÷ (total equally likely outcomes).",
        "I can write P(rolling a 4) on a dice as 1/6.",
        "I know an impossible event is 0 and a certain event is 1.",
      ],
      steps: [
        { label: "Activate (3 min):", content: "Ask how likely it is to roll a 5 on a dice and how we could write it as a fraction." },
        { label: "Model (10 min):", content: "Model the fraction rule: favourable over total. Write P(red) for a 4-section spinner as 1/4 and P(even) on a dice as 3/6. Place 0 (impossible) and 1 (certain) on a scale." },
        { label: "Guided practice (10 min):", content: "Students write probabilities as fractions for given dice/spinner/bag situations in their books." },
        { label: "Check (3 min):", content: "Exit question: a 10-section spinner has 3 red sections — write P(red), and write the probability of an impossible event." },
      ],
      vocab: "probability, fraction, favourable outcome, total outcomes, impossible, certain, likelihood",
      support: "Provide the 'favourable / total' frame to fill in; start with denominators that match a visible number of sections.",
      extension: "Compare two probabilities written as fractions and order chance events on a 0-1 line.",
      assessment: "Students represent probabilities of equally likely outcomes as correct fractions — links to R3 in the SOLO Show task.",
    },
    {
      num: 8, band: "Y",
      title: "Building random generators with fractions, decimals and percentages",
      outcomes: ["Y4"], duration: "25-35 min",
      syllabus: "MA3-CHAN-01, MAO-WM-01 | CHAN-B: create random generators; benchmark fractions, decimals, percentages",
      source: "DoE Lessons 5 & 7 (adapted)",
      doeLink: "Lessons 5 & 7 -- Creating random generators to set probabilities",
      resources: "Blank spinner templates, split pins, coloured pencils, Resource: 'Express Probabilities as Decimals, Fractions and Percentages (Year 7 Chance)'",
      li: "create a random generator to follow a set probability, and link fractions, decimals and percentages",
      sc: [
        "I can work out how many equal sections an outcome needs for a given probability.",
        "I can match 1/2, 1/4 and 1/10 to their decimals and percentages.",
        "I can design a spinner that follows set proportions.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Ask how many of 8 equal sections should be red so red comes up half the time. Connect 1/2 = 0.5 = 50%." },
        { label: "Model (11 min):", content: "Model 'sections = fraction × total': for P = 1/5 on 10 sections, 2 sections. Build a small table of benchmark fractions, decimals and percentages." },
        { label: "Guided practice (12 min):", content: "Students design a spinner to set probabilities (e.g. win 1/4, draw 1/2, lose 1/4), then write each probability as a fraction, decimal and percentage." },
        { label: "Check (4 min):", content: "Exit question: on a 12-section spinner, how many sections give P = 1/3? Write 1/4 as a percentage." },
      ],
      vocab: "random generator, spinner, proportion, probability, fraction, decimal, percentage, benchmark, section",
      support: "Pre-divide spinner templates into equal sections; provide a fraction-decimal-percentage matching strip.",
      extension: "Design a spinner where one outcome is twice as likely as another and state all probabilities as fractions.",
      assessment: "Students build random generators that meet set probabilities and convert between fractions, decimals and percentages — links to Y4 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["blank spinner templates", "split pins", "coloured pencils"],
    },
    {
      num: 9, band: "Y",
      title: "Probabilities for outcomes that are not equally likely",
      outcomes: ["Y5"], duration: "25-30 min",
      syllabus: "MA3-CHAN-01, MAO-WM-01 | CHAN-B: assign probabilities (fractions) to unequal outcomes",
      source: "DoE Lessons 6-7 (adapted)",
      doeLink: "Lessons 6-7 -- Outcomes that are not equally likely",
      resources: "Bags of coloured counters, unequal spinners, Resource: 'Possible Outcomes Using a Spinner (unequal sections)' (mrmaisonet)",
      li: "record the outcomes of a chance experiment that are not equally likely and assign each a probability as a fraction",
      sc: [
        "I can count favourable outcomes over the total when outcomes are unequal.",
        "I can write probabilities with denominators of 2, 3, 4, 5, 6, 8 and 10.",
        "I know all the probabilities of an event add up to 1.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show a bag of 3 red and 2 blue counters. Ask which colour is more likely and how to write P(red)." },
        { label: "Model (10 min):", content: "Model P(red) = 3/5 and P(blue) = 2/5, and check they total 1. Repeat with an 8-section spinner (5 yellow, 3 purple)." },
        { label: "Guided practice (10 min):", content: "Students assign probabilities as fractions for several unequal bags/spinners and verify the probabilities sum to 1." },
        { label: "Check (3 min):", content: "Exit question: a bag has 4 red and 2 blue — write P(blue), and check P(red) + P(blue) = 1." },
      ],
      vocab: "outcome, not equally likely, favourable, total, probability, fraction, denominator, sum to one",
      support: "Use physical counters students can count; provide the 'favourable / total' frame and shade fraction strips.",
      extension: "Given some probabilities, work out the missing one knowing they total 1.",
      assessment: "Students assign correct fractional probabilities to unequal outcomes and check they total 1 — links to Y5 in the SOLO Show task.",
    },
    {
      num: 10, band: "Y",
      title: "Expected vs observed frequencies, and sampling with replacement",
      outcomes: ["Y6"], duration: "30-40 min",
      syllabus: "MA3-CHAN-01, MAO-WM-01 | CHAN-B: compare expected and observed frequencies; sampling with replacement",
      source: "DoE Lesson 8 (adapted)",
      doeLink: "Lesson 8 -- Comparing expected and observed frequencies",
      resources: "Dice, coins, bag of counters, tally sheets, online dice/spinner simulator, Resource: Math with Mr J 'Theoretical vs Experimental Probability'",
      li: "compare the frequencies I expect with the frequencies I observe, and sample with replacement",
      sc: [
        "I can work out an expected frequency as probability × number of trials.",
        "I can record observed results and compare them with expected.",
        "I can explain sampling with replacement and why it keeps the chances the same.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Ask how many 6s we'd expect in 60 dice rolls. Establish expected frequency = probability × trials." },
        { label: "Model (10 min):", content: "Flip a coin 10 times (observed wobbles from 5), then use a simulator for 1000 flips (observed settles near 50%). Define expected vs observed and introduce sampling with replacement." },
        { label: "Guided practice (14 min):", content: "Students run a small chance experiment (real, then simulated for large trials), tally observed results, and compare with the expected frequency in their books." },
        { label: "Check (4 min):", content: "Exit question: in 80 coin flips, how many heads are expected? Why are 1000 trials more reliable than 10?" },
      ],
      vocab: "expected frequency, observed frequency, trial, simulation, sampling with replacement, relative frequency",
      support: "Provide a pre-formatted tally sheet; run the large-trial part as a class using a projected simulator.",
      extension: "Estimate the make-up of a hidden bag by sampling with replacement and justifying the estimate from the relative frequencies.",
      assessment: "Students compare expected and observed frequencies and explain sampling with replacement — links to Y6 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["dice", "coins", "bag of counters", "tally sheets"],
    },
    {
      num: 11, band: "G",
      title: "Sample space and the probability of an event (Stage 4)",
      outcomes: ["G2"], duration: "30-40 min",
      syllabus: "MA4-PRO-C-01, MAO-WM-01 | Stage 4 PRO-A: sample space; P(event) = favourable ÷ total; 0-1 scale",
      source: "Original mini lesson",
      li: "list the sample space and express the probability of an event as favourable ÷ total on the 0-1 scale",
      sc: [
        "I can list the sample space for a chance experiment.",
        "I can calculate P(event) = favourable ÷ total.",
        "I know probabilities range from 0 to 1 and all outcomes total 1.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Ask for the sample space of a dice roll, {1,2,3,4,5,6}. Establish that we need all outcomes before finding a probability." },
        { label: "Model (12 min):", content: "Model P(even) on a 5-section spinner: favourable {2,4} ÷ total 5 = 2/5. Place 0 (impossible) and 1 (certain) on a scale and check all outcome probabilities total 1." },
        { label: "Guided practice (12 min):", content: "Students list sample spaces and calculate event probabilities for several experiments, then confirm the probabilities sum to 1." },
        { label: "Check (4 min):", content: "Exit question: for a dice, write the sample space and P(rolling an even number)." },
      ],
      vocab: "sample space, event, outcome, favourable, probability, impossible, certain, sum to one",
      support: "Provide the sample space pre-listed; use a 0-1 probability line to place each event.",
      extension: "Calculate probabilities of compound conditions (e.g. greater than 4) and order several events on the 0-1 scale.",
      assessment: "Students list a sample space and calculate event probabilities on the 0-1 scale — links to G2 in the SOLO Show task.",
    },
    {
      num: 12, band: "G",
      title: "Theoretical vs observed probability and relative frequency (Stage 4)",
      outcomes: ["G3"], duration: "30-40 min",
      syllabus: "MA4-PRO-C-01, MAO-WM-01 | Stage 4 PRO-A: theoretical vs observed probability; relative frequency",
      source: "Original mini lesson",
      li: "compare theoretical (expected) probability with observed probability (relative frequency) from repeated trials",
      sc: [
        "I can state the theoretical probability of a fair event.",
        "I can calculate observed probability (relative frequency) as successes ÷ trials.",
        "I can use a random number generator to repeat an experiment many times.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "State P(heads) = 1/2 in theory, then report 13 heads in 20 flips. Name which is theoretical and which is observed." },
        { label: "Model (12 min):", content: "Model relative frequency = successes ÷ trials (e.g. 18/40 = 9/20). Use a random number generator to repeat a dice experiment and watch the observed probability approach 1/6 as trials grow." },
        { label: "Guided practice (12 min):", content: "Students record relative frequencies over 12, 60 and 120 trials (using a simulator for speed) and describe how the observed value approaches the theoretical." },
        { label: "Check (4 min):", content: "Exit question: a coin lands heads 36 times in 80 flips — write the relative frequency; what happens to it as trials increase?" },
      ],
      vocab: "theoretical probability, observed probability, relative frequency, trial, simulation, random number generator",
      support: "Provide a results table with trial counts pre-filled; run the simulator as a class.",
      extension: "Design and run an experiment, predict the theoretical probability, and write a short report comparing it with the observed relative frequency.",
      assessment: "Students distinguish theoretical from observed probability and use repeated trials to explore relative frequency — links to G3 in the SOLO Show task.",
    },
  ],
};
