/**
 * Unit 35 — Addition & Subtraction Strategies, Decimals & Percentages (Stage 3 Year B).
 * Deliverable B. Built from units/u35/00_rubric_draft.md + 01_mapping_review.md.
 * Matches the UNIT DATA SCHEMA at the bottom of scripts/build_program_template.js.
 *
 * Multi-strand unit around the big idea "addition and subtraction problems can be solved
 * using a variety of strategies": efficient add/subtract of large numbers and decimals,
 * percentages of quantities & discounts, estimation, elapsed time, multi-step problems.
 *
 * Program has the resource appendix merged (resource_appendix_attached: true); a
 * standalone Unit35_Resource_Appendix.docx is also emitted (Stage 5). Every resource
 * URL verified live in Stage 3 (units/u35/03_resources_staged.csv).
 *
 * Outcome -> Mini Lesson map (teaching sequence, then Stage-4 Green cards):
 *   Y1->1 R4->2 Y2->3 R2->4 R3->5 R1->6 Y4->7 Y5->8 Y3->9 Y6->10 G1->11 G2->12 G3->13
 */
module.exports = {
  unit_number: "35",
  unit_title: "Addition & Subtraction Strategies, Decimals & Percentages",
  term: null,
  duration: "2-3 weeks",

  resource_appendix_attached: true,

  // Every URL verified live in Stage 3 (oEmbed + curl); see units/u35/03_resources_staged.csv.
  resources: {
    r1: [
      { type: "video", label: "How to Find a Percent of a Number | Math with Mr. J", url: "https://www.youtube.com/watch?v=5CAncQ4TZD4" },
      { type: "video", label: "Converting Between Fractions, Decimals, and Percents | Math with Mr. J", url: "https://www.youtube.com/watch?v=2vjbNZaFz3c" },
      { type: "worksheet", label: "Corbettmaths — Percentages of an Amount (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2018/11/Percentages-of-amounts-234-pdf.pdf" },
    ],
    r2: [
      { type: "video", label: "Place Value to the Thousandths — Representing Decimal Numbers | Miacademy", url: "https://www.youtube.com/watch?v=BsZJGMRWEK0" },
      { type: "video", label: "Expanded Form with Decimals | Math with Mr. J", url: "https://www.youtube.com/watch?v=GX8o-S6Vxig" },
      { type: "worksheet", label: "Corbettmaths — Place Value (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/place-value-pdf.pdf" },
    ],
    r3: [
      { type: "video", label: "Adding and Subtracting Decimals (How to) | Math with Mr. J", url: "https://www.youtube.com/watch?v=PnwLv6khwk8" },
      { type: "video", label: "How to Add and Subtract Decimals (Step-by-Step Examples) | Math with Mr. J", url: "https://www.youtube.com/watch?v=Cg-_TeiaSa8" },
      { type: "worksheet", label: "Corbettmaths — Adding Decimals (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/adding-decimals-pdf.pdf" },
      { type: "worksheet", label: "Corbettmaths — Subtracting Decimals (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/subtracting-decimals-pdf.pdf" },
    ],
    r4: [
      { type: "video", label: "Calculating Elapsed Time Using a Timeline | EasyTeaching", url: "https://www.youtube.com/watch?v=ML6r7BEZo7M" },
      { type: "video", label: "Learn How to Find Elapsed Time | Mr. Tom Teaches", url: "https://www.youtube.com/watch?v=Ths2BdqtO4s" },
      { type: "worksheet", label: "Corbettmaths — Timetables (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/timetables-pdf.pdf" },
    ],
    y1: [
      { type: "video", label: "How to Add & Subtract Large Numbers (Without a Calculator) | Math with Mr. J", url: "https://www.youtube.com/watch?v=186wdnoAYJc" },
      { type: "video", label: "Adding Large Numbers — A Quick Review | Math with Mr. J", url: "https://www.youtube.com/watch?v=T9asFgfN5bg" },
      { type: "worksheet", label: "Corbettmaths — Place Value (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/place-value-pdf.pdf" },
    ],
    y2: [
      { type: "video", label: "How to Use Bridging to Support Mental Addition and Subtraction | Third Space Learning", url: "https://www.youtube.com/watch?v=oDDC1thyc2Q" },
      { type: "video", label: "Addition and Subtraction: The Compensation Strategy | Charlotte Dooley", url: "https://www.youtube.com/watch?v=X3kgzlb8VrM" },
      { type: "worksheet", label: "Corbettmaths — Place Value (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/place-value-pdf.pdf" },
    ],
    y3: [
      { type: "video", label: "How to Add and Subtract Decimals (Step-by-Step Examples) | Math with Mr. J", url: "https://www.youtube.com/watch?v=Cg-_TeiaSa8" },
      { type: "video", label: "Estimating Decimal Sums | Math with Mr. J", url: "https://www.youtube.com/watch?v=x05LHZJNKQ0" },
      { type: "worksheet", label: "Corbettmaths — Subtracting Decimals (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/subtracting-decimals-pdf.pdf" },
    ],
    y4: [
      { type: "video", label: "How to Find a Percent of a Number | Math with Mr. J", url: "https://www.youtube.com/watch?v=5CAncQ4TZD4" },
      { type: "video", label: "Converting Between Fractions, Decimals, and Percents | Math with Mr. J", url: "https://www.youtube.com/watch?v=2vjbNZaFz3c" },
      { type: "worksheet", label: "Corbettmaths — Percentages of an Amount (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2018/11/Percentages-of-amounts-234-pdf.pdf" },
      { type: "worksheet", label: "Corbettmaths — Fractions, Decimals, Percentages (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/fractions-decimals-percentages-pdf.pdf" },
    ],
    y5: [
      { type: "video", label: "Estimating Whole Number Sums & Differences | Math with Mr. J", url: "https://www.youtube.com/watch?v=EvQf38lnAJc" },
      { type: "video", label: "Estimating Decimal Sums | Math with Mr. J", url: "https://www.youtube.com/watch?v=x05LHZJNKQ0" },
      { type: "worksheet", label: "Corbettmaths — Estimation (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/estimation-pdf.pdf" },
    ],
    y6: [
      { type: "video", label: "Multi-Step Word Problem (Addition, Subtraction, Multiplication) | Khan Academy", url: "https://www.youtube.com/watch?v=-sSDb_wZqKQ" },
      { type: "video", label: "How to Add & Subtract Large Numbers | Math with Mr. J", url: "https://www.youtube.com/watch?v=186wdnoAYJc" },
      { type: "worksheet", label: "Corbettmaths — Estimation (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/estimation-pdf.pdf" },
    ],
    g1: [
      { type: "video", label: "How to Find a Percent of a Number | Math with Mr. J", url: "https://www.youtube.com/watch?v=5CAncQ4TZD4" },
      { type: "video", label: "Converting Between Fractions, Decimals, and Percents | Math with Mr. J", url: "https://www.youtube.com/watch?v=2vjbNZaFz3c" },
      { type: "worksheet", label: "Corbettmaths — Percentages of an Amount (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2018/11/Percentages-of-amounts-234-pdf.pdf" },
    ],
    g2: [
      { type: "video", label: "Increasing/Decreasing by a Percentage | Corbettmaths", url: "https://www.youtube.com/watch?v=tUtgC7ZrsRc" },
      { type: "video", label: "Percentage Change | Corbettmaths", url: "https://www.youtube.com/watch?v=Q2gRAS08fE0" },
      { type: "worksheet", label: "Corbettmaths — Increasing/Decreasing by a Percentage (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2018/11/Increasing-by-a-Percentage-pdf.pdf" },
      { type: "worksheet", label: "Corbettmaths — Percentage Change (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/percentage-change-pdf.pdf" },
    ],
    g3: [
      { type: "video", label: "Percent Problems — Finding the Whole | Math with Mr. J", url: "https://www.youtube.com/watch?v=9sMQEajxVwk" },
      { type: "video", label: "How to Find a Percent of a Number | Math with Mr. J", url: "https://www.youtube.com/watch?v=5CAncQ4TZD4" },
      { type: "worksheet", label: "Corbettmaths — Reverse Percentages (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/reverse-percentages-pdf.pdf" },
    ],
  },
  beyond_resources: [
    { type: "video", label: "How to Find a Percent of a Number | Math with Mr. J", url: "https://www.youtube.com/watch?v=5CAncQ4TZD4" },
    { type: "video", label: "Increasing/Decreasing by a Percentage | Corbettmaths", url: "https://www.youtube.com/watch?v=tUtgC7ZrsRc" },
    { type: "video", label: "Percent Problems — Finding the Whole | Math with Mr. J", url: "https://www.youtube.com/watch?v=9sMQEajxVwk" },
    { type: "video", label: "Percentage Change | Corbettmaths", url: "https://www.youtube.com/watch?v=Q2gRAS08fE0" },
    { type: "worksheet", label: "Corbettmaths — Percentages of an Amount (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2018/11/Percentages-of-amounts-234-pdf.pdf" },
    { type: "worksheet", label: "Corbettmaths — Increasing/Decreasing by a Percentage (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2018/11/Increasing-by-a-Percentage-pdf.pdf" },
    { type: "worksheet", label: "Corbettmaths — Reverse Percentages (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/reverse-percentages-pdf.pdf" },
    { type: "website", label: "Maths is Fun — Percentages (interactive)", url: "https://www.mathsisfun.com/percentage.html" },
    { type: "website", label: "Maths is Fun — Percentage Change (interactive)", url: "https://www.mathsisfun.com/numbers/percentage-change.html" },
  ],

  syllabus_strands_summary: "Additive Relations, Percentages, Decimals and Time, extended with Stage 4 Percentages",
  strand_abbreviations_note: "AR = Additive relations. RN = Represents numbers (decimals/percentages). MR = Multiplicative relations. NSM = Non-spatial measure (time). FRC = Fractions, decimals & percentages (Stage 4). A/B = syllabus content groups (B is the new add/subtract content for this Year-B unit).",

  syllabus_outcomes: [
    { code: "MAO-WM-01", descriptor: "Develops understanding and fluency through exploring, applying and communicating mathematical reasoning." },
    { code: "MA3-AR-01", descriptor: "Selects and applies appropriate strategies to solve addition and subtraction problems." },
    { code: "MA3-RN-03", descriptor: "Determines percentages of quantities, and finds equivalent fractions and decimals for benchmark percentage values." },
    { code: "MA3-NSM-02", descriptor: "Measures and compares duration, using 12- and 24-hour time and am and pm notation." },
    { code: "MA3-MR-02", descriptor: "Constructs and completes number sentences, applying the order of operations to calculations." },
    { code: "MA4-FRC-C-01", descriptor: "Stage 4 (group A): represents and operates with percentages — percentage increase/decrease, financial applications and the unitary method." },
  ],

  content_points: {
    red: {
      heading: "Number & time recall (single procedures)",
      heading_short: "Red -- Foundation",
      points: [
        "Find 10% (÷10), 25% (÷4) and 50% (half) of a quantity.",
        "Express thousandths as decimals; partition decimals by place value.",
        "Add and subtract decimals up to 3 decimal places.",
        "Use start and finish times to calculate elapsed time.",
      ],
    },
    yellow: {
      heading: "Strategies, percentages & problem solving (applying)",
      heading_short: "Yellow -- On-level",
      points: [
        "Use place value to add/subtract 3+ numbers; decide when a calculator is efficient.",
        "Apply efficient strategies (levelling, addition for subtraction, constant difference, bridging).",
        "Solve decimal word problems and justify the chosen strategy.",
        "Represent percentages of quantities as fractions/decimals; find 10/25/50% discounts.",
        "Round to estimate and check the reasonableness of answers.",
        "Solve multi-step word problems requiring more than one operation.",
      ],
    },
    green: {
      heading: "Extended -- Stage 4 Percentages",
      heading_short: "Green -- Extension",
      points: [
        "Find any percentage of a quantity, not just 10/25/50% (MA4-FRC-C-01).",
        "Calculate percentage increases and decreases, including discounts and 10% GST (MA4-FRC-C-01).",
        "Find the whole (original amount) from a given percentage using the unitary method (MA4-FRC-C-01).",
      ],
    },
  },

  working_mathematically: [
    { process: "Communicating", description: "Students compare, evaluate and communicate the addition and subtraction strategies they choose, using clear mathematical language." },
    { process: "Understanding and fluency", description: "Students add and subtract large numbers and decimals accurately, and find percentages of quantities." },
    { process: "Reasoning", description: "Students justify why a strategy is appropriate and use estimation to judge the reasonableness of solutions." },
    { process: "Problem solving", description: "Students solve multi-step word problems involving money, time and percentages, and (Stage 4) percentage increase/decrease problems." },
  ],

  outcomes: [
    { code: "R1", desc: "Find 10%, 25% and 50% of a quantity.", content_point: "RN-B percentages: 10% is one-tenth of 100%; equate 10% to ÷10, 25% to ÷4, 50% to half | MA3-RN-03", lesson_ref: "Mini Lesson 6" },
    { code: "R2", desc: "Express thousandths as decimals; partition decimals by place value.", content_point: "RN-B decimals: express thousandths as decimals; use place value to partition decimals | MA3-RN-03", lesson_ref: "Mini Lesson 4" },
    { code: "R3", desc: "Add and subtract decimals up to 3 decimal places.", content_point: "AR-B: model the addition and subtraction of decimals up to 3 decimal places | MA3-AR-01", lesson_ref: "Mini Lesson 5" },
    { code: "R4", desc: "Use start and finish times to calculate elapsed time.", content_point: "NSM-B time: use start and finish times to calculate the elapsed time of events | MA3-NSM-02", lesson_ref: "Mini Lesson 2" },
    { code: "Y1", desc: "Add/subtract 3+ numbers with place value; decide when a calculator is efficient.", content_point: "AR-B: add/subtract 3+ numbers with different digit lengths; determine when a calculator is efficient; compare strategies | MA3-AR-01", lesson_ref: "Mini Lesson 1" },
    { code: "Y2", desc: "Apply efficient strategies (levelling, constant difference, bridging).", content_point: "AR-B: apply known strategies such as levelling, addition for subtraction, constant difference and bridging | MA3-AR-01", lesson_ref: "Mini Lesson 3" },
    { code: "Y3", desc: "Solve decimal word problems and justify the strategy.", content_point: "AR-B: solve word problems involving add/subtract of decimals to 3 dp; justify the strategy used | MA3-AR-01", lesson_ref: "Mini Lesson 9" },
    { code: "Y4", desc: "Represent percentages of quantities as fractions/decimals; find 10/25/50% discounts.", content_point: "RN-B percentages: represent common percentages of quantities and lengths as fractions and decimals; estimate discounts of 10/25/50% | MA3-RN-03", lesson_ref: "Mini Lesson 7" },
    { code: "Y5", desc: "Round to estimate and check the reasonableness of answers.", content_point: "AR-B: round to obtain estimates; use estimation to check the reasonableness of solutions | MA3-AR-01", lesson_ref: "Mini Lesson 8" },
    { code: "Y6", desc: "Solve multi-step word problems requiring more than one operation.", content_point: "AR-B / MR-B: solve multistep word problems, including problems that require more than one operation | MA3-AR-01 / MA3-MR-02", lesson_ref: "Mini Lesson 10" },
    { code: "G1", desc: "Find any percentage of a quantity.", content_point: "Stage 4 FRC-A: apply knowledge of percentages to calculate quantities in various contexts | MA4-FRC-C-01", lesson_ref: "Mini Lesson 11" },
    { code: "G2", desc: "Calculate percentage increase and decrease, incl. discounts and GST.", content_point: "Stage 4 FRC-A: calculate percentage increases/decreases; financial applications incl. GST, profit and loss | MA4-FRC-C-01", lesson_ref: "Mini Lesson 12" },
    { code: "G3", desc: "Find the whole from a percentage (reverse percentage, unitary method).", content_point: "Stage 4 FRC-A: solve real-life percentage problems using the unitary method | MA4-FRC-C-01", lesson_ref: "Mini Lesson 13" },
  ],

  lessons: [
    {
      num: 1, band: "Y",
      title: "Adding and subtracting large numbers",
      outcomes: ["Y1"], duration: "30 min",
      syllabus: "MA3-AR-01, MAO-WM-01 | AR-B: add/subtract 3+ numbers; choose efficient tools",
      source: "DoE Lessons 1 & 2 (adapted)",
      doeLink: "Lessons 1 & 2 -- Place value strategies for addition and subtraction",
      resources: "Resource 1 - shopping receipt, place-value charts, calculators",
      li: "use place value to add or subtract 3 or more numbers and decide when a calculator is efficient",
      sc: [
        "I can line up numbers by place value to add or subtract them.",
        "I can add 3 or more numbers with different numbers of digits.",
        "I can decide when a calculator is the most efficient tool.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show a shopping receipt and ask students to total three items mentally, then check with place value." },
        { label: "Model (10 min):", content: "Add 1240 + 56 + 308 by lining up place values; subtract 2050 - 875. Discuss when a calculator would be quicker (many large numbers)." },
        { label: "Guided practice (12 min):", content: "Students add and subtract sets of 3+ numbers, choosing mental, written or calculator methods and explaining why." },
        { label: "Check (4 min):", content: "Exit question: 3406 + 78 + 920 = ? Would you use a calculator? Why?" },
      ],
      vocab: "place value, column, regroup, efficient, strategy, calculator, estimate",
      support: "Provide a place-value grid so digits line up; start with two numbers.",
      extension: "Add a column of five 4-digit numbers and check with an estimate.",
      assessment: "Students add and subtract several numbers efficiently — links to Y1 in the SOLO Show task.",
    },
    {
      num: 2, band: "R",
      title: "Calculating elapsed time",
      outcomes: ["R4"], duration: "25-30 min",
      syllabus: "MA3-NSM-02, MAO-WM-01 | NSM-B: use start and finish times to find elapsed time",
      source: "DoE Lessons 1, 7 & 8 (adapted)",
      doeLink: "Lessons 1, 7 & 8 -- Duration and timetables",
      resources: "Geared clock face, time number line, timetable cards",
      li: "use start and finish times to calculate the elapsed time of an event",
      sc: [
        "I can find how long an event lasts from its start and finish times.",
        "I can bridge through the hour to count the minutes.",
        "I can use a time number line to keep track.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "A film starts at 3:45 pm and finishes at 5:20 pm. Ask how long it lasted." },
        { label: "Model (10 min):", content: "Use a time number line: 3:45 -> 4:00 (15 min) -> 5:00 (1 h) -> 5:20 (20 min) = 1 h 35 min. Bridge through the hour." },
        { label: "Guided practice (10 min):", content: "Students find elapsed times for events and timetable entries using a number line." },
        { label: "Check (4 min):", content: "Exit question: a bus leaves at 9:50 am and arrives at 11:15 am. How long is the trip?" },
      ],
      vocab: "elapsed time, duration, start time, finish time, bridge, am, pm, number line",
      support: "Use a geared clock and count on in 5-minute jumps to the next hour first.",
      extension: "Solve elapsed-time problems that cross 12-hour boundaries and use 24-hour time.",
      assessment: "Students calculate elapsed time — links to R4 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["geared clock face", "time number line", "timetable cards"],
    },
    {
      num: 3, band: "Y",
      title: "Efficient add/subtract strategies",
      outcomes: ["Y2"], duration: "30 min",
      syllabus: "MA3-AR-01, MAO-WM-01 | AR-B: levelling, addition for subtraction, constant difference, bridging",
      source: "DoE Lesson 2 (adapted)",
      doeLink: "Lesson 2 -- Mental and written strategies",
      resources: "Number lines, mini whiteboards",
      li: "apply known strategies such as levelling, constant difference and bridging, and choose an efficient one",
      sc: [
        "I can use bridging to add through a ten or hundred.",
        "I can use constant difference to make a subtraction easier.",
        "I can pick an efficient strategy and explain why.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show 47 + 29. Ask how rounding 29 to 30 (then adjusting) makes it easier." },
        { label: "Model (10 min):", content: "Bridging: 47 + 29 = 47 + 30 - 1 = 76. Constant difference: 83 - 48 = 85 - 50 = 35. Levelling for addition." },
        { label: "Guided practice (12 min):", content: "Students solve additions and subtractions with different strategies and decide which is most efficient." },
        { label: "Check (4 min):", content: "Exit question: use constant difference to work out 72 - 39." },
      ],
      vocab: "strategy, bridging, levelling, constant difference, compensation, efficient, mental",
      support: "Model each strategy on a number line; start with adding through a ten.",
      extension: "Choose the most efficient strategy for a set of mixed problems and justify each choice.",
      assessment: "Students apply efficient add/subtract strategies — links to Y2 in the SOLO Show task.",
    },
    {
      num: 4, band: "R",
      title: "Thousandths and partitioning decimals",
      outcomes: ["R2"], duration: "25 min",
      syllabus: "MA3-RN-03, MAO-WM-01 | RN-B: express thousandths as decimals; partition decimals",
      source: "DoE Lesson 3 (adapted)",
      doeLink: "Lesson 3 -- Decimal place value",
      resources: "Place-value chart, decimal cards",
      li: "express thousandths as decimals and partition a decimal by place value",
      sc: [
        "I can write thousandths as a decimal (e.g. 6 thousandths = 0.006).",
        "I can partition a decimal into its place-value parts.",
        "I can say the value of each digit after the point.",
      ],
      steps: [
        { label: "Activate (3 min):", content: "Show 2.456 on a place-value chart. Ask the value of the 6." },
        { label: "Model (10 min):", content: "Partition 2.456 = 2 + 0.4 + 0.05 + 0.006. Write 6 thousandths as 0.006 and 25 thousandths as 0.025." },
        { label: "Guided practice (8 min):", content: "Students partition decimals to 3 dp and write thousandths as decimals using a chart." },
        { label: "Check (4 min):", content: "Exit question: partition 3.072 and write 'eighteen thousandths' as a decimal." },
      ],
      vocab: "decimal, tenths, hundredths, thousandths, partition, place value, expand",
      support: "Use a labelled place-value chart; build the number digit by digit.",
      extension: "Partition decimals in more than one way and order a set of decimals to 3 dp.",
      assessment: "Students express thousandths and partition decimals — links to R2 in the SOLO Show task.",
    },
    {
      num: 5, band: "R",
      title: "Adding and subtracting decimals",
      outcomes: ["R3"], duration: "25-30 min",
      syllabus: "MA3-AR-01, MAO-WM-01 | AR-B: add and subtract decimals to 3 dp",
      source: "DoE Lessons 3 & 4 (adapted)",
      doeLink: "Lessons 3 & 4 -- Adding and subtracting decimals",
      resources: "Place-value chart, decimal grids",
      li: "add and subtract decimals up to 3 decimal places",
      sc: [
        "I can line up the decimal points to add or subtract.",
        "I can add a zero to fill an empty place (e.g. 3.4 as 3.40).",
        "I can add and subtract decimals to 3 decimal places.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show 2.65 + 1.4. Ask why lining up the decimal points (and place values) matters." },
        { label: "Model (10 min):", content: "Add 12.75 + 8.6 (write 8.60) and subtract 9.3 - 4.85 (write 9.30). Stress lining up place values." },
        { label: "Guided practice (10 min):", content: "Students add and subtract decimals to 3 dp, filling empty places with zeros." },
        { label: "Check (4 min):", content: "Exit question: 3.4 - 1.85 = ? and 2.305 + 1.7 = ?" },
      ],
      vocab: "decimal, decimal point, place value, line up, tenths, hundredths, thousandths",
      support: "Use grid paper and a place-value chart so digits line up.",
      extension: "Add and subtract decimals with different numbers of decimal places in one problem.",
      assessment: "Students add and subtract decimals to 3 dp — links to R3 in the SOLO Show task.",
    },
    {
      num: 6, band: "R",
      title: "Finding 10%, 25% and 50%",
      outcomes: ["R1"], duration: "25-30 min",
      syllabus: "MA3-RN-03, MAO-WM-01 | RN-B: 10% = ÷10, 25% = ÷4, 50% = half",
      source: "DoE Lessons 4 & 5 (adapted)",
      doeLink: "Lessons 4 & 5 -- Benchmark percentages",
      resources: "Hundred grids, mini whiteboards",
      li: "find 10%, 25% and 50% of a quantity",
      sc: [
        "I know 10% is one-tenth of 100%, so 10% is dividing by 10.",
        "I can find 25% by dividing by 4 and 50% by halving.",
        "I can find these percentages of a quantity.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show a hundred grid. Shade 10%, 25% and 50%. Ask what fraction each is." },
        { label: "Model (10 min):", content: "10% of 80 = 80 ÷ 10 = 8. 25% of 80 = 80 ÷ 4 = 20. 50% of 80 = half = 40." },
        { label: "Guided practice (10 min):", content: "Students find 10%, 25% and 50% of a range of quantities (whole numbers and money)." },
        { label: "Check (4 min):", content: "Exit question: find 10%, 25% and 50% of 60." },
      ],
      vocab: "per cent, %, 10%, 25%, 50%, divide, half, quarter, tenth, quantity",
      support: "Connect each percentage to its fraction (½, ¼, 1/10) and use a hundred grid.",
      extension: "Find amounts like 75% (50% + 25%) and 5% (half of 10%).",
      assessment: "Students find 10/25/50% of a quantity — links to R1 in the SOLO Show task.",
    },
    {
      num: 7, band: "Y",
      title: "Percentages of quantities and discounts",
      outcomes: ["Y4"], duration: "30 min",
      syllabus: "MA3-RN-03, MAO-WM-01 | RN-B: percentages as fractions/decimals; estimate discounts",
      source: "DoE Lessons 5 & 6 (adapted)",
      doeLink: "Lessons 5 & 6 -- Percentages and discounts",
      resources: "Shopping catalogues, mini whiteboards",
      li: "represent common percentages as fractions and decimals and estimate discounts of 10%, 25% and 50%",
      sc: [
        "I can write 10%, 25% and 50% as fractions and decimals.",
        "I can estimate a 10%, 25% or 50% discount on a price.",
        "I can work out the new price after a discount.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "A $60 jacket is '25% off'. Ask roughly how much you save." },
        { label: "Model (10 min):", content: "25% = ¼ = 0.25. 25% of $60 = $15 off, so the price is $45. Estimate a 10% discount on $39 (about $4)." },
        { label: "Guided practice (12 min):", content: "Students find discounts of 10/25/50% on catalogue prices and the new price each time." },
        { label: "Check (4 min):", content: "Exit question: a $40 game is 50% off. What is the discount and the new price?" },
      ],
      vocab: "percentage, fraction, decimal, discount, sale, estimate, new price, save",
      support: "Use the benchmark fractions and a hundred grid; round prices to estimate.",
      extension: "Compare two discounts (e.g. 25% off vs $15 off) and decide which is better.",
      assessment: "Students find percentage discounts — links to Y4 in the SOLO Show task.",
    },
    {
      num: 8, band: "Y",
      title: "Estimating and checking reasonableness",
      outcomes: ["Y5"], duration: "25-30 min",
      syllabus: "MA3-AR-01, MAO-WM-01 | AR-B: round to estimate; check reasonableness",
      source: "DoE Lesson 6 (adapted)",
      doeLink: "Lesson 6 -- Estimation and reasonableness",
      resources: "Mini whiteboards, number lines",
      li: "round numbers to estimate and use the estimate to check whether an answer is reasonable",
      sc: [
        "I can round numbers to make an estimate.",
        "I can use an estimate to check if an answer is reasonable.",
        "I can spot an answer that is clearly wrong.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show 412 + 389 = 4801. Ask whether that looks reasonable and why not." },
        { label: "Model (10 min):", content: "Estimate 412 + 389 as 400 + 400 = 800. The true answer 801 is close — 4801 is unreasonable. Round to estimate first, then compute." },
        { label: "Guided practice (10 min):", content: "Students estimate sums and differences by rounding, then check given answers for reasonableness." },
        { label: "Check (4 min):", content: "Exit question: estimate 596 + 207 by rounding, then say if 803 is reasonable." },
      ],
      vocab: "estimate, round, reasonable, approximate, check, nearest ten, nearest hundred",
      support: "Round each number to the nearest hundred and add the rounded numbers.",
      extension: "Estimate multi-step calculations and decide how close the estimate should be.",
      assessment: "Students estimate and check reasonableness — links to Y5 in the SOLO Show task.",
    },
    {
      num: 9, band: "Y",
      title: "Decimal word problems",
      outcomes: ["Y3"], duration: "30 min",
      syllabus: "MA3-AR-01, MAO-WM-01 | AR-B: decimal word problems; justify the strategy",
      source: "DoE Lessons 3, 6, 7 & 8 (adapted)",
      doeLink: "Lessons 3, 6-8 -- Decimal word problems",
      resources: "Resource 1 - shopping receipt, mini whiteboards",
      li: "solve word problems involving adding and subtracting decimals and justify the strategy used",
      sc: [
        "I can pull the numbers out of a word problem and decide to add or subtract.",
        "I can solve the problem with decimals to 3 dp.",
        "I can explain why my strategy is appropriate.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "From a receipt: items cost $4.50, $2.75 and $1.20. Ask for the total and the change from $10." },
        { label: "Model (10 min):", content: "Total = 4.50 + 2.75 + 1.20 = 8.45. Change from $10 = 10.00 - 8.45 = 1.55. Justify lining up decimals." },
        { label: "Guided practice (12 min):", content: "Students solve money and measurement decimal word problems, justifying each strategy." },
        { label: "Check (4 min):", content: "Exit question: a bottle holds 1.25 L; 0.4 L is poured out. How much is left? Explain your method." },
      ],
      vocab: "decimal, total, difference, change, justify, strategy, word problem, reasonable",
      support: "Highlight the numbers and the question; provide a place-value grid.",
      extension: "Solve two-step decimal problems and write a decimal word problem for a partner.",
      assessment: "Students solve and justify decimal word problems — links to Y3 in the SOLO Show task.",
    },
    {
      num: 10, band: "Y",
      title: "Multi-step word problems",
      outcomes: ["Y6"], duration: "30-35 min",
      syllabus: "MA3-AR-01, MA3-MR-02, MAO-WM-01 | AR-B/MR-B: multistep problems, more than one operation",
      source: "DoE Lessons 7 & 8 (adapted)",
      doeLink: "Lessons 7 & 8 -- Rich multi-step tasks",
      resources: "Mini whiteboards, problem cards",
      li: "solve multi-step word problems that require more than one operation",
      sc: [
        "I can break a problem into steps and decide the operations.",
        "I can solve each step and use the result in the next.",
        "I can check my final answer is reasonable.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "You buy 3 tickets at $12 each and pay with $50. Ask how to find the change in two steps." },
        { label: "Model (12 min):", content: "Step 1: 3 x 12 = 36. Step 2: 50 - 36 = 14. Then a longer problem mixing +, - and a discount." },
        { label: "Guided practice (14 min):", content: "Students plan and solve multi-step problems, recording each step and checking with an estimate." },
        { label: "Check (4 min):", content: "Exit question: 4 drinks at $2.50 and 2 snacks at $3.20 — what is the total, and the change from $20?" },
      ],
      vocab: "multi-step, operation, step, plan, total, change, estimate, reasonable",
      support: "Provide a step-by-step planning frame; do one step at a time.",
      extension: "Create a multi-step problem with at least three operations for a partner to solve.",
      assessment: "Students solve multi-step word problems — links to Y6 in the SOLO Show task.",
    },
    {
      num: 11, band: "G",
      title: "Any percentage of a quantity (Stage 4)",
      outcomes: ["G1"], duration: "30 min",
      syllabus: "MA4-FRC-C-01, MAO-WM-01 | Stage 4 FRC-A: percentages of quantities in various contexts",
      source: "Original mini lesson",
      li: "find any percentage of a quantity, not just the 10/25/50% benchmarks",
      sc: [
        "I can find 1% by dividing by 100.",
        "I can build other percentages from 10% and 1% (e.g. 15% = 10% + 5%).",
        "I can find any percentage of a quantity.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Ask how to find 15% of $80 if you already know 10% of $80 = $8." },
        { label: "Model (12 min):", content: "10% of 80 = 8, 5% = half of that = 4, so 15% = 12. Find 1% of 80 = 0.8 and build 3% = 2.4. Find 20% of 45." },
        { label: "Guided practice (12 min):", content: "Students find percentages like 15%, 20%, 5% and 1% of quantities by building from 10% and 1%." },
        { label: "Check (4 min):", content: "Exit question: find 15% of 60 and 5% of 200." },
      ],
      vocab: "percentage, 1%, 10%, build, divide by 100, quantity, of",
      support: "Always find 10% first, then halve for 5% or take a tenth again for 1%.",
      extension: "Find percentages like 12.5% and 35% and check using a different build.",
      assessment: "Students find any percentage of a quantity — links to G1 in the SOLO Show task.",
    },
    {
      num: 12, band: "G",
      title: "Percentage increase and decrease (Stage 4)",
      outcomes: ["G2"], duration: "30-35 min",
      syllabus: "MA4-FRC-C-01, MAO-WM-01 | Stage 4 FRC-A: percentage increase/decrease; GST, profit/loss",
      source: "Original mini lesson",
      li: "calculate percentage increases and decreases, including discounts and GST",
      sc: [
        "I can decrease a price by a percentage to find a sale price.",
        "I can increase a price by a percentage (e.g. add 10% GST).",
        "I can solve a real-life percentage increase or decrease problem.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "A $50 item is reduced by 20%. Ask for the discount and the new price." },
        { label: "Model (12 min):", content: "Decrease: 20% of 50 = 10, new price = 40. Increase (GST): 10% of $30 = $3, price incl. GST = $33." },
        { label: "Guided practice (12 min):", content: "Students find sale prices (decrease) and prices including 10% GST (increase) for AUD amounts." },
        { label: "Check (5 min):", content: "Exit question: add 10% GST to a $60 part, then find a 25% discount on a $48 item." },
      ],
      vocab: "increase, decrease, discount, GST, percentage, new price, original, mark-up",
      support: "Find the percentage amount first, then add or subtract it from the original.",
      extension: "Apply a discount and then GST to the same amount and discuss the order.",
      assessment: "Students calculate percentage increase and decrease — links to G2 in the SOLO Show task.",
    },
    {
      num: 13, band: "G",
      title: "Finding the whole from a percentage (Stage 4)",
      outcomes: ["G3"], duration: "30 min",
      syllabus: "MA4-FRC-C-01, MAO-WM-01 | Stage 4 FRC-A: unitary method, reverse percentage",
      source: "Original mini lesson",
      li: "find the whole (original) amount when given a percentage of it, using the unitary method",
      sc: [
        "I can find 1% when I know what a percentage is worth.",
        "I can multiply 1% by 100 to find the whole.",
        "I can solve a reverse-percentage word problem.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "20% of a number is 16. Ask how to find the whole number." },
        { label: "Model (12 min):", content: "Unitary method: 20% = 16, so 1% = 16 ÷ 20 = 0.8, and 100% = 0.8 x 100 = 80. Check: 20% of 80 = 16." },
        { label: "Guided practice (10 min):", content: "Students find the whole from a given percentage using the unitary method, then check." },
        { label: "Check (4 min):", content: "Exit question: 25% of a price is $12. What is the full price?" },
      ],
      vocab: "percentage, whole, original, unitary method, 1%, 100%, reverse, find the whole",
      support: "Always find 1% first, then multiply by 100 for the whole.",
      extension: "Solve reverse-percentage problems after a discount (find the original price from a sale price).",
      assessment: "Students find the whole from a percentage — links to G3 in the SOLO Show task.",
    },
  ],
};
