/**
 * Unit 30 — Angles & Time (Stage 3 Year B) — teacher program data.
 * Deliverable B. Built from units/u30/00_rubric_draft.md + 01_mapping_review.md.
 * Matches the UNIT DATA SCHEMA at the bottom of scripts/build_program_template.js.
 *
 * Program has the resource appendix merged at the end (resource_appendix_attached:
 * true); a standalone Unit30_Resource_Appendix.docx is also emitted (Stage 5).
 * Every resource URL verified live in Stage 3 (units/u30/03_resources_staged.csv).
 *
 * Outcome → Mini Lesson map (DoE teaching order: Angles cluster L1-5 first with the
 * Green Stage-4 angle cards beside it, then Time cluster L6-8):
 *   R1→1 R2→2 R3→3 Y1→4 Y2→5 Y3→6 Y4→7 G1→8 G2→9 G3→10 R4→11 Y5→12 Y6→13
 */
module.exports = {
  unit_number: "30",
  unit_title: "Angles & Time",
  term: null,
  duration: "2-3 weeks",

  resource_appendix_attached: true,

  // Every URL verified live in Stage 3 (oEmbed + curl); see units/u30/03_resources_staged.csv.
  resources: {
    r1: [
      { type: "video", label: "How to Measure Angles Using a Protractor | Math with Mr. J", url: "https://www.youtube.com/watch?v=j5D7acsExxw" },
      { type: "video", label: "How to Use a Protractor to Measure an Angle | Math with Mr. J", url: "https://www.youtube.com/watch?v=N8TGOMH5Y50" },
      { type: "video", label: "How to Read a Protractor | Math with Mr. J", url: "https://www.youtube.com/watch?v=QQJoyKQg_qo" },
      { type: "worksheet", label: "Corbettmaths — Measuring Angles (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2018/02/measuring-angles.pdf" },
    ],
    r2: [
      { type: "video", label: "Types of Angles: Acute, Obtuse, Right, Straight, Reflex | Math with Mr. J", url: "https://www.youtube.com/watch?v=UsE1hu-q0Cs" },
      { type: "video", label: "How to Read a Protractor | Math with Mr. J", url: "https://www.youtube.com/watch?v=QQJoyKQg_qo" },
      { type: "worksheet", label: "Corbettmaths Primary — Types of Angles (PDF)", url: "https://corbettmathsprimary.com/wp-content/uploads/2018/06/types-of-angles-pdf.pdf" },
    ],
    r3: [
      { type: "video", label: "Drawing an Angle with a Protractor (110°) | Math with Mr. J", url: "https://www.youtube.com/watch?v=1RtpTO6lSfc" },
      { type: "video", label: "How to Draw Angles with a Protractor | Math with Mr. J", url: "https://www.youtube.com/watch?v=zh-tj7oTQlc" },
      { type: "video", label: "Types of Angles: Acute, Obtuse, Right, Straight, Reflex | Math with Mr. J", url: "https://www.youtube.com/watch?v=UsE1hu-q0Cs" },
      { type: "worksheet", label: "Corbettmaths Primary — Types of Angles (PDF)", url: "https://corbettmathsprimary.com/wp-content/uploads/2018/06/types-of-angles-pdf.pdf" },
    ],
    r4: [
      { type: "video", label: "24 Hour Clock System | Grade 5 | TutWay", url: "https://www.youtube.com/watch?v=5h2OMqAo4Pw" },
      { type: "video", label: "24-12 Hour Time Conversion | Dr Frost Maths", url: "https://www.youtube.com/watch?v=Uz8_xKutjW8" },
      { type: "worksheet", label: "Corbettmaths — Timetables (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/timetables-pdf.pdf" },
    ],
    y1: [
      { type: "video", label: "Parallel, Intersecting, and Perpendicular Lines | Math with Mr. J", url: "https://www.youtube.com/watch?v=u7E1iZdnkeY" },
      { type: "video", label: "Parallel, Intersecting & Perpendicular Lines | Grade 4 | Sheena Doria", url: "https://www.youtube.com/watch?v=kQNHFpFS-ss" },
      { type: "worksheet", label: "Corbettmaths — Angle Facts (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/angle-facts-pdf1.pdf" },
    ],
    y2: [
      { type: "video", label: "Angles on a Straight Line and About a Point | Mr Mathematics", url: "https://www.youtube.com/watch?v=juix_jB1pss" },
      { type: "video", label: "Types of Angles: Acute, Obtuse, Right, Straight, Reflex | Math with Mr. J", url: "https://www.youtube.com/watch?v=UsE1hu-q0Cs" },
      { type: "worksheet", label: "Corbettmaths — Missing Angles (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/missing-angles-pdf1.pdf" },
    ],
    y3: [
      { type: "video", label: "Angles on a Straight Line and About a Point | Mr Mathematics", url: "https://www.youtube.com/watch?v=juix_jB1pss" },
      { type: "worksheet", label: "Corbettmaths — Angle Facts (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/angle-facts-pdf1.pdf" },
      { type: "worksheet", label: "Corbettmaths — Missing Angles (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/missing-angles-pdf1.pdf" },
    ],
    y4: [
      { type: "video", label: "Calculating Angles about a Point | Mr Mathematics", url: "https://www.youtube.com/watch?v=rw29zg1Md8c" },
      { type: "video", label: "Angles on a Straight Line and About a Point | Mr Mathematics", url: "https://www.youtube.com/watch?v=juix_jB1pss" },
      { type: "worksheet", label: "Corbettmaths — Angle Facts (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/angle-facts-pdf1.pdf" },
    ],
    y5: [
      { type: "video", label: "Elapsed Time: Finding Start, End and Total Time | Miacademy", url: "https://www.youtube.com/watch?v=lVAjqxAmUGU" },
      { type: "video", label: "Elapsed Time on a Number Line | eSpark", url: "https://www.youtube.com/watch?v=pwVGOX2pRig" },
      { type: "video", label: "Calculate Duration of Time (the easy way) | Easy Tips", url: "https://www.youtube.com/watch?v=zkN5uLurn4s" },
    ],
    y6: [
      { type: "video", label: "Calculate Duration of Time (the easy way) | Easy Tips", url: "https://www.youtube.com/watch?v=zkN5uLurn4s" },
      { type: "video", label: "Elapsed Time: Finding Start, End and Total Time | Miacademy", url: "https://www.youtube.com/watch?v=lVAjqxAmUGU" },
      { type: "worksheet", label: "Corbettmaths — Timetables (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/timetables-pdf.pdf" },
    ],
    g1: [
      { type: "video", label: "Complementary Angles & Supplementary Angles | Math with Mr. J", url: "https://www.youtube.com/watch?v=Qpq_XEeBBZw" },
      { type: "video", label: "What are Vertical Angles? | Math with Mr. J", url: "https://www.youtube.com/watch?v=DJRTIGwJlbU" },
      { type: "worksheet", label: "Corbettmaths — Angle Facts (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/angle-facts-pdf1.pdf" },
    ],
    g2: [
      { type: "video", label: "Complementary and Supplementary Angles: How to Find Missing Angles | Math with Mr. J", url: "https://www.youtube.com/watch?v=E_ulN2FjJac" },
      { type: "video", label: "Calculating Angles about a Point | Mr Mathematics", url: "https://www.youtube.com/watch?v=rw29zg1Md8c" },
      { type: "worksheet", label: "Corbettmaths — Missing Angles (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/missing-angles-pdf1.pdf" },
    ],
    g3: [
      { type: "video", label: "Angles: Parallel Lines | Corbettmaths", url: "https://www.youtube.com/watch?v=mM-PU6hmkrg" },
      { type: "video", label: "Alternate, Corresponding and Co-interior Angles (Parallel Lines) | Cognito", url: "https://www.youtube.com/watch?v=I5auyoXYoX0" },
      { type: "worksheet", label: "Corbettmaths — Angles in Parallel Lines (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/angles-in-parallel-lines-pdf1.pdf" },
      { type: "worksheet", label: "Corbettmaths — Angles: Parallel Lines (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/angles-parallel-lines-pdf.pdf" },
    ],
  },
  beyond_resources: [
    { type: "video", label: "Complementary Angles & Supplementary Angles | Math with Mr. J", url: "https://www.youtube.com/watch?v=Qpq_XEeBBZw" },
    { type: "video", label: "What are Vertical Angles? | Math with Mr. J", url: "https://www.youtube.com/watch?v=DJRTIGwJlbU" },
    { type: "video", label: "Angles: Parallel Lines | Corbettmaths", url: "https://www.youtube.com/watch?v=mM-PU6hmkrg" },
    { type: "video", label: "Alternate, Corresponding and Co-interior Angles | Cognito", url: "https://www.youtube.com/watch?v=I5auyoXYoX0" },
    { type: "worksheet", label: "Corbettmaths — Angles in Parallel Lines (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/angles-in-parallel-lines-pdf1.pdf" },
    { type: "worksheet", label: "Corbettmaths — Missing Angles (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/missing-angles-pdf1.pdf" },
    { type: "website", label: "Maths is Fun — Angles (interactive)", url: "https://www.mathsisfun.com/angles.html" },
    { type: "website", label: "Maths is Fun — Parallel Lines & Transversals (interactive)", url: "https://www.mathsisfun.com/geometry/parallel-lines.html" },
    { type: "website", label: "Maths is Fun — Supplementary Angles (interactive)", url: "https://www.mathsisfun.com/geometry/supplementary-angles.html" },
    { type: "website", label: "Maths is Fun — Complementary Angles (interactive)", url: "https://www.mathsisfun.com/geometry/complementary-angles.html" },
  ],

  syllabus_strands_summary: "Angles and Time, extended with Stage 4 Angle relationships",
  strand_abbreviations_note: "GM = Geometric Measure (Angles). NSM = Non-spatial Measure (Time). ANG = Angle relationships (Stage 4). A/B = syllabus content groups (A measure/convert fluency, consolidated as prior learning; B relationships/duration, taught as home content).",

  syllabus_outcomes: [
    { code: "MAO-WM-01", descriptor: "Develops understanding and fluency in mathematics through exploring and connecting mathematical concepts, choosing and applying mathematical techniques to solve problems, and communicating their thinking and reasoning coherently and clearly." },
    { code: "MA3-GM-03", descriptor: "Estimates, measures and compares angles, constructs and classifies angles, and investigates the angle relationships formed by intersecting lines." },
    { code: "MA3-NSM-02", descriptor: "Measures and compares duration, using 12- and 24-hour time and am/pm notation, and solves problems involving duration." },
    { code: "MA4-ANG-C-01", descriptor: "Stage 4 (group A): applies angle relationships to solve problems, including complementary, supplementary and vertically opposite angles and those formed by transversals of parallel lines." },
  ],

  content_points: {
    red: {
      heading: "Angles A & Time A (measure & convert fluency)",
      heading_short: "Red -- Foundation",
      points: [
        "Measure angles up to 360° using a protractor.",
        "Estimate angles using benchmarks and record using the degrees symbol (°).",
        "Create angles with a protractor and classify them as acute, obtuse or reflex.",
        "Compare 12- and 24-hour time, convert between them, and read and use timetables.",
      ],
    },
    yellow: {
      heading: "Angles B & Time B (relationships & duration)",
      heading_short: "Yellow -- On-level",
      points: [
        "Perpendicular lines meet at right angles; identify angle types formed by intersecting lines.",
        "Recognise right angles, angles on a straight line and angles at a point embedded in diagrams.",
        "Adjacent angles add to 90° (right angle) and 180° (straight line); find a missing adjacent angle.",
        "Angles at a point add to 360° (angle of revolution).",
        "Calculate elapsed time from start/finish, adding and subtracting time using bridging strategies.",
        "Solve duration problems in 12- and 24-hour time; represent time intervals as decimals.",
      ],
    },
    green: {
      heading: "Extended -- Stage 4 Angle relationships",
      heading_short: "Green -- Extension",
      points: [
        "Identify vertically opposite angles; apply complementary (90°) and supplementary (180°) (MA4-ANG-C-01).",
        "Use angle relationships to find unknown angles in diagrams, giving reasons (MA4-ANG-C-01).",
        "Corresponding, alternate and co-interior angles formed by a transversal of parallel lines (MA4-ANG-C-01).",
      ],
    },
  },

  working_mathematically: [
    { process: "Communicating", description: "Students describe angles using degrees and the language of right/straight/revolution, and describe time in 12- and 24-hour notation." },
    { process: "Understanding and fluency", description: "Students measure and create angles with a protractor, classify angles, and convert between 12- and 24-hour time." },
    { process: "Reasoning", description: "Students reason that adjacent angles add to 90°/180° and angles at a point to 360°, and justify a missing angle or elapsed time." },
    { process: "Problem solving", description: "Students find unknown angles in diagrams and solve duration problems across 12- and 24-hour time, including timetables." },
  ],

  outcomes: [
    { code: "R1", desc: "Measure angles up to 360° using a protractor.", content_point: "GM-A Angles: measure angles of up to 360° using a protractor | MA3-GM-03", lesson_ref: "Mini Lesson 1" },
    { code: "R2", desc: "Estimate angles using benchmarks and record using the degrees symbol (°).", content_point: "GM-A Angles: estimate size using known angles as benchmarks; record using the symbol for degrees (°) | MA3-GM-03", lesson_ref: "Mini Lesson 2" },
    { code: "R3", desc: "Create angles with a protractor and classify them as acute, obtuse or reflex.", content_point: "GM-A Angles: create angles of up to 360° with a protractor; classify acute, obtuse and reflex | MA3-GM-03", lesson_ref: "Mini Lesson 3" },
    { code: "R4", desc: "Compare 12- and 24-hour time, convert between them, and read and use timetables.", content_point: "NSM-A Time: 24-hour time avoids am/pm confusion; convert 24<->12; read/use timetables | MA3-NSM-02", lesson_ref: "Mini Lesson 11" },
    { code: "Y1", desc: "Perpendicular lines meet at right angles; identify angle types formed by intersecting lines.", content_point: "GM-B Angles: perpendicular lines intersect at right angles; identify angle types (right/straight 180°/point 360°) from intersecting lines | MA3-GM-03", lesson_ref: "Mini Lesson 4", pairing_note: "Suggested: pair with Y3" },
    { code: "Y2", desc: "Recognise right angles, angles on a straight line and angles at a point embedded in diagrams.", content_point: "GM-B Angles: recognise right angles, angles on a straight line and angles at a point embedded in diagrams | MA3-GM-03", lesson_ref: "Mini Lesson 5" },
    { code: "Y3", desc: "Adjacent angles add to 90° and 180°; find a missing adjacent angle.", content_point: "GM-B Angles: adjacent angles form a right angle (add to 90°) and on a straight line (add to 180°) | MA3-GM-03", lesson_ref: "Mini Lesson 6" },
    { code: "Y4", desc: "Angles at a point add to 360° (angle of revolution).", content_point: "GM-B Angles: angles at a point form an angle of revolution and add to 360° | MA3-GM-03", lesson_ref: "Mini Lesson 7" },
    { code: "Y5", desc: "Calculate elapsed time from start/finish, adding and subtracting time using bridging strategies.", content_point: "NSM-B Time: use start/finish times to calculate elapsed time; add/subtract time mentally using bridging | MA3-NSM-02", lesson_ref: "Mini Lesson 12" },
    { code: "Y6", desc: "Solve duration problems in 12- and 24-hour time; represent time intervals as decimals.", content_point: "NSM-B Time: represent time intervals as decimals; solve duration problems in 12- and 24-hour notation | MA3-NSM-02", lesson_ref: "Mini Lesson 13" },
    { code: "G1", desc: "Complementary, supplementary and vertically opposite angles.", content_point: "Stage 4 ANG-A: vertically opposite angles; complementary (90°) and supplementary (180°); adjacent angles | MA4-ANG-C-01", lesson_ref: "Mini Lesson 8" },
    { code: "G2", desc: "Find unknown angles using angle relationships and reasoning.", content_point: "Stage 4 ANG-A: use angle relationships (incl. angles at a point) to find unknown angles in diagrams, with reasons | MA4-ANG-C-01", lesson_ref: "Mini Lesson 9" },
    { code: "G3", desc: "Angles formed by a transversal across parallel lines (corresponding, alternate, co-interior).", content_point: "Stage 4 ANG-A: corresponding, alternate and co-interior angle pairs; equal/supplementary on parallel lines | MA4-ANG-C-01", lesson_ref: "Mini Lesson 10", pairing_note: "Suggested: pair with G2" },
  ],

  lessons: [
    {
      num: 1, band: "R",
      title: "Measuring angles with a protractor",
      outcomes: ["R1"], duration: "25-30 min",
      syllabus: "MA3-GM-03, MAO-WM-01 | GM-A: measure angles of up to 360° using a protractor",
      source: "DoE Lesson 3 (adapted)",
      doeLink: "Lesson 3 -- Angles at a point (measuring angles)",
      resources: "Protractors, Resource 1 - using a protractor, Resource 4 - angle identifier, Resource 14 - protractor misconception",
      li: "use a protractor correctly to measure angles up to 360°",
      sc: [
        "I can place the protractor's centre on the vertex and a base line along one arm.",
        "I can read the correct scale (inner or outer) to measure the angle.",
        "I can measure reflex angles up to 360°.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show how a protractor is formed (two 180° halves). Identify the vertex and arms of a marked angle and predict its size." },
        { label: "Model (10 min):", content: "Model measuring a 60° angle: centre on the vertex, base line on one arm, read up from 0 on the correct scale. Then measure an obtuse and a reflex angle (measure the inner angle and subtract from 360° for the reflex)." },
        { label: "Guided practice (10 min):", content: "Students measure a set of angles (acute, obtuse, reflex) and record each, watching for the common 'wrong scale' misconception (Resource 14)." },
        { label: "Check (3 min):", content: "Exit question: measure two given angles and state which scale you read." },
      ],
      vocab: "protractor, angle, vertex, arm, degrees, scale, acute, obtuse, reflex, right angle",
      support: "Use Resource 4 (angle identifier) to confirm right angles first; provide angles already aligned to the base line.",
      extension: "Measure angles where neither arm sits on the base line; measure reflex angles by measuring the inner angle and subtracting from 360°.",
      assessment: "Students measure angles up to 360° accurately with a protractor — links to R1 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["protractors", "angle-identifier card (Resource 4)"],
    },
    {
      num: 2, band: "R",
      title: "Estimating angles and recording in degrees",
      outcomes: ["R2"], duration: "20-25 min",
      syllabus: "MA3-GM-03, MAO-WM-01 | GM-A: estimate using benchmarks; record using the symbol for degrees (°)",
      source: "DoE Lesson 4 (adapted)",
      doeLink: "Lesson 4 -- Angles embedded in diagrams",
      resources: "Benchmark angle fan, protractors, Resource 11 - angles in images",
      li: "estimate the size of angles using benchmark angles and record using the degrees symbol",
      sc: [
        "I can use 90°, 180° and 360° as benchmarks to estimate an angle.",
        "I can say whether an angle is a bit less or a bit more than a benchmark.",
        "I can record a measurement using the ° symbol.",
      ],
      steps: [
        { label: "Activate (3 min):", content: "Show a right angle (90°) and a straight angle (180°) as benchmarks. Show a new angle and ask students to estimate using the benchmarks." },
        { label: "Model (9 min):", content: "Model estimating an angle as 'a bit less than 90°, about 70°', then measure to check, recording 70°. Emphasise the degrees symbol." },
        { label: "Guided practice (9 min):", content: "Students estimate then measure a set of angles, recording both with the ° symbol, and compare estimate to measurement." },
        { label: "Check (3 min):", content: "Exit question: estimate the marked angle using a benchmark, then state how you'd record 125 degrees." },
      ],
      vocab: "estimate, benchmark, right angle, straight angle, degrees, symbol (°), acute, obtuse",
      support: "Provide a benchmark angle fan to hold against each angle before estimating.",
      extension: "Estimate angles in images/photographs and justify the estimate against a benchmark before measuring.",
      assessment: "Students estimate angles using benchmarks and record measurements with the degrees symbol — links to R2 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["benchmark angle fan", "protractors"],
    },
    {
      num: 3, band: "R",
      title: "Creating and classifying angles",
      outcomes: ["R3"], duration: "25-30 min",
      syllabus: "MA3-GM-03, MAO-WM-01 | GM-A: create angles with a protractor; classify acute, obtuse, reflex",
      source: "DoE Lessons 4-5 (adapted)",
      doeLink: "Lessons 4-5 -- Creating angles and classifying angle types",
      resources: "Protractors, rulers, Resource 10 - missing angle",
      li: "construct angles of a given size with a protractor and classify angles as acute, obtuse or reflex",
      sc: [
        "I can draw an angle of a given size using a protractor and ruler.",
        "I can classify an angle as acute (<90°), obtuse (90-180°) or reflex (>180°).",
        "I can name the classification of an angle from its measurement.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Recall the angle types: acute, right, obtuse, straight, reflex. Sort a few measured angles into classes." },
        { label: "Model (10 min):", content: "Model constructing a 130° angle: draw one arm, place the protractor, mark 130°, join. Classify it as obtuse. Then construct and classify a reflex angle (210°)." },
        { label: "Guided practice (10 min):", content: "Students construct a set of given angles, then classify each as acute, obtuse or reflex and label the size in degrees." },
        { label: "Check (3 min):", content: "Exit question: construct a 45° angle and classify it; classify an angle of 250°." },
      ],
      vocab: "construct, create, protractor, acute, right, obtuse, straight, reflex, classify, degrees",
      support: "Provide one arm pre-drawn and the protractor pre-aligned; classify before constructing using a sorted reference.",
      extension: "Construct a reflex angle by drawing its inner angle and reasoning about 360 minus the inner angle; create an angle puzzle for a partner.",
      assessment: "Students construct angles accurately and classify them correctly — links to R3 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["protractors", "rulers"],
    },
    {
      num: 4, band: "Y",
      title: "Perpendicular lines and angle types at intersections",
      outcomes: ["Y1"], duration: "25-30 min",
      syllabus: "MA3-GM-03, MAO-WM-01 | GM-B: perpendicular lines; angle types formed by intersecting lines",
      source: "DoE Lesson 1 (adapted)",
      doeLink: "Lesson 1 -- Perpendicular lines intersect at right angles",
      resources: "Craft sticks, right-angle tester (paper corner/set square), Resource 4 - angle identifier",
      li: "recognise perpendicular lines and identify the angle types formed when straight lines intersect",
      sc: [
        "I know perpendicular lines cross at right angles (90°).",
        "I can identify right angles, angles on a straight line (180°) and angles at a point (360°) at an intersection.",
        "I can find perpendicular lines in the classroom or in pictures.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Cross two craft sticks. Ask when the angle where they cross is exactly 90°, introducing 'perpendicular'." },
        { label: "Model (10 min):", content: "Cross two lines and mark the four angles. Identify the right angles, the angles on a straight line (adding to 180°) and the full turn at the point (360°). Use the right-angle tester to confirm 90°." },
        { label: "Guided practice (10 min):", content: "Students test classroom objects and images for perpendicular lines and label the angle types they find at intersections." },
        { label: "Check (3 min):", content: "Exit question: are these two lines perpendicular? Name one pair of angles on a straight line at the intersection." },
      ],
      vocab: "perpendicular, intersect, right angle, straight line, angle at a point, revolution, degrees",
      support: "Model making a right angle with two craft sticks and confirm with Resource 4; trace the right angle into the workbook.",
      extension: "Find perpendicular lines on a school map or playground and in magazine images; rearrange craft sticks to make a right angle a different way.",
      assessment: "Students recognise perpendicular lines and angle types at intersections — links to Y1 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["craft sticks", "right-angle tester (paper corner / set square)"],
    },
    {
      num: 5, band: "Y",
      title: "Angles embedded in diagrams",
      outcomes: ["Y2"], duration: "20-30 min",
      syllabus: "MA3-GM-03, MAO-WM-01 | GM-B: recognise right angles, angles on a straight line and angles at a point embedded in diagrams",
      source: "DoE Lessons 3-4 (adapted)",
      doeLink: "Lessons 3-4 -- Recognising angles embedded in diagrams",
      resources: "Right-angle tester, Resource 11 - angles in images, Resource 12 - stained glass window, Resource 13 - angles in engineering",
      li: "recognise right angles, angles on a straight line and angles at a point embedded in diagrams",
      sc: [
        "I can find right angles inside a diagram or picture.",
        "I can find angles on a straight line and angles at a point in a diagram.",
        "I can label the angle types I find.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show a stained-glass or engineering image. Ask students to point out a right angle and an angle on a straight line." },
        { label: "Model (9 min):", content: "On a diagram, highlight one type of angle at a time: first right angles, then angles on a straight line, then angles at a point. Use the right-angle tester to confirm." },
        { label: "Guided practice (10 min):", content: "Students mark and label right angles, angles on a straight line and angles at a point in a set of diagrams/images." },
        { label: "Check (3 min):", content: "Exit question: in this diagram, mark one right angle and one angle on a straight line." },
      ],
      vocab: "embedded, diagram, right angle, angle on a straight line, angle at a point, vertex, revolution",
      support: "Find one type of angle at a time; use Resource 4 (angle identifier) to confirm right angles before others.",
      extension: "Find right angles, angles on a straight line and angles at a point in the classroom, on a school map or in design images and justify each.",
      assessment: "Students recognise and label angle types embedded in diagrams — links to Y2 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["right-angle tester", "design/engineering images (Resources 11-13)"],
    },
    {
      num: 6, band: "Y",
      title: "Adjacent angles on a right angle and a straight line",
      outcomes: ["Y3"], duration: "25-30 min",
      syllabus: "MA3-GM-03, MAO-WM-01 | GM-B: adjacent angles add to 90° and to 180°",
      source: "DoE Lessons 2 & 5 (adapted)",
      doeLink: "Lesson 2 -- Adjacent angles that form a right or straight angle",
      resources: "Protractors, house/building plan (Resource), Resource 10 - missing angle",
      li: "investigate adjacent angles that add to 90° and 180° and find a missing adjacent angle",
      sc: [
        "I know two adjacent angles that form a right angle add to 90°.",
        "I know adjacent angles on a straight line add to 180°.",
        "I can find a missing adjacent angle by subtracting from 90° or 180°.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Split a right angle into two adjacent angles. Ask what the two parts must add to (90°)." },
        { label: "Model (10 min):", content: "Model: if one adjacent angle in a right angle is 35°, the other is 90 - 35 = 55°. On a straight line, if one angle is 120°, the other is 180 - 120 = 60°. Check by measuring." },
        { label: "Guided practice (10 min):", content: "Students find missing adjacent angles on right angles and straight lines (Resource 10), and label angles on a building plan." },
        { label: "Check (3 min):", content: "Exit question: one adjacent angle on a straight line is 75° — find the other. Two adjacent angles make a right angle and one is 28° — find the other." },
      ],
      vocab: "adjacent, common arm, common vertex, right angle, straight line, supplementary (sum), missing angle, degrees",
      support: "Use Resource 4 to identify the right angle/straight line first; provide the 'sum = 90 (or 180)' frame to fill in.",
      extension: "Student A measures one adjacent angle and Student B calculates the missing one; create a building plan with some angles given for a partner to complete.",
      assessment: "Students find missing adjacent angles using the 90°/180° relationships — links to Y3 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["protractors", "building/house plan", "missing-angle cards (Resource 10)"],
    },
    {
      num: 7, band: "Y",
      title: "Angles at a point (angle of revolution)",
      outcomes: ["Y4"], duration: "25-30 min",
      syllabus: "MA3-GM-03, MAO-WM-01 | GM-B: angles at a point form an angle of revolution and add to 360°",
      source: "DoE Lessons 3 & 5 (adapted)",
      doeLink: "Lessons 3 & 5 -- Angles at a point",
      resources: "Protractors, pattern blocks, Resource 10 - missing angle",
      li: "investigate angles at a point and establish that they add to 360°, finding a missing angle at a point",
      sc: [
        "I know the angles around a point make a full turn of 360°.",
        "I can measure the angles meeting at a point and check they total 360°.",
        "I can find a missing angle at a point by subtracting from 360°.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Fit pattern blocks around a point. Ask what the angles around the point must total (a full turn, 360°)." },
        { label: "Model (10 min):", content: "Measure three angles meeting at a point (e.g. 120°, 150°, 90°) and check they total 360°. If one is missing, find it by 360 minus the others." },
        { label: "Guided practice (10 min):", content: "Students measure and verify angles at a point total 360°, and find missing angles at a point (Resource 10)." },
        { label: "Check (3 min):", content: "Exit question: three angles at a point are 140°, 100° and one unknown — find the unknown." },
      ],
      vocab: "angle at a point, angle of revolution, full turn, 360 degrees, missing angle, vertex",
      support: "Measure and record one angle of the revolution at a time, then add; use pattern blocks to see the full turn.",
      extension: "Create a 5-armed angle of revolution with a ruler and protractor, then swap with a partner to measure and check.",
      assessment: "Students establish that angles at a point total 360° and find missing angles — links to Y4 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["protractors", "pattern blocks"],
    },
    {
      num: 8, band: "G",
      title: "Complementary, supplementary and vertically opposite angles (Stage 4)",
      outcomes: ["G1"], duration: "30-35 min",
      syllabus: "MA4-ANG-C-01, MAO-WM-01 | Stage 4 ANG-A: complementary, supplementary, vertically opposite angles",
      source: "Original mini lesson",
      li: "identify vertically opposite angles and apply the terms complementary and supplementary",
      sc: [
        "I can name a pair of complementary angles (adding to 90°).",
        "I can name a pair of supplementary angles (adding to 180°).",
        "I can identify vertically opposite angles and know they are equal.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Recall adjacent angles adding to 90° and 180° (Mini Lesson 6). Introduce the names complementary and supplementary." },
        { label: "Model (11 min):", content: "Define complementary (sum 90°) and supplementary (sum 180°). Cross two lines and identify the two pairs of vertically opposite angles, establishing that they are equal." },
        { label: "Guided practice (12 min):", content: "Students find the complement or supplement of given angles and identify vertically opposite pairs at intersections, stating they are equal." },
        { label: "Check (4 min):", content: "Exit question: what is the complement of 35°? The supplement of 110°? Mark a pair of vertically opposite angles." },
      ],
      vocab: "complementary, supplementary, vertically opposite, adjacent, equal, intersect, degrees",
      support: "Provide the 'sum = 90' and 'sum = 180' frames; colour vertically opposite pairs the same colour.",
      extension: "Combine relationships: given one angle at an intersection, find all four angles using vertically opposite and supplementary reasoning.",
      assessment: "Students apply complementary, supplementary and vertically opposite relationships — links to G1 in the SOLO Show task.",
    },
    {
      num: 9, band: "G",
      title: "Finding unknown angles with reasoning (Stage 4)",
      outcomes: ["G2"], duration: "30-35 min",
      syllabus: "MA4-ANG-C-01, MAO-WM-01 | Stage 4 ANG-A: find unknown angles in diagrams using angle relationships, with reasons",
      source: "Original mini lesson",
      li: "use angle relationships to find unknown angles embedded in diagrams and give reasons",
      sc: [
        "I can choose the right relationship (at a point, on a line, vertically opposite) for a diagram.",
        "I can set up a simple equation to find an unknown angle.",
        "I can give a reason for each step.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show a diagram with one unknown angle on a straight line. Ask which relationship helps and why." },
        { label: "Model (12 min):", content: "Model finding x where two angles on a line are x and 110°: x + 110 = 180, so x = 70° (reason: angles on a straight line). Then a 'at a point' example and a vertically opposite example." },
        { label: "Guided practice (12 min):", content: "Students find unknown angles in a set of diagrams, writing the relationship used as a reason for each." },
        { label: "Check (4 min):", content: "Exit question: find x where angles at a point are x, 140° and 90°, and give your reason." },
      ],
      vocab: "unknown angle, equation, angles at a point, angles on a straight line, vertically opposite, reason, justify",
      support: "Provide the relationship to use and the equation frame; restrict to one relationship per diagram first.",
      extension: "Solve diagrams needing two relationships in sequence and write a full reasoned solution.",
      assessment: "Students find unknown angles using angle relationships with reasons — links to G2 in the SOLO Show task.",
    },
    {
      num: 10, band: "G",
      title: "Angles on parallel lines and a transversal (Stage 4)",
      outcomes: ["G3"], duration: "30-40 min",
      syllabus: "MA4-ANG-C-01, MAO-WM-01 | Stage 4 ANG-A: corresponding, alternate and co-interior angles; parallel lines and a transversal",
      source: "Original mini lesson",
      li: "identify corresponding, alternate and co-interior angles formed by a transversal of parallel lines",
      sc: [
        "I can identify corresponding, alternate and co-interior angle pairs.",
        "I know corresponding and alternate angles are equal on parallel lines.",
        "I know co-interior angles are supplementary (add to 180°) on parallel lines.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Draw two parallel lines and a transversal. Name the eight angles formed and ask which look equal." },
        { label: "Model (12 min):", content: "Identify and name corresponding (F), alternate (Z) and co-interior (C) angle pairs. Establish that corresponding and alternate angles are equal and co-interior angles are supplementary on parallel lines." },
        { label: "Guided practice (14 min):", content: "Students name angle pairs on parallel-line diagrams and find unknown angles using the equal/supplementary relationships." },
        { label: "Check (4 min):", content: "Exit question: name the type of angle pair shaded, and find the unknown angle given one is 70° (parallel lines)." },
      ],
      vocab: "transversal, parallel lines, corresponding, alternate, co-interior, equal, supplementary, perpendicular",
      support: "Use F/Z/C shape cues over each pair; colour equal angles the same colour.",
      extension: "Justify that two lines are parallel using alternate or co-interior angle facts; solve multi-step parallel-line diagrams.",
      assessment: "Students identify and use corresponding, alternate and co-interior angles on parallel lines — links to G3 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["grid paper", "ruler"],
    },
    {
      num: 11, band: "R",
      title: "12- and 24-hour time and timetables",
      outcomes: ["R4"], duration: "30 min",
      syllabus: "MA3-NSM-02, MAO-WM-01 | NSM-A: compare 12- and 24-hour time, convert, and read timetables",
      source: "DoE Lessons 6 & 8 (adapted)",
      doeLink: "Lessons 6 & 8 -- 24-hour time and timetables",
      resources: "Geared clock, printed bus/train timetables, Resource 18 - excursion planning",
      li: "convert between 12- and 24-hour time and read and use timetables",
      sc: [
        "I know 24-hour time avoids confusion between am and pm.",
        "I can convert between 24-hour and 12-hour time (e.g. 15:30 = 3:30 pm).",
        "I can read and use a 12- or 24-hour timetable.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Ask whether 7:00 means morning or evening, and how 24-hour time removes the doubt (19:00)." },
        { label: "Model (10 min):", content: "Convert 15:30 to 3:30 pm and 9:15 am to 09:15. Read a bus timetable in 24-hour time and find the next departure after a given time." },
        { label: "Guided practice (12 min):", content: "Students convert a set of times both ways and answer questions from a real timetable (e.g. which train arrives before 4:00 pm)." },
        { label: "Check (4 min):", content: "Exit question: write 20:45 in 12-hour time; using the timetable, find the next bus after 1:10 pm." },
      ],
      vocab: "12-hour time, 24-hour time, am, pm, convert, timetable, departure, arrival",
      support: "Provide a 12<->24 conversion strip; highlight am/pm split at 12:00.",
      extension: "Plan an excursion timetable (Resource 18) using 24-hour time and calculate time at each location.",
      assessment: "Students convert between 12- and 24-hour time and use timetables — links to R4 in the SOLO Show task.",
    },
    {
      num: 12, band: "Y",
      title: "Calculating elapsed time",
      outcomes: ["Y5"], duration: "30 min",
      syllabus: "MA3-NSM-02, MAO-WM-01 | NSM-B: calculate elapsed time; add/subtract time using bridging strategies",
      source: "DoE Lessons 6-7 (adapted)",
      doeLink: "Lessons 6-7 -- Calculating elapsed time",
      resources: "Geared clock, number line, Resource 16 - elapsed times, Resource 17 - elapsed time cards",
      li: "use start and finish times to calculate elapsed time using bridging strategies",
      sc: [
        "I can find elapsed time by counting on from the start time.",
        "I can bridge to the next hour to make the jump easier.",
        "I can add and subtract time mentally to find a duration.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "From 10:40 to 11:25 — ask how long that is. Model bridging to 11:00 first." },
        { label: "Model (10 min):", content: "Model elapsed time on a number line: 10:40 -> 11:00 (20 min) -> 11:25 (25 min), total 45 min. Then a problem crossing several hours." },
        { label: "Guided practice (12 min):", content: "Students calculate elapsed times for a set of start/finish pairs (Resource 16/17) using bridging, recording the jumps." },
        { label: "Check (4 min):", content: "Exit question: how long from 2:50 pm to 4:15 pm? Show your bridging steps." },
      ],
      vocab: "elapsed time, duration, start time, finish time, bridging, count on, number line",
      support: "Use a geared clock to model the jumps; provide questions with o'clock and half-past times first.",
      extension: "Calculate elapsed time mentally and record the strategy; write elapsed-time word problems for a partner.",
      assessment: "Students calculate elapsed time using bridging strategies — links to Y5 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["geared (manipulable) clock", "number line", "elapsed-time cards (Resource 17)"],
    },
    {
      num: 13, band: "Y",
      title: "Duration problems and time as decimals",
      outcomes: ["Y6"], duration: "30-35 min",
      syllabus: "MA3-NSM-02, MAO-WM-01 | NSM-B: solve duration problems in 12/24-hour time; represent time intervals as decimals",
      source: "DoE Lessons 7-8 (adapted)",
      doeLink: "Lessons 7-8 -- Solving problems involving duration",
      resources: "Geared clock, timetables, Resource 18 - excursion planning",
      li: "solve duration problems in 12- and 24-hour time and represent time intervals as decimals",
      sc: [
        "I can solve a duration problem using 12- or 24-hour times.",
        "I can represent common time intervals as decimals (15 min = 0.25 h, 30 min = 0.5 h).",
        "I can work out a finish time given a start time and a duration.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "A movie starts at 18:40 and runs 1 h 35 min. Ask what time it finishes (20:15)." },
        { label: "Model (11 min):", content: "Model finding a finish time by adding a duration across the hour. Then represent intervals as decimals: 15 min = 0.25 h, 45 min = 0.75 h, and use this in a simple rate problem." },
        { label: "Guided practice (12 min):", content: "Students solve a set of duration problems (some in 24-hour time) and convert common intervals to decimals (Resource 18)." },
        { label: "Check (4 min):", content: "Exit question: a train leaves at 14:20 and travels 50 min — when does it arrive? Write 45 minutes as a decimal of an hour." },
      ],
      vocab: "duration, elapsed time, finish time, 24-hour time, decimal, hour, interval, quarter/half hour",
      support: "Use a geared clock to model finish times; provide a fraction-decimal time chart (15/30/45 min).",
      extension: "Plan part of an excursion timetable and express time spent at each stop as a fraction and a decimal of the day.",
      assessment: "Students solve duration problems and represent time intervals as decimals — links to Y6 in the SOLO Show task.",
    },
  ],
};
