/**
 * Unit 34 — Measurement: Mass, Length, Perimeter & Decimals (Stage 3 Year B).
 * Deliverable B. Built from units/u34/00_rubric_draft.md + 01_mapping_review.md.
 * Matches the UNIT DATA SCHEMA at the bottom of scripts/build_program_template.js.
 *
 * Multi-strand measurement unit (mass · length · perimeter · decimals) around the big
 * idea "what needs to be measured determines the unit of measurement".
 *
 * Program has the resource appendix merged (resource_appendix_attached: true); a
 * standalone Unit34_Resource_Appendix.docx is also emitted (Stage 5). Every resource
 * URL verified live in Stage 3 (units/u34/03_resources_staged.csv — 25 videos oEmbed-
 * verified, all worksheets curl HTTP 200).
 *
 * Outcome -> Mini Lesson map (teaching sequence, then Stage-4 Green cards):
 *   R1->1 R2->2 Y1->3 R3->4 Y6->5 R4->6 Y3->7 Y4->8 Y5->9 Y2->10 G1->11 G2->12 G3->13
 */
module.exports = {
  unit_number: "34",
  unit_title: "Measurement — Mass, Length, Perimeter & Decimals",
  term: null,
  duration: "2-3 weeks",

  resource_appendix_attached: true,

  // Every URL verified live in Stage 3 (oEmbed + curl); see units/u34/03_resources_staged.csv.
  resources: {
    r1: [
      { type: "video", label: "Converting Between Fractions, Decimals, and Percents | A Mini Course | Math with Mr. J", url: "https://www.youtube.com/watch?v=2vjbNZaFz3c" },
      { type: "video", label: "Fractions to Percents | Math with Mr. J", url: "https://www.youtube.com/watch?v=XXf4wHb2lYc" },
      { type: "worksheet", label: "Corbettmaths — Fractions, Decimals, Percentages (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/fractions-decimals-percentages-pdf.pdf" },
    ],
    r2: [
      { type: "video", label: "Kilograms and Grams | Converting kg to g and g to kg | Math with Mr. J", url: "https://www.youtube.com/watch?v=zXUICZRXDwQ" },
      { type: "video", label: "Metric Units of Mass | Convert mg, g, and kg | Math with Mr. J", url: "https://www.youtube.com/watch?v=ptrKThVQwh4" },
      { type: "worksheet", label: "Corbettmaths — Metric Units (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/metric-units-pdf.pdf" },
    ],
    r3: [
      { type: "video", label: "Place Value to the Thousandths — Representing Decimal Numbers | Miacademy", url: "https://www.youtube.com/watch?v=BsZJGMRWEK0" },
      { type: "video", label: "Expanded Form with Decimals | Math with Mr. J", url: "https://www.youtube.com/watch?v=GX8o-S6Vxig" },
      { type: "worksheet", label: "Corbettmaths — Place Value (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/place-value-pdf.pdf" },
      { type: "worksheet", label: "Corbettmaths — Ordering Decimals (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/ordering-decimals-pdf1.pdf" },
    ],
    r4: [
      { type: "video", label: "Fractions: Finding the Original | Corbettmaths", url: "https://www.youtube.com/watch?v=pdUg0UwXBHk" },
      { type: "video", label: "Fractions of Numbers: Finding the Whole | Partners in Prime", url: "https://www.youtube.com/watch?v=x0ljSSMfZXw" },
      { type: "worksheet", label: "Corbettmaths — Fractions of Amounts (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/fractions-of-amounts-pdf.pdf" },
    ],
    y1: [
      { type: "video", label: "Metric Mass Measurements — Grams, Kilograms, and Tonnes | Miacademy", url: "https://www.youtube.com/watch?v=Nek4OfX8zKE" },
      { type: "video", label: "Metric Units of Mass | Convert mg, g, and kg | Math with Mr. J", url: "https://www.youtube.com/watch?v=ptrKThVQwh4" },
      { type: "worksheet", label: "Corbettmaths — Metric Units (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/metric-units-pdf.pdf" },
    ],
    y2: [
      { type: "video", label: "Metric Units of Length | Convert mm, cm, m and km | Math with Mr. J", url: "https://www.youtube.com/watch?v=kOJFSH_Bn9U" },
      { type: "video", label: "Meters and Centimeters | Converting m to cm and cm to m | Math with Mr. J", url: "https://www.youtube.com/watch?v=gALZRL4v2NM" },
      { type: "worksheet", label: "Corbettmaths — Metric Units (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/metric-units-pdf.pdf" },
    ],
    y3: [
      { type: "video", label: "Same Area, Different Perimeter | Miss Hutchison", url: "https://www.youtube.com/watch?v=bsl-r7dRSnc" },
      { type: "video", label: "How to Find the Perimeter of a Rectangle | Math with Mr. J", url: "https://www.youtube.com/watch?v=teMDmMxy550" },
      { type: "worksheet", label: "Corbettmaths — Perimeter (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/perimeter-pdf.pdf" },
    ],
    y4: [
      { type: "video", label: "Finding the Area of a Rectangle Using the Formula | Math with Mr. J", url: "https://www.youtube.com/watch?v=1Ugk12y7TQM" },
      { type: "video", label: "How to Find the Area of Rectangles and Squares | Math with Mr. J", url: "https://www.youtube.com/watch?v=_ejDO6aPPzU" },
      { type: "worksheet", label: "Corbettmaths — Area of a Rectangle (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/area-of-a-rectangle-pdf.pdf" },
    ],
    y5: [
      { type: "video", label: "How to Find Perimeter | Math with Mr. J", url: "https://www.youtube.com/watch?v=TSLc5p2VuYM" },
      { type: "video", label: "Finding the Perimeter and Area of a Composite Shape | Math with Mr. J", url: "https://www.youtube.com/watch?v=rBpsauKXPfs" },
      { type: "worksheet", label: "Corbettmaths — Perimeter (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/perimeter-pdf.pdf" },
    ],
    y6: [
      { type: "video", label: "Adding and Subtracting Decimals (How to) | Math with Mr. J", url: "https://www.youtube.com/watch?v=PnwLv6khwk8" },
      { type: "video", label: "How to Add and Subtract Decimals (Step-by-Step Examples) | Math with Mr. J", url: "https://www.youtube.com/watch?v=Cg-_TeiaSa8" },
      { type: "worksheet", label: "Corbettmaths — Adding Decimals (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/adding-decimals-pdf.pdf" },
      { type: "worksheet", label: "Corbettmaths — Subtracting Decimals (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/subtracting-decimals-pdf.pdf" },
    ],
    g1: [
      { type: "video", label: "Finding the Area of a Triangle | A Step-By-Step Guide | Math with Mr. J", url: "https://www.youtube.com/watch?v=-ZPfB1uDjEw" },
      { type: "video", label: "Area of Parallelograms | How to Find the Area of a Parallelogram | Math with Mr. J", url: "https://www.youtube.com/watch?v=uj6k22WubCk" },
      { type: "worksheet", label: "Corbettmaths — Area of a Triangle (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/area-of-a-triangle-pdf.pdf" },
      { type: "worksheet", label: "Corbettmaths — Area of a Parallelogram (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/area-of-a-parallelogram-pdf.pdf" },
    ],
    g2: [
      { type: "video", label: "How to Find the Area of a Composite Shape | L-Shaped Example | Math with Mr. J", url: "https://www.youtube.com/watch?v=LAXHgQwcrDc" },
      { type: "video", label: "Finding the Area of Composite Figures with Triangles | Math with Mr. J", url: "https://www.youtube.com/watch?v=bo483Varm-U" },
      { type: "worksheet", label: "Corbettmaths — Area of Compound Shapes (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/area-of-compound-shapes-pdf.pdf" },
    ],
    g3: [
      { type: "video", label: "Perimeter of Composite Figures | Math with Mr. J", url: "https://www.youtube.com/watch?v=4c_-Q5gADcQ" },
      { type: "video", label: "Circumference of a Circle | Math with Mr. J", url: "https://www.youtube.com/watch?v=_E0C5ECDS0U" },
      { type: "worksheet", label: "Corbettmaths — Circumference (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/circumference-pdf.pdf" },
    ],
  },
  beyond_resources: [
    { type: "video", label: "Finding the Area of a Triangle | Math with Mr. J", url: "https://www.youtube.com/watch?v=-ZPfB1uDjEw" },
    { type: "video", label: "Area of Parallelograms | Math with Mr. J", url: "https://www.youtube.com/watch?v=uj6k22WubCk" },
    { type: "video", label: "How to Find the Area of a Composite Shape | Math with Mr. J", url: "https://www.youtube.com/watch?v=LAXHgQwcrDc" },
    { type: "video", label: "Circumference of a Circle | Math with Mr. J", url: "https://www.youtube.com/watch?v=_E0C5ECDS0U" },
    { type: "worksheet", label: "Corbettmaths — Area of a Triangle (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/area-of-a-triangle-pdf.pdf" },
    { type: "worksheet", label: "Corbettmaths — Area of Compound Shapes (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/area-of-compound-shapes-pdf.pdf" },
    { type: "worksheet", label: "Corbettmaths — Circumference (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/circumference-pdf.pdf" },
    { type: "website", label: "Maths is Fun — Area (interactive)", url: "https://www.mathsisfun.com/area.html" },
    { type: "website", label: "Maths is Fun — Circle (interactive)", url: "https://www.mathsisfun.com/geometry/circle.html" },
  ],

  syllabus_strands_summary: "Mass, Length & Perimeter, Decimals and Additive Relations, extended with Stage 4 Area & Length",
  strand_abbreviations_note: "NSM = Non-spatial measure (mass). GM = Geometric measure (length/perimeter). RN = Represents numbers (decimals). RQF = Representing quantity fractions. AR = Additive relations. ARE/LEN = Area / Length (Stage 4). A/B = syllabus content groups (B is the new measurement content for this Year-B unit).",

  syllabus_outcomes: [
    { code: "MAO-WM-01", descriptor: "Develops understanding and fluency through exploring, applying and communicating mathematical reasoning." },
    { code: "MA3-NSM-01", descriptor: "Selects and uses the appropriate unit and device to measure the masses of objects." },
    { code: "MA3-GM-02", descriptor: "Selects and uses the appropriate unit and device to measure lengths and distances including perimeters." },
    { code: "MA3-RN-02", descriptor: "Compares and orders decimals up to 3 decimal places." },
    { code: "MA3-RQF-02", descriptor: "Determines ½, ¼, ⅕ and ⅓ of measures and quantities; connects fractions, decimals and percentages." },
    { code: "MA3-AR-01", descriptor: "Selects and applies appropriate strategies to solve addition and subtraction problems (including with decimals)." },
    { code: "MA4-ARE / LEN", descriptor: "Stage 4 (group A): area of triangles, parallelograms and composite shapes (ARE); perimeter of composite shapes and circumference of circles (LEN)." },
  ],

  content_points: {
    red: {
      heading: "Measurement & number recall (single procedures)",
      heading_short: "Red -- Foundation",
      points: [
        "Recognise % means per cent; swap between benchmark fractions, decimals and percentages.",
        "Convert between kilograms and grams, and between kilograms and tonnes.",
        "Read and record mass and length using decimal notation to 3 decimal places (whole-number/decimal equivalence).",
        "Generate the whole quantity from a non-unit fractional part.",
      ],
    },
    yellow: {
      heading: "Measurement (applying, multi-step & word problems)",
      heading_short: "Yellow -- On-level",
      points: [
        "Solve problems involving different units of mass.",
        "Convert between metres and kilometres and compare lengths/distances in the same unit.",
        "Investigate and compare perimeters of rectangles with the same area.",
        "Determine the number of different rectangles for a given area.",
        "Solve length and perimeter problems, including problems with different units of length.",
        "Solve word problems involving the addition and subtraction of decimals; justify the strategy.",
      ],
    },
    green: {
      heading: "Extended -- Stage 4 Area & Length",
      heading_short: "Green -- Extension",
      points: [
        "Use formulas to find the area of triangles and parallelograms (MA4-ARE-C-01).",
        "Find the area of composite shapes and convert between area units (cm², m²) (MA4-ARE-C-01).",
        "Find the perimeter of composite shapes and the circumference of circles using C = πd (MA4-LEN-C-01).",
      ],
    },
  },

  working_mathematically: [
    { process: "Communicating", description: "Students describe units of mass and length, justify which unit is most suitable, and explain conversion and perimeter strategies using clear mathematical language." },
    { process: "Understanding and fluency", description: "Students convert between metric units, record measurements in decimal notation to 3 dp, and add and subtract decimals accurately." },
    { process: "Reasoning", description: "Students reason about the relationship between the size of a unit and the number of units, and about rectangles with equal area but different perimeter." },
    { process: "Problem solving", description: "Students solve multi-step mass, length and perimeter word problems, and (Stage 4) area and circumference problems." },
  ],

  outcomes: [
    { code: "R1", desc: "Recognise % means per cent; connect benchmark fractions, decimals and percentages.", content_point: "RQF/RN: recognise that % means percent; identify and use equivalent percentages, decimals and fractions to solve problems | MA3-RQF-02 / MA3-RN-02 | Year B", lesson_ref: "Mini Lesson 1" },
    { code: "R2", desc: "Convert between metric units of mass (kg↔g, kg↔tonnes).", content_point: "NSM-B Mass: convert between kilograms and grams and between kilograms and tonnes | MA3-NSM-01 | Year B", lesson_ref: "Mini Lesson 2" },
    { code: "R3", desc: "Read and record mass and length in decimal notation to 3 decimal places.", content_point: "Measurement decimals (mass = NSM-A, length = GM-B): recognise whole-number/decimal equivalence of measurements; interpret and record mass and length using decimal notation up to 3 dp | MA3-RN-02 / MA3-RN-01 | Year A & B", lesson_ref: "Mini Lesson 4" },
    { code: "R4", desc: "Generate the whole quantity from a non-unit fractional part.", content_point: "RQF: build up to the whole — generate the whole quantity from non-unit fractional parts | MA3-RQF-02 | Year B", lesson_ref: "Mini Lesson 6" },
    { code: "Y1", desc: "Solve problems involving different units of mass.", content_point: "NSM-B Mass: solve problems involving different units of mass | MA3-NSM-01 | Year B", lesson_ref: "Mini Lesson 3" },
    { code: "Y2", desc: "Convert between metres and kilometres and compare lengths in the same unit.", content_point: "GM-B Length: use the decimal place value system to convert between metres and kilometres; convert measurements to the same unit to compare lengths and distances; relate the size of a unit to the number of units | MA3-GM-02 | Year B", lesson_ref: "Mini Lesson 10" },
    { code: "Y3", desc: "Investigate and compare perimeters of rectangles with the same area.", content_point: "GM-B Length/perimeter: investigate and compare perimeters of rectangles with the same area | MA3-GM-02 | Year B", lesson_ref: "Mini Lesson 7" },
    { code: "Y4", desc: "Determine the number of different rectangles for a given area.", content_point: "GM-B Length/perimeter: determine the number of different rectangles that can be formed using whole-number dimensions for a given area | MA3-GM-02 | Year B", lesson_ref: "Mini Lesson 8" },
    { code: "Y5", desc: "Solve length and perimeter problems, including different units of length.", content_point: "GM-B Length/perimeter: solve a variety of problems involving length and perimeter, including problems involving different units of length | MA3-GM-02 | Year B", lesson_ref: "Mini Lesson 9" },
    { code: "Y6", desc: "Solve word problems adding and subtracting decimals; justify the strategy.", content_point: "AR-B: solve word problems involving the addition and subtraction of decimals; justify why the strategy used is appropriate | MA3-AR-01 | Year B", lesson_ref: "Mini Lesson 5" },
    { code: "G1", desc: "Use formulas to find the area of triangles and parallelograms.", content_point: "Stage 4 ARE-A: establish and use the formula to find the area of a parallelogram and of a triangle | MA4-ARE-C-01 | Stage 4 (group A)", lesson_ref: "Mini Lesson 11" },
    { code: "G2", desc: "Find the area of composite shapes; convert between area units (cm², m²).", content_point: "Stage 4 ARE-A: find the area of composite figures by dissection; convert between metric units of area | MA4-ARE-C-01 | Stage 4 (group A)", lesson_ref: "Mini Lesson 12" },
    { code: "G3", desc: "Find the perimeter of composite shapes and the circumference of circles.", content_point: "Stage 4 LEN-A: find the perimeter of composite plane shapes; calculate the circumference of a circle using C = πd | MA4-LEN-C-01 | Stage 4 (group A)", lesson_ref: "Mini Lesson 13" },
  ],

  lessons: [
    {
      num: 1, band: "R",
      title: "Fractions, decimals and percentages",
      outcomes: ["R1"], duration: "20-25 min",
      syllabus: "MA3-RQF-02, MA3-RN-02, MAO-WM-01 | FDP: % means per cent; equivalent fractions, decimals, percentages",
      source: "DoE Lessons 1-3 (adapted)",
      doeLink: "Lessons 1-3 -- Daily number sense: fractions, decimals and percentages",
      resources: "Resource 1 - grid paper, individual whiteboards",
      li: "make connections between benchmark fractions, decimals and percentages",
      sc: [
        "I know % means 'per cent' (out of 100).",
        "I can match benchmark fractions, decimals and percentages (e.g. ½ = 50% = 0.5).",
        "I can use equivalent forms to solve a simple problem.",
      ],
      steps: [
        { label: "Activate (3 min):", content: "Shade ½ of a 10x10 grid; ask the percentage and decimal. Establish % = out of 100." },
        { label: "Model (10 min):", content: "Benchmark table: ½ = 50% = 0.5; ¼ = 25% = 0.25; ¾ = 75% = 0.75." },
        { label: "Guided practice (8 min):", content: "Students convert between benchmark fractions, decimals and percentages (e.g. 50% of 60)." },
        { label: "Check (3 min):", content: "Exit: write 0.75 as a fraction and a percentage." },
      ],
      vocab: "per cent, %, fraction, decimal, percentage, equivalent, benchmark, out of 100",
      support: "Use a shaded 10x10 grid; start with ½ and ¼.",
      extension: "Convert 12 out of 60 to a fraction, decimal and percentage.",
      assessment: "Students connect benchmark fractions, decimals and percentages — links to R1.",
    },
    {
      num: 2, band: "R",
      title: "Converting units of mass",
      outcomes: ["R2"], duration: "25-30 min",
      syllabus: "MA3-NSM-01, MAO-WM-01 | NSM-B: convert between kilograms and grams and between kilograms and tonnes",
      source: "DoE Lesson 1 (adapted)",
      doeLink: "Lesson 1 -- Pumpkin mass",
      resources: "Equal-arm balances or digital scales, metric weights, Resource 2 - world's largest pumpkins",
      li: "convert between common metric units of mass",
      sc: [
        "I know 1 kg = 1000 g and 1 tonne = 1000 kg.",
        "I can convert between grams and kilograms.",
        "I can convert between kilograms and tonnes.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Heft and weigh a pumpkin piece. Record its mass in grams, then ask how to write the same mass in kilograms." },
        { label: "Model (10 min):", content: "Convert 2500 g = 2.5 kg (÷1000), 3 kg = 3000 g (x1000), 1200 kg = 1.2 t (÷1000). Use a place-value chart to show the x1000 / ÷1000 shift." },
        { label: "Guided practice (10 min):", content: "Students convert masses between g, kg and tonnes using scales and the world's-largest-pumpkins data." },
        { label: "Check (4 min):", content: "Exit question: 4500 g = ___ kg, and 2.3 t = ___ kg." },
      ],
      vocab: "mass, gram, kilogram, tonne, convert, x1000, divide by 1000, place value",
      support: "Provide a g-kg-t conversion chart; use scales to read masses in both g and kg.",
      extension: "Convert masses given in decimal tonnes (e.g. 0.085 t) to kilograms and grams.",
      assessment: "Students convert between metric units of mass — links to R2 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["equal-arm balances or digital scales", "metric weights"],
    },
    {
      num: 3, band: "Y",
      title: "Mass problems with different units",
      outcomes: ["Y1"], duration: "30 min",
      syllabus: "MA3-NSM-01, MAO-WM-01 | NSM-B: solve problems involving different units of mass",
      source: "DoE Lessons 2 & 3 (adapted)",
      doeLink: "Lessons 2 & 3 -- Which unit is best? / mass word problems",
      resources: "Resource 4 - grams, kilograms, tonnes?, Resource 6 - household waste, individual whiteboards",
      li: "solve problems involving different units of mass",
      sc: [
        "I can choose the most suitable unit (g, kg or tonnes) for an object.",
        "I can convert so masses are in the same unit before comparing or adding.",
        "I can solve a word problem that mixes units of mass.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Sort items (apple, school bag, car, dining table) to the best unit of mass. Discuss why a dining table is best in kg, not g." },
        { label: "Model (10 min):", content: "Solve a mixed-unit problem: a bin holds 8 kg, another holds 3500 g — total in kg? Convert first (3.5 kg), then add (11.5 kg)." },
        { label: "Guided practice (12 min):", content: "Students solve household-waste problems, converting between kg and tonnes and comparing masses across units." },
        { label: "Check (4 min):", content: "Exit question: a recycling centre collects 4.5 t of paper in bags of 250 kg — how many bags?" },
      ],
      vocab: "mass, unit, gram, kilogram, tonne, convert, compare, total, difference",
      support: "Provide the converted values so students focus on choosing the unit and solving.",
      extension: "Solve multi-step problems mixing all three units (g, kg, t) with decimals.",
      assessment: "Students solve problems involving different units of mass — links to Y1 in the SOLO Show task.",
    },
    {
      num: 4, band: "R",
      title: "Decimal notation for measurements",
      outcomes: ["R3"], duration: "25-30 min",
      syllabus: "MA3-RN-02, MA3-RN-01, MAO-WM-01 | RN-B: decimal notation for masses and lengths up to 3 dp",
      source: "DoE Lessons 3 & 4 (adapted)",
      doeLink: "Lessons 3 & 4 -- Crocodile facts and measurements",
      resources: "Place-value chart, Resource 11 - crocodile measurements, Resource 12 - crocodile conversion chart",
      li: "connect decimal representations to the metric system and record measurements to 3 decimal places",
      sc: [
        "I know a whole-number and a decimal can name the same measurement (e.g. 2500 g = 2.5 kg).",
        "I can interpret a mass or length written in decimal notation.",
        "I can record a mass or length using decimal notation up to 3 decimal places.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show 1 m 250 mm on a place-value chart. Ask how to write it as a decimal number of metres (1.250 m)." },
        { label: "Model (10 min):", content: "Record 2 kg 350 g = 2.350 kg, 4 m 75 cm = 4.75 m, 1 m 8 mm = 1.008 m. Stress each place value (tenths, hundredths, thousandths)." },
        { label: "Guided practice (10 min):", content: "Students convert crocodile masses and lengths into decimal notation to 3 dp and back." },
        { label: "Check (4 min):", content: "Exit question: write 3 kg 60 g in kilograms as a decimal, and 2.045 m in metres and millimetres." },
      ],
      vocab: "decimal notation, tenths, hundredths, thousandths, place value, equivalent, mass, length",
      support: "Use a labelled place-value chart with columns for tenths/hundredths/thousandths.",
      extension: "Order a set of measurements written in mixed units by first writing each to 3 dp.",
      assessment: "Students record measurements in decimal notation to 3 dp — links to R3 in the SOLO Show task.",
    },
    {
      num: 5, band: "Y",
      title: "Adding and subtracting decimals",
      outcomes: ["Y6"], duration: "30 min",
      syllabus: "MA3-AR-01, MAO-WM-01 | AR-B: add and subtract decimals to solve word problems; justify the strategy",
      source: "DoE Lessons 2, 3 & 6 (adapted)",
      doeLink: "Lessons 2, 3 & 6 -- Decimal addition and subtraction strategies",
      resources: "Decimal place-value chart, individual whiteboards",
      li: "solve word problems involving the addition and subtraction of decimals and justify the strategy used",
      sc: [
        "I can line up decimal points to add and subtract decimals.",
        "I can choose an efficient strategy (levelling, constant difference, bridging).",
        "I can justify why my strategy works for the problem.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show 2.65 + 1.4. Ask why lining up the decimal points (and the place values) matters." },
        { label: "Model (10 min):", content: "Add 12.75 + 8.6 and subtract 9.3 - 4.85 using a written strategy; then use constant difference for 6.02 - 5.97. Justify each choice." },
        { label: "Guided practice (12 min):", content: "Students solve decimal word problems (lengths, masses, money), choosing and justifying a strategy." },
        { label: "Check (4 min):", content: "Exit question: a ribbon is 3.4 m; 1.85 m is cut off — how much is left? Show your strategy." },
      ],
      vocab: "decimal, decimal point, place value, levelling, constant difference, bridging, justify, strategy",
      support: "Use a place-value chart and grid so digits line up; start with one-decimal-place numbers.",
      extension: "Solve multi-step decimal problems mixing addition and subtraction, and explain the most efficient order.",
      assessment: "Students add and subtract decimals in word problems and justify the strategy — links to Y6 in the SOLO Show task.",
    },
    {
      num: 6, band: "R",
      title: "Building the whole from a part",
      outcomes: ["R4"], duration: "20-25 min",
      syllabus: "MA3-RQF-02, MAO-WM-01 | RQF: generate the whole quantity from non-unit fractional parts",
      source: "DoE Lessons 5-7 (adapted)",
      doeLink: "Lessons 5-7 -- Daily number sense: build up to the whole",
      resources: "Fraction bars, counters",
      li: "generate the whole quantity from a non-unit fractional part",
      sc: [
        "I can find one part when I know a non-unit fraction (e.g. if ¾ is 18, one quarter is 6).",
        "I can build up to the whole from the part.",
        "I can check by finding the fraction of my answer.",
      ],
      steps: [
        { label: "Activate (3 min):", content: "Tell students ¾ of a bag of marbles is 18. Ask how many marbles are in the whole bag." },
        { label: "Model (9 min):", content: "Use a fraction bar: ¾ = 18, so each quarter (÷3) = 6, and the whole (x4) = 24. Repeat with ⅖ = 10 -> whole = 25." },
        { label: "Guided practice (10 min):", content: "Students find the whole from a given non-unit fractional part using a bar model, then check." },
        { label: "Check (3 min):", content: "Exit question: ⅔ of a length is 12 m. How long is the whole length?" },
      ],
      vocab: "fraction, non-unit fraction, part, whole, unit fraction, build up, divide, multiply",
      support: "Draw the fraction bar and find one part first; use counters for the part.",
      extension: "Find the whole from a part for fractions like ⅗ and ⅝, then find a different fraction of that whole.",
      assessment: "Students generate the whole from a fractional part — links to R4 in the SOLO Show task.",
    },
    {
      num: 7, band: "Y",
      title: "Same area, different perimeter",
      outcomes: ["Y3"], duration: "30-35 min",
      syllabus: "MA3-GM-02, MAO-WM-01 | GM-B: investigate and compare perimeters of rectangles with the same area",
      source: "DoE Lessons 5 & 6 (adapted)",
      doeLink: "Lessons 5 & 6 -- Different shapes, same perimeter / Darryl's fencing",
      resources: "1 cm grid paper, 30 cm rulers, individual whiteboards",
      li: "investigate and compare perimeters of rectangles with the same area",
      sc: [
        "I can draw different rectangles that all have the same area.",
        "I can find the perimeter of each rectangle.",
        "I can compare the perimeters and say which is largest or smallest.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "On grid paper, draw a rectangle with area 12 cm². Ask whether another rectangle of area 12 cm² has the same perimeter." },
        { label: "Model (12 min):", content: "Draw all rectangles of area 12 cm² (1x12, 2x6, 3x4) and find each perimeter (26, 16, 14 cm). Notice the closer to a square, the smaller the perimeter." },
        { label: "Guided practice (14 min):", content: "Students investigate rectangles with a fixed area (e.g. 24 cm²), record perimeters in a table, and compare." },
        { label: "Check (4 min):", content: "Exit question: two rectangles both have area 16 cm². Could they have different perimeters? Give an example." },
      ],
      vocab: "area, perimeter, rectangle, dimensions, length, width, compare, square",
      support: "Provide grid paper with the area outlined; help count perimeter by ones around the edge.",
      extension: "For a fixed area, predict which rectangle gives the smallest perimeter and explain why.",
      assessment: "Students compare perimeters of rectangles with the same area — links to Y3 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["1 cm grid paper", "30 cm rulers"],
    },
    {
      num: 8, band: "Y",
      title: "Rectangles for a given area",
      outcomes: ["Y4"], duration: "30 min",
      syllabus: "MA3-GM-02, MAO-WM-01 | GM-B: determine the number of different rectangles for a given area",
      source: "DoE Lessons 5 & 6 (adapted)",
      doeLink: "Lessons 5 & 6 -- Different shapes, same perimeter",
      resources: "1 cm grid paper, individual whiteboards",
      li: "determine the number of different rectangles that can be formed using whole-number dimensions for a given area",
      sc: [
        "I can use factors to find whole-number side lengths for a given area.",
        "I can list all the different rectangles with that area.",
        "I can say how many different rectangles there are.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Ask how many different whole-number rectangles have an area of 12 cm². Connect to factor pairs of 12." },
        { label: "Model (10 min):", content: "List factor pairs of 12 (1x12, 2x6, 3x4) -> 3 rectangles. Repeat for area 16 (1x16, 2x8, 4x4) -> 3 rectangles. Treat 2x6 and 6x2 as the same." },
        { label: "Guided practice (12 min):", content: "Students find all rectangles for given areas (e.g. 18, 24, 36 cm²) using factor pairs and count them." },
        { label: "Check (4 min):", content: "Exit question: how many different rectangles (whole-number sides) have an area of 20 cm²? List them." },
      ],
      vocab: "area, rectangle, factor, factor pair, dimensions, whole number, square",
      support: "Provide a factor list for the target number; build each rectangle on grid paper.",
      extension: "Find an area with exactly 2 (or exactly 4) different rectangles and explain using factors.",
      assessment: "Students determine the number of rectangles for a given area — links to Y4 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["1 cm grid paper"],
    },
    {
      num: 9, band: "Y",
      title: "Length and perimeter problems",
      outcomes: ["Y5"], duration: "30-35 min",
      syllabus: "MA3-GM-02, MAO-WM-01 | GM-B: solve length and perimeter problems including different units",
      source: "DoE Lessons 5-8 (adapted)",
      doeLink: "Lessons 5-8 -- Fencing, mystery bones and mega trees",
      resources: "Resource 14 - missing perimeter problems, soft measuring tape, 30 cm rulers",
      li: "solve a variety of problems involving length and perimeter, including problems involving different units of length",
      sc: [
        "I can find a missing side length using the perimeter.",
        "I can solve perimeter problems where lengths are in different units.",
        "I can solve a real-life length or perimeter problem.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "A rectangle has perimeter 30 cm and one side 7 cm. Ask how to find the other side." },
        { label: "Model (12 min):", content: "Find a missing side from the perimeter; then a fencing problem mixing units (sides 1.2 m and 80 cm) — convert to the same unit first, then add." },
        { label: "Guided practice (14 min):", content: "Students solve missing-side, mixed-unit and real-life perimeter problems (gardens, fences), converting units as needed." },
        { label: "Check (4 min):", content: "Exit question: a garden has a perimeter of 15.5 m with 4 sides — give one possible set of side lengths." },
      ],
      vocab: "length, perimeter, side, convert, unit, metre, centimetre, missing side, total",
      support: "Provide the conversion and a labelled diagram; find one missing side at a time.",
      extension: "Design an irregular shape with a given perimeter and justify the side lengths chosen.",
      assessment: "Students solve length and perimeter problems with different units — links to Y5 in the SOLO Show task.",
    },
    {
      num: 10, band: "Y",
      title: "Converting and comparing lengths",
      outcomes: ["Y2"], duration: "30 min",
      syllabus: "MA3-GM-02, MAO-WM-01 | GM-B: convert between metres and kilometres; compare lengths in the same unit",
      source: "DoE Lessons 7 & 8 (adapted)",
      doeLink: "Lessons 7 & 8 -- Mystery bones and mega trees",
      resources: "Resource 20 - conversion chart, trundle wheels, soft measuring tape",
      li: "use the decimal place value system to convert between metres and kilometres and compare lengths and distances",
      sc: [
        "I know 1 km = 1000 m and can convert between metres and kilometres.",
        "I can convert measurements to the same unit before comparing them.",
        "I understand that a larger unit needs a smaller measure for the same length.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show 2500 m. Ask how to write it in kilometres (2.5 km). Discuss why the number gets smaller when the unit gets bigger." },
        { label: "Model (10 min):", content: "Convert 1.8 km = 1800 m, 3450 m = 3.45 km. Compare distances by converting to the same unit (e.g. 0.9 km vs 950 m)." },
        { label: "Guided practice (12 min):", content: "Students convert m<->km using the conversion chart and order a set of distances given in mixed units." },
        { label: "Check (4 min):", content: "Exit question: order 1.2 km, 950 m and 1100 m from shortest to longest." },
      ],
      vocab: "length, distance, metre, kilometre, convert, place value, compare, order, unit",
      support: "Provide a m-km conversion chart; convert everything to metres before comparing.",
      extension: "Convert tree heights and diameters to mm and cm, and investigate relationships between the measurements.",
      assessment: "Students convert and compare metric units of length — links to Y2 in the SOLO Show task.",
    },
    {
      num: 11, band: "G",
      title: "Area of triangles and parallelograms (Stage 4)",
      outcomes: ["G1"], duration: "30-35 min",
      syllabus: "MA4-ARE-C-01, MAO-WM-01 | Stage 4 ARE-A: area of triangles and parallelograms",
      source: "Original mini lesson",
      li: "use formulas to find the area of triangles and parallelograms",
      sc: [
        "I can find the area of a parallelogram using base x height.",
        "I can find the area of a triangle using ½ x base x height.",
        "I can identify the perpendicular height to use.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show a parallelogram. Cut and rearrange it into a rectangle to see that area = base x height." },
        { label: "Model (12 min):", content: "Find the area of a parallelogram (base 8 cm, height 5 cm = 40 cm²) and a triangle (½ x 8 x 5 = 20 cm²). Stress using the perpendicular height, not the slant side." },
        { label: "Guided practice (12 min):", content: "Students find areas of triangles and parallelograms from given base and height measurements." },
        { label: "Check (5 min):", content: "Exit question: find the area of a triangle with base 10 cm and height 6 cm." },
      ],
      vocab: "area, base, perpendicular height, parallelogram, triangle, formula, square units",
      support: "Provide the formula and a labelled diagram; identify the height before substituting.",
      extension: "Find a missing base or height when given the area, by working backwards from the formula.",
      assessment: "Students find the area of triangles and parallelograms — links to G1 in the SOLO Show task.",
    },
    {
      num: 12, band: "G",
      title: "Composite area and area units (Stage 4)",
      outcomes: ["G2"], duration: "30-35 min",
      syllabus: "MA4-ARE-C-01, MAO-WM-01 | Stage 4 ARE-A: composite area by dissection; convert area units",
      source: "Original mini lesson",
      li: "find the area of composite shapes and convert between area units",
      sc: [
        "I can split a composite (L-shape) figure into rectangles.",
        "I can add the part areas to find the total area.",
        "I can convert between cm² and m².",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show an L-shaped figure. Ask how we could split it to find its area." },
        { label: "Model (12 min):", content: "Dissect an L-shape into two rectangles, find each area, and add. Then convert: 1 m² = 10 000 cm², so 30 000 cm² = 3 m²." },
        { label: "Guided practice (12 min):", content: "Students find areas of composite figures by dissection and convert areas between cm² and m²." },
        { label: "Check (5 min):", content: "Exit question: an L-shape splits into a 6x4 and a 3x2 rectangle — what is its total area?" },
      ],
      vocab: "composite figure, dissect, rectangle, area, total, square centimetre, square metre, convert",
      support: "Mark the dividing line on the figure; provide each rectangle's dimensions.",
      extension: "Find a missing length in a composite figure when the total area is given.",
      assessment: "Students find composite areas and convert area units — links to G2 in the SOLO Show task.",
    },
    {
      num: 13, band: "G",
      title: "Composite perimeter and circumference (Stage 4)",
      outcomes: ["G3"], duration: "30 min",
      syllabus: "MA4-LEN-C-01, MAO-WM-01 | Stage 4 LEN-A: perimeter of composite shapes; circumference of circles",
      source: "Original mini lesson",
      li: "find the perimeter of composite shapes and the circumference of circles",
      sc: [
        "I can find the perimeter of a composite shape by finding all side lengths.",
        "I know the circumference of a circle is C = π x diameter.",
        "I can calculate a circumference using π ≈ 3.14.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show an L-shaped figure with some sides missing. Ask how to work out the missing sides before adding the perimeter." },
        { label: "Model (11 min):", content: "Find the perimeter of a composite shape by deducing missing sides. Then introduce C = πd: a circle with diameter 10 cm has C ≈ 3.14 x 10 = 31.4 cm." },
        { label: "Guided practice (11 min):", content: "Students find perimeters of composite shapes and circumferences of circles (given the diameter) using π ≈ 3.14." },
        { label: "Check (4 min):", content: "Exit question: find the circumference of a circle with diameter 8 cm (use π ≈ 3.14)." },
      ],
      vocab: "perimeter, composite shape, missing side, circle, circumference, diameter, radius, pi (π)",
      support: "Provide the missing side lengths and the formula C = πd; use π ≈ 3.14.",
      extension: "Find the circumference from the radius (C = 2πr), and the perimeter of a shape made from a rectangle and a half-circle.",
      assessment: "Students find composite perimeters and circumferences — links to G3 in the SOLO Show task.",
    },
  ],
};
