/**
 * Unit 36 — Fractions & Chance (Stage 3 Year B).
 * Deliverable B. Built from units/u36/00_rubric_draft.md + 01_mapping_review.md.
 * Matches the UNIT DATA SCHEMA at the bottom of scripts/build_program_template.js.
 *
 * Fractions unit (the whole & different-sized wholes, FDP benchmarks, fractions of numbers,
 * comparing/ordering related denominators, complement principle, equivalence add/subtract,
 * word problems) with a chance strand (probabilities using fractions & benchmark FDP).
 *
 * Program has the resource appendix merged (resource_appendix_attached: true); a standalone
 * Unit36_Resource_Appendix.docx is also emitted (Stage 5). Every resource URL verified live
 * in Stage 3 (units/u36/03_resources_staged.csv).
 *
 * Outcome -> Mini Lesson map (teaching sequence, then Stage-4 Green cards):
 *   R1->1 Y1->2 R2->3 R3->4 Y2->5 Y3->6 R4->7 Y4->8 Y5->9 Y6->10 G1->11 G2->12 G3->13
 */
module.exports = {
  unit_number: "36",
  unit_title: "Fractions & Chance",
  term: null,
  duration: "2-3 weeks",

  resource_appendix_attached: true,

  // Every URL verified live in Stage 3 (oEmbed + curl); see units/u36/03_resources_staged.csv.
  resources: {
    r1: [
      { type: "video", label: "Fractions — Understanding the Language | Math with Mr. J", url: "https://www.youtube.com/watch?v=38KfKBpwAv4" },
      { type: "video", label: "Fractions — A Mini Review Course | Math with Mr. J", url: "https://www.youtube.com/watch?v=9UFyLHY8yPc" },
      { type: "worksheet", label: "Corbettmaths — Fractions (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/fractions-pdf.pdf" },
    ],
    r2: [
      { type: "video", label: "Converting Between Fractions, Decimals, and Percents | Math with Mr. J", url: "https://www.youtube.com/watch?v=2vjbNZaFz3c" },
      { type: "video", label: "Modeling Equivalent Fractions | Math with Mr. J", url: "https://www.youtube.com/watch?v=pIognJLah-I" },
      { type: "worksheet", label: "Corbettmaths — Fractions, Decimals, Percentages (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/fractions-decimals-percentages-pdf.pdf" },
    ],
    r3: [
      { type: "video", label: "How to Find Fractions of Amounts (Step-by-Step) | Maths with Mrs B", url: "https://www.youtube.com/watch?v=Md4Oeb_xDUk" },
      { type: "video", label: "How to Find a Fraction of a Whole Number | The Organic Chemistry Tutor", url: "https://www.youtube.com/watch?v=ZPtxMHtXCM4" },
      { type: "worksheet", label: "Corbettmaths — Fractions of Amounts (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/fractions-of-amounts-pdf.pdf" },
    ],
    r4: [
      { type: "video", label: "Subtracting a Fraction from a Whole Number | Math with Mr. J", url: "https://www.youtube.com/watch?v=xCcld_YyVhM" },
      { type: "video", label: "Subtracting Fractions with Like Denominators | Math with Mr. J", url: "https://www.youtube.com/watch?v=QL4KiVVmreI" },
      { type: "worksheet", label: "Corbettmaths — Fractions (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/fractions-pdf.pdf" },
    ],
    y1: [
      { type: "video", label: "Fractions: Finding the Original | Corbettmaths", url: "https://www.youtube.com/watch?v=pdUg0UwXBHk" },
      { type: "video", label: "Fractions of Numbers: Finding the Whole | Partners in Prime", url: "https://www.youtube.com/watch?v=x0ljSSMfZXw" },
      { type: "worksheet", label: "Corbettmaths — Fractions of Amounts (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/fractions-of-amounts-pdf.pdf" },
    ],
    y2: [
      { type: "video", label: "Comparing Fractions | How to Compare Fractions | Math with Mr. J", url: "https://www.youtube.com/watch?v=u_QTuWj107o" },
      { type: "video", label: "Modeling Equivalent Fractions | Math with Mr. J", url: "https://www.youtube.com/watch?v=pIognJLah-I" },
      { type: "worksheet", label: "Corbettmaths — Equivalent Fractions (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/equivalent-fractions-pdf.pdf" },
    ],
    y3: [
      { type: "video", label: "Ordering Fractions | Math with Mr. J", url: "https://www.youtube.com/watch?v=i2PfHDs88YE" },
      { type: "video", label: "Comparing Fractions | How to Compare Fractions | Math with Mr. J", url: "https://www.youtube.com/watch?v=u_QTuWj107o" },
      { type: "worksheet", label: "Corbettmaths — Ordering Fractions (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/ordering-fractions-pdf.pdf" },
    ],
    y4: [
      { type: "video", label: "Subtracting Fractions with Common Denominators (Step by Step) | Math with Mr. J", url: "https://www.youtube.com/watch?v=VTCOHFJOAA8" },
      { type: "video", label: "Adding & Subtracting Fractions with Unlike Denominators | Math with Mr. J", url: "https://www.youtube.com/watch?v=XsW8HJutIgM" },
      { type: "worksheet", label: "Corbettmaths — Adding Fractions: Same Denominators (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2018/11/Fractions-Addition-1-pdf.pdf" },
    ],
    y5: [
      { type: "video", label: "Adding and Subtracting Fractions Word Problems | Math with Mr. J", url: "https://www.youtube.com/watch?v=JgQSMwNOWCI" },
      { type: "video", label: "Subtracting Fractions — Fraction Word Problems | Math with Mr. J", url: "https://www.youtube.com/watch?v=sxu_i1_SMqM" },
      { type: "worksheet", label: "Corbettmaths — Fractions (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/fractions-pdf.pdf" },
    ],
    y6: [
      { type: "video", label: "An Intro to Probability | Basic Probability | Math with Mr. J", url: "https://www.youtube.com/watch?v=6IdNYdA6no8" },
      { type: "video", label: "An Intro to Finding Probability | Math with Mr. J", url: "https://www.youtube.com/watch?v=zE-Y_QCHOt8" },
      { type: "worksheet", label: "Corbettmaths — Probability (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/probability-pdf.pdf" },
    ],
    g1: [
      { type: "video", label: "Adding & Subtracting Fractions with Unlike Denominators | Math with Mr. J", url: "https://www.youtube.com/watch?v=XsW8HJutIgM" },
      { type: "video", label: "Adding Fractions with Unlike Denominators | Math with Mr. J", url: "https://www.youtube.com/watch?v=CoCmsyFQ_Xc" },
      { type: "worksheet", label: "Corbettmaths — Adding Fractions (Different Denominators) (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2024/01/Adding-Fractions.pdf" },
    ],
    g2: [
      { type: "video", label: "Multiplying Whole Numbers and Fractions | Math with Mr. J", url: "https://www.youtube.com/watch?v=2gFCEY9Hxas" },
      { type: "video", label: "How to Multiply a Whole Number by a Fraction | Math with Mr. J", url: "https://www.youtube.com/watch?v=Z6liyRWnLv4" },
      { type: "worksheet", label: "Corbettmaths — Multiplying Fractions (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/multiplying-fractions-pdf.pdf" },
    ],
    g3: [
      { type: "video", label: "Calculating Probability (Practice Problems Included) | Math with Mr. J", url: "https://www.youtube.com/watch?v=m95FVOfCx44" },
      { type: "video", label: "Complementary Events in Probability | Math and Stats Help", url: "https://www.youtube.com/watch?v=hJbj7UQIJNw" },
      { type: "worksheet", label: "Corbettmaths — Probability (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/probability-pdf.pdf" },
    ],
  },
  beyond_resources: [
    { type: "video", label: "Adding & Subtracting Fractions with Unlike Denominators | Math with Mr. J", url: "https://www.youtube.com/watch?v=XsW8HJutIgM" },
    { type: "video", label: "Multiplying Whole Numbers and Fractions | Math with Mr. J", url: "https://www.youtube.com/watch?v=2gFCEY9Hxas" },
    { type: "video", label: "Calculating Probability | Math with Mr. J", url: "https://www.youtube.com/watch?v=m95FVOfCx44" },
    { type: "video", label: "Complementary Events in Probability | Math and Stats Help", url: "https://www.youtube.com/watch?v=hJbj7UQIJNw" },
    { type: "worksheet", label: "Corbettmaths — Adding Fractions (Different Denominators) (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2024/01/Adding-Fractions.pdf" },
    { type: "worksheet", label: "Corbettmaths — Multiplying Fractions (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/multiplying-fractions-pdf.pdf" },
    { type: "worksheet", label: "Corbettmaths — Probability (PDF)", url: "https://corbettmaths.com/wp-content/uploads/2013/02/probability-pdf.pdf" },
    { type: "website", label: "Maths is Fun — Adding Fractions (interactive)", url: "https://www.mathsisfun.com/fractions_addition.html" },
    { type: "website", label: "Maths is Fun — Probability (interactive)", url: "https://www.mathsisfun.com/data/probability.html" },
  ],

  syllabus_strands_summary: "Representing Quantity Fractions, Percentages and Chance, extended with Stage 4 Fractions & Probability",
  strand_abbreviations_note: "RQF = Representing quantity fractions. RN = Represents numbers (percentages). CHAN = Chance. FRC = Fractions, decimals & percentages (Stage 4). PRO = Probability (Stage 4). A/B = syllabus content groups (this unit genuinely mixes A and B fraction content).",

  syllabus_outcomes: [
    { code: "MAO-WM-01", descriptor: "Develops understanding and fluency through exploring, applying and communicating mathematical reasoning." },
    { code: "MA3-RQF-01", descriptor: "Compares and orders fractions with denominators of 2, 3, 4, 5, 6, 8 and 10." },
    { code: "MA3-RQF-02", descriptor: "Determines fractions of measures and quantities; adds and subtracts fractions." },
    { code: "MA3-RN-03", descriptor: "Determines percentages of quantities, and finds equivalent fractions and decimals for benchmark percentage values." },
    { code: "MA3-CHAN-01", descriptor: "Conducts chance experiments and quantifies the probability using fractions." },
    { code: "MA4-FRC / PRO", descriptor: "Stage 4 (group A): operates with fractions of different denominators and multiplies fractions (FRC); finds probabilities of complementary events (PRO)." },
  ],

  content_points: {
    red: {
      heading: "Fractions & benchmarks (recall & single procedures)",
      heading_short: "Red -- Foundation",
      points: [
        "Recognise the number 1 as the whole; compare halves/quarters of different-sized wholes (RQF-A).",
        "Recall benchmark fraction-decimal-percentage equivalence (½ = 50% = 0.5, ¼ = 25%, ¾ = 75%).",
        "Find a half, quarter, fifth or tenth of a whole number.",
        "Subtract a unit fraction from a whole number using the complement principle (RQF-A).",
      ],
    },
    yellow: {
      heading: "Fractions & chance (applying)",
      heading_short: "Yellow -- On-level",
      points: [
        "Build the whole quantity from a non-unit fractional part.",
        "Compare fractions with related denominators (2,4,8; 3,6; 5,10) using area and discrete models.",
        "Order common fractions with related denominators using diagrams and number lines.",
        "Use equivalence to add and subtract fractions with related denominators.",
        "Solve word problems involving adding or subtracting fractions with related denominators.",
        "Assign probabilities using fractions and benchmark fractions, decimals and percentages.",
      ],
    },
    green: {
      heading: "Extended -- Stage 4 Fractions & Probability",
      heading_short: "Green -- Extension",
      points: [
        "Add and subtract fractions with different denominators by finding a common denominator (MA4-FRC-C-01).",
        "Multiply a fraction by a whole number and by another fraction (MA4-FRC-C-01).",
        "List the sample space and find probabilities of complementary events, P(not A) = 1 - P(A) (MA4-PRO-C-01).",
      ],
    },
  },

  working_mathematically: [
    { process: "Communicating", description: "Students describe fractions, compare them using models, and explain how likely a chance outcome is using fractions, decimals and percentages." },
    { process: "Understanding and fluency", description: "Students find fractions of quantities, compare and order related denominators, and add and subtract fractions using equivalence." },
    { process: "Reasoning", description: "Students justify the need for a common whole, use the complement principle, and reason about probabilities." },
    { process: "Problem solving", description: "Students solve fraction word problems and chance problems, and (Stage 4) add/multiply unlike fractions and find complementary probabilities." },
  ],

  outcomes: [
    { code: "R1", desc: "Recognise the whole; compare halves and quarters of different-sized wholes.", content_point: "RQF-A: recognise the number 1 as the whole; compare halves/quarters of different-sized wholes | MA3-RQF-02", lesson_ref: "Mini Lesson 1" },
    { code: "R2", desc: "Recall benchmark fraction-decimal-percentage equivalence.", content_point: "RN-B: % means percent and 100% is the whole; recall equivalent percentages, decimals and fractions | MA3-RN-03", lesson_ref: "Mini Lesson 3" },
    { code: "R3", desc: "Find a half, quarter, fifth or tenth of a whole number.", content_point: "RQF / RN-B: find fractional quantities of whole numbers (halves, quarters, fifths, tenths); find 10% of a quantity | MA3-RQF-02 / MA3-RN-03", lesson_ref: "Mini Lesson 4" },
    { code: "R4", desc: "Subtract a unit fraction from a whole number (complement principle).", content_point: "RQF-A: subtract a unit fraction from any whole number including 1 (complement principle) | MA3-RQF-02", lesson_ref: "Mini Lesson 7" },
    { code: "Y1", desc: "Build the whole quantity from a non-unit fractional part.", content_point: "RQF-B: build up to the whole from a given fractional part; generate the whole from non-unit fractional parts | MA3-RQF-02", lesson_ref: "Mini Lesson 2" },
    { code: "Y2", desc: "Compare fractions with related denominators using models.", content_point: "RQF-B: compare/represent fractions with denominators 2,4,8; 3,6; 5,10 (area & discrete models); subdivide a rectangle to show the relationship | MA3-RQF-01", lesson_ref: "Mini Lesson 5" },
    { code: "Y3", desc: "Order common fractions with related denominators.", content_point: "RQF-B: order common fractions with related denominators using diagrams and number lines | MA3-RQF-01", lesson_ref: "Mini Lesson 6" },
    { code: "Y4", desc: "Add and subtract fractions with related denominators using equivalence.", content_point: "RQF-B: use equivalence to add and subtract fractional quantities with related denominators | MA3-RQF-02", lesson_ref: "Mini Lesson 8" },
    { code: "Y5", desc: "Solve word problems adding or subtracting fractions with related denominators.", content_point: "RQF-B: solve word problems involving adding/subtracting fractional quantities with related denominators | MA3-RQF-02", lesson_ref: "Mini Lesson 9" },
    { code: "Y6", desc: "Assign probabilities using fractions and benchmark FDP.", content_point: "CHAN-B: assign probabilities to outcomes using fractions; use benchmark fractions/decimals/percentages for likelihood | MA3-CHAN-01", lesson_ref: "Mini Lesson 10" },
    { code: "G1", desc: "Add and subtract fractions with different denominators.", content_point: "Stage 4 FRC-A: compare/order fractions with different denominators; add/subtract by finding a common denominator | MA4-FRC-C-01", lesson_ref: "Mini Lesson 11" },
    { code: "G2", desc: "Multiply a fraction by a whole number and by another fraction.", content_point: "Stage 4 FRC-A: multiply fractions; apply knowledge of fractions of quantities to solve problems | MA4-FRC-C-01", lesson_ref: "Mini Lesson 12" },
    { code: "G3", desc: "List the sample space and find probabilities of complementary events.", content_point: "Stage 4 PRO-A: list the sample space; determine probabilities for complementary events, P(not A) = 1 - P(A) | MA4-PRO-C-01", lesson_ref: "Mini Lesson 13" },
  ],

  lessons: [
    {
      num: 1, band: "R",
      title: "The whole and different-sized wholes",
      outcomes: ["R1"], duration: "25-30 min",
      syllabus: "MA3-RQF-02, MAO-WM-01 | RQF-A: the number 1 as the whole; compare halves/quarters of different wholes",
      source: "DoE Lesson 1 (adapted)",
      doeLink: "Lesson 1 -- Compare fractions with different-sized wholes",
      resources: "Resource 1 - build it up, paper strips, fraction tiles",
      li: "recognise the number 1 as the whole and compare halves and quarters of different-sized wholes",
      sc: [
        "I know the number 1 represents the whole.",
        "I can see that half of a big shape is bigger than half of a small shape.",
        "I can explain why fractions need a common whole to compare fairly.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show half of a large pizza and half of a small pizza. Ask: are these halves equal? Why not?" },
        { label: "Model (10 min):", content: "Fold paper strips of different lengths into halves and quarters. Compare the actual sizes; establish that fractions only compare fairly when the whole (1) is the same." },
        { label: "Guided practice (10 min):", content: "Students compare halves and quarters of different-sized wholes and justify which is larger." },
        { label: "Check (4 min):", content: "Exit question: is ½ of a 10 cm strip the same length as ½ of a 20 cm strip? Explain." },
      ],
      vocab: "whole, one, fraction, half, quarter, compare, equal, common whole",
      support: "Use same-size strips first to see equal halves, then introduce different-size wholes.",
      extension: "Compare thirds and sixths of different-sized wholes and explain using the common whole.",
      assessment: "Students compare fractions of different-sized wholes — links to R1 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["paper strips", "fraction tiles"],
    },
    {
      num: 2, band: "Y",
      title: "Building the whole from a part",
      outcomes: ["Y1"], duration: "25-30 min",
      syllabus: "MA3-RQF-02, MAO-WM-01 | RQF-B: generate the whole from a non-unit fractional part",
      source: "DoE Lesson 1 (adapted)",
      doeLink: "Lesson 1 -- Build up to the whole",
      resources: "Fraction strips, number lines, counters",
      li: "generate the whole quantity from a given non-unit fractional part",
      sc: [
        "I can find one part when I know a non-unit fraction (e.g. if ¾ is 18, one quarter is 6).",
        "I can build up to the whole from the part.",
        "I can check by finding the fraction of my answer.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Tell students ¾ of a jar of marbles is 18. Ask how many marbles are in the whole jar." },
        { label: "Model (10 min):", content: "Use a fraction bar: ¾ = 18, so one quarter = 18 ÷ 3 = 6, and the whole = 6 × 4 = 24. Repeat with ⅖ = 10 → 25." },
        { label: "Guided practice (10 min):", content: "Students find the whole from a non-unit fractional part using a bar model, then check." },
        { label: "Check (4 min):", content: "Exit question: ⅔ of a length is 12 m. How long is the whole length?" },
      ],
      vocab: "fraction, non-unit fraction, part, whole, unit fraction, build up, divide, multiply",
      support: "Draw the fraction bar and find one part first; use counters for the part.",
      extension: "Find the whole from parts like ⅗ and ⅝, then find a different fraction of that whole.",
      assessment: "Students generate the whole from a fractional part — links to Y1 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["fraction strips", "number lines", "counters"],
    },
    {
      num: 3, band: "R",
      title: "Fraction, decimal and percentage benchmarks",
      outcomes: ["R2"], duration: "25 min",
      syllabus: "MA3-RN-03, MAO-WM-01 | RN-B: % means percent; recall equivalent FDP benchmarks",
      source: "DoE Lesson 2 (adapted)",
      doeLink: "Lesson 2 -- Benchmark fractions, decimals and percentages",
      resources: "Hundred grids, fraction-decimal-percentage cards",
      li: "make connections between benchmark fractions, decimals and percentages",
      sc: [
        "I know % means per cent and 100% is the whole.",
        "I can recall ½ = 50% = 0.5, ¼ = 25% = 0.25 and ¾ = 75% = 0.75.",
        "I can match a fraction, a decimal and a percentage that are equal.",
      ],
      steps: [
        { label: "Activate (3 min):", content: "Shade ½ of a hundred grid. Ask what percentage and decimal that is." },
        { label: "Model (10 min):", content: "Build a benchmark table: ½ = 50% = 0.5; ¼ = 25% = 0.25; ¾ = 75% = 0.75; 1/10 = 10% = 0.1. Show each on the grid." },
        { label: "Guided practice (8 min):", content: "Students match fraction, decimal and percentage cards and complete a benchmark table." },
        { label: "Check (4 min):", content: "Exit question: write ¾ as a decimal and a percentage." },
      ],
      vocab: "per cent, %, fraction, decimal, percentage, equivalent, benchmark, whole",
      support: "Use a shaded hundred grid so each percentage is visible; start with ½ and ¼.",
      extension: "Add 1/5 = 20% and 1/3 ≈ 33% to the table and discuss the non-exact ones.",
      assessment: "Students recall benchmark FDP equivalence — links to R2 in the SOLO Show task.",
    },
    {
      num: 4, band: "R",
      title: "Fractions of whole numbers",
      outcomes: ["R3"], duration: "25-30 min",
      syllabus: "MA3-RQF-02, MA3-RN-03, MAO-WM-01 | find halves, quarters, fifths and tenths of numbers",
      source: "DoE Lessons 3 & 5 (adapted)",
      doeLink: "Lessons 3 & 5 -- Understanding tenths / tape diagrams",
      resources: "Resource 14 - tape diagram, Resource 15 - lolly shop cards",
      li: "find fractional quantities of whole numbers (halves, quarters, fifths and tenths)",
      sc: [
        "I can find a half or a quarter of a number by dividing.",
        "I can find a fifth and a tenth of a number.",
        "I know 10% of a number is the same as one-tenth of it.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Use a tape diagram for 20 lolly cards. Ask for half, then a quarter." },
        { label: "Model (10 min):", content: "½ of 20 = 10 (÷2); ¼ of 20 = 5 (÷4); ⅕ of 20 = 4 (÷5); 1/10 of 20 = 2 (÷10). Connect 1/10 to 10%." },
        { label: "Guided practice (10 min):", content: "Students find halves, quarters, fifths and tenths of whole numbers using tape diagrams." },
        { label: "Check (4 min):", content: "Exit question: find ¼ of 40 and 1/10 of 50." },
      ],
      vocab: "fraction, half, quarter, fifth, tenth, of, divide, tape diagram, 10%",
      support: "Use repeated halving (half, then half again for a quarter); use the tape diagram.",
      extension: "Find eighths from quarters and tenths from fifths; find 25% and 10% of money amounts.",
      assessment: "Students find fractions of whole numbers — links to R3 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["tape diagram", "lolly shop cards"],
    },
    {
      num: 5, band: "Y",
      title: "Comparing fractions (related denominators)",
      outcomes: ["Y2"], duration: "30 min",
      syllabus: "MA3-RQF-01, MAO-WM-01 | RQF-B: compare fractions with related denominators (area model)",
      source: "DoE Lesson 4 (adapted)",
      doeLink: "Lesson 4 -- Compare common fractions with related denominators",
      resources: "Resource 12 - area model fractions, Resource 13 - fraction wall",
      li: "compare fractions with related denominators using an area model and a collection of objects",
      sc: [
        "I can use an area model or fraction wall to compare fractions.",
        "I can compare fractions with related denominators (e.g. ½ and ⅜; ⅔ and ⅚).",
        "I can rename a fraction to a related denominator to compare (e.g. ½ = 2/4).",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show ½ and ⅜ on a fraction wall. Ask which is bigger and how you can tell." },
        { label: "Model (12 min):", content: "Use an area model: rename ½ as 4/8, then compare with ⅜. Subdivide a rectangle by length and width to see eighths from halves and quarters." },
        { label: "Guided practice (10 min):", content: "Students compare fractions with related denominators using the area model and fraction wall." },
        { label: "Check (4 min):", content: "Exit question: which is bigger, ⅔ or ⅚? Use a model to show why." },
      ],
      vocab: "compare, fraction, related denominator, area model, fraction wall, equivalent, rename",
      support: "Provide a fraction wall; line up the two fractions and read off which is longer.",
      extension: "Compare three related fractions and order them using the area model.",
      assessment: "Students compare fractions with related denominators — links to Y2 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["area model cards", "fraction wall"],
    },
    {
      num: 6, band: "Y",
      title: "Ordering fractions (related denominators)",
      outcomes: ["Y3"], duration: "25-30 min",
      syllabus: "MA3-RQF-01, MAO-WM-01 | RQF-B: order fractions with related denominators using number lines",
      source: "DoE Lesson 5 (adapted)",
      doeLink: "Lesson 5 -- Ordering fractions with related denominators",
      resources: "Number lines, Resource 16 - fraction cards, fraction wall",
      li: "order common fractions with related denominators using diagrams and number lines",
      sc: [
        "I can place fractions with related denominators on a number line.",
        "I can rename fractions to a common denominator to order them.",
        "I can order a set of fractions from smallest to largest.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Place ½, ¼ and ¾ on a 0-1 number line. Ask which is smallest." },
        { label: "Model (10 min):", content: "Order ⅖, ½ and ⅗ by renaming to tenths (4/10, 5/10, 6/10) and placing on a number line." },
        { label: "Guided practice (10 min):", content: "Students order sets of fractions with related denominators using a number line and a fraction wall." },
        { label: "Check (4 min):", content: "Exit question: order ¼, ½ and ⅜ from smallest to largest." },
      ],
      vocab: "order, fraction, number line, related denominator, smallest, largest, rename, equivalent",
      support: "Provide a marked number line; rename to a common denominator first.",
      extension: "Order a mixed set including fractions greater than 1 (e.g. 5/4).",
      assessment: "Students order fractions with related denominators — links to Y3 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["number lines", "fraction cards"],
    },
    {
      num: 7, band: "R",
      title: "Subtracting a fraction from a whole",
      outcomes: ["R4"], duration: "25 min",
      syllabus: "MA3-RQF-02, MAO-WM-01 | RQF-A: subtract a unit fraction from a whole (complement principle)",
      source: "DoE Lesson 6 (adapted)",
      doeLink: "Lesson 6 -- Subtracting a unit fraction from a whole",
      resources: "Resource 13 - fraction wall, number lines, Resource 18 - fractions",
      li: "subtract a unit fraction from a whole number using the complement principle",
      sc: [
        "I know that 1 = a fraction plus its complement (e.g. 1 = ⅓ + ⅔).",
        "I can subtract a unit fraction from 1 (e.g. 1 − ¼ = ¾).",
        "I can subtract a unit fraction from a whole number (e.g. 3 − ¼ = 2¾).",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show a whole circle. Take away ⅓. Ask how much is left and how you know." },
        { label: "Model (10 min):", content: "Use the complement: 1 − ⅓ = ⅔; 1 − ¼ = ¾. Then 3 − ¼: keep 2 wholes, 1 − ¼ = ¾, so 2¾." },
        { label: "Guided practice (8 min):", content: "Students subtract unit fractions from 1 and from whole numbers using a fraction wall or number line." },
        { label: "Check (3 min):", content: "Exit question: 2 − ⅕ = ?" },
      ],
      vocab: "whole, unit fraction, complement, subtract, left, number line, fraction wall",
      support: "Use a fraction wall to see the complement; start with subtracting from 1.",
      extension: "Subtract non-unit fractions from whole numbers (e.g. 3 − ⅔).",
      assessment: "Students subtract a unit fraction from a whole — links to R4 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["fraction wall", "number lines"],
    },
    {
      num: 8, band: "Y",
      title: "Adding and subtracting fractions",
      outcomes: ["Y4"], duration: "30 min",
      syllabus: "MA3-RQF-02, MAO-WM-01 | RQF-B: use equivalence to add/subtract related denominators",
      source: "DoE Lessons 6 & 7 (adapted)",
      doeLink: "Lessons 6 & 7 -- Adding and subtracting fractions",
      resources: "Fraction wall, Resource 18 - fractions",
      li: "use equivalence to add and subtract fractions with related denominators",
      sc: [
        "I can add and subtract fractions with the same denominator.",
        "I can rename a fraction to a related denominator before adding (e.g. ½ = 2/4).",
        "I can add fractions like ½ + ¼ = ¾.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show ⅜ + 2/8 on a fraction wall. Ask for the total." },
        { label: "Model (10 min):", content: "Add same denominators: ⅜ + 2/8 = ⅝. Related: ½ + ¼ → rename ½ as 2/4 → 2/4 + ¼ = ¾. Subtract ¾ − ¼ = 2/4 = ½." },
        { label: "Guided practice (12 min):", content: "Students add and subtract fractions with related denominators, renaming to a common denominator." },
        { label: "Check (4 min):", content: "Exit question: ⅔ + ⅙ = ? (rename ⅔ as 4/6)." },
      ],
      vocab: "add, subtract, fraction, denominator, equivalent, rename, common denominator, simplify",
      support: "Use a fraction wall; rename one fraction so both denominators match.",
      extension: "Add three related fractions and simplify the answer.",
      assessment: "Students add and subtract fractions with related denominators — links to Y4 in the SOLO Show task.",
    },
    {
      num: 9, band: "Y",
      title: "Fraction word problems",
      outcomes: ["Y5"], duration: "30 min",
      syllabus: "MA3-RQF-02, MAO-WM-01 | RQF-B: word problems adding/subtracting related denominators",
      source: "DoE Lesson 7 (adapted)",
      doeLink: "Lesson 7 -- Solving fraction word problems",
      resources: "Bar models, Resource 18 - fractions",
      li: "solve word problems involving adding or subtracting fractions with related denominators",
      sc: [
        "I can draw a bar model to represent a fraction word problem.",
        "I can decide whether to add or subtract the fractions.",
        "I can solve the problem and check my answer.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Francis ate ⅜ of a chocolate bar, then ¼ more. Ask how much he ate altogether." },
        { label: "Model (10 min):", content: "Draw a bar model; rename ¼ as 2/8; ⅜ + 2/8 = ⅝. Then a 'how much is left' problem using subtraction." },
        { label: "Guided practice (12 min):", content: "Students solve add/subtract fraction word problems with related denominators using bar models." },
        { label: "Check (4 min):", content: "Exit question: a jug is ⅔ full, then ⅙ is poured out. How much is left?" },
      ],
      vocab: "word problem, fraction, bar model, add, subtract, related denominator, total, left",
      support: "Provide a part-drawn bar model; help rename to the same denominator.",
      extension: "Solve two-step fraction word problems and create one for a partner.",
      assessment: "Students solve fraction word problems — links to Y5 in the SOLO Show task.",
    },
    {
      num: 10, band: "Y",
      title: "Chance with fractions",
      outcomes: ["Y6"], duration: "30-35 min",
      syllabus: "MA3-CHAN-01, MAO-WM-01 | CHAN-B: assign probabilities using fractions and benchmark FDP",
      source: "DoE Lesson 8 (adapted)",
      doeLink: "Lesson 8 -- Chance using fractions, decimals and percentages",
      resources: "Spinners, coloured counters, bags, Resource - spinner bar model",
      li: "assign probabilities to outcomes using fractions and use benchmark FDP to describe likelihood",
      sc: [
        "I can write the probability of an outcome as a fraction.",
        "I can assign probabilities when outcomes are not equally likely.",
        "I can use benchmark fractions, decimals and percentages to describe how likely an outcome is.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show a spinner split into 4 equal parts (2 red, 1 blue, 1 green). Ask the chance of landing on red." },
        { label: "Model (12 min):", content: "P(red) = 2/4 = ½ = 50%; P(blue) = ¼ = 25%. For an unequal spinner, use a bar model to read off the fractions." },
        { label: "Guided practice (14 min):", content: "Students assign probabilities to spinner and bag outcomes as fractions and describe each with a benchmark FDP." },
        { label: "Check (4 min):", content: "Exit question: a bag has 3 red and 1 blue counter. Write P(red) as a fraction and a percentage." },
      ],
      vocab: "chance, probability, outcome, likely, fraction, equally likely, spinner, benchmark",
      support: "Use equal-section spinners first; count the favourable sections over the total.",
      extension: "Design a spinner to match given probabilities (e.g. P(red) = ⅜).",
      assessment: "Students assign probabilities using fractions — links to Y6 in the SOLO Show task.",
      is_hands_on: true,
      materials: ["spinners", "coloured counters", "bags"],
    },
    {
      num: 11, band: "G",
      title: "Fractions with different denominators (Stage 4)",
      outcomes: ["G1"], duration: "30-35 min",
      syllabus: "MA4-FRC-C-01, MAO-WM-01 | Stage 4 FRC-A: add/subtract fractions with different denominators",
      source: "Original mini lesson",
      li: "add and subtract fractions with different (unrelated) denominators by finding a common denominator",
      sc: [
        "I can find a common denominator for two unlike fractions.",
        "I can rename both fractions and then add or subtract.",
        "I can simplify the answer where possible.",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Show ⅓ + ¼. Ask why we can't just add the tops and bottoms." },
        { label: "Model (12 min):", content: "Common denominator of 3 and 4 is 12: ⅓ = 4/12, ¼ = 3/12, so ⅓ + ¼ = 7/12. Subtract ½ − ⅓ = 3/6 − 2/6 = 1/6." },
        { label: "Guided practice (12 min):", content: "Students add and subtract fractions with different denominators by finding a common denominator." },
        { label: "Check (5 min):", content: "Exit question: ¾ − ⅓ = ?" },
      ],
      vocab: "fraction, denominator, common denominator, equivalent, rename, add, subtract, simplify",
      support: "Provide a list of multiples to find the common denominator; use a fraction wall.",
      extension: "Add three unlike fractions and simplify; add mixed numbers.",
      assessment: "Students add/subtract unlike fractions — links to G1 in the SOLO Show task.",
    },
    {
      num: 12, band: "G",
      title: "Multiplying fractions (Stage 4)",
      outcomes: ["G2"], duration: "30 min",
      syllabus: "MA4-FRC-C-01, MAO-WM-01 | Stage 4 FRC-A: multiply fractions",
      source: "Original mini lesson",
      li: "multiply a fraction by a whole number and by another fraction",
      sc: [
        "I can multiply a fraction by a whole number (e.g. ⅔ × 6 = 4).",
        "I can multiply two fractions by multiplying tops and bottoms.",
        "I can connect 'of' to multiplication (½ of ¾ = ½ × ¾).",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Ask what ⅔ of 6 is, connecting 'of' to multiplication." },
        { label: "Model (12 min):", content: "⅔ × 6 = (2 × 6) ÷ 3 = 4. Multiply two fractions: ½ × ¾ = (1×3)/(2×4) = ⅜." },
        { label: "Guided practice (10 min):", content: "Students multiply fractions by whole numbers and by other fractions, simplifying where possible." },
        { label: "Check (4 min):", content: "Exit question: find ¾ × 8 and ⅓ × ½." },
      ],
      vocab: "multiply, fraction, whole number, numerator, denominator, of, simplify, product",
      support: "Model 'of' with an area diagram; multiply tops and bottoms.",
      extension: "Multiply a mixed number by a fraction and simplify.",
      assessment: "Students multiply fractions — links to G2 in the SOLO Show task.",
    },
    {
      num: 13, band: "G",
      title: "Probability and complementary events (Stage 4)",
      outcomes: ["G3"], duration: "30 min",
      syllabus: "MA4-PRO-C-01, MAO-WM-01 | Stage 4 PRO-A: sample space; complementary events",
      source: "Original mini lesson",
      li: "list the sample space and find the probability of complementary events",
      sc: [
        "I can list all the possible outcomes (the sample space).",
        "I know complementary events together cover everything (total = 1).",
        "I can find P(not A) = 1 − P(A).",
      ],
      steps: [
        { label: "Activate (4 min):", content: "Roll a die. Ask for all the possible outcomes (the sample space)." },
        { label: "Model (12 min):", content: "Sample space {1,2,3,4,5,6}. P(rolling a 6) = ⅙, so P(not a 6) = 1 − ⅙ = ⅚. Complementary events add to 1." },
        { label: "Guided practice (10 min):", content: "Students list sample spaces and find probabilities of complementary events for dice, spinners and bags." },
        { label: "Check (4 min):", content: "Exit question: P(red) = ¼. What is P(not red)?" },
      ],
      vocab: "sample space, outcome, probability, complementary event, not, total, 1, certain",
      support: "List the outcomes first; use 'everything minus the event' for the complement.",
      extension: "Find complementary probabilities for two-step experiments.",
      assessment: "Students find complementary probabilities — links to G3 in the SOLO Show task.",
    },
  ],
};
